### ISSUE TITLE
Unsafe Login. IMAP: H3 NO EXAMINE Unsafe login

### ISSUE THREAD

**Issue by Aspire1Inspire2** [FlowCrypt/flowcrypt-android#1011]
I got rejected receiving mails using imap. I was trying to log in to 163.com email server when this happens.

I was told that the email client app should return its identity to allow connecting to the email server.

The developer of that email server provides the following code:
```
Properties props = new Properties(); 
props.setProperty("mail.store.protocol", "imap"); 
props.setProperty("mail.imap.host", "imap.163.com"); 
props.setProperty("mail.imap.port", "143"); 

HashMap IAM = new HashMap();
//IMAP ID: key, value pair. E.g. name，version，vendor，support-email
IAM.put("name","myname");      
IAM.put("version","1.0.0");      
IAM.put("vendor","myclient");      
IAM.put("support-email","testmail@test.com");  
Session session = Session.getInstance(props); 

IMAPStore store = (IMAPStore) session.getStore("imap");
//user account and password
store.connect("testmail@163.com", "password"); 

store.id(IAM);
```

The developer provides the following link to explain context:
https://javaee.github.io/javamail/docs/api/index.html?com/sun/mail/imap/IMAPStore.html

Could you evaluate if this situation is a valid case to make it more secure/compatible with imap server?

**Comment by DenBond7** [comment]
Hello. It seems you use a plain authentication. That's not safe and we don't support such a connection.

Do you mean this one (https://mail.163.com/) email provider?

**Comment by Aspire1Inspire2** [comment]
> Hello. It seems you use a plain authentication. That's not safe and we don't support such a connection.
> 
> Do you mean this one (https://mail.163.com/) email provider?

Yes, that is correct. 

I am not familliar with java. 
So sounds like they were asking for a plain text password to be sent over imap protocol? 
I believe they made ssl encryption, will that be OK?

**Comment by DenBond7** [comment]
I've tried to register a new account on 163.com. But I can't complete the setup process, it seems this email provider doesn't support my country. Anyway, this email provider supports SSL connection.

![image](https://user-images.githubusercontent.com/2863246/104094960-d6612a80-529c-11eb-9e8f-731ab4d3218c.png)

You can read more details [here](https://help.mail.163.com/faqDetail.do?code=d7a5dc8471cd0c0e8b4b8f4f8e49998b374173cfe9171305fa1ce630d7f67ac2cda80145a1742516)

**Comment by Aspire1Inspire2** [comment]
Thanks for the information!
Yes, that is how I opened up my imap/smtp service.

You need to verify your phone number to receive a two-factor authentication code to open the third party imap/smtp service.

When I log in to the imap/smtp service, the flowcrypt shows me the error I mentioned at the beginning of this issue.

Do you have difficulty getting the authentication code to your cell number? Is there anything I can help?

**Comment by DenBond7** [comment]
> Do you have difficulty getting the authentication code to your cell number? Is there anything I can help?

Yup. It seems the server doesn't send a verification code to me. If you provide the credentials which can help me connect to the IMAP server I will be able to investigate this issue. Maybe you can create a test account for me. If yes, please send me login/password to den@flowcrypt.com

**Comment by DenBond7** [comment]
deprecated
