### ISSUE TITLE
Submit FlowCrypt to F-Droid

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-android#1021]
F-Droid is an installable catalogue of FOSS (Free and Open Source Software) applications for the Android platform. It works similarly to Google's Play Store, but exclusively for FOSS. It doesn't cost anything to be included and I believe we may meet F-Droid's standard for being FOSS.

Let me know if this is something you want to try and I'll submit us.

I learned about this from a user who suggested it: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgxwLsJrrTrsNvfDqJfwrndQRxQSC

**Comment by tomholub** [comment]
FlowCrypt is not FOSS, it's a proprietary license.

Btw all submissions to app stores must be under my own account.

I'd consider submitting to F-Droid if they accepted a source-available proprietary app.

**Comment by seisvelas** [comment]
>FlowCrypt is not FOSS, it's a proprietary license.

You've made this distinction to me before, but I don't fully understand. I think our license allows modification and redistribution, so what about our Android client isn't open source? I've been curious since the first time you mentioned this.

**Comment by tomholub** [comment]
It allows modification and redistribution, but it forbids certain
modifications (related to our business needs) making it not FOSS.

**Comment by seisvelas** [comment]
That makes sense! I found the docs where F-Droid defines what can be included and we definitely are not compliant (only FSF approved licenses), so closing this issue
