### ISSUE TITLE
Intermittent decryption errors for user

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-android#1030]
> My messages are forwarded encrypted from the anonaddy.me service to my gmail account, using an AES-256 4096 bit public key.
> 
> Some messages can be decrypted and read fine in FlowCrypt. Others result in a java.Exception.IllegalBlockSize or java.Exception.BadPaddingSize.
> 
> The Mailvelope chrome extension on desktop can decrypt the same message fine.

ref: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgxwLsKDFfrMXxJJknklDbGgfsdWN

Any tips for how to debug this?

**Comment by DenBond7** [comment]
@seisvelas I've checked ACRA logs. Unfortunately, I don't see any errors of IllegalBlockSize or BadPaddingSize. Could you ask the user to write me at den@flowcrypt.com with additional details(maybe screenshots)?

**Comment by DenBond7** [comment]
for me https://mail.google.com/mail/u/1/#inbox/FMfcgxwLsSWMtCTLSZpHVsSCgmZSMBzn

**Comment by DenBond7** [comment]
Deprecated
