### ISSUE TITLE
Migrate from jcenter to Maven Central 

### ISSUE THREAD

**Issue by IvanPizhenko** [FlowCrypt/flowcrypt-android#1036]
Reason: JFrog is shutting down jcenter
https://www.infoq.com/news/2021/02/jfrog-jcenter-bintray-closure/
Alternatives:
https://docs.gradle.org/current/userguide/declaring_repositories.html

What to do:
- Remove `jcenter()`
- Add `mavenCentral()` if not yet there

**Comment by DenBond7** [comment]
@IvanPizhenko Thanks for the reminder!

Details: https://developer.android.com/studio/build/jcenter-migration

**Comment by DenBond7** [comment]
Due to missing some libs on `mavenCentral()` we can't remove `jcenter() `right now. So I've moved this issue to `soon`.

**Comment by DenBond7** [comment]
can be completed after #243 

```
implementation 'com.burhanrashid52:photoeditor:2.0.0'
implementation 'io.github.everythingme:overscroll-decor-android:1.1.1'
```
