### ISSUE TITLE
cannot decrypt message - error handling

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#104]
I can't decrypt a message. I received the next error:

```
09-25 11:52:12.627 26680-26720/com.flowcrypt.email.debug W/System.err: java.lang.UnsupportedOperationException
09-25 11:52:12.656 26680-26720/com.flowcrypt.email.debug W/System.err:     at com.eclipsesource.v8.V8Object$Undefined.getString(V8Object.java:920)
09-25 11:52:12.656 26680-26720/com.flowcrypt.email.debug W/System.err:     at com.flowcrypt.email.js.MeaningfulV8ObjectContainer.getAttributeAsString(Js.java:418)
09-25 11:52:12.656 26680-26720/com.flowcrypt.email.debug W/System.err:     at com.flowcrypt.email.js.PgpDecrypted.getContent(PgpDecrypted.java:71)
09-25 11:52:12.657 26680-26720/com.flowcrypt.email.debug W/System.err:     at com.flowcrypt.email.ui.loader.DecryptMessageAsyncTaskLoader.decryptText(DecryptMessageAsyncTaskLoader.java:182)
09-25 11:52:12.657 26680-26720/com.flowcrypt.email.debug W/System.err:     at com.flowcrypt.email.ui.loader.DecryptMessageAsyncTaskLoader.getMessagePartsFromProcessedMime(DecryptMessageAsyncTaskLoader.java:141)
09-25 11:52:12.657 26680-26720/com.flowcrypt.email.debug W/System.err:     at com.flowcrypt.email.ui.loader.DecryptMessageAsyncTaskLoader.parseRawMessage(DecryptMessageAsyncTaskLoader.java:105)
09-25 11:52:12.657 26680-26720/com.flowcrypt.email.debug W/System.err:     at com.flowcrypt.email.ui.loader.DecryptMessageAsyncTaskLoader.loadInBackground(DecryptMessageAsyncTaskLoader.java:64)
09-25 11:52:12.657 26680-26720/com.flowcrypt.email.debug W/System.err:     at com.flowcrypt.email.ui.loader.DecryptMessageAsyncTaskLoader.loadInBackground(DecryptMessageAsyncTaskLoader.java:45)
09-25 11:52:12.657 26680-26720/com.flowcrypt.email.debug W/System.err:     at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:302)
09-25 11:52:12.657 26680-26720/com.flowcrypt.email.debug W/System.err:     at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:57)
09-25 11:52:12.657 26680-26720/com.flowcrypt.email.debug W/System.err:     at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:45)
09-25 11:52:12.657 26680-26720/com.flowcrypt.email.debug W/System.err:     at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:138)
09-25 11:52:12.657 26680-26720/com.flowcrypt.email.debug W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
09-25 11:52:12.657 26680-26720/com.flowcrypt.email.debug W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
09-25 11:52:12.657 26680-26720/com.flowcrypt.email.debug W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
09-25 11:52:12.657 26680-26720/com.flowcrypt.email.debug W/System.err:     at java.lang.Thread.run(Thread.java:761)
```

**Comment by tomholub** [comment]
I'll look into it

**Comment by tomholub** [comment]
Is this happening on all messages, or only some? Is it a test account or your personal account?

**Comment by tomholub** [comment]
I'll look into this tomorrow

**Comment by DenBond7** [comment]
Ok, maybe we will do it together. I tested the Gmail  private key and I can't decrypt a message in other email providers using this key too.

**Comment by tomholub** [comment]
Try to use that key in one of the accounts in Chrome plugin. See if it works there.

**Comment by DenBond7** [comment]
I found in what the problem. It's a strange behavior in Gmail and CryptUp.

Generally, it all works perfectly. I created new private keys for outlook and yahoo accounts and I can encrypt/decrypt all messages. So, here we don't have a problem.

Why and when I receive such error? A little history: In my Gmail, I have other one account which works too. For example, my Gmail is my@gmail.com and my other one account is my@example.com. And when I tried to send an encrypted message to my@example.com CruptUp doesn't ask me about the public key of my@example.com and just sent the message. When I opened that message in FlowCrypt(my@example.com) I can't decrypt it. I think CruptUp used the my@gmail.com public key to send the message to the my@example.com account.

Now I added manually the public key of my@example.com in CryptUp settings and then sent a message to my@example.com from my@gmail.com. And it all works fine.

**Comment by tomholub** [comment]
There are lots of different reasons why a message may fail to decrypt. methods in PgpDecrypted objects will give you a good amount of info, and you'll have to test for different scenarios in certain order to figure out what is the problem.

Here is what we do in JavaScript:
```js
      tool.crypto.message.decrypt(db, url_params.account_email, url_params.message, optional_password, function (result) {
        if(result.success) {
          // render
        } else if(result.format_error) {
            render_error(window.lang.pgp_block.bad_format + '\n\n' + result.format_error);
        } else if(result.missing_passphrases.length) {
          render_passphrase_prompt(result.missing_passphrases);
        } else if(result.counts.potentially_matching_keys === result.counts.attempts && result.counts.key_mismatch === result.counts.attempts) {
          // missing the right private key to decrypt this message - auto check backups, maybe there is a new backup to use. If no backup matches the longids it's encrypted for, offer to import key
        } else if(result.counts.unsecure_mdc) {
          // show unsecure MDC error
        } else if(result.counts.errors) {
          render_error(window.lang.pgp_block.cant_open + window.lang.pgp_block.bad_format + '\n\n' + '<em>' + result.errors.join('<br>') + '</em>');
        } else {
          delete result.message;
          render_error(window.lang.pgp_block.cant_open + window.lang.pgp_block.write_me + '\n\nDiagnostic info: "' + JSON.stringify(result) + '"');
        }
      });
```
You can use this as a guide to do something similar in Java. Just notice there are slight differences in how to access the info:
 - imagine that `result` above is something similar to your `PgpDecrypted` object
 - `result.success` becomes `pgpDecrypted.isSuccess()` in Java.
 - `result.format_error` becomes `pgpDecrypted.getFormatError()`
 - `result.missing_passphrases` becomes `pgpDecrypted.getMissingPassphraseLongids()`
 - `result.counts.potentially_matching_keys` becomes `pgpDecrypted.countPotentiallyMatchingKeys()`
 - `result.counts.attemts` becomes `pgpDecrypted.countAttempts()` 
and so on

Here are the error messages that the code is referencing (window.lang.XXXXX): https://github.com/FlowCrypt/flowcrypt-browser/blob/master/chrome/js/common/lang.js

Feel free to ask questions

**Comment by tomholub** [comment]
To display errors, there should be a fragment similar to the "green border" fragment, but the one that has red color border. Take that fragment and put error message inside of it as standard text, and action buttons below if needed (eg key mismatch -> offer to import key).

**Comment by tomholub** [comment]
Similar to what the desktop client does

**Comment by tomholub** [comment]
ref https://mail.google.com/mail/u/1/#inbox/15f0ef3da6ff5c03

**Comment by DenBond7** [comment]
@tomholub Could you generate different errors for me? I mean different emails. To begin with the most common.

**Comment by tomholub** [comment]
Yes I hope to prepare a special email account with many emails gone wrong.

You can start for example by encrypting email from account A to account B, then copy-pasting the encrypted message block and sending it as a plain text email to account C. Then try to open it in account C - you should get a key mismatch error.

**Comment by DenBond7** [comment]
@tomholub  I did some preparations for this issue. Notify me please when wrong emails will be ready. Then I will continue. I added your logic, but I want to test the app with different emails.

**Comment by tomholub** [comment]
I have created an email for compatibility tests, where users or developers of other plugins can send us test email.

I have already created a bunch of emails there for testing. I will send you credentials separately.

You can go through folder named "decrypt error"

**Comment by DenBond7** [comment]
It's great. I continue work on this issue now.

**Comment by DenBond7** [comment]
@tomholub How to detect such type of errors? How to retrieve diagnostic info?
![image](https://user-images.githubusercontent.com/2863246/32377650-0ca3360a-c0b1-11e7-853b-ee4fa1823d2d.png)

In code I received `pgpDecrypted.getFormatError() != null` and in my case this is the format error.
![image](https://user-images.githubusercontent.com/2863246/32377789-7dec58be-c0b1-11e7-816f-ec72b7b9e097.png)

**Comment by tomholub** [comment]
In the first example, the code went through all of the known types of errors, and couldn't find anything (all known errors were empty). Then it just dumped all of the contents of `pgpDecrypted` in one JSON. You don't have too do that, just display: 

Diagnostic info: `pgpDecrypted.getOtherErrors()` - this should be an array of strings, you could join them with newlines

That should be enough for now.

Second example: the sentence in the middle is the content of getFormatError, you can display that like in the chrome app.

**Comment by DenBond7** [comment]
> In the first example, the code went through all of the known types of errors, and couldn't find anything (all known errors were empty).

But in the Android app, I don't receive a similar result.

![2017-11-06_11-00-44](https://user-images.githubusercontent.com/2863246/32432920-ed7a6be4-c2e1-11e7-927e-2b260ac97440.png)

![image](https://user-images.githubusercontent.com/2863246/32433025-40fe95ec-c2e2-11e7-81b7-cd3367fea710.png)

Do we have a different error parse logic for a web and android JS code?

**Comment by tomholub** [comment]
That's interesting, we probably use older version of OpenPGP.js on Android.

I would release it as is (still an improvement) and later, I'll update the libraries, after that we can revisit.

**Comment by DenBond7** [comment]
How to identify these problems? How to distinguish them from each other?

![image](https://user-images.githubusercontent.com/2863246/32456835-a3d5b3b0-c32f-11e7-806a-96d7ad5aa019.png)

![image](https://user-images.githubusercontent.com/2863246/32456866-bb023392-c32f-11e7-84b4-247958dcc67a.png)

Currently, I detect them as 

![image](https://user-images.githubusercontent.com/2863246/32456982-1c306f94-c330-11e7-9469-8ebf7f161bed.png)

and in code

com.flowcrypt.email.ui.loader.DecryptMessageAsyncTaskLoader

```
if (Objects.equals(pgpDecrypted.countPotentiallyMatchingKeys(), pgpDecrypted.countAttempts())) {
                pgpMessageDecryptError = MessagePartPgpMessage.PgpMessageDecryptError.MISSING_PRIVATE_KEY;
 errorMessage = getContext().getString(R.string.decrypt_error_could_not_open_message) +
                        "\n\n" + getContext().getString(R.string.decrypt_error_single_sender);
}
```

**Comment by tomholub** [comment]
If you already know it's a key mismatch scenario from
```
result.counts.potentially_matching_keys === result.counts.attempts && result.counts.key_mismatch === result.counts.attempts
```
Then you should see if `pgpDecrypted.getEncryptedForLongids().length > 1`. 
If yes, show "your current key cannot open this message" error.
Else show "Normally, messages are encrypted for at least two people" error as you do now.

Also, the condition should change to something like:

```java
if (Objects.equals(pgpDecrypted.countPotentiallyMatchingKeys(), pgpDecrypted.countAttempts()) && Objects.equals(pgpDecrypted.countKeyMismatchErrors(), pgpDecrypted.countAttempts())) {
                ...
}
```

To make sure that potentially matching keys, decrypt attemts and key mismatch errors (resulting from attempts) all match, meaning this is definitely only a key mismatch error.

By the way, feel free to change my code to return int instead of Integer. I'm not used to Java and often don't see these subtleties. If you change my functions to return int, then you can compare 
```java
if (pgpDecrypted.countPotentiallyMatchingKeys() == pgpDecrypted.countAttempts() && pgpDecrypted.countKeyMismatchErrors() == pgpDecrypted.countAttempts()) {
                ...
}
```
which I think is a lot more readable.

**Comment by DenBond7** [comment]
Ok, for 

> Message encrypted for public keys that don't much

I must add the button "Import missing key" and allow users import their private keys? And after that I must try to decrypt the message again. Right?

**Comment by tomholub** [comment]
I would actually show button to import a private key in both of these scenarios. I don't do it yet in Chrome, but I plan to update it in the future.

When the user is done adding the new key, just re-load the message activity so that it will try to load and decrypt the message again using current set of keys.

**Comment by tomholub** [comment]
see `tests/secondary` gmail label to test this. These messages are encrypted for the secondary private key. 

You can manually load the key from the second backup email. The pass phrase for this key is the same as the first key, just add ` 2` (space and number two) at the end.

**Comment by DenBond7** [comment]
Basically completed and ready for testing :)
