### ISSUE TITLE
do key parsing in Kotlin

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#1044]
Whenever you only need basic functionality - like parsing a key - you can use this library.

Let me know if it replicates the existing parsing functionality fully.

Then over time, we'll find more and more places to replace node, until it's gone.

[Pgp.kt.txt](https://github.com/FlowCrypt/flowcrypt-android/files/6034479/Pgp.kt.txt)

It uses latest PGPainless https://github.com/pgpainless/pgpainless/

**Comment by DenBond7** [comment]
@tomholub Does it support a few keys in one source(single string)?

**Comment by tomholub** [comment]
Not as currently implemented. We'll have to add that.

**Comment by tomholub** [comment]
We could implement it here, in Pgp.kt. Then copy it back to the original source. Eventually we may have a proper library to maintain this class.

**Comment by DenBond7** [comment]
I'm closing it. Covered by https://github.com/FlowCrypt/flowcrypt-android/issues/1053
