### ISSUE TITLE
port MsgBlockParser from TypeScript to Kotlinpgp message block parser 

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#1052]
As a part of #1051 we'll need to port the following https://github.com/FlowCrypt/flowcrypt-browser/blob/master/extension/js/common/core/msg-block-parser.ts but only method `detectBlocks` with its private counterpart `detectBlockNext`. I recommend to port it line-by-line so that we can easily reason about it - the original parser is well battle tested.

The Android codebase already has a class similar to TypeScript's MsgBlock here https://github.com/FlowCrypt/flowcrypt-browser/blob/master/extension/js/common/core/msg-block.ts - @DenBond7 can you please point us to where is the Android/Kotlin equivalent defined?

For the implementation I'd recommend to do it in this order:

1) open the typescript codebase in vscode to better understand it
2) from https://github.com/FlowCrypt/flowcrypt-browser/blob/master/test/source/tests/unit-node.ts copy first 3 tests that start with `[unit][MsgBlockParser.detectBlocks]` into kotlin
3) copy the algorithm and translate into Kotlin line by line
4) most test cases are unfortunately, in browser-extension, run as integration tests. I recommend to find a way to run all tests and export the results into a file, to work as data for unit tests in Kotlin. I'm not entirely sure what the right way to do this is, since the test runner is in NodeJS but the tested code itself runs in puppeteer. When unsure, ask @rrrooommmaaa for help
5) once exported data for unit tests, write appropriate Kotlin unit tests and fix implementation if necessary

**Comment by tomholub** [comment]
This will be for @IvanPizhenko whom I've just invited to the repo https://github.com/FlowCrypt/flowcrypt-android/invitations

**Comment by DenBond7** [comment]
> can you please point us to where is the Android/Kotlin equivalent defined?

Please look at [MsgBlockDeserializer](https://github.com/FlowCrypt/flowcrypt-android/blob/master/FlowCrypt/src/main/java/com/flowcrypt/email/api/retrofit/node/gson/MsgBlockDeserializer.kt). There you will find the info which blocks we currently support on Android

And in this [place](https://github.com/FlowCrypt/flowcrypt-android/tree/master/FlowCrypt/src/main/java/com/flowcrypt/email/api/retrofit/response/model/node) lie Kotlin classes for blocks

**Comment by IvanPizhenko** [comment]
I have a question - where to place method `detectBlocks()`? i.e. in what class and in what package?

**Comment by IvanPizhenko** [comment]
Meanwhile will put into https://github.com/FlowCrypt/flowcrypt-android/tree/master/FlowCrypt/src/main/java/com/flowcrypt/email/api/retrofit/response/model/node

**Comment by tomholub** [comment]
I also don't know. Den will clarify tomorrow.

**Comment by DenBond7** [comment]
> I have a question - where to place method `detectBlocks()`? i.e. in what class and in what package?

@IvanPizhenko Please use `com.flowcrypt.email.core.msg` as a package and store `MsgBlockParser` there. I think later we will move all blocks to `com.flowcrypt.email.core.msg.blocks`

**Comment by IvanPizhenko** [comment]
I think I've ported the code, now need to get some unit tests.
@rrrooommmaaa Can you plase point me where are unit tests for the block parser?

**Comment by tomholub** [comment]
> from https://github.com/FlowCrypt/flowcrypt-browser/blob/master/test/source/tests/unit-node.ts copy first 3 tests that start with [unit][MsgBlockParser.detectBlocks] into kotlin

Can start here

**Comment by IvanPizhenko** [comment]
@tomholub So I have got those 3 tests passing - what's next?

**Comment by IvanPizhenko** [comment]
I think I will post PR now and add any extra unit tests later.

**Comment by IvanPizhenko** [comment]
will do after #1077 is merged - it's on top of it

**Comment by tomholub** [comment]
Agree, can get the basics merged, then talk more

**Comment by tomholub** [comment]
I asked here about more test data https://github.com/FlowCrypt/flowcrypt-browser/issues/3482
