### ISSUE TITLE
Email providers and some logic questions

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#106]
1. how to be with the private key: 
a) use the private key for all accounts
b) Each account uses own private key. I can filter the private keys by email. This field not yet added to the keys table.

1. Do I must delete contacts after the account sign-out?

1. Does account have own contacts or can use all available contacts in the table?

**Comment by tomholub** [comment]
1) private key
 - decrypting: all private keys are available to decrypt messages on all accounts
 - encrypting: all private keys available. There will be a system how to choose the right key to use for encrypting. For now, just put the public key equivalent of the first private key into contacts for each email account, and then use the standard procedure to find public key in your contacts when sending email (let me know if this is clear, I may need to clarify)

2) do not delete contacts, keep them

3) All contacts are shared across accounts without limitation. There will be no account-level customization of contacts.

**Comment by tomholub** [comment]
We don't support switching between accounts yet, right? We could move this into version 10 and specify the details there further.

**Comment by DenBond7** [comment]
> We don't support switching between accounts yet, right?

Yes, we don't support this yet.

> We could move this into version 10 and specify the details there further.

I think yes. I will add some changes and then I will move this issue into version 10.

**Comment by tomholub** [comment]
> For now, just put the public key equivalent of the first private key into contacts for each email account, and then use the standard procedure to find public key in your contacts when sending email (let me know if this is clear, I may need to clarify)
> 
> Yes, clarify what did you mean, please

When encrypting, you should not use private key. You should use public key. Getting the private key from db and converting it to public every time you encrypt is not necessary.

Instead, during setup, you should put private key into `keys` table and equivalent public key into `contacts` table, just like any other contact.

When encrypting, use the contacts table to look up all recipients, including your own sending email.

**Comment by tomholub** [comment]
So when I write to joe@example.com from my own email, it should try to find both emails in `contacts` table (joe@example + tom@cryptup.org) and encrypt for them.

If we cannot find our own public key in contacts table (maybe user manually deleted it?), then you should pick a private key, turn it into public key, save it into contacts, and use the public key from the contacts (next time).

**Comment by tomholub** [comment]
Let me know if you have more questions / need clarification, or if anything needs to be done on this, else we can close it.
