### ISSUE TITLE
use JavaMail as a replacement for parseDateStr

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#1062]
part of #1051 

Please see if there is any readily available date parsing library for email in Java that behaves similarly and passes our tests. If there is, please use it.

**Comment by DenBond7** [comment]
@tomholub 

 > javascript has a "magic" date parser we use that we'll need in Kotlin. Maybe some mail library has this (we use it to parse email headers)

If we are going to use JavaMail to work with MIME messages we don't need to port `parseDateStr` to Kotlin. JavaMail does it himself

**Comment by DenBond7** [comment]
#1058

**Comment by DenBond7** [comment]
@tomholub Could you clarify where we use `parseDateStr`? I see usage in `flowcrypt-android.js` only.

**Comment by tomholub** [comment]
If you don't use it, then you can skip this.
