### ISSUE TITLE
A bug with show attachments

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#107]
Does not display attachments

**Comment by tomholub** [comment]
confirmed, cannot see attachments in encrypted messages

**Comment by DenBond7** [comment]
Why did this error happen?
Because different providers have some different behavior when working with attachments.

For example:
1. Gmail has next details
```
Content-Type: application/pdf; name="0746-3479-0937-4785.pdf"
Content-Disposition: attachment; filename="0746-3479-0937-4785.pdf"
Content-Transfer-Encoding: base64
X-Attachment-Id: f_j85kxm4k0
```

Gmail uses custom header "X-Attachment-Id" to makes the unique attachment.

2. Yahoo(Outlook) has next details
```
Content-Type: application/pdf
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename="LGDBHE41865.pdf"
Content-ID: <57afb96f-c3a2-68a7-98be-4b1e61428a0f@yahoo.com>
```

Yahoo uses MIME header "Content-ID" to makes the unique attachment.

That's why we received such error.

**Comment by DenBond7** [comment]
For me

> The MIME specification allows us to identify message parts using the header Content-ID. HTML in one part of the message can refer to another part of the message with URLs that use the scheme cid:. Content IDs should be unique across all messages, so you may want to use a generator that uses the host name of the computer sending the message, the current time, and a sequence number to avoid possible collision. Practically, however, many programmers don’t bother following the specs and just use an id they find meaningful. Email clients seem to handle it without trouble.
> 
> When you set the ContentID on the MimeBodyPart, you must include angle brackets (< and >) around the content id. JavaMail does not do it for you, even though the angle brackets are part of the specification for the MIME Content-ID header.
