### ISSUE TITLE
Save project-specific formatting settings in the repo

### ISSUE THREAD

**Issue by IvanPizhenko** [FlowCrypt/flowcrypt-android#1074]
@DenBond7 Such formatting settings can be saved per project and checked in into repo, so you don't need to to tune IDE-wide settings. Then, when you open project, setting become effective automatically, no matter what the IDE-wide settings are. This was already done in another repository and works good. I suggest to do the same here. I can prepare PR.

_Originally posted by @IvanPizhenko in https://github.com/FlowCrypt/flowcrypt-android/pull/1064#issuecomment-796883337_

**Comment by tomholub** [comment]
Yes, this will be good.

@DenBond7 I expect this should cause minimal to none formatting issues, so we shouldn't have big merge conflicts following this update (hopefully).

**Comment by IvanPizhenko** [comment]
@tomholub I'd also introduce ktlint here, as we did in other projects. But this may take some additional effort to reformat non-conforming code.

**Comment by DenBond7** [comment]
> I'd also introduce ktlint here, as we did in other projects. But this may take some additional effort to reformat non-conforming code.

That's a good idea. I added https://github.com/detekt/detekt some time ago. But haven't completed the setup process.

**Comment by IvanPizhenko** [comment]
there is Intellij plugin for ktlint which helps with reformatting code and Gradle plugin which check source code conformance during the build, also can reformat code. But both of them cannot reformat one specific case - too long lines. You'll have to edit such files manually to split too long lines into shorter ones.
