### ISSUE TITLE
Settle on the correct modules.xml content

### ISSUE THREAD

**Issue by IvanPizhenko** [FlowCrypt/flowcrypt-android#1075]
@DenBond7 
My Andriod Studio version info:
Android Studio 4.1.2
Build #AI-201.8743.12.41.7042882, built on December 20, 2020
Registry: ide.new.welcome.screen.force=true, external.system.auto.import.disabled=true
Non-Bundled Plugins: org.intellij.plugins.markdown, org.jetbrains.kotlin, com.samdark.intellij-visual-studio-code-dark-plus

I've made a clean clone of this repo and opened it in the Android Studio, and here's what it has done:
```diff
 <project version="4">
   <component name="ProjectModuleManager">
     <modules>
-      <module fileurl="file://$PROJECT_DIR$/flowcrypt-android.iml" filepath="$PROJECT_DIR$/flowcrypt-android.iml" />
+      <module fileurl="file://$PROJECT_DIR$/.idea/modules/flowcrypt-android.iml" filepath="$PROJECT_DIR$/.idea/modules/flowcrypt-android.iml" />
       <module fileurl="file://$PROJECT_DIR$/.idea/modules/FlowCrypt/flowcrypt-android.FlowCrypt.iml" filepath="$PROJECT_DIR$/.idea/modules/FlowCrypt/flowcrypt-android.FlowCrypt.iml" />
     </modules>
   </component>
-</project>
+</project>
```
Can you please make sure you also have the same latest stable version of the Android Studio and try to do the same?
I believe this way we can find out what it should be.

_Originally posted by @IvanPizhenko in https://github.com/FlowCrypt/flowcrypt-android/pull/1064#issuecomment-796913627_

**Comment by IvanPizhenko** [comment]
I wanted to do a test on the clean machine, how it behaves with module.xml and installed Android Studio on my Windows laptop which didn't have neither IntelliJ IDEA nor Android Studio before, and I have found out that repository is not usable on Windows due to file name issue. See #1076.

**Comment by tomholub** [comment]
We could possibly ignore this file, if it otherwise doesn't have adverse effect to ignore it. It seems to want to keep flipping back and forth

**Comment by IvanPizhenko** [comment]
That's what @DenBond7 have done in the #1077, however in other repos, according to JetBrains support recommendations, we do ignore only following in the `.idea` directory:
```
/shelf/
/workspace.xml
```

**Comment by DenBond7** [comment]
@IvanPizhenko 
> Can you please make sure you also have the same latest stable version of the Android Studio and try to do the same?
I believe this way we can find out what it should be.

I have the following

```
Android Studio 4.1.2
Build #AI-201.8743.12.41.7042882, built on December 20, 2020
Runtime version: 1.8.0_242-release-1644-b3-6222593 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.4.0-66-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 8083M
Cores: 16
Registry: ide.editor.tabs.open.at.the.end=true, ide.new.welcome.screen.force=true, external.system.auto.import.disabled=true, debugger.watches.in.variables=false
Non-Bundled Plugins: com.alayouni.ansiHighlight, String Manipulation, org.asciidoctor.intellij.asciidoc, org.intellij.plugins.markdown, com.intellij.ideolog, org.jetbrains.kotlin, izhangzhihao.rainbow.brackets, mobi.hsz.idea.gitignore, krasa.CpuUsageIndicator, com.developerphil.adbidea, com.kogitune.intellij.androidPostfixCompletion, com.konifar.material_icon_generator, de.mprengemann.intellij.plugin.androidicons, net.nerrd.intellij.plugin.dpicalculator, com.jetbrains.edu, Docker, ru.adelf.idea.dotenv
Current Desktop: ubuntu:GNOME
```
I've also tested with the following on Windows 10:

```
Android Studio 4.1.2
Build #AI-201.8743.12.41.7042882, built on December 20, 2020
Runtime version: 1.8.0_242-release-1644-b01 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Registry: ide.new.welcome.screen.force=true, external.system.auto.import.disabled=true
Non-Bundled Plugins: org.jetbrains.kotlin, de.mprengemann.intellij.plugin.androidicons, Dart, cn.yiiguxing.plugin.translate, io.flutter, wu.seal.tool.jsontokotlin
```

In the end, after importing the project I have the same result that you have. It seems we had old settings, maybe something was changed in the Android Studio settings since 2017. Now all works well. **We can close it.**

>That's what @DenBond7 have done in the #1077, however in other repos, according to JetBrains support recommendations, we do ignore only following in the .idea directory 

I've updated .gitignore with the default rules which you can see if you will create a new sample project via Android Studio.
Also, I've excluded `/.idea/misc.xml`. We had conflicts with this file on different machines. Similar to the following: [link 1](https://stackoverflow.com/questions/38590022/should-we-ignore-misc-xml-and-projectfoldername-iml-in-pycharm-idea-folder), [link 2](https://intellij-support.jetbrains.com/hc/en-us/articles/206544839?page=1#comment_200744749)

**Comment by IvanPizhenko** [comment]
Yes, I've seen new `.gitignore` and it looks good. So I close this one.
