### ISSUE TITLE
It is not possible to work with this repository on Windows

### ISSUE THREAD

**Issue by IvanPizhenko** [FlowCrypt/flowcrypt-android#1076]
git checkout fails as follows:
```
error: invalid path 'docker-mailserver/maildata_source/denbond7.com/android/.Sent/cur/1601981390.M95147P4532.mail,S=1461,W=1504:2,S'
error: invalid path 'docker-mailserver/maildata_source/denbond7.com/android/.Sent/cur/1601981874.M109669P4589.mail,S=401,W=415:2,S'
....
(totally 104 errors like above)
```
Symbol `:` is not allowed in the file names on the NTFS. While allowed on Linux (I can checkout and work with repo on Linux) and possibly on Mac, I think in general we should strongly avoid it. All these files must be renamed (for example, using double underscore instead of colon) and any code that uses it must be accordingly updated.

**Comment by tomholub** [comment]
Agree, this could be updated to make it easier to contribute across platforms

**Comment by IvanPizhenko** [comment]
@DenBond7 So is it possible to do something with this one?

**Comment by DenBond7** [comment]
@IvanPizhenko  I think yes, but it won't be fast. Need to investigate the email server settings. I know that it has different approaches to store messages. But if I won't be able to make migration I have to recreate messages manually. It'll take some time.

**Comment by tomholub** [comment]
Maybe Ivan could later help with this later? It may not need to involve actually recreating messages, rather renaming files and changing the logic of how we access them. There could be a less labor intensive way to do it.

**Comment by DenBond7** [comment]
Helpful links
https://wiki2.dovecot.org/MailboxFormat
https://wiki2.dovecot.org/Migration/MailFormat

**Comment by DenBond7** [comment]
@IvanPizhenko I've added some changes. Please try if that works for you.

**Comment by IvanPizhenko** [comment]
I've merged but will try a bit later. The main point that was preventing using it on Windows is presence of the ":" in file names. If that is no longer there, pretty sure it will work.

**Comment by IvanPizhenko** [comment]
Merged it. Repository checks out after this, so that mean ":" in file names are gone. I think the rest of issues related to Windows, if any, will be more easy to resolve.
