### ISSUE TITLE
port getting `keywords` from Node

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#1080]
@tomholub Please look at this. Need to port getting `keywords` from Node to complete this issue

https://github.com/FlowCrypt/flowcrypt-android/blob/0558575d71d2e45c1186e389c3ff6193cc03c399/FlowCrypt/src/main/java/com/flowcrypt/email/extensions/PGPKeyRingExt.kt#L48

_Originally posted by @DenBond7 in https://github.com/FlowCrypt/flowcrypt-android/issues/1055#issuecomment-797305766_

**Comment by tomholub** [comment]
Thank you - I'll close this as per comment below there - not needed.
