### ISSUE TITLE
Need to cross check `isFullyEncrypted`  impl

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#1087]
Need to cross check this `isFullyEncrypted` - for one thing there is a dummy gnu S2K requiring special treatment, second there could be some null-like encryption method like plain. (sometimes the spec is messy). That will be for another PR.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-android/pull/1085#discussion_r594932563_

**Comment by DenBond7** [comment]
https://github.com/pgpainless/pgpainless/issues/99

**Comment by IvanPizhenko** [comment]
PGPainless has made a change
https://github.com/pgpainless/pgpainless/commit/d082f126b31f9fbc93f328682510753aa7c5cbf3

**Comment by IvanPizhenko** [comment]
Should be already covered in the #1216
