### ISSUE TITLE
Sender email and other recipients not visible when reading an email

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-android#1089]
ref: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgxwLswDplrbdKvjnLFCNLWHlGCQg

>When I receive email I don't see if it's for me or I am just in copy. And to whom else this email was sent.

This is a good point!

**Comment by tomholub** [comment]
Yes, I had the same issue - this would be a duplicate of #321

**Comment by seisvelas** [comment]
I even commented on that one before! Sorry, I'd forgotten about it. 

Thanks!
