### ISSUE TITLE
verify signed messages(inband)

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#1097]
When we receive a signed message, currently we only render it in gray border. We should also parse out information from the message about which key signed it, and do signature verification. 

Before loading the message, we'd pull public keys from local contacts that are recorded for the email that we received the message from. Then offer these to the verification method as possible public keys it was signed with. If none of them match the signed message, we'd show signature not verified.

See https://github.com/FlowCrypt/flowcrypt-ios/issues/278#issuecomment-959548150 and further discussion below for what to render in what situation (not verified, valid, invalid)

**Comment by tomholub** [comment]
Here, before loading the message, we'd pull public keys from local contacts that are recorded for the email that we received the message from. Then offer these to the verification method as possible public keys it was signed with. If none of them match the signed message, we'd show "could not verify message".

This should be done after issues in https://github.com/FlowCrypt/flowcrypt-android/milestone/90 so that we can pull more than one public key per email.

**Comment by tomholub** [comment]
Here a code snippet from iOS, regarding rendering various signature statuses

```swift
  private func renderPgpSignatureCheckResult(
    signature: VerifyRes?, 
    sender: RecipientWithOrderedPublicKeys
  ) -> ProcessedMessage.MessageSignature {
    if signature is nil then return .unsigned // render "not signed" in red
    if signature.error is not nil then return .error(signature.error) // render the "cannot verify signature: \(error)"
    if signature.signer is nil then return .unsigned // render "not signed" in red
    let signingPubKey = sender.pubkeys.find { $0.longids.contains(signature.signer) }
    if signingPubKey is nil or signature.match is nil then return .missingPubkey(longid: signature.signer) // render "cannot verify signature: no Public Key $longid" in red
    if signature.match is false then return .bad // render "bad signature" in red
    return .good
  }
```

**Comment by tomholub** [comment]
As this issue is designed, the user will always see "no public key" when they receive a signed message from a new person. To fix this, either in the same PR or in a separate PR, we improve the flow as follows:

1) user taps a message
2) message gets downloaded from Gmail API
3) message gets processed / decrypted / verified with whatever public keys we have locally
4) result gets rendered including signature verification, and if we are not missing any public keys, then this is the last step
5) if we are missing a public key, the verification "badge" will show gray `🕒 verifying signature..`
6) at this point we fetch remote public keys **by sender email**, but user is no longer waiting for it
7) after remote public keys are fetched and local storage is updated, we check if any of the keys from local storage now contain the `longid` that signed the message. If they don't, now we render "missing pub key" badge
8) if one of the keys now contain the longid of the key that signed the message, we re-process the whole message with that public key - in background. The badge still says `🕒 verifying signature`. Once we've done re-processing the message, we only look at the result of signature verification and re-render the badge with the final verification result, without re-rendering the rest of the message.

**Comment by tomholub** [comment]
Looks like this on iOS

![image](https://user-images.githubusercontent.com/6306961/143597414-9e7143d1-9303-4394-8d78-b58ccf4442ca.png)

**Comment by tomholub** [comment]
@DenBond7 I'd like you to start working in this tomorrow - please check if you have everything you need.

**Comment by DenBond7** [comment]
> Here a code snippet from iOS, regarding rendering various signature statuses
> Looks like this on iOS

@tomholub Do we have examples for all cases? I mean UI

**Comment by tomholub** [comment]
yup I'll take some screenshots

**Comment by DenBond7** [comment]
Need to test the following cases:(in progress)

- [ ] signed for `sender@flowcrypt.test`. App has a cached pub key for `sender@flowcrypt.test`

**Comment by tomholub** [comment]
![IMG_1521](https://user-images.githubusercontent.com/6306961/145085927-b2ac6ad1-bef9-434a-be2f-3881e531d6b5.PNG)
![IMG_1520](https://user-images.githubusercontent.com/6306961/145085937-88840a39-123f-4738-a2b7-8f3064bedaa0.PNG)
![IMG_1519](https://user-images.githubusercontent.com/6306961/145085941-3dfce6d0-cb17-4f57-a1ea-020dc0e60c2c.PNG)
![IMG_1518](https://user-images.githubusercontent.com/6306961/145085946-d0d50e76-5ffd-4f9d-af43-5faac2a0aeff.PNG)
![IMG_1517](https://user-images.githubusercontent.com/6306961/145085948-a538a64b-ab2c-4bc7-8bc6-8b01eb474c03.PNG)

**Comment by tomholub** [comment]
This one is a bit broken - the badge is supposed to wrap around

![IMG_C8829161E870-1](https://user-images.githubusercontent.com/6306961/145086140-6cf010f7-b720-4776-be90-b049aaf59bf3.jpeg)

**Comment by DenBond7** [comment]
Thank you!

**Comment by tomholub** [comment]
I'll send you credentials for that account. You can test

**Comment by tomholub** [comment]
Here is updated code from iOS, that also takes into account partial and mixed signatures. Maybe, that would be for another issue later.

I think more interesting for you could be the TypeScript code that produces `verifyRes` ? 

```ts
    private func evaluateSignatureVerificationResult(
        signature: MsgBlock.VerifyRes?
    ) async -> ProcessedMessage.MessageSignature {
        guard let signature = signature else { return .unsigned }
        if let error = signature.error { return .error(error) }
        guard let signer = signature.signer else { return .unsigned }
        guard signature.match != nil else { return .missingPubkey(signer) }
        guard signature.match == true else { return .bad }
        guard signature.partial != true else { return .partial }
        guard signature.mixed != true else { return .goodMixed }
        return .good
    }
}
```

**Comment by tomholub** [comment]
Were you able to log into the e2e test account successfully?

**Comment by DenBond7** [comment]
> Were you able to log into the e2e test account successfully?

Yup, all works perfectly.

**Comment by DenBond7** [comment]
@tomholub honestly, I'm a little confused with the current code. Currently, we support various types of different cases. I mean we support a lot of time MIME messages: with inner MIME, with PGP (encryption, signing), even PGP in PGP. We split all parsed msg blocks into 2 groups: `content` and `other`(like atts). After that, we transform all blocks from `content` to formated HTML. Now I'm thinking about how to deal with signatures. 

Please loot at this example

```
Return-Path: <denbond7@flowcrypt.test>
Delivered-To: default@flowcrypt.test
Received: from mail.flowcrypt.test
	by mail.flowcrypt.test with LMTP
	id kgZDL3j0sGGSBQAAc/RpdQ
	(envelope-from <denbond7@flowcrypt.test>)
	for <default@flowcrypt.test>; Wed, 08 Dec 2021 18:07:52 +0000
Received: from localhost (localhost [127.0.0.1])
	by mail.flowcrypt.test (Postfix) with ESMTP id BB9526C0A07
	for <default@flowcrypt.test>; Wed,  8 Dec 2021 18:07:52 +0000 (UTC)
Date: Wed, 8 Dec 2021 20:07:49 +0200 (GMT+02:00)
From: denbond7@flowcrypt.test
To: default@flowcrypt.test
Message-ID: <111413685.9.1638986869313@flowcrypt.test>
Subject: Encrypted + signed
Mime-Version: 1.0
Content-Type: multipart/mixed; 
	boundary="----=_Part_8_111556158.1638986869241"

------=_Part_8_111556158.1638986869241
Content-Type: text/plain; charset=us-ascii
Content-Transfer-Encoding: 7bit

-----BEGIN PGP MESSAGE-----
Version: PGPainless

hF4D16Pe22XLHvsSAQdA0EYKe+cg7EFOsmSGIUz55HKj9mAQ0l5CD/SnNvdEyH8w
DVGPGDO3+wYyR6vjWdqzLl68JGwfpYMY5H8avp+xJXojaOYNU8jIeUWM2HaRDRfM
hF4DTxRYvSK3u1MSAQdAvCdXhN2UyZHo9SNIhkc3QbnJUpytM9ImItOjadJQi10w
wDYNT+8ymf/nQk0RpUUkqVEcah2go9R3gjbvlbr2tlfYAJa2b2s7FMuMv8OqO8V0
0rcB1aUqzdIKfWHPY6HfuSTAR9mlD5ucPp3unLYzo857h4v16sAUxVCxo3Y4RlXT
qL2MttauH3ZbUgjRmSZU3V+5zGEBZykjF+0aBcxIaB4jEFQT0AvZ2TconoNMRChf
HZNifsrjFVc8JT1OaXdceH5v09BtPNfzvudBMU0GzQ7qymHEdXCpro4D1M1D+eJ6
M70+vltwnnY2eezULhsNsB9nXBZjO6eGUiADeCIHA0E0s+4sEXCChCM=
=iI3Z
-----END PGP MESSAGE-----

-----BEGIN PGP MESSAGE-----
Version: PGPainless

hF4D16Pe22XLHvsSAQdA0EYKe+cg7EFOsmSGIUz55HKj9mAQ0l5CD/SnNvdEyH8w
DVGPGDO3+wYyR6vjWdqzLl68JGwfpYMY5H8avp+xJXojaOYNU8jIeUWM2HaRDRfM
hF4DTxRYvSK3u1MSAQdAvCdXhN2UyZHo9SNIhkc3QbnJUpytM9ImItOjadJQi10w
wDYNT+8ymf/nQk0RpUUkqVEcah2go9R3gjbvlbr2tlfYAJa2b2s7FMuMv8OqO8V0
0rcB1aUqzdIKfWHPY6HfuSTAR9mlD5ucPp3unLYzo857h4v16sAUxVCxo3Y4RlXT
qL2MttauH3ZbUgjRmSZU3V+5zGEBZykjF+0aBcxIaB4jEFQT0AvZ2TconoNMRChf
HZNifsrjFVc8JT1OaXdceH5v09BtPNfzvudBMU0GzQ7qymHEdXCpro4D1M1D+eJ6
M70+vltwnnY2eezULhsNsB9nXBZjO6eGUiADeCIHA0E0s+4sEXCChCM=
=iI3Z
-----END PGP MESSAGE-----

------=_Part_8_111556158.1638986869241--
```

Both of these PGP blocks are encrypted and signed. I understand that it is an irregular case. But how should I handle such a case? The Android app can parse, decrypt and show this content. But what about inband signatures? Here we can have a verified signature for the first PGP block and an unverified for the second.

**Comment by tomholub** [comment]
Good question. I'll share what we've done on iOS.

**Comment by DenBond7** [comment]
Also, It would be nice to have the latest version of the iOS app, maybe @Kharchevskyi can update it

**Comment by tomholub** [comment]
I can make a build if you can tell me the uuid of your iOS device.

**Comment by tomholub** [comment]
```ts
export type VerifyRes = {
  signer?: string;
  match: boolean | null;
  error?: string;
  mixed?: boolean;
  partial?: boolean;
};

export const fmtContentBlock = (allContentBlocks: MsgBlock[]): { contentBlock: MsgBlock, text: string } => {
  let msgContentAsHtml = '';
  let msgContentAsText = '';
  const contentBlocks = allContentBlocks.filter(b => !Mime.isPlainImgAtt(b))
  const imgsAtTheBottom: MsgBlock[] = [];
  const inlineImgsByCid: { [cid: string]: MsgBlock } = {};
  for (let plainImgBlock of allContentBlocks.filter(b => Mime.isPlainImgAtt(b))) {
    if (plainImgBlock.attMeta!.cid) {
      inlineImgsByCid[plainImgBlock.attMeta!.cid.replace(/>$/, '').replace(/^</, '')] = plainImgBlock;
    } else {
      imgsAtTheBottom.push(plainImgBlock);
    }
  }

  var verifyRes: (VerifyRes | undefined) = undefined;
  var mixedSignatures = false;
  var signedBlockCount = 0;
  for (const block of contentBlocks) {
    if (block.verifyRes) {
      ++signedBlockCount;
      if (!verifyRes) {
        verifyRes = block.verifyRes;
      } else if (!block.verifyRes.match) {
        if (verifyRes.match) {
          verifyRes = block.verifyRes;
        }
      } else if (verifyRes.match && block.verifyRes.signer !== verifyRes.signer) {
        mixedSignatures = true;
      }
    }
    if (block.type === 'decryptedText') {
      msgContentAsHtml += fmtMsgContentBlockAsHtml(Str.asEscapedHtml(block.content.toString()), 'green');
      msgContentAsText += block.content.toString() + '\n';
    } else if (block.type === 'decryptedHtml') {
      // todo - add support for inline imgs? when included using cid
      msgContentAsHtml += fmtMsgContentBlockAsHtml(stripHtmlRootTags(block.content.toString()), 'green');
      msgContentAsText += Xss.htmlUnescape(Xss.htmlSanitizeAndStripAllTags(block.content.toString(), '\n') + '\n');
    } else if (block.type === 'plainText') {
      msgContentAsHtml += fmtMsgContentBlockAsHtml(Str.asEscapedHtml(block.content.toString()), 'plain');
      msgContentAsText += block.content.toString() + '\n';
    } else if (block.type === 'plainHtml') {
      const dirtyHtmlWithImgs = fillInlineHtmlImgs(stripHtmlRootTags(block.content.toString()), inlineImgsByCid);
      msgContentAsHtml += fmtMsgContentBlockAsHtml(dirtyHtmlWithImgs, 'plain');
      msgContentAsText += Xss.htmlUnescape(Xss.htmlSanitizeAndStripAllTags(dirtyHtmlWithImgs, '\n') + '\n');
    } else if (block.type === 'verifiedMsg') {
      msgContentAsHtml += fmtMsgContentBlockAsHtml(block.content.toString(), 'gray');
      msgContentAsText += Xss.htmlSanitizeAndStripAllTags(block.content.toString(), '\n') + '\n';
    } else {
      msgContentAsHtml += fmtMsgContentBlockAsHtml(block.content.toString(), 'plain');
      msgContentAsText += block.content.toString() + '\n';
    }
  }

  if (verifyRes && verifyRes.match) {
    if (mixedSignatures) {
      verifyRes.mixed = true;
    }
    if (signedBlockCount > 0 && signedBlockCount != contentBlocks.length) {
      verifyRes.partial = true;
    }
  }

  for (const inlineImg of imgsAtTheBottom.concat(Object.values(inlineImgsByCid))) { // render any images we did not insert into content, at the bottom
    let alt = `${inlineImg.attMeta!.name || '(unnamed image)'} - ${inlineImg.attMeta!.length! / 1024}kb`;
    // in current usage, as used by `endpoints.ts`: `block.attMeta!.data` actually contains base64 encoded data, not Uint8Array as the type claims
    let inlineImgTag = `<img src="data:${inlineImg.attMeta!.type};base64,${inlineImg.attMeta!.data}" alt="${Xss.escape(alt)} " />`;
    msgContentAsHtml += fmtMsgContentBlockAsHtml(inlineImgTag, 'plain');
    msgContentAsText += `[image: ${alt}]\n`;
  }

  msgContentAsHtml = `
  <!DOCTYPE html><html>
    <head>
      <meta name="viewport" content="width=device-width" />
      <style>
        body { word-wrap: break-word; word-break: break-word; hyphens: auto; margin-left: 0px; padding-left: 0px; }
        body img { display: inline !important; height: auto !important; max-width: 95% !important; }
        body pre { white-space: pre-wrap !important; }
        body > div.MsgBlock > table { zoom: 75% } /* table layouts tend to overflow - eg emails from fb */
      </style>
    </head>
    <body>${msgContentAsHtml}</body>
  </html>`;
  const contentBlock = MsgBlock.fromContent('plainHtml', msgContentAsHtml);
  contentBlock.verifyRes = verifyRes;
  return { contentBlock: contentBlock, text: msgContentAsText.trim() };
}
```

**Comment by DenBond7** [comment]
> I can make a build if you can tell me the uuid of your iOS device.

Thanks! I will look at this info tomorrow in the morinig.

**Comment by tomholub** [comment]
That's assuming that you have similar logic to separate "content blocks" that get combined into a single renderable "content block" for the webview. Which I think you already have.

The most important part is this, which joins all of the individual `verify res` into one combined one.

```ts
    if (block.verifyRes) {
      ++signedBlockCount;
      if (!verifyRes) {
        verifyRes = block.verifyRes;
      } else if (!block.verifyRes.match) {
        if (verifyRes.match) {
          verifyRes = block.verifyRes;
        }
      } else if (verifyRes.match && block.verifyRes.signer !== verifyRes.signer) {
        mixedSignatures = true;
      }
    }
```

and this, which adds information about whether all blocks are signed, and if it was signed with mixed keys

```ts
  if (verifyRes && verifyRes.match) {
    if (mixedSignatures) {
      verifyRes.mixed = true;
    }
    if (signedBlockCount > 0 && signedBlockCount != contentBlocks.length) {
      verifyRes.partial = true;
    }
  }
```

Then it gets returned as a single `VerifyRes` which actually you should probably call `CombinedVerifyRes` since the type is different.

```ts
contentBlock.verifyRes = verifyRes;
```

That's it for the signature processing part (on iOS done in TypeScript)

Then you have rendering part (on iOS done in Swift) which is this comment https://github.com/FlowCrypt/flowcrypt-android/issues/1097#issuecomment-988191413 and it directly uses that `CombinedVerifyRes` output.

Together, they make sure that **good** signature means that all content blocks are signed and successfully verified, and they are all signed with the same key.

**good+mixed** signature means that all content blocks are signed, but could have been signed by different key.

**partial** means that only some of the content blocks are signed. But the ones that are, have valid signature.

etc as per https://github.com/FlowCrypt/flowcrypt-android/issues/1097#issuecomment-988191413

**Comment by DenBond7** [comment]
Great. I will investigate. Thank you!

**Comment by DenBond7** [comment]
To make this PR a little simpler I propose to verify signed content just with existing pub keys. Fetching remote pub keys will be completed in a separate issue.

**Comment by tomholub** [comment]
Sure

**Comment by DenBond7** [comment]
@tomholub Is it possible to use the same icons for statuses(`signed`, `encrypted`) as we use them on iOS? It would be great to have SVG icons for that.

**Comment by tomholub** [comment]
They come from https://developer.apple.com/sf-symbols/ which is ios specific, I don't think we can use them on Android - there may be a license restriction.

**Comment by DenBond7** [comment]
Got it. In that case, I will use internal icons.

**Comment by DenBond7** [comment]
just UI examples for badges

![image](https://user-images.githubusercontent.com/2863246/145564894-4dacf833-3d65-40f5-ae9f-31ddbd90383c.png)
![image](https://user-images.githubusercontent.com/2863246/145565016-d8092181-0403-493a-b02c-2238d8be1853.png)
![image](https://user-images.githubusercontent.com/2863246/145565109-db4cd945-cc85-480f-bc7c-abcda6db4d2f.png)

**Comment by tomholub** [comment]
all good

**Comment by DenBond7** [comment]
@tomholub Please let me clarify some questions: what does "bad signature" mean in detail?

**Comment by tomholub** [comment]
> @tomholub Please let me clarify some questions: what does "bad signature" mean in detail?

Signature could not be successfully verified for other reason than not having the right public key.

For example, the message was changed in transit.

**Comment by DenBond7** [comment]
## What is already done?

1. offline verification of inband signature that comes as PGP message

```
-----BEGIN PGP MESSAGE-----
Version: PGPainless

owGbwMvMwCXWaL/vvdiErcGMpxWSGEAgODM9LzVFoTyzJEOhJCNVoTg1OT8vRSE7
tbKjlIVBjIuBjZUpcevzDwyKnAIwzWKKLHfMHwmFMAmaprieNocJp/Uy/A/MjTzK
N9UkpXLTg0dXFFasM5wQxT93ufHj+o9hhzuO97YxMlwwsG+6lNHn4xkilcwbmmhx
/ernRzJH7rFaPLM7d/zlHj4A
=Yz2p
-----END PGP MESSAGE-----
```
2. offline verification of `cleartext` signature

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

[...]
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v0.9.7 (GNU/Linux)
Comment: For info see http://www.gnupg.org

iEYEARECAAYFAjdYCQoACgkQJ9S6ULt1dqz6IwCfQ7wP6i/i8HhbcOSKF4ELyQB1
oCoAoOuqpRqEzr4kOkQqHRLE/b8/Rw2k
=y6kj
-----END PGP SIGNATURE-----
```

3. Added examples to the local email server for the following cases

### I. Inband signature
**can't verify signature (missing pub key)**
- [x] encrypted + signed
- [x] only signed

**valid signature (good)**
- [x] encrypted + signed
- [x] only signed

**valid signature (partially)**
- [x] encrypted + signed
- [x] only signed

**valid signature (good+mixed)**
- [x] encrypted + signed
- [x] only signed

## What is left?

1. Add tests for `Inband` signature
2. Add tests for `cleartext` signature
3. Add support of `detached` signature
4. Add online verification(`lookup`)

For simplicity, I propose to do 1. in the current issue, move 2 for soon, and do 3 and 4 in separate issues.

@tomholub What do you think?

**Comment by tomholub** [comment]
What is `Inband` signature?

**Comment by tomholub** [comment]
Agree that 2 can be moved to `soon` milestone. Actually, 3 and 4 could also be done in a different milestone. I'll file them.

**Comment by DenBond7** [comment]
> What is `Inband` signature?

It's PGPainless terminology :), means not detached.

**Comment by tomholub** [comment]
Got it. Yes - agree to finish 1 here, and then move onto the next task in current milestone. (forward attachments)
