### ISSUE TITLE
allow encrypting files up to 25MB

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#1099]
now that https://github.com/FlowCrypt/flowcrypt-android/issues/1059 is done, can we allow encrypting of files as large as we want? I would like to allow up to 25MB for all users.

**Comment by DenBond7** [comment]
#140

**Comment by DenBond7** [comment]
For me. How to investigate max message size.(From [wikipedia](https://en.wikipedia.org/wiki/Simple_Mail_Transfer_Protocol#Extension_discovery_mechanism))

<pre><font color="#4E9A06"><b>denbond7@WorkPC</b></font>:<font color="#3465A4"><b>~</b></font>$ telnet localhost 25
Trying 127.0.0.1...
Connected to localhost.
Escape character is &apos;^]&apos;.
220 mail.denbond7.com ESMTP
EHLO debug
250-mail.denbond7.com
250-PIPELINING
250-SIZE 10240000
250-ETRN
250-STARTTLS
250-AUTH PLAIN LOGIN
250-AUTH=PLAIN LOGIN
250-ENHANCEDSTATUSCODES
250-8BITMIME
250-DSN
250 CHUNKING</pre>
