### ISSUE TITLE
non-gmail account: store message in Sent folder later (queue)

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#110]
This is related to #91, so if we use a queue for everything, this will get solved as a side effect.

If I'm sending a 3MB attachment, on yahoo it will get uploaded two times (once send, once store) which takes a LOT of time.

**Comment by tomholub** [comment]
We can probably move this out of this milestone, let me know if you agree

**Comment by DenBond7** [comment]
Yes, I agree. It's not necessary right now.
