### ISSUE TITLE
decrypt large messages and pgp/mime encoded files of any size

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#1101]
after #1057 which has to be also done in a streaming manner, we should be able to decrypt messages and pgp/mime encrypted attachments inside of them regardless of size

This is similar to #1100 except that issue is about stand-alone encrypted attachment files, whereas this issue is about attachments that are inside of a pgp/mime encrypted message.

**Comment by DenBond7** [comment]
PgpMsg.fmtContentBlock() 
--------------------------------------Node-------------------------------------------------------Kotlin------------------------------------------------

![image](https://user-images.githubusercontent.com/2863246/126447179-cb9672ab-9ac2-4665-8d4f-8b7fd1258614.png)

**Comment by tomholub** [comment]
Hm it's missing some chunks of text - not good. I'll file an issue and @IvanPizhenko can have a look.

**Comment by tomholub** [comment]
It's not strictly necessary that we support very large messages immediately after switching to Kotlin. If streaming large messages involves additional work, then that can be done later after the switch.

**Comment by DenBond7** [comment]
It will be finally resolved with #1420. I'm closing it for now.
