### ISSUE TITLE
update readme or add script to check for compilation issues

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#1106]
@IvanPizhenko 
> Now just want to see if semaphore passes.

It was compilation issues. To prevent such an issue you can use 2 ways (for both way you have to have at least 1 connected device - an emulator or a real device):

1. Use Android Studio to just print tests names(**Print all tests**)
![image](https://user-images.githubusercontent.com/2863246/111960888-fca31200-8af8-11eb-8c59-dd5ac4ab20e0.png)

If that task passes there are no compilation issues

2. Use the following command `./gradlew clean :FlowCrypt:connectedDevTestDebugAndroidTest -Pandroid.testInstrumentationRunnerArguments.log=true`. If the task fails you will see compilation errors like this
![image](https://user-images.githubusercontent.com/2863246/111961258-818e2b80-8af9-11eb-8ab1-9e94378b77bd.png)

_Originally posted by @DenBond7 in https://github.com/FlowCrypt/flowcrypt-android/issues/1102#issuecomment-803872204_

**Comment by tomholub** [comment]
I'm pulling this out into an issue - maybe can add `./script/compile.sh` or something similar. Either that, or update the readme - this is useful to know.

**Comment by IvanPizhenko** [comment]
I'd say test.sh

**Comment by IvanPizhenko** [comment]
There's a trouble with running tests inside the cloud Linux VM. I just can't run native x86 Android emulator.
```
Unfortunately, your computer does not support hardware accelerated virtualization.
Here are some of your options:
 1) Use a physical device for testing
 2) Develop on a Windows/OSX computer with an Intel processor that supports VT-x and NX
 3) Develop on a Linux computer that supports VT-x or SVM
 4) Use an Android Virtual Device based on an ARM system image
   (This is 10x slower than hardware accelerated virtualization)
```
Will try ARM one - looks like the only option.
The other option is to purchase dedicated physical box for Linux -$500 min for something reasonable - do not plan to do that.

**Comment by IvanPizhenko** [comment]
But tests run in the CI. How that is possible? Does CI use physical machines?

**Comment by DenBond7** [comment]
CI supports virtualization. We can run x86 emulators

**Comment by DenBond7** [comment]
> I'd say test.sh

Actually, you just print all tests. I think it'll be better to call it print-all-tests.sh.

**Comment by IvanPizhenko** [comment]
@DenBond7 I've found that there's already a script named `run-all-test.sh` with a following content:
```shell
./gradlew --console=verbose :FlowCrypt:connectedDevTestDebugAndroidTest
```
Isn't this the same?

**Comment by IvanPizhenko** [comment]
Found something about "nested virtualization" - will try to enable it on the VM. But meanwhile trying the ARM image.

**Comment by IvanPizhenko** [comment]
Hmm... no luck with ARM either...
```
The emulator process for AVD ARM_Nexus_S_API_S was killed.
```
seems like need to try that "nested virtualization"

**Comment by DenBond7** [comment]
@IvanPizhenko 

> Isn't this the same?

Almost the same. `run-all-test.sh ` runs all tests. `print-all-tests.sh` should be just print all tests.

> You've added -Pandroid.testInstrumentationRunnerArguments.log=true. What does it mean?

From [here](https://developer.android.com/reference/android/test/InstrumentationTestRunner)

`To run in 'log only' mode -e log true This option will load and iterate through all test classes and methods, but will bypass actual test execution. Useful for quickly obtaining info on the tests to be executed by an instrumentation command.`

> Maybe just update that script and add this extra option?

Yes, we can do that.

**Comment by DenBond7** [comment]
> Hmm... no luck with ARM either...
> 
> ```
> The emulator process for AVD ARM_Nexus_S_API_S was killed.
> ```
> 
> seems like need to try that "nested virtualization"

@IvanPizhenko Please look at this line

https://github.com/FlowCrypt/flowcrypt-android/blob/63b6748abf4fd92a3660da245be33b0b184a88c1/script/ci-install-android-sdk.sh#L15

That's how we enable virtualization.

**Comment by IvanPizhenko** [comment]
I am talking about enabling nested virtualization in the VM settings. At the moment VM itself does not support it. Android studio has already installed emulator but it cannot be used because no any virtualization available in the my Linux VM.

**Comment by IvanPizhenko** [comment]
I'd rather need to do something like this
https://stackoverflow.com/questions/53931366/how-to-enable-nested-virtualization-on-an-existing-google-cloud-vm-instance/53934114

**Comment by tomholub** [comment]
Thank you for looking into this - please document the result. I haven't run the Android test suite myself yet.

**Comment by tomholub** [comment]
@IvanPizhenko are you in fact on Windows, and running a linux box in a VM itself? Is it VMWare or something else?

That would indeed explain why you cannot easily virtualize. Our CI most likely runs Ubuntu in a VM on top of Ubuntu, that may be a different situation than what you are doing, since they may be using different software to virtualize their host Ubuntu system.

**Comment by tomholub** [comment]
I'm thinking, if you are on Windows it may be more worthwhile to focus on #1076 which would allow you to skip these nested virtualization issues.

**Comment by IvanPizhenko** [comment]
I am currently using GCloud instance. I think it is faster to recreate instance with nested virtualization enabled than solve #1076. Another problem with Windows is that tests use Docker. Docker on Windows requires WSL2, and WSL2 works bad with VirtualBox (read this thread https://github.com/MicrosoftDocs/WSL/issues/798 ), which I have to use for some other stuff. So in sense of running tests Windows unfortunately is not a variant for me.

**Comment by tomholub** [comment]
In that case, you may be able to follow the `semaphore.yml` file more or less step by step to get tests working there.

**Comment by IvanPizhenko** [comment]
Just recreated VM with nested virtualization, started AVD via AVD Manger and it just works. Just if someone else needs to do the same - one extra step is to add your Linux user into the group kvm.
