### ISSUE TITLE
encryptKey and decryptKey exceptions should not be ignored

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#1107]
@IvanPizhenko Please tell me is there any reason to don't print the `stacktrace` of an exception?

_Originally posted by @DenBond7 in https://github.com/FlowCrypt/flowcrypt-android/pull/1103#discussion_r598600901_

I'd say silently swallowing the exceptions is not ideal - I'd rather throw them so that we can deal with them. Returning an empty string could cause data loss. Let's say you change pass phrase of existing private key. Something fails. The result is empty string and that gets saved back to storage, replacing original private key -> data loss.

**Comment by tomholub** [comment]
I think the solution here is to not catch the exceptions at all.

**Comment by IvanPizhenko** [comment]
I just tried to mimic what typescript does and don't break existing code. Here is example of how it is used:
```kotlin
        val encryptedKey = PgpKey.encryptKey(decryptedKey, newPassphrase)

        if (TextUtils.isEmpty(encryptedKey)) {
          throw IllegalStateException("Can't encrypt key with longid " + longId!!)
        }
```
well, I can rewrite that using exceptions

**Comment by tomholub** [comment]
Yup - better throw that exception directly in `encryptKey`, to not rely on developers having to remember to test for it after.
