### ISSUE TITLE
Prepare version 1.1.6 to a release

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#1108]
It looks like in this version we will be able to replace all node functionality except decrypting messages (because of some complex parsing going on just before decryption). Decrypting messages will probably be addressed in 1.1.7.

Does this mean that test reliability could be improved for all tests except message decrypt tests? Or does node need to be completely gone for it to improve?

**Comment by DenBond7** [comment]
@tomholub Unfortunately, we should completely drop the Node realization(I have to remove that code) to improve tests execution.

**Comment by tomholub** [comment]
understood

**Comment by DenBond7** [comment]
- [ ] check all tests
- [ ] test the app manually
- [ ] check build release apk

**Comment by DenBond7** [comment]
This release will include the following changes

1. Updated libs
2. Updated the Google Play icons. Migrated to use only vectors for the launcher icon.
3. Improved switching between accounts
4. Dropped support for Android 7
5. Ported all calls for Node.js to Kotlin (except decryption)
6. Migrated to use JavaMail to compose a message
7. Fixed deleting messages using IMAP
8. Fixed the permission issue for attachments

**Comment by DenBond7** [comment]
Adroid Instrumentation tests were passed
![image](https://user-images.githubusercontent.com/2863246/113289904-87ee8580-92f9-11eb-9288-21cf98e57b9b.png)

**Comment by tomholub** [comment]
All good. Will there be a separate PR to finalize the release, or it's not needed this time?

**Comment by DenBond7** [comment]
I'm going to add a few changes to the current issue. We can make a separate PR where you can modify 
```
appVersionCode = 115
appVersionName = '1.1.5'
```
or you can just update a PR that I'm going to create. This issue means preparing for production a new version 1.1.6 with minor changes that we don't need to extract to separate issues. I think the separate PR will be better(to be much clear)

**Comment by tomholub** [comment]
did a 10% release
