### ISSUE TITLE
start using Kotlin code where possible, drop deprecated node calls

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#1109]
The following already have ports available that is (I think) not used yet:

- [x] [zxcvbnStrengthBar](https://github.com/FlowCrypt/flowcrypt-android/issues/1110) - #1061
- [x] [parseKeys](https://github.com/FlowCrypt/flowcrypt-android/issues/1119) - #1052 and #1053
- [x] [Encrypt/decrypt a key ](https://github.com/FlowCrypt/flowcrypt-android/issues/1129)

**Comment by DenBond7** [comment]
@tomholub yes, you are right
