### ISSUE TITLE
Can't import keys exported from OpenKeyChain app

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-android#1111]
> FlowCrypt simply did not import the keys that were exported by OpenKeyChain.
> 
> I was tempted to send you a copy of the file, but it contains my private key so that I will not send it.
> 
> Just install OpenKeyChain on an Android phone, import a private key into it and then try to export it to FlowCrypt on the same phone

ref: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgxwLswFxLTVFcDbxbbzrDmKKgsnM

I haven't tried this out myself yet, but I will momentarily and will report results (whether I can reproduce it or not)

**Comment by tomholub** [comment]
Maybe OpenKeyChain uses binary format? (in which case chrome extension should accept it)

**Comment by seisvelas** [comment]
>Maybe OpenKeyChain uses binary format? (in which case chrome extension should accept it)

Yep, this indeed appears to be the problem! I've advised the user on how they can work around this to load their OpenKeyChain key into FlowCrypt on Android.

**Comment by tomholub** [comment]
I would still fix this on Android - this is in fact duplicate of #309
