### ISSUE TITLE
update readme regarding test annotation

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#1115]
> @DenBond7 should I put this annotation on the any new tests that I'm introducing? I've assumed tests would go to CI by default, but seems like you are marking test explicitly to have them in the CI.

Yes, if we are talking about [Android Instrumentation tests ](https://developer.android.com/training/testing/unit-testing/instrumented-unit-tests)(`../FlowCrypt/src/androidTest/java`). Don't need to do that for Junit tests (`../FlowCrypt/src/test/java`)

_Originally posted by @DenBond7 in https://github.com/FlowCrypt/flowcrypt-android/issues/1103#issuecomment-804657898_

**Comment by DenBond7** [comment]
Reassigned. There are some Android things.
