### ISSUE TITLE
Waited for the root of the view hierarchy to have window focus and not request layout for 10 seconds

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#1121]
ref https://flowcrypt.semaphoreci.com/jobs/c44c169a-f790-4c25-aac7-ae7e220203f0

java.lang.RuntimeException: Waited for the root of the view hierarchy to have window focus and not request layout for 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus. Root:28:03
	Root{application-window-token=android.view.ViewRootImpl$W@10705e7, window-token=android.view.ViewRootImpl$W@10705e7, has-window-focus=false, layout-params-type=1, layout-params-string={(0,0)(fillxfill) sim={forwardNavigation} ty=BASE_APPLICATION wanim=0x10302fe

During that issues, we can see the following

![image](https://user-images.githubusercontent.com/2863246/112284776-4410d600-8c92-11eb-94ed-7d36c003f847.png)

**Comment by DenBond7** [comment]
It seems an Android emulator bug :(

**Comment by tomholub** [comment]
It would theoretically be possible to use an actual Android device for testing. We'd just need to set up a physical testing rig, or better use a service that comes attached with a physical android phone.

**Comment by DenBond7** [comment]
Need to investigate this problem. It might crash on one emulator but works great on another one (for example with a different Android version).

**Comment by DenBond7** [comment]
> It seems an Android emulator bug :(

It seems this one https://github.com/FlowCrypt/flowcrypt-android/issues/1116 relates to the Android emulator bug too. After adding some debug code I've found that sometimes during tests the emulator turns off. I will try to switch to another one(maybe a different Android version).

**Comment by DenBond7** [comment]
I'm moving it to later. I haven't seen such a bug for a long time

**Comment by IvanPizhenko** [comment]
Why can emulator turn off?

**Comment by DenBond7** [comment]
@IvanPizhenko 
> Why can emulator turn off suddenly?

It very depends. For now, most problems were described here https://github.com/FlowCrypt/flowcrypt-android/issues/1105.
Due to using `Node.js` I have to increase the RAM of an emulator. But it seems it causes `device offline` issue. If I use an emulator as-is very often we receive `OutOfMemoryException`. To prevent that I could use [Android Test Orchestrator](https://developer.android.com/training/testing/junit-runner#using-android-test-orchestrator). But in that case, every test will take 3-4 seconds additional time and sometimes a test fails due to `Node.js.`


I hope after dropping `Node.js` we will have more reliable tests.

**Comment by DenBond7** [comment]
deprecated
