### ISSUE TITLE
Setup android:fullBackupContent (Auto Backup)

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#113]
Need to setup using [instructions](https://developer.android.com/guide/topics/data/autobackup.html)

On SDK version 23 and up, your app data will be automatically backed up and restored on app install. Consider adding the attribute `android:fullBackupContent` to specify an `@xml` resource which configures which files to backup. More info: https://developer.android.com/training/backup/autosyncapi.html

**Comment by tomholub** [comment]
I'm not sure we should use this - security concerns. We can discuss it later to see if it makes sense.

**Comment by DenBond7** [comment]
Yes. If we will not plan use it I must disable this option.

**Comment by tomholub** [comment]
Let's disable it for now, and revisit in the future.

**Comment by tomholub** [comment]
I'm closing this for now
