### ISSUE TITLE
found backup will disrupt logging into other account

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#114]
To reproduce:
1) install app
2) login into account that does have backup, but do not fill the password
3) select use another account
4) login into account that does NOT have a backup
5) after connecting, it will still show the "found backup" screen

It should only refer to backups found on currently selected account during setup.

**Comment by DenBond7** [comment]
https://github.com/FlowCrypt/flowcrypt-android/commit/53d2e8d77ebe61afae67a89d30e1c0f5a740e453
