### ISSUE TITLE
Delete emails from inbox don't stay deleted

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-android#1144]
How to reproduce:

1. Delete an email from your inbox (encrypted or unencrypted, it doesn't matter)
2. The email disappears
3. Swipe to refresh the inbox
4. The email is back!

Ref: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgxwLtGrPSXrhSsgbtlwKvwmVVFDz
Ref: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgxwLtGldXhFLBQwQhCpbQWfqPzdL

I was able to reproduce this issue on my own phone with Android installed.

**Comment by DenBond7** [comment]
Thank you for reporting. It's a duplicate of #1135.

**Comment by seisvelas** [comment]
Woah, sorry I didn't check to see whether there was already an issue. My bad!
