### ISSUE TITLE
[tom] Add flowcrypt.com to be able to test the Enterprise version

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#1146]
![image](https://user-images.githubusercontent.com/2863246/113401059-7960a680-93ab-11eb-95db-feed24210334.png)

**Comment by tomholub** [comment]
ah - yes

**Comment by DenBond7** [comment]
I'm moving it to 1.1.8. not urgent

**Comment by DenBond7** [comment]
Remind you about this one. For now, I'm moving it to 1.1.9

**Comment by tomholub** [comment]
Sorry I'm still kicking this issue to another milestone

**Comment by DenBond7** [comment]
No prob. It can wait.

**Comment by DenBond7** [comment]
Already is available
