### ISSUE TITLE
NEED_PASSPHRASE: Missing pass phrase

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#1167]
One user is getting this with an imported key:

![image](https://user-images.githubusercontent.com/6306961/114769103-45956180-9d59-11eb-9260-04734e922d13.png)

I believe they imported this as a secondary key. Could there be a bug in the import process that doesn't store the pass phrase along with the key, or stores a wrong one?

**Comment by DenBond7** [comment]
I'll recheck the import process to be sure. Do we know what a version the user use? I mean the app version.

**Comment by tomholub** [comment]
first observed on 1.1.5, also present after upgrade to 1.1.6 (but didn't try re-importing on 1.1.6 yet).

**Comment by DenBond7** [comment]
@tomholub 
> first observed on 1.1.5

So the migration to using Kotlin didn't cause this issue. That's good. But maybe it's a bug with the decryption process.

**Comment by DenBond7** [comment]
Added debug info. For now, I'm moving it to 1.1.8 and will wait for additional details.

**Comment by tomholub** [comment]
Did you end up receiving any acra reports about this, or was the debugging info only visible to user?

**Comment by DenBond7** [comment]
> Did you end up receiving any acra reports about this, or was the debugging info only visible to user?

I've written to the user on Thu, Apr 29, 9:05 PM. No feedback. I think it's not relevant today

**Comment by DenBond7** [comment]
deprecated
