### ISSUE TITLE
integrate with EKM to pull keys during setup

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#1168]
part of https://github.com/FlowCrypt/flowcrypt-android/issues/1298

EKM = Email Key Manager https://flowcrypt.com/docs/technical/enterprise/email-deployment-overview.html

OrgRule definitions https://flowcrypt.com/docs/business/org-rules.html

Here is OrgRule class on browser - I know we already have an existing implementation hera that may look different, but I would suggest aligning the Android approach (to parsing and using OrgRules) with the browser - by porting this class to kotlin and using the same wording for methods. If we do this on all three platforms, it will be much easier to review: https://github.com/FlowCrypt/flowcrypt-browser/blob/master/extension/js/common/org-rules.ts

Immediately after authentication when we receive the OIDC and OrgRules, we should check if `orgRules.usesKeyManager() == true`. If yes, we should:

- [x] 1) check if `orgRules.mustAutoImportOrAutogenPrvWithKeyManager() == true` and if not, skip following steps (and instead show regular setup flow)
- [x] 2) check if `orgRules.mustAutogenPassPhraseQuietly() == false`. If not, show an error that this combination of OrgRules (PRV_AUTOIMPORT_OR_AUTOGEN + PASS_PHRASE_QUIET_AUTOGEN) is not supported on this platform
- [x] 3) check if `orgRules.forbidStoringPassPhrase() == true`. If not, show an error that this combination of OrgRules (PRV_AUTOIMPORT_OR_AUTOGEN + missing FORBID_STORING_PASS_PHRASE) is not supported on iOS.
- [x] 4) check if `orgRules.mustSubmitToAttester() == false`. If not, show an error that this combination of OrgRules (PRV_AUTOIMPORT_OR_AUTOGEN + ENFORCE_ATTESTER_SUBMIT) is not supported on iOS.
- [x] 5) check if `orgRules.forbidCreatingPrivateKey() == true`. If not, show an error that this combination of OrgRules (PRV_AUTOIMPORT_OR_AUTOGEN  + missing NO_PRV_CREATE) is not supported on iOS.
- [x] 6) get the EKM URL from `key_manager_url` OrgRule (already includes `https://`, but may or may not include a trailing slash - please normalize the URL to contain a trailing slash before you use the URL).
- [x] 7) call `GET <ekm>/v1/keys/private`. Into authorization header please put `Bearer <ID_TOKEN>`. On error, offer retry
- [x] 8) if there are no private keys there (empty array), show an error to the user that there are no private keys configured for them and that they should ask their systems administrator or help desk. Offer retry
- [x] 9) ask user to provide a passphrase (similar UI to creating a new key), then ask to confirm
- [x] 10) encrypt the received keys with the pass phrase. Keep pass phrase in memory #372 , store encrypted key in storage
- [x] 11) finish setup without any further user interaction
- [x] 12) do not submit any public key to attester(added by @DenBond7)

The goal is that if user has keys already configured on EKM and appropriate OrgRules are in place, they only need to authenticate and choose a pass phrase, and everything will be done automatically. After authentication and successful automatic setup, they will be sent to their inbox.

In this flow, __do not submit any public key to attester__.

**Comment by tomholub** [comment]
@DenBond7 this task is ready to implement. Maybe you will want to do some prepwork first in a separate PR, client class for EKM, things like that. You can then test this functionality on your company account - the OrgRules are not fully matching there but the EKM url is there, so you can authenticate with the EKM and try retrieving your keys etc as if the OrgRules were set that way. Then you can mock it up.

**Comment by DenBond7** [comment]
#748 #750

**Comment by DenBond7** [comment]
@tomholub Could you clarify this one?
> 1) send OIDC token to EKM to retrieve an access token and store it. Fail on error, offer retry

Here #748 is described the current logic that we have for enterprise users. I'd like to have more details about `retrieve an access token and store it.` Do I need to call some API?

**Comment by tomholub** [comment]
Actually, for EKM, you can skip this access token handling - I just newly found out. Therefore, you can take the OIDC token and use it directly to call GET keys endpoint.

**Comment by DenBond7** [comment]
![#1168](https://user-images.githubusercontent.com/2863246/117118178-2490c100-ad99-11eb-8afd-225f25b0594d.jpeg)

**Comment by tomholub** [comment]
- please update domain==google.com to domain IN (googlemail.com, gmail.com)

**Comment by tomholub** [comment]
- please skip the `GET <EKM>/v1/access-token` step, and the storage of access token. Instead, send OIDC token to `<EKM>/keys/private` in next step

**Comment by tomholub** [comment]
Otherwise all good. It seems that you will have to implement #372 first as a pre-requisite. 

Thank you for this chart!

**Comment by DenBond7** [comment]
I've updated the chart to fit all needs.

**Comment by tomholub** [comment]
Looks good! The final functionality will also be changed by https://github.com/FlowCrypt/flowcrypt-android/issues/1202 but that's not relevant for this particular issue. It can be changed after. The outcome will be - instead of calling flowcrypt.com/api, the app will first try opportunistically calling https://fes.customerdomain.com to see if there is an API running there instead. If yes, use that, if no, use FlowCrypt backend. But that's for later.

**Comment by DenBond7** [comment]
@tomholub Could you share details about the following:

1. `orgRules.passPhraseMustBeChosenByUser()`
2. `orgRules.forbidCreatingPrivateKey()`

I don't see that methods in https://github.com/FlowCrypt/flowcrypt-browser/blob/master/extension/js/common/org-rules.ts

**Comment by tomholub** [comment]
Here are more details about these OrgRules. I don't need full support of this behavior on Android, right now I only care that in the above described flow, we check that they are both enabled.

- passPhraseMustBeChosenByUser (PASS_PHRASE_CHOSEN_BY_USER) - https://github.com/FlowCrypt/flowcrypt-browser/issues/3596

- forbidCreatingPrivateKey (NO_PRV_CREATE) - simply means that the android app is not allowed to create a private key for this user. The only valid setup option is to import it. We don't have to support this OrgRule during regular (non-EKM) flow yet, however we can file an issue to support it later. For non-EKM flow, enabling this rule would mean that the user must import the key manually. See https://flowcrypt.com/docs/business/org-rules.html

**Comment by tomholub** [comment]
Correction - as per the discussion in https://github.com/FlowCrypt/flowcrypt-browser/issues/3596 - there is no more `PASS_PHRASE_CHOSEN_BY_USER` to check. The reasoning is, that `PASS_PHRASE_CHOSEN_BY_USER` is really just an opposite of `PASS_PHRASE_QUIET_AUTOGEN`. Therefore: in step 2 which originally said `2) check if orgRules.passPhraseMustBeChosenByUser() == true. If not, show an error that this combination of OrgRules (PRV_AUTOIMPORT_OR_AUTOGEN + missing PASS_PHRASE_CHOSEN_BY_USER) is not supported on iOS` it should now say `2) check if orgRules.mustAutogenPassPhraseQuietly() == false. If not, show an error that this combination of OrgRules (PRV_AUTOIMPORT_OR_AUTOGEN + PASS_PHRASE_QUIET_AUTOGEN) is not supported on this platform`

**Comment by DenBond7** [comment]
@tomholub I've updated the chart to fit your comments

**Comment by DenBond7** [comment]
> ask user to provide a passphrase (similar UI to creating a new key), then ask to confirm

To do that I need refactor some code to prevent duplicates. it will be for a separate issue

**Comment by DenBond7** [comment]
@DenBond7 Add test for the following cases

- [ ] Login. Show retry if failed
- [ ] Get domain rules. Show retry if failed
- [ ] Handle all cases for "org rules combination is not supported"
- [ ] Get private keys via ekm. Show retry if failed
- [ ] Get private keys via ekm. Empty list
- [ ] Get private keys via ekm. Return not fully decrypted key

**Comment by tomholub** [comment]
Also a successful scenario test, in case you don't have it yet.
