### ISSUE TITLE
downloading encrypted attachments - decrypt

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#118]

**Comment by DenBond7** [comment]
> I forgot - is decrypting attachments not implemented yet?

@tomholub https://github.com/FlowCrypt/flowcrypt-android/issues/82 We decided to do it in a new issue.

For now, we can only download attachments, the decryption not implemented yet.

**Comment by tomholub** [comment]
Ok good, let's do it in v10

**Comment by tomholub** [comment]
Added functionality to decrypt files, supply it to the decrypt function as byte[].

Debugged like this:
```Java
byte[] encrypted = IOUtils.toByteArray(context.getAssets().open("sample/sample.henry.txt.pgp"));
PgpDecrypted decrypted = crypto_message_decrypt(encrypted);
byte[] decrypted_bytes = decrypted.getBytes();

System.out.println("---------- DECRYPTED: ");
System.out.println(IOUtils.toString(decrypted_bytes, "UTF-8"));
System.out.println("---------- ^^^DECRYPTED");
```
Result;
```
10-15 19:49:48.116 27516-27587/com.flowcrypt.email.debug I/System.out: ---------- DECRYPTED: 
10-15 19:49:48.116 27516-27587/com.flowcrypt.email.debug I/System.out: this is encrypted text
10-15 19:49:48.116 27516-27587/com.flowcrypt.email.debug I/System.out: it worked
10-15 19:49:48.116 27516-27587/com.flowcrypt.email.debug I/System.out: ---------- ^^^DECRYPTED
```

Remember that you'll have to check `pgpDecrypted.isSuccess()` just like normal message. After that, get your decrypted file with `pgpDecrypted.getBytes();`

**Comment by tomholub** [comment]
if you supplied `String` into `js.crypto_message_decrypt()`, then use `PgpDecrypted.getString()`. (normal messages)

If you supplied encrypted message as `byte[]`, then use `PgpDecrypted.getBytes()` afted decrypting (downloadable files)

**Comment by DenBond7** [comment]
@tomholub I added support of decryption of attachments. We will support decrypt all attachments or maybe we have limitation by size?

Why do I ask you? Because we use String or byte[] and it's not good for a performance. Such methods will be a reason for memory leaks for big attachments.

**Comment by tomholub** [comment]
I would add the same limit that we have for sending. When we have time to improve it, then we raise the limit.

**Comment by DenBond7** [comment]
Comleted
