### ISSUE TITLE
more than one public key per recipient

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#1188]
(I'm filing a separate issue to discuss from #480 )

Right now, we import one public key per recipient email. So for recipient@domain.com I can only have one public key. Would it be possible to allow more than one public key per each recipient email? Then we can import any keys, but have to change logic on how to choose the right key when we send out encrypted message, for example.

**Comment by DenBond7** [comment]
> So for recipient@domain.com I can only have one public key.

That's true for now

> Would it be possible to allow more than one public key per each recipient email?

I think yes. For example, we can store a few pub keys as a single source in the database record. In that case, a user will have a list of pub keys(in most cases with a single pub key) instead of a single key.

> Then we can import any keys, but have to change logic on how to choose the right key when we send out encrypted message, for example.

It's possible. For now, we just create a data class that contains only recipient emails. But we also can store for example `email<->fingerprint` pair. After that during the creation raw MIME message, we can choose the right key. Of course, we should create UI for that.

Anyway, it's possible.

**Comment by tomholub** [comment]
> After that during the creation raw MIME message, we can choose the right key. Of course, we should create UI for that.

This would be automatic - we'd have rules about how to choose the right one. No user interaction.

> I think yes. For example, we can store a few pub keys as a single source in the database record. In that case, a user will have a list of pub keys(in most cases with a single pub key) instead of a single key.

Would this end up being three db rows with three public keys, or one row with several public keys in it?

**Comment by DenBond7** [comment]
>Would this end up being three db rows with three public keys, or one row with several public keys in it?

only one row as before. Just `public_key` column will contain a list of keys. Also, we can add a new column, for example, `default_key`, and store a fingerprint of the default key.

**Comment by tomholub** [comment]
Would it alternatively be possible to do a migration and be able to store more than one row per recipient, with one key per row? It's more work but it would be the most flexible.

**Comment by DenBond7** [comment]
> Would it alternatively be possible to do a migration and be able to store more than one row per recipient, with one key per row?

yes, we can do that. I don't see any problems with that.

**Comment by IvanPizhenko** [comment]
why not store additional keys in the additional table?

**Comment by tomholub** [comment]
That's roughly what we do on browser extension - a list of recipients in one table with references to public keys, and a public key table next to it.

**Comment by tomholub** [comment]
On other platforms (browser and iOS) we have renamed `Contact` to `RecipientWithPubKeys` as follows:

```
struct RecipientWithPubKeys {
    let email: String
    /// name if known
    let name: String?
    /// last time an email was sent to this contact, update when email is sent
    let lastUsed: Date?
    /// public keys
    var pubKeys: [PubKey]
}
```

So instead of `Contact` that has one pubkey in it, it's a recipient which has an array.

> @tomholub I'd like to clarify the relationships between contacts and pub_keys tables. Will it be one-to-many or many-to-many?
> Is there a situation when we can have a single pub key for two different email addresses? (a pub key that contains a few user ids). What we are going to support?

To give you some examples:

Tom may have a key for Tom + Human + Security
Human may have a key for Human
Mart may have a key for Mart + Security

So you can definitely have a situation where Tom has more than one key (expected) but also where one key is shared by Tom and Human or Tom and Mart (I think this answers your question).

In this situation, it would be best to de-duplicate keys by their fingerprints. So that you don't have to store the shared key twice, and when you update it on one end, then it updates on both.

I suppose that makes it many-to-many?

**Comment by tomholub** [comment]
It's ok to do it this way, if you prefer it. It's true it will probably make it simpler for you.

But you can no longer de-duplicate by key fingerprint, and it cannot be a unique index. So your unique index will probably be recipient_id+fingerprint?

**Comment by DenBond7** [comment]
@tomholub Depending on a new logic I'd like to discuss a few questions. I will post them as separate comments (one by one) to be able to extract them to separate issues.

**Comment by DenBond7** [comment]
Importing pub keys

Here we can have two cases:
1) key with a single user id: for example key for A@flowcrypt.test It's a simple case.

Here we have the same behavior as before.

2) key with a few user ids: for example key for A@flowcrypt.test, B@flowcrypt.test

Here we have 2 theoretical recipients: `A@flowcrypt.test`, `B@flowcrypt.test`. Should I add 2 entries to the local database

```
1| FINGERPRINT| A@flowcrypt.test | KEY
2| FINGERPRINT| B@flowcrypt.test | KEY
```

**Comment by DenBond7** [comment]
Creating an encrypted message

When we create a new message we check if a user has a pub key. But before we had one user <-> one pub key.
After changes a user can have a few pub keys with different states, for example:
1) `one good` + `one expired`
2) `one good` + `one good`
3) `one expired` + `one expired`

How to handle such cases?
What color should I use for chips in these cases?

**Comment by DenBond7** [comment]
Encryption and signing. NEW messages

Imagine that I have the following records in the local database

```
1| FINGERPRINT| sender@flowcrypt.test | KEY
2| FINGERPRINT| recipient@flowcrypt.test | KEY1
3| FINGERPRINT| recipient@flowcrypt.test | KEY2
```

I'm a `sender`. I'd like to encrypt and sign a message for a `recipient`. What combination of keys should I use?

1. `KEY` + `KEY1`
2. `KEY` + `KEY2`
3. `KEY` + `KEY1` + `KEY2`

**Comment by DenBond7** [comment]
Also need to add an ability to see the public key details. Before we used to show the contact details that have only one key. But now we need to change that screen

Before
`Contacts list ->  public key info`

now
`Recipients list -> Recipients details with pub key list -> public key info`

**Comment by tomholub** [comment]
yes - correct
