### ISSUE TITLE
Use .test TLD

### ISSUE THREAD

**Issue by IvanPizhenko** [FlowCrypt/flowcrypt-android#1189]
According to @seisvelas 

Very small nitpick: when using test accounts that aren't real, like expired@denbond7.com, it's better to use a .test TLD. If there were ever an unexpected side-effect of the code whereby the owner of expired@denbond7.com could influence what happens somehow, someone could buy the domain denbond7.com and make that happen.

Unlikely, I know, but not unimaginable, and the solution is to simply use .test TLD, so why not?

.test TLD is reserved by IETF and will never be installed on the global DNS, so it's safer.

Eventually I'm going to review this codebase for exactly this and switch everything to .test TLD test accounts anyway. But just note going forward that .test TLD test accounts are preferable :)

**Comment by DenBond7** [comment]
@seisvelas when we were starting to use an email server it was created just to use it locally on my PC. That's why I didn't care about the domain name. 

For now I'm totally agree that we should use your recommendation. Thank you for reporting.
After renaming the code will be much clearer. A very good idea!

**Comment by DenBond7** [comment]
[TLDs for Testing, & Documentation Examples](https://tools.ietf.org/html/rfc2606#page-2)

**Comment by IvanPizhenko** [comment]
From RFC:
```

3. Reserved Example Second Level Domain Names

   The Internet Assigned Numbers Authority (IANA) also currently has the
   following second level domain names reserved which can be used as
   examples.

        example.com
        example.net
        example.org
```

**Comment by DenBond7** [comment]
@seisvelas @tomholub 
> it's better to use a .test TLD

How do you think which template should I use for our purposes (local email server, users, keys and etc.)?

1. user@denbond7.test
2. user@flowcrypt.test
3. user@test.test
4. user@example.test
5. your example

I'd like to resolve this issue as soon as possible. Sometimes hard to don't use `denbond7.com` in the current code.

**Comment by seisvelas** [comment]
I like option 2 the best. 4 is also very clear. They are all equally beneficial from a security perspective, so whatever you think is clearest (unless someone else has input on this, that's my 2¢).
