### ISSUE TITLE
SHARED_PREFERENCES debug section contains sensitive info

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#119]
can we make the app skip this section?

**Comment by DenBond7** [comment]
Yes, of course. https://github.com/ACRA/acra/issues/252

**Comment by DenBond7** [comment]
We can add `customReportContent = { }` and decide what we want to send.

**Comment by DenBond7** [comment]
For now, we receive (https://github.com/ACRA/acra/wiki/ReportContent)

- [ ] [STACK_TRACE]
- [ ] [LOGCAT]
- [ ] [SHARED_PREFERENCES]
- [ ] [ENVIRONMENT]
- [ ] [TOTAL_MEM_SIZE]
- [ ] [INITIAL_CONFIGURATION]
- [ ] [DISPLAY]
- [ ] [AVAILABLE_MEM_SIZE]
- [ ] [PHONE_MODEL]
- [ ] [CRASH_CONFIGURATION]
- [ ] [DEVICE_FEATURES]
- [ ] [BUILD_CONFIG]
- [ ] [FILE_PATH]
- [ ] [INSTALLATION_ID]
- [ ] [USER_CRASH_DATE]
- [ ] [HASH]
- [ ] [APP_VERSION_NAME]
- [ ] [USER_APP_START_DATE]
- [ ] [BUILD]
- [ ] [DUMPSYS_MEMINFO]
- [ ] [USER_EMAIL]
- [ ] [REPORT_ID]
- [ ] [PRODUCT]
- [ ] [PACKAGE_NAME]
- [ ] [BRAND]
- [ ] [ANDROID_VERSION]
- [ ] [APP_VERSION_CODE]
- [ ] [IS_SILENT]
- [ ] [CUSTOM_DATA]

Please select what I must send if some crash occurred.

**Comment by tomholub** [comment]
I'm looking at it, all looks good except for SHARED_PREFERENCES. Over time, if we find that sensitive info sneaks in from other parts, we may disallow it in the future.
