### ISSUE TITLE
Display basic message information

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#1191]
We should add something similar to the following to see base info

![image](https://user-images.githubusercontent.com/2863246/115861171-24103600-a43b-11eb-887b-4ba8a4dbff2e.png)

**Comment by tomholub** [comment]
This may not be the best guidance (web app) - could you show a screenshot from mobile app?

**Comment by DenBond7** [comment]
For example

![image](https://user-images.githubusercontent.com/2863246/115863797-a0f0df00-a43e-11eb-90e8-c47a9f1056ab.png)

**Comment by DenBond7** [comment]
The final version for now

![Untitled](https://user-images.githubusercontent.com/2863246/116093392-490cdf00-a6af-11eb-8b50-5683df1a6dd6.png)

**Comment by DenBond7** [comment]
I've added some tests. Need to add more tests for different cases. It will be for a separate issue.
