### ISSUE TITLE
search pubic keys of recipients on WKD

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#1201]
part of https://github.com/FlowCrypt/flowcrypt-android/issues/1298

trust it more than results on Attester (search first on WKD, then on Attester if WKD doesn't return public key)

1) ~port `Wkd` class from browser extension~ done
2) ~add tests for it independently of the rest of the codebase, merge the class unused~ done
3) another PR to start using this class during public key lookups - this issue

The WKD class must be **unaffected** by `disallow_attester_search_for_domains`

**Comment by DenBond7** [comment]
@tomholub Could you show me the logic that you use from the web extension? Where you use the `WKD` client to fetch pub keys.

**Comment by tomholub** [comment]
Every single time when public key is pulled from external sources, it would use a general `PubLookup` class, which has `lookupEmail(email: string)` method on it.

It's implemented here: https://github.com/FlowCrypt/flowcrypt-browser/blob/master/extension/js/common/api/pub-lookup.ts

When the method is called:
1) it will try pulling from WKD. If WKD returns any result, then the PubLookup method itself will return that result. If not, it will proceed to step 2
2) try pulling from Attester. If attester returns any result, then the PubLookup method itself will return that result. Else, proceed to step 3
3) return empty result

In the code I linked above, there is also a third pubkey source `internalSks` which we will not be implementing on Android.

**Comment by tomholub** [comment]
Inside the `Attester` class, `disallow_attester_search_for_domains` would be used so that it returns empty in case searching is disabled on that domain (or completely), meaning this setting does not affect searching on WKD.

**Comment by tomholub** [comment]
I recommend to open above code in vscode so that you can explore it (with ctrl+click) and get a better understanding of where it is used (right click + see usages) or how it fits together.

**Comment by DenBond7** [comment]
As I understand it relates to `search by email` only (for fingerprints we use `attester`). Right?

I'd like to remind you what logic we use:

1. User types `user@example.test`
2. We search `by email` via `attester`
3. User sends a message. We already have a pub key for `user@example.test` in the cache
4. User creates a new message again
5. User types `user@example.test`
6. As we already have a pub key for `user@example.test` in the cache we make a request by `fingerprint`(via `attester`) to fetch the latest pub key to keep keys fresh

**Comment by tomholub** [comment]
> As we already have a pub key for user@example.test in the cache we make a request by fingerprint(via attester) to fetch the latest pub key to keep keys fresh

The browser extension logic is here:

https://github.com/FlowCrypt/flowcrypt-browser/blob/ecf83dda1cb272a1096321ab4ff244ca567364ca/extension/chrome/elements/compose-modules/compose-storage-module.ts#L141

1) This should be using `PubLookup` as well - a general place to search for external public keys

2) `PubLookup.getFingerprint(fingerprint: string)` should only try Attester, because WKD does not support pulling by fingerprint. However, `disallow_attester_search_for_domains` is set to `["*"]` then attester should always return an empty result, even when searching by fingerprint. I'm not sure if I highlighted this before. Is this already implemented or should we first add that?

3) That means, with `disallow_attester_search_for_domains: ["*"]` in client configuration, that keys will never get updated this way.

I'll file an issue for 3) separately, as we still need a solution for WKD, and it will work by re-fetching by email. I thought we already did that on browser extension - will investigate, and then describe the logic on that issue too.

**Comment by DenBond7** [comment]
> However, disallow_attester_search_for_domains is set to ["*"] then attester should always return an empty result, even when searching by fingerprint. I'm not sure if I highlighted this before. Is this already implemented or should we first add that?

It's already `true` for now = if disallow_attester_search_for_domains is set to ["*"] then attester always return an empty result

**Comment by tomholub** [comment]
> It's already true for now = if disallow_attester_search_for_domains is set to ["*"] then attester always return an empty result

Even when calling by fingerprint? Just checking :-)

**Comment by DenBond7** [comment]
> > It's already true for now = if disallow_attester_search_for_domains is set to ["*"] then attester always return an empty result
> 
> Even when calling by fingerprint? Just checking :-)

Yup :)

https://github.com/FlowCrypt/flowcrypt-android/blob/4771ba023fe437cce404ad7b2f851b8474106c42/FlowCrypt/src/main/java/com/flowcrypt/email/api/retrofit/FlowcryptApiRepository.kt#L113

**Comment by tomholub** [comment]
Ok, then you can follow https://github.com/FlowCrypt/flowcrypt-android/issues/1201#issuecomment-896004144 - let me know and I'll be happy to clarify further.

**Comment by DenBond7** [comment]
Btw, does the `WKD` server always return a single pub key?

**Comment by tomholub** [comment]
Definitely not - it's an array of public keys, may be zero, one or more than one. Good question.

**Comment by DenBond7** [comment]
For now, our logic works just with a single key. Should I use the first matched?

**Comment by tomholub** [comment]
Ok but that's only a temporary solution. 

All public keys returned from WKD should be processed, they should all be inserted or updated in local storage (comparing them by fingerprint), and when sending out a message, instead of choosing the best fitting public key like we did before, we should encrypt for all valid pubkeys that we have for that person. I'll file another issue.

**Comment by DenBond7** [comment]
> All public keys returned from WKD should be processed, they should all be inserted or updated in local storage (comparing them by fingerprint), and when sending out a message, instead of choosing the best fitting public key like we did before, we should encrypt for all valid pubkeys that we have for that person. I'll file another issue.

in that case, we should firstly done the following https://github.com/FlowCrypt/flowcrypt-android/issues/1188

**Comment by DenBond7** [comment]
One more question. As I understand WKD returns keys in RAW format. Is it possible to receive armored keys here or should I always expect RAW keys?

**Comment by DenBond7** [comment]
> They always must come in raw. If they cannot be parsed as raw, then the response from WKD is wrong.

Should I check that? Why I ask. `PGPainless` can parse keys from different sources. In most cases, I don't care what exactly source do I have. if `PGPainless` can't recognize keys I will receive nothing.

One more question. Should I check that the input contains only pub keys? (throw errors or filter only pub keys, etc.)

**Comment by DenBond7** [comment]
For me

https://www.uriports.com/blog/setting-up-openpgp-web-key-directory/
https://shibumi.dev/posts/how-to-setup-your-own-wkd-server/

**Comment by tomholub** [comment]
Do you intend on running your own WKD for testing? I don't recommend that - WKD can be trivially mocked. To mock it, you can get the right URL here https://metacode.biz/openpgp/web-key-directory for a particular email, and then serve the binary key on that URL.

**Comment by DenBond7** [comment]
Need to test the following

- [ ] no results for wkd_no_results@flowcrypt.test
- [ ] wkd advanced. no `policy` file (wkd_advanced_no_policy@flowcrypt.test)
- [ ] wkd advanced. has `policy` file && no result (wkd_advanced_no_result@flowcrypt.test)
- [ ] wkd advanced. has `policy` file && has single pub key(wkd_advanced_pub@flowcrypt.test)
- [ ] wkd advanced skipped. wkd direct. no `policy` file (wkd_direct_no_policy@flowcrypt.test)
- [ ] wkd advanced skipped. wkd direct. has `policy` file && no result(wkd_direct_no_result@flowcrypt.test)
- [ ] wkd advanced skipped. wkd direct. has `policy` file && has single pub key(wkd_direct_pub@flowcrypt.test)
- [ ] wkd advanced timeout. wkd direct available(wkd_advanced_timeout@flowcrypt.test)
- [ ] wkd advanced timeout. wkd direct timeout(wkd_advanced_direct_timeout@flowcrypt.test)

**Comment by DenBond7** [comment]
Just for history. To be able to test WKD need to execute the following 

```cmd
adb root
adb shell "echo 1 > /proc/sys/net/ipv4/ip_forward"
adb shell "iptables -t nat -A PREROUTING -s 127.0.0.1 -p tcp --dport 443 -j REDIRECT --to 1212"
adb shell "iptables -t nat -A OUTPUT -s 127.0.0.1 -p tcp --dport 443 -j REDIRECT --to 1212"
```

We run a mock web server on https://localhost:1212. For testing we need to route all traffic for `localhost` to `localhost:1212`
