### ISSUE TITLE
No sound notification for new mail in FlowCrypt

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-android#1217]
>I get a sound notification for regular (non encrypted) text messages. A simple ding. It would be nice to get something similar for a new flowcrypt inbox item

ref: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgxwLtkXqFmlNLXKbdhXjDfFDhJWS

I don't know anything about this - I personally wouldn't like a ding. But maybe this has nothing to do with FlowCrypt, and this is an Android setting? I have no idea, so asking here.

**Comment by DenBond7** [comment]
I think it relates to `Android settings -> Apps -> FlowCrypt -> Notifications`. It's a little hard to provide any advice without additional details.

**Comment by seisvelas** [comment]
Thanks, that worked. Sorry, should have looked a little more into that myself before asking here!
