### ISSUE TITLE
a port of Mime.processDecoded (to MsgBlocks)

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#1223]
For decoding mime content, in TS we use this method:

```ts
  public static decode = async (mimeMsg: Uint8Array): Promise<MimeContent> => {
    let mimeContent: MimeContent = { attachments: [], headers: {}, subject: undefined, text: undefined, html: undefined, signature: undefined, from: undefined, to: [], cc: [], bcc: [] };
    const parser = new MimeParser();
    const leafNodes: { [key: string]: MimeParserNode } = {};
    parser.onbody = (node: MimeParserNode) => {
      const path = String(node.path.join('.'));
      if (typeof leafNodes[path] === 'undefined') {
        leafNodes[path] = node;
      }
    };
    return await new Promise((resolve, reject) => {
      try {
        parser.onend = () => {
          try {
            for (const name of Object.keys(parser.node.headers)) {
              mimeContent.headers[name] = parser.node.headers[name][0].value;
            }
            mimeContent.rawSignedContent = Mime.retrieveRawSignedContent([parser.node]);
            for (const node of Object.values(leafNodes)) {
              if (Mime.getNodeType(node) === 'application/pgp-signature') {
                mimeContent.signature = node.rawContent;
              } else if (Mime.getNodeType(node) === 'text/html' && !Mime.getNodeFilename(node)) {
                // html content may be broken up into smaller pieces by attachments in between
                // AppleMail does this with inline attachments
                mimeContent.html = (mimeContent.html || '') + Mime.getNodeContentAsUtfStr(node);
              } else if (Mime.getNodeType(node) === 'text/plain' && (!Mime.getNodeFilename(node) || Mime.isNodeInline(node))) {
                mimeContent.text = (mimeContent.text ? `${mimeContent.text}\n\n` : '') + Mime.getNodeContentAsUtfStr(node);
              } else if (Mime.getNodeType(node) === 'text/rfc822-headers') {
                if (node._parentNode && node._parentNode.headers.subject) {
                  mimeContent.subject = node._parentNode.headers.subject[0].value;
                }
              } else {
                mimeContent.attachments.push(Mime.getNodeAsAttachment(node));
              }
            }
            const headers = Mime.headerGetAddress(mimeContent, ['from', 'to', 'cc', 'bcc']);
            mimeContent.subject = String(mimeContent.subject || mimeContent.headers.subject || '');
            mimeContent = Object.assign(mimeContent, headers);
            resolve(mimeContent);
          } catch (e) {
            reject(e);
          }
        };
        parser.write(mimeMsg);
        parser.end();
      } catch (e) { // todo - on Android we may want to fail when this happens, evaluate effect on browser extension
        Catch.reportErr(e);
        resolve(mimeContent);
      }
    });
  }
```

But @DenBond7 probably already has some method for decoding mime. Therefore I don't want to reimplement the above, but instead use Den's methods (and its outputs) for the above purpose (if possible)

Then you take outputs from the MIME decode, and you feed them into a new method that needs implementing, similar to the one below:

```ts
  public static processDecoded = (decoded: MimeContent): MimeProccesedMsg => {
    const blocks: MsgBlock[] = [];
    if (decoded.text) {
      const blocksFromTextPart = MsgBlockParser.detectBlocks(Str.normalize(decoded.text)).blocks;
      // if there are some encryption-related blocks found in the text section, which we can use, and not look at the html section
      if (blocksFromTextPart.find(b => b.type === 'encryptedMsg' || b.type === 'signedMsg' || b.type === 'publicKey' || b.type === 'privateKey')) {
        blocks.push(...blocksFromTextPart); // because the html most likely containt the same thing, just harder to parse pgp sections cause it's html
      } else if (decoded.html) { // if no pgp blocks found in text part and there is html part, prefer html
        blocks.push(MsgBlock.fromContent('plainHtml', decoded.html));
      } else { // else if no html and just a plain text message, use that
        blocks.push(...blocksFromTextPart);
      }
    } else if (decoded.html) {
      blocks.push(MsgBlock.fromContent('plainHtml', decoded.html));
    }
    for (const file of decoded.attachments) {
      const treatAs = file.treatAs();
      if (treatAs === 'encryptedMsg') {
        const armored = PgpArmor.clip(file.getData().toUtfStr());
        if (armored) {
          blocks.push(MsgBlock.fromContent('encryptedMsg', armored));
        }
      } else if (treatAs === 'signature') {
        decoded.signature = decoded.signature || file.getData().toUtfStr();
      } else if (treatAs === 'publicKey') {
        blocks.push(...MsgBlockParser.detectBlocks(file.getData().toUtfStr()).blocks);
      } else if (treatAs === 'privateKey') {
        blocks.push(...MsgBlockParser.detectBlocks(file.getData().toUtfStr()).blocks);
      } else if (treatAs === 'encryptedFile') {
        blocks.push(MsgBlock.fromAttachment('encryptedAttachment', '', { name: file.name, type: file.type, length: file.getData().length, data: file.getData() }));
      } else if (treatAs === 'plainFile') {
        blocks.push(MsgBlock.fromAttachment('plainAttachment', '', {
          name: file.name, type: file.type, length: file.getData().length, data: file.getData(), inline: file.inline, cid: file.cid
        }));
      }
    }
    if (decoded.signature) {
      for (const block of blocks) {
        if (block.type === 'plainText') {
          block.type = 'signedText';
          block.signature = decoded.signature;
        } else if (block.type === 'plainHtml') {
          block.type = 'signedHtml';
          block.signature = decoded.signature;
        }
      }
      if (!blocks.find(block => ['plainText', 'plainHtml', 'signedMsg', 'signedHtml', 'signedText'].includes(block.type))) { // signed an empty message
        blocks.push(new MsgBlock("signedMsg", "", true, decoded.signature));
      }
    }
    return { headers: decoded.headers, blocks, from: decoded.from, to: decoded.to, rawSignedContent: decoded.rawSignedContent };
  }
```

**Comment by tomholub** [comment]
This is an interesting method that needs re-implementing, which will help the app decide how to treat each attachment. Here `this` is some sort of attachment object that has name, size, mime type and similar meta info on it.

```ts
  public treatAs = (): Attachment$treatAs => {
    if (['PGPexch.htm.pgp', 'PGPMIME version identification', 'Version.txt', 'PGPMIME Versions Identification'].includes(this.name)) {
      return 'hidden';  // PGPexch.htm.pgp is html alternative of textual body content produced by PGP Desktop and GPG4o
    } else if (this.name === 'signature.asc' || this.type === 'application/pgp-signature') {
      return 'signature';
    } else if (!this.name && !this.type.startsWith('image/')) { // this.name may be '' or undefined - catch either
      return this.length < 100 ? 'hidden' : 'encryptedMsg';
    } else if (this.name === 'msg.asc' && this.length < 100 && this.type === 'application/pgp-encrypted') {
      return 'hidden'; // mail.ch does this - although it looks like encrypted msg, it will just contain PGP version eg "Version: 1"
    } else if (Attachment.encryptedMsgNames.includes(this.name)) {
      return 'encryptedMsg';
    } else if (this.name.match(/(\.pgp$)|(\.gpg$)|(\.[a-zA-Z0-9]{3,4}\.asc$)/g)) { // ends with one of .gpg, .pgp, .???.asc, .????.asc
      return 'encryptedFile';
    } else if (this.name.match(/(cryptup|flowcrypt)-backup-[a-z0-9]+\.(key|asc)$/g)) {
      return 'privateKey';
    } else if (this.type === 'application/pgp-keys') {
      return 'publicKey';
    } else if (this.name.match(/^(0|0x)?[A-F0-9]{8}([A-F0-9]{8})?.*\.asc$/g)) { // name starts with a key id
      return 'publicKey';
    } else if (this.name.toLowerCase().includes('public') && this.name.match(/[A-F0-9]{8}.*\.asc$/g)) { // name contains the word "public", any key id and ends with .asc
      return 'publicKey';
    } else if (this.name.match(/\.asc$/) && this.hasData() && Buf.with(this.getData().subarray(0, 100)).toUtfStr().includes('-----BEGIN PGP PUBLIC KEY BLOCK-----')) {
      return 'publicKey';
    } else if (this.name.match(/\.asc$/) && this.length < 100000 && !this.inline) {
      return 'encryptedMsg';
    } else {
      return 'plainFile';
    }
  }

```

**Comment by DenBond7** [comment]
@IvanPizhenko Have you worked with JavaMail before?

**Comment by DenBond7** [comment]
@tomholub I've looked at TS code. It seems that your logic is clear and can be transferred to Kotlin. There is a lot of work with `JavaMail`. How I see that
1) Parse inputStream to [MimeMessage](https://javaee.github.io/javamail/docs/api/javax/mail/internet/MimeMessage.html)
2) Analyze the parsed message. Part by part. @IvanPizhenko Please look for example at the following 
https://github.com/FlowCrypt/flowcrypt-android/blob/1cb358396ad72d9336e89a159276ec137eeb90ae/FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/MsgDetailsViewModel.kt#L389
here you will find how I iterate over the parts. Please feel free to look at other examples over the app.
3) During analyzing we can decrypt found parts and generate MsgBlock
4) As I understand in the end we should receive something similar to 

```
data class ParseDecryptedMsgResult constructor(
    @Expose val text: String?,
    @Expose val replyType: String,
    @Expose val subject: String?,
    @SerializedName("error")
    @Expose override val apiError: ApiError?, // here we should have decryptionError
    var msgBlocks: MutableList<MsgBlock>?) {}
```

**Comment by IvanPizhenko** [comment]
> @IvanPizhenko Have you worked with `JavaMail` before?

a bit, I've implemented some sending emails in the FES.

**Comment by IvanPizhenko** [comment]
@tomholub So which one I should continue with now - this one or #1057 ?

**Comment by tomholub** [comment]
This one please. It's a prerequisite for the other one.

**Comment by IvanPizhenko** [comment]
@tomholub where can I get some unit tests for this?

**Comment by tomholub** [comment]
I'll extract some test cases for you

**Comment by IvanPizhenko** [comment]
And question in advance to @DenBond7 - creating `MimeMessage` object requires `Session` object. How can I obtain it for unit tests?

**Comment by tomholub** [comment]
Den: what is that session for? Hopefully, there would not be any session needed if one is just creating a message object for local use.

**Comment by IvanPizhenko** [comment]
@tomholub please look at `MimeMessage` constructors here: https://javaee.github.io/javamail/docs/api/javax/mail/internet/MimeMessage.html
So either `Session` or `Folder`.

**Comment by IvanPizhenko** [comment]
Update: but ones with `Folder` are protected, so likely `Session`. The ones with `Folder` are likely used in the subclasses like `IMAPMessage` and `POP3Message`.

**Comment by tomholub** [comment]
I will shortly be sharing test cases of this method that combines both:

```ts
  public static process = async (mimeMsg: Uint8Array): Promise<MimeProccesedMsg> => {
    const decoded = await Mime.decode(mimeMsg);
    return Mime.processDecoded(decoded);
  }
```

This is because the data that goes from `Mime.decode` into `Mime.processDecoded` is platform-specific. JavaMail will return some quite different fromat from what emailjs returns in typescript, and it's an implementation detail. The important part is that `bytes` go in, and some structured object comes out, and the structured object coming out of `processDecoded` should be substantially similar, even if in a different format, to the test cases I will be sharing below.

**Comment by tomholub** [comment]
I'd like to stress it out - the goal will be to return output of "similar meaning" but not byte-to-byte exact responses, it's totally fine and expected that the outputs will be somewhat different, as long as fundamentally both achieve the same purpose.

**Comment by DenBond7** [comment]
> And question in advance to @DenBond7 - creating `MimeMessage` object requires `Session` object. How can I obtain it for unit tests?

Just use `Session.getInstance(Properties ())`. It will be enough in your case.

**Comment by DenBond7** [comment]
> Den: what is that session for? Hopefully, there would not be any session needed if one is just creating a message object for local use.

Session contains connection settings. If we aren't going to use any network operations we can use a very simple instance like this one `Session.getInstance(Properties ())`

**Comment by IvanPizhenko** [comment]
@tomholub that's ok, I just have ported all mentioned above methods and now need to test them, either one by one or in combination, whatever tests are available.

**Comment by IvanPizhenko** [comment]
@DenBond7 Thank you, I will try that.

**Comment by tomholub** [comment]
@IvanPizhenko here below. The input is a byte array, for easy sharing I base64 encoded it. Best would be to decode them and store them file by file in tests assets as textual mime messages (the way they get transferred over email), then load the files (as a stream?) to test with them.

[mime-process.zip](https://github.com/FlowCrypt/flowcrypt-android/files/6528609/mime-process.zip)

**Comment by DenBond7** [comment]
@IvanPizhenko 
About testing. Basically, you don't need to add support of all cases and tests for them. Currently on Android we support only the following

- MsgBlock.Type.DECRYPTED_HTML, 
- MsgBlock.Type.PLAIN_HTML
- MsgBlock.Type.DECRYPTED_TEXT
- MsgBlock.Type.PLAIN_TEXT
- MsgBlock.Type.PUBLIC_KEY
- MsgBlock.Type.DECRYPTED_ATT

So for now we have to cover only those cases to drop Node.js

**Comment by DenBond7** [comment]
@IvanPizhenko I think `MimeContent` is redundant. `JavaMail` covers it with `MimeMessage`. You don't need to parse MIME message manually, just use `JavaMail` and `MimeMessage` as a parsed object.

```
@Suppress("ArrayInDataClass")
  data class MimeContent(
    val attachments: List<BodyPart>,
    var signature: ByteArray?,
    val subject: String,
    val html: String?,
    val text: String?,
    val from: Array<Address>?,
    val to: Array<Address>?,
    val cc: Array<Address>?,
    val bcc: Array<Address>?
  )
```

**Comment by tomholub** [comment]
@DenBond7 how about signedText and signedHtml? This may also be returned by current node - what would happen to them?

**Comment by tomholub** [comment]
Or maybe you don't even send them to node, since they are not encrypted?

**Comment by DenBond7** [comment]
@tomholub Could you clarify a question? Too many 'node' words, I'm not sure that I understand right according to the context.

**Comment by tomholub** [comment]
We also have MsgBlock types `signedHtml` and `signedText` that may be returned by NodeJS (I saw it in some of the test cases above). There's also `publicKey` for example. How are these handled on Android?

**Comment by tomholub** [comment]
I see - you treat signedText and signedHtml as "other" and render them as text (which would be a bug in the case of signedHtml).

If that is the case, Ivan's still has to be able to process most of the test cases that I submitted above, else these blocks would not show up, even to be rendered as "other".

@IvanPizhenko see what level of compatibility can you achieve easily. Then we can discuss if we need to support the remaining tests or not yet.

**Comment by IvanPizhenko** [comment]
@tomholub @DenBond7 Do we need the `rawSignedContent`?
```typescript
mimeContent.rawSignedContent = Mime.retrieveRawSignedContent([parser.node]);
```
Otherwise I almost have it ready.

**Comment by DenBond7** [comment]
> Do we need the rawSignedContent?

As we don't support handling the signed content yet I think it's redundant for now. it can be done as improvements

**Comment by IvanPizhenko** [comment]
ok
