### ISSUE TITLE
Email sent with FlowCrypt app opens fine in FlowCrypt, but not in Thunderbird

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-android#1227]
Here is what happens in Thunderbird:

<img width="820" alt="Screen Shot 2021-05-12 at 11 41 25 p m" src="https://user-images.githubusercontent.com/44826516/118083512-4f23e080-b37c-11eb-875b-45935ec99efb.png">

This is what happens in FlowCrypt:

<img width="182" alt="Screen Shot 2021-05-12 at 11 45 56 p m" src="https://user-images.githubusercontent.com/44826516/118083539-58ad4880-b37c-11eb-8a90-87d032c87395.png">

ref: https://mail.google.com/mail/u/4/#inbox/FMfcgxwLtkdQPnKTlfpPzRwFPKNLkSfj

I am not able to reproduce this. I send a message from the app to Thunderbird and it successfully gets decrypted.

Any ideas?

**Comment by tomholub** [comment]
Ask them what Thunderbird version they use, and compare to yours

**Comment by tomholub** [comment]
There is a Thunderbird on old versions that uses Enigmail, and recent version that implements OpenPGP itself. His looks like the recent version.

**Comment by seisvelas** [comment]
Sorry, I must clarify: this is Thunderbird running on my machine with OpenPGP. The user sent me this using FlowCrypt, and when I open it using Thunderbird, it doesn't decrypt. I'm on version 78.10.1 (64-bit) for MacOS.

**Comment by seisvelas** [comment]
However, this problem only occurs with mail sent by *this* user - if I send an email with FlowCrypt and open it in Thunderbird, it opens fine.

So the problem would seem to be with his FlowCrypt setup somehow

**Comment by tomholub** [comment]
Are they on firefox or chrome?

Have they switched to rich text format?

**Comment by DenBond7** [comment]
> Are they on firefox or chrome?
> 
> Have they switched to rich text format?

As I understand we have the following: Android FlowCrypt -> Thunderbird App on PC

**Comment by DenBond7** [comment]
@seisvelas Btw, if it just for testing, could you share the source of that message (raw MIME)?

**Comment by tomholub** [comment]
Sorry - thought we are on another repo.

**Comment by tomholub** [comment]
@seisvelas another question then - on Android, are they on Gmail account or on non-Gmail account over IMAP/SMTP?

**Comment by seisvelas** [comment]
The email address giving the feedback is cinematicbokeh@outlook.com, so I'd guess they're using outlook. Should I still ask?

**Comment by seisvelas** [comment]
The email address giving the feedback is `@outlook.com`, so I'd guess they are using outlook.

Would you like me to ask anyway?

**Comment by DenBond7** [comment]
> Would you like me to ask anyway?

It can be an alias for Gmail account. In that case the app uses Gmail API to send a message. It would be nice to know what a exactly the user uses - a separate outlook account or an alias on Gmail.

**Comment by DenBond7** [comment]
It seems there is a problem with signing. All users after 1.1.7(include) were affected. It can be a compatibility issue(`PGPainless`) or incorrect library usage(`PGPainless`). I'm investigating it.

**Comment by DenBond7** [comment]
it was fixed by https://github.com/pgpainless/pgpainless/issues/160 and https://github.com/FlowCrypt/flowcrypt-android/pull/1384.

I've checked it myself. @seisvelas This fix will be included in the upcoming release(I hope it'll be next week)
