### ISSUE TITLE
Handle import non-encrypted keys

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#1233]
> We don't have to support non-encrypted keys. On browser, when you import non-encrypted keys, you are asked to enter a pass phrase to encrypt the key with, before we store it into storage. On Android, we can ask the user to encrypt the keys and try importing again - for now (unless we already do the same thing as on browser?)

I'll create an issue for that. On Android we don't handle such a case

_Originally posted by @DenBond7 in https://github.com/FlowCrypt/flowcrypt-android/issues/372#issuecomment-843198926_

**Comment by tomholub** [comment]
When this notification is not relevant (test email), maybe you can just :eyes: it and skip over

**Comment by DenBond7** [comment]
![ezgif com-optimize](https://github.com/FlowCrypt/flowcrypt-android/assets/2863246/216cbdb3-9ee7-4c51-b96a-2f06f2946ef2)
