### ISSUE TITLE
Pass phrase in memory. Make a backup

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#1253]
as a part of #372

**Comment by DenBond7** [comment]
@tomholub 
Currently, before making a backup we check a passphrase (is it strong enough). So we have to ask for all missing passphrases to continue. Am I right?

**Comment by tomholub** [comment]
Yes, I would ask for all pass phrases for keys that the user wants to back up.

**Comment by DenBond7** [comment]
![1](https://user-images.githubusercontent.com/2863246/122527750-4af67d00-d024-11eb-8ee5-94f30275339b.gif)
