### ISSUE TITLE
current structure of db?

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#1259]
You will still need longids - potentially - once we add support for verifying signatures. A message is signed for certain longid, and you'll need to look that up in contacts.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-android/pull/1249#discussion_r639575836_

After the above change, I worry you may miss longid information that will be useful in the future. Are longids still in db?

**Comment by DenBond7** [comment]
> After the above change, I worry you may miss longid information that will be useful in the future. Are longids still in db?

Yup. I didn't remove them. But due to https://github.com/FlowCrypt/flowcrypt-android/issues/1188 we will have changes in the database structure soon.

**Comment by tomholub** [comment]
Got it. Thanks!
