### ISSUE TITLE
change attester url to attester.flowcrypt.com

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#128]
I will be discontinuing the old URL. Please change attester url to: `https://attester.flowcrypt.com/`

This domain uses GeoDNS based on latency, meaning that each user will be using server that is the closest to them.

**Comment by DenBond7** [comment]
Does that API already work? I receiving the error 502.

**Comment by tomholub** [comment]
It's supposed to work, although we had a short downtime in germany location (the one closest to you).

What do you see when you open https://attester.flowcrypt.com/ in browser? I see

```
Attester

Public Key Server for FlowCrypt (CryptUp) users and their contacts: search our Public Keys

To communicate with our users, add https://attester.cryptup.io to list of public key servers in your email client.

Developers: see JSON API /lookup/human@flowcrypt.com (recommended) or legacy HKP compatible search

Attester searches our own records plus pgp.mit.edu, keyserver.pgp.com, keys.mailvelope.com, keybase.io and more.

API /health ok
```
If you see the same, it should be ok. You can also see if https://attester.flowcrypt.com/health returns a 200 now.

**Comment by DenBond7** [comment]
Last two days https://attester.flowcrypt.com/ is often not available. (504 Gateway Time-out).
This situation helped me found one bug :)

**Comment by tomholub** [comment]
This night London instance was down for a good couple hours - unfortunately - is it still down now?

**Comment by DenBond7** [comment]
Now, all Ok.

**Comment by tomholub** [comment]
I have finally resolved the recurring downtime with our attesters. A lousy regex + huge unexpected string = server down.
