### ISSUE TITLE
Android app not accepting passphrase used in Chrome extension

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-android#1296]
ref: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGkXmdVSPcTvXfHmdBtTwZGRnnK

> Hello,
> I've successfully configured and used FlowCrypt with Chrome Extension.
> Unfortunately I was not able to import my secret key using FlowCrypt app on Android phone.
> The error message is "wrong pass phrase", although I've successfully used this phrase with FlowCrypt Chrome Extension already.
> May I ask you if FlowCrypt Android app supports PGP RSA 4096 bit keys?
> What is the maximal length of the pass phrase on Android?
> Are there any other restrictions on the pass phrase on Android in comparison to Chrome Extension?

In addition, the user clarified that it's very unlikely that the passphrase entered in the Android app is different, as they are using a password manager:

> I copy and paste the passphrase from the password manager (keepass2android) and I use the same password database on my PC with Chrome Extension.
> So yes, the passphrase is the same.

Do really long passphrases or 4096 bit keys cause problems on the app? Let me know how I can help troubleshoot this. Otherwise my plan is to just manually see how length becomes a problem on Android vs Chrome.

**Comment by seisvelas** [comment]
The user informed us that the passphrase is 128 characters long. So all I have to do is create a 4096 bit key with a passphrase of this length, import it into the browser extension, then into the Android app, and see if anything goes wrong.

**Comment by tomholub** [comment]
I'm unsure - need to check as you say. Does the pass phrase have any unusual things like UTF characters, newlines or maybe spaces (maybe even spaces on the beginning or end?)

**Comment by DenBond7** [comment]
Just want to clarify some moments. On Android side we don't do any manipulation with input. We use the entered pass phrase as-is. As I remember we don't have any restriction of the pass phrase length. So I see the following places where we can have an issue:

1. `EditText` where a user enters a pass phrase. It would be nice if the user will try to enter his passphrase manually(symbol by symbol using the standard Android keyboard).
2. [Passphrase](https://github.com/pgpainless/pgpainless/blob/master/pgpainless-core/src/main/java/org/pgpainless/util/Passphrase.java) - we use `Passphrase.fromPassword(typedText)`
3. `PGPainless`. We use it to check a passphrase.

@seisvelas By the way, could we ask what version does he use?

**Comment by tomholub** [comment]
I forgot we now use PGPainless on Android. There is a possibility for incompatibility between OpenPGP.js and PGPainless.

@seisvelas please ask the user if this key was generated on FlowCrypt browser extension, or if it was actually generated elsewhere and then imported into FlowCrypt. (if generated elsewhere, they could try to go to browser extension -> backup -> as a file, to export it from browser extension and then import into Android from there instead of the original source)

**Comment by gjikia** [comment]
@tomholub hi, the key was generated on a Linux machine and then successfully imported to FlowCrypt browser extension. The backup from the browser extension and an attempt to import the backup into an Android app has unfortunately failed again because of the "incorrect pass phrase".

**Comment by tomholub** [comment]
Could you try changing pass phrase on FlowCrypt extension, then exporting / importing into Android?

Sorry about the trouble. We'll still have to troubleshoot the original problem later, but this could work for you.

**Comment by gjikia** [comment]
Changing and exporting the pass phrase on on FlowCrypt extension (64 characters, no special characters) and importing into Android did not help. FlowCrypt app still complaints about the "incorrect pass phrase".
Does Android FlowCrypt app support subkeys? 
The OpenPGP subkeys were generated and exported like it is described here:  https://wiki.debian.org/GnuPG/AirgappedMasterKey .

**Comment by tomholub** [comment]
Thank you for trying that!

> Does Android FlowCrypt app support subkeys?

It support subkeys, but it seems like the implementation differs slightly between browser and Android.

Could we trouble you to create another set of test keys with a test pass phrase that you could both share with us publicly? With that, we'll be able to fix it on Android.

**Comment by gjikia** [comment]
So I've created a test key using the procedure, mentioned above, which produces the error ""Incorrect pass phrase" in Flowcrypt
[test-key.zip](https://github.com/FlowCrypt/flowcrypt-android/files/6797533/test-key.zip).
The password is password12345678

**Comment by tomholub** [comment]
Thank you!

@IvanPizhenko when you have some time please investigate this one

**Comment by tomholub** [comment]
If I understand it correctly, the above keypair works in FlowCrypt browser extension, but does not work in FlowCrypt Android app, suggesting an incompatibility.

If the issue ends up being in PGPainless, then we can report it there with some minimal repro.

**Comment by IvanPizhenko** [comment]
Yes, this goes down to PGPainless. I've opened an issue https://github.com/pgpainless/pgpainless/issues/154

**Comment by DenBond7** [comment]
@tomholub I confirm that PGPainless `org.pgpainless:pgpainless-core:0.2.4` fixes this issue.

**Comment by DenBond7** [comment]
fixed by #1344

**Comment by DenBond7** [comment]
@gjikia A new version with this fix is already available on `Google Play`

**Comment by gjikia** [comment]
Thank you, everything functioning as expected now.
