### ISSUE TITLE
auto-cancel previous ci builds if new commit pushed to branch

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#1299]
@DenBond7 you can add a similar change here https://github.com/FlowCrypt/flowcrypt-ios/commit/b9e14272d03e554dd6fd2c2ad24bd4407b8ca10f if you'd like to be able to push to a branch more often but don't always have to wait for all previous jobs to finish. I use it on flowcrypt-browser and it speeds things up (and uses less resources)

**Comment by DenBond7** [comment]
https://docs.semaphoreci.com/essentials/auto-cancel-previous-pipelines-on-a-new-push/#auto-cancel-both-running-and-queued-pipelines-on-a-new-push

**Comment by DenBond7** [comment]
for me

```diff
auto_cancel:
- queued:
-   when: "true" # enable auto-cancel for branches, tags and pull-request
+ running:
+   when: "branch != 'master'" # Auto-cancel all pipelines on a new push to a non-master branch
```
