### ISSUE TITLE
rename Servers screen in settings to Attester + functionality

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#131]
See the "Attester" screen in FlowCrypt Settings -> Additional Settings -> Attester

Basically, get all known addresses of the user, and then submit one call with all addresses to /lookup/email/ Attester API, then compare the results.

I will make the attester return longids to make this easier (do not compare pubkeys - compare longids).

The steps are, for each result from Attester API:
 - if no public key found, print email address and "example@email.com: No public key recorded. Your contacts may not know that you are using encryption." (orange color `#d18826`)
 - if public key found, and the longid does not match any longids of saved keys: "example@email.com : Wrong public key recorded. Incoming encrypted email may not be readable." (red color `#d14836`)
 - if public key found, and the longid does match one of the saved keys: "example@email.com : Submitted, can receive encrypted email." (green color `#31A217`)

You can re-use list design from "Keys" section, just remove the dates, remove the "+" button, and instead of Key Words, show the status of each  email.

**Comment by tomholub** [comment]
This is extremely helpful for debugging when user has trouble reading email, plus in the future, we will add action buttons to fix issues.

**Comment by DenBond7** [comment]
For me
POST /lookup/email
  
```
{
   "email":[
      "denbond7@test.com",
      "denbond7@test.net"
   ]
}
```

response(200): 

```
{
   "results":[
      {
         "has_cryptup":true,
         "pubkey":"-----BEGIN PGP PUBLIC KEY BLOCK-----END PGP PUBLIC KEY BLOCK-----",
         "email":"denbond7@test.com",
         "attested":true
      },
      {
         "has_cryptup":true,
         "pubkey":"-----BEGIN PGP PUBLIC KEY BLOCK-----END PGP PUBLIC KEY BLOCK-----",
         "email":"denbond7@test.net",
         "attested":false
      }
   ]
}
```

**Comment by DenBond7** [comment]
I completed this task on my side. I added a new field [here](https://github.com/FlowCrypt/flowcrypt-android/commit/1be7740257b63853a8c48afddc1106d143272678#diff-fdb26397b7e6e15cae88b1c5dafb530e). It's a `@SerializedName("longid")`. When you will add this property in the API all will work fine.

Example

```
{
   "results":[
      {
         "has_cryptup":true,
         "pubkey":"-----BEGIN PGP PUBLIC KEY BLOCK-----END PGP PUBLIC KEY BLOCK-----",
         "email":"denbond7@test.com",
         "attested":true,
         "longid": "DS787SSDSDS787SD"
      },
      {
         "has_cryptup":true,
         "pubkey":"-----BEGIN PGP PUBLIC KEY BLOCK-----END PGP PUBLIC KEY BLOCK-----",
         "email":"denbond7@test.net",
         "attested":false
         "longid": "D343433DSDS787SD"
      }
   ]
}
```

**Comment by tomholub** [comment]
Yes, I was planning that anyway, will do.

**Comment by tomholub** [comment]
Done. Note that `longid` may be null when pubkey not found.

**Comment by DenBond7** [comment]
> Note that longid may be null when pubkey not found.

Checked. All are working fine.
