### ISSUE TITLE
Attester - minor bug with multiple identities

### ISSUE THREAD

**Issue by vigi86** [FlowCrypt/flowcrypt-android#1313]
Hi, first of all: thanks for this amazing browser extension & app.

I ran into a little issue. I have one key with 2 identities (2 emails in one key). In the advanced settings of the browser extension I am able to see both identities in the Attester. However, the mobile app shows me two identities, but two times the same mail, which is wrong.

Browser (correct):
![image](https://user-images.githubusercontent.com/8401847/123594098-91e82d80-d7ef-11eb-8cdd-60c0cbc96082.png)

App (wrong):
![image](https://user-images.githubusercontent.com/8401847/123594317-d8d62300-d7ef-11eb-9a1a-dc4222b2205a.png)

Cheers 🍻

**Comment by DenBond7** [comment]
Hello @vigi86. Thank you for the feedback. I'll investigate an issue and add a reply soon.

**Comment by DenBond7** [comment]
ref #131

**Comment by tomholub** [comment]
On the browser extension, I believe we show the email address that we searched for, not the primary email address we parsed from the key.

I would do the same on android: show search string.

Thank you for the report!

**Comment by DenBond7** [comment]
> On the browser extension, I believe we show the email address that we searched for, not the primary email address we parsed from the key.

You are right. On Android, we show the primary email address we parsed from the fetched key

**Comment by DenBond7** [comment]
@vigi86 We've found a place of difference. It will be fixed in the upcoming releases. Thanks!

**Comment by vigi86** [comment]
You are very welcome! 🤙🏻
Thank you for your amazing work!
