### ISSUE TITLE
implement WKD client class

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#1317]
part of #1298 

This issue is a subset of #1201 as follows:

1. port Wkd class from browser extension
2. add tests for it independently of the rest of the codebase, merge the class unused

I hope we can ideally find a WKD client implementation done in Java so we don't have to re-implement it. If there isn't any, I hope we can at least find z-base-32 hash algorithm so we don't have to implement this low level code. If there isn't even that, we'll have to implement these.

**Comment by IvanPizhenko** [comment]
@tomholub I could not find ready client for WKD, but it looks like it should not be very hard to implement it.
Regarding ZBase32 - there is library (actually additional codec for the Apache Commons Codec framework)
https://mvnrepository.com/artifact/com.sandinh/zbase32-commons-codec

**Comment by IvanPizhenko** [comment]
Btw, zbase32 is not hash algorithm, it is data encoding algorithm, like base64.

**Comment by IvanPizhenko** [comment]
@tomholub So I still not sure should we use that zbase32 library or not because it is uncertain which license does it use. Please check it and explicitly approve or deny.

**Comment by tomholub** [comment]
Thank you for checking this thoroughly! :+1: 

Both Apache 2.0 and MIT License, or a combination, is fine. Let's start using it, and if it turns out the license is something else, we'll have to re-implement it.

Sorry for the brain fart in the description, of course it's an encoding mechanism, a pretty simple one.

**Comment by tomholub** [comment]
Here is the actual class to port - sorry I failed to mention it earlier:

https://github.com/FlowCrypt/flowcrypt-browser/blob/master/extension/js/common/api/key-server/wkd.ts

**Comment by tomholub** [comment]
I now see I mentioned it, just forgot to link it.

**Comment by IvanPizhenko** [comment]
Thank you!
