### ISSUE TITLE
IMAP: P3 BAD User is authenticated but not connected

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-android#1338]
The user sees this error when trying to authenticate via Outlook:

![Screenshot_20210703_003459_com flowcrypt email](https://user-images.githubusercontent.com/44826516/125179098-557ddf80-e1a8-11eb-8e12-a273f5e14322.jpg)

Suggestions?

**Comment by seisvelas** [comment]
ref: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGkZGgXnpZXhtKwRKNJhfBdBsfn

**Comment by DenBond7** [comment]
It seems that the user uses a regular connection type(not OAuth 2.0). There can be different issues. For example he can use 2FA. In that case he should create the app password instead of using the account password. Also IMAP access can be disabled in the settings.

**Comment by seisvelas** [comment]
Okay, thanks! I've asked whether the user has 2FA enabled on Outlook.

**Comment by seisvelas** [comment]
2FA is enabled, as is IMAP in Outlook settings. Any other suggestions?

**Comment by DenBond7** [comment]
What about the app password? Does he use the app password or the account password?

Btw, could you add me to the conversation?

**Comment by seisvelas** [comment]
I asked, and cc'd the email to you

**Comment by DenBond7** [comment]
deprecated
