### ISSUE TITLE
When will new version be released?

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-android#1342]
ref: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGkZQKvJnHbTTpjcxtPmSzRZRQf

A user is awaiting for some fixes in the new version and wants to know when it will be available.

**Comment by DenBond7** [comment]
@tomholub What do you think about that? Since 1.1.8 we have the following changes:

- Added the full support for keeping a pass phrase in RAM
- Fixed a bug of importing pub keys (#1304)
- Added using EKM to pull keys during setup

**Comment by tomholub** [comment]
Let's do a release now. I was waiting until you are available again, just in case.

**Comment by DenBond7** [comment]
Got it. I'll let you know when it will be ready.

**Comment by DenBond7** [comment]
ref #1343
