### ISSUE TITLE
PgpMsg.fmtContentBlock() missing chunks of text

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#1346]
PgpMsg.fmtContentBlock() 
--------------------------------------Node-------------------------------------------------------Kotlin------------------------------------------------

![image](https://user-images.githubusercontent.com/2863246/126447179-cb9672ab-9ac2-4665-8d4f-8b7fd1258614.png)

_Originally posted by @DenBond7 in https://github.com/FlowCrypt/flowcrypt-android/issues/1101#issuecomment-883951517_

**Comment by DenBond7** [comment]
@IvanPizhenko Please look at this issue after #1101

**Comment by tomholub** [comment]
Isn't it the same issue? :-) I've just created a more specific one with this bug above, as pre-requisite to continue with #1101

**Comment by IvanPizhenko** [comment]
@DenBond7 Please tell me:
1. At which branch should I look? is it `issue_1101_use_pgpainless_for_msg_decryption`? I've looked at your recent commits and you seem to  have made lots of changes after me. I will start from the last commit on that branch.
2.  Please add new or point me to an existing test email message, which I can use to investigate this.

**Comment by DenBond7** [comment]
@IvanPizhenko 
> At which branch should I look? is it issue_1101_use_pgpainless_for_msg_decryption? I've looked at your recent commits and you seem to have made lots of changes after me. I will start from the last commit on that branch.

`issue_1101_use_pgpainless_for_msg_decryption`

> Please add new or point me to an existing test email message, which I can use to investigate this.

Do you have access to `flowcrypt.compatibility`?

**Comment by tomholub** [comment]
I've sent Ivan the credentials on company email. There, you can find the email by subject

**Comment by DenBond7** [comment]
@IvanPizhenko 
> There, you can find the email by subject

by subject and date

**Comment by DenBond7** [comment]
![image](https://user-images.githubusercontent.com/2863246/126609426-689edb3d-cd57-4f70-9734-2cd56724bb32.png)

**Comment by tomholub** [comment]
The last screenshot with different css height is minor, I think it's ok to ignore it.

**Comment by IvanPizhenko** [comment]
I've tried to use @DenBond7 branch, but unit tests even do not compile on it. So first please make all present unit tests compiled successfully and passing, after that I can proceed further on that branch. Another way, (which I think I will take now) is to use master as base. Later on either me or @DenBond7 will have to merge any fixes into his branch.

**Comment by DenBond7** [comment]
@IvanPizhenko I think you can use the master branch

**Comment by IvanPizhenko** [comment]
Seems to have fixed it. I can't make warranty that content and visual look will be absolutely identical with Node and Kotlin, but now there should not be losses of text like this.

**Comment by tomholub** [comment]
Excellent. Identical result is not the goal of course. Thanks!
