### ISSUE TITLE
Kotlin decryption. don't break message render view when a public key is not valid

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#1348]
![image](https://user-images.githubusercontent.com/2863246/126484758-27dd5ffd-cb2c-40fb-a2bc-759f308331bc.png)

ref https://github.com/pgpainless/pgpainless/issues/158

**Comment by tomholub** [comment]
There are probably two issues here.

One, when any error happens parsing the public key, it should only affect the rendering of pubkey block, but still render the rest of the message normally.

Two, this looks like some incompatibility between OpenPGP.js and PGPainless that could probably be addressed in PGPainless.

**Comment by DenBond7** [comment]
> One, when any error happens parsing the public key, it should only affect the rendering of pubkey block, but still render the rest of the message normally.

I think so

**Comment by DenBond7** [comment]
![image](https://user-images.githubusercontent.com/2863246/126611439-a9e6d88d-0512-4649-84a2-8f8a2e2e8d00.png)

**Comment by tomholub** [comment]
@DenBond7 I think PGPainless rejected the public key correctly. So the only task here is to make sure that when parsing of public keys fails or they fail verification, it does not affect the whole rendering.

In this case, best would be to render everything as it was on the left, but in stead of the public key part, add a red box with `This message contained a Public Key that was not valid:\n\n${e::class.name}: ${e.message}`

**Comment by DenBond7** [comment]
> In this case, best would be to render everything as it was on the left, but in stead of the public key part, add a red box with This message contained a Public Key that was not valid:\n\n${e::class.name}: ${e.message}

I will show something like this one

![Selection_840](https://user-images.githubusercontent.com/2863246/134005839-f90ed81f-222c-44cf-a3ec-da421d2861a6.png)
