### ISSUE TITLE
Support MsgBlock.Type.SIGNED_MSG (Kotlin)

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#1353]
![image](https://user-images.githubusercontent.com/2863246/126601147-0a013228-b06f-4103-b9d1-a52ccacd05e6.png)

**Comment by DenBond7** [comment]
It looks like this one

  -----BEGIN PGP SIGNED MESSAGE-----
 Hash: [Hash algorithm]
 [Human Readable Message Body]
 -----BEGIN PGP SIGNATURE-----
 [Signature]
 -----END PGP SIGNATURE-----

We should display `[Human Readable Message Body]` for a user

**Comment by DenBond7** [comment]
[#1353.patch.txt](https://github.com/FlowCrypt/flowcrypt-android/files/6860525/1353.patch.txt)

**Comment by DenBond7** [comment]
ref https://github.com/pgpainless/pgpainless/issues/172

**Comment by tomholub** [comment]
This one is important to fix before any release.

Even if you were to print out the whole `-----BEGIN` and everything including signature, that would still be better than only showing this error. People often receive signed messages.

**Comment by DenBond7** [comment]
#1420 fixes all issues. I'm closing it.
