### ISSUE TITLE
PGPainless: compatibility issue?

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#1358]
![image](https://user-images.githubusercontent.com/2863246/126610835-11b56d2e-d6fa-4aaf-8b52-855838055687.png)

**Comment by tomholub** [comment]
This would be something to report to PGPainless likely

**Comment by tomholub** [comment]
@DenBond7 however an actionable item here for you will later be the same as https://github.com/FlowCrypt/flowcrypt-android/issues/1348 - not break the whole decrypt view when this happens, and still render the other parts.

**Comment by IvanPizhenko** [comment]
@DenBond7 @tomholub I have found this email in the "compatibility" mailbox, copied key out of it, and added simple unit test with it:
```kotlin
  @Test
  fun testPublicKey_Issue1358() {
    val keyText = loadResourceAsString("keys/issue-1358.public.gpg-key")
    val actual = PgpKey.parseKeys(keyText)
    assertEquals(1, actual.getAllKeys().size)
  }
```
And this unit test passes, key can be parsed successfully. I was using current version on the master. So it is unlikely PGPainless or maybe last PGPainless update has fixed it. I will post PR with some updated tests.

**Comment by IvanPizhenko** [comment]
@DenBond7 Reassigned to you, since there seems to be no issues on the PGPainless side, please look into Android specific parts.

**Comment by DenBond7** [comment]
it was encountered on `pgpainless-core:0.2.4`. After trying to use `pgpainless-core:0.2.7` I can't reproduce an error. We can close it.
