### ISSUE TITLE
Kotlin decryption. Test decryption errors after moving to use PGPainless for the message decryption

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#1360]
It would be nice to have such tests. I think it's very important to prevent security bugs (for example after upgrading PGPainless to a newer version). We should be sure that a received content is parsed to expected `blocks` and Android shows the expected UI.

**Comment by DenBond7** [comment]
I'm talking about things like this one

![image](https://user-images.githubusercontent.com/2863246/126613373-3cb52543-b588-490c-aadd-bd8e3beddb51.png)

**Comment by DenBond7** [comment]
@tomholub It would be nice to create a list of the decryption errors that we would like to handle. I think it will be useful for all platforms

**Comment by tomholub** [comment]
Yes. All error scenarios that are interesting are represented in flowcrypt.compatibility account as email messages, so we can extract them from there (as you have done)

**Comment by tomholub** [comment]
`tests/decrypt error` label should have most of them. If you see any that are (expected) errors and not labeled that way, feel free to add the label, so that they are all in one place.

**Comment by DenBond7** [comment]
> tests/decrypt error label should have most of them. If you see any that are (expected) errors and not labeled that way, feel free to add the label, so that they are all in one place.

For now, I see the following decryption errors

1. Encrypted message inside signed
2. WRONG CHECKSUM - Message is either badly formatted or not compatible with FlowCrypt
3. NO_MDC - Security threat. The message is missing integrity checks (MDC)
4. BAD_MDC - Security threat. Opening this message is dangerous because it was modified in transit
5. Message encrypted for public keys that don't match(An active account doesn't have a right private key)
6. Message encrypted for another public key (only one public key used, the sender public key)

**Comment by tomholub** [comment]
5 and 6 are the same thing - should be returning KEY_MISMATCH error

Also there is FORMAT error - take any armored message, remove some lines from the middle, and then try to read it.

> Encrypted message inside signed

This one doesn't really sound like an error.

**Comment by DenBond7** [comment]
Updated

**Comment by tomholub** [comment]
On browser extension I also have "other" when it throws some exception I don't recognize.

**Comment by tomholub** [comment]
I suppose you have something similar

**Comment by DenBond7** [comment]
Updated

**Comment by DenBond7** [comment]
@tomholub Please look at the following screenshots. Do they look good?
### WRONG CHECKSUM
![image](https://user-images.githubusercontent.com/2863246/134630154-38155e60-9bbe-44e0-897a-f727bb255a1a.png)

### NO_MDC
![image](https://user-images.githubusercontent.com/2863246/134630298-551f4286-6ebd-48c2-a5df-6bc592f6f3d3.png)

### BAD_MDC
![image](https://user-images.githubusercontent.com/2863246/134630402-4253a3a8-9390-43bc-8b32-d943d2c35fa4.png)

### KEY_MISMATCH
![image](https://user-images.githubusercontent.com/2863246/134630800-d7c1b1b8-8f70-4d40-b0cc-522838c9fbba.png)

### FORMAT
![image](https://user-images.githubusercontent.com/2863246/134633221-90d09dfa-e083-4cf5-9ca8-36b348efdd5a.png)

**Comment by tomholub** [comment]
It's all good for now. For the mdc checks missing/wrong, eventually we'll show the content of the decrypted message instead of the armor, but that is already filed for later https://github.com/FlowCrypt/flowcrypt-android/issues/1363#issuecomment-922845072

else good

**Comment by DenBond7** [comment]
> 3. BAD_MDC - Security threat. Opening this message is dangerous because it was modified in transit

@tomholub Do you know how to reproduce this error? I need to have it for flowcrypt.test

**Comment by DenBond7** [comment]
> NO_MDC - Security threat. The message is missing integrity checks (MDC)

For history. To reproduce this error we can use an old version of GnuPG. For example [GnuPG 1.4](https://www.gnupg.org/ftp/gcrypt/gnupg/gnupg-1.4.23.tar.bz2)

via `gpg --encrypt --sign --armor --disable-mdc -r fingerprint` we can create a PGP message without MDC like this one

```
-----BEGIN PGP MESSAGE-----

hQIMA3LvK1JdDBkzAQ//RjLOB+l/hvljxS+WamHcsx6JH4YVWcrElifdlmmFTB0z
R+F3mlJXLLAbpwAs0hLpfpsI+cpf3Ori67FfGyQPxCY3O0ilamPIvaJm7CqBJ08Y
c0zwVXpmOfAj0cv3NtPKERx88LgukolLk72m5UV2jVKv5fwH685B202rO08GcCt6
GO8CfvyzMv42ys8KgiPkZd8snY9NBT5918nHqHywBFmU9N3suiLM2nKvvFsg+bAg
+0yGkhrFxyWuoL+OYiytR1rutDQjiqwBM7rWvwNFqN3hcBtY46qqQNq0PMe2n1Xm
1fcYI2ESganoO6Ovt2m5LbEyRAJYbVpeTAe/zS1EcmF7Abcn4Zy6mrWi+7eaVfju
8zhE4rxCxkQCFLb+bNc5hBl7ZTT7u7PcoRVGG8KSJc401ztef14RpzzpyP/RIhpq
V4m88VZ9yimr7eIvGPG2WHW445JCq47iu61j8FyVnscgFCMNTyn3t2k/IS/dyVEA
PeN36NUBhd8rM5i6WopO9szqFtwNI0Y9+xvjy07OBueU0enmxA3dcdq21Zc80F/3
kkyD7W5dh4p4uBFzyL/o187hSlqGFk2+d9d6qDKVm7Ff3cY2ivF8SHXjtYk9kau2
ZhFyoT8D1Jf3sYxCOdj72FyByPv/ugrxce/wu9bVBZbw7WDxcxmgvEsXv+UxTTrJ
wKHaEMxIbu1scpeSVUEaaAKeiviCkkC5m8jHTpjCmcVt8Sl8ucw/m5AwWIJosR20
0NmxsgsEhT10fyuynWi3JhDpi+Z+TPTAxNgTqHR5pCBga/gyAQUbpNcWASylp6qa
AmqrP2IFEhED6MUmxcNLomIscRVUSS29+JHJZ7RLKORKymJq2stMnpuntwV+Hq7P
ZqSyI7YtiUvgFsINTdpydAWmIEkSOfIDNoDFDEcxFa7AYz72YEVUHVuuS5pmJ/A+
fmkvS74gJMTqf7NYRE40uUUF9gPCS86qOeyzlYqxYdCZ0ipDrUQEMFNSgwLVuDBH
EM23JNOSs13nABklfWYkS9AAV1WYn/UxOHgBPspS1I+izTt2DQmjCd7RChk6a12K
R8C2GYrhhlsqMNZhwaI6gGKEg5yD2Ru3oVZPGrdifMaAu1mbOVzUHfJTFzzH/2xe
AD30MkqtGBtQ0rBnaMC4E8+JIA==
=5QII
-----END PGP MESSAGE-----
```

I've used the [following link](https://askubuntu.com/a/819230) to set up GnuPG on docker

**Comment by tomholub** [comment]
You can extract message with subject `encrypted - MDC hash mismatch - modification detected - should fail` from compatibility account

**Comment by tomholub** [comment]
NO_MDC is different from BAD_MDC. First case there is no checksum, in second case there is checksum but it's wrong.

**Comment by DenBond7** [comment]
> You can extract message with subject `encrypted - MDC hash mismatch - modification detected - should fail` from compatibility account

it requires adding keys(with a passphrase) of `flowcrypt.compatibility` to the Android emulator. I don't like that idea. The best would be to create a PGP message with BAD_MDC for `flowcrypt.test` accounts. If it sounds too difficult I think we can leave it as is(or for later). We handle `BAD_MDC` via `JUnit` tests(`PGPainless`). On Android(Instrumentation tests with UI), we have tests for all decryption errors, except `BAD_MDC`(we handle it, but don't have a UI test)

**Comment by tomholub** [comment]
sounds ok to me
