### ISSUE TITLE
Email Smart Sync

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#137]
- [ ] https://developer.android.com/topic/performance/scheduling.html

- [ ] https://developer.android.com/training/basics/network-ops/managing.html

- [ ] https://tools.ietf.org/html/rfc4549

- [ ] https://tools.ietf.org/html/rfc4551#section-3.1.1

**Comment by tomholub** [comment]
Is this a performance improvement?

**Comment by DenBond7** [comment]
No. In general, it's about full synchronization. There are a lot of nuances. I decided to collect them here.

**Comment by tomholub** [comment]
Ok I'll let you decide which milestone this is appropriate for

**Comment by DenBond7** [comment]
for me https://medium.com/google-developers/scheduling-jobs-like-a-pro-with-jobscheduler-286ef8510129

**Comment by DenBond7** [comment]
Yesterday I found some bugs. I'll try to fix them today and then I'll merge issue_137 to 0.6.4.
