### ISSUE TITLE
refetch client configuration on every startup

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#1375]
we should be pulling client configuration again from FES on every startup of the app, in background (don't hold up UI functionality while fetching). It doesn't need authentication, so it should be pretty easy to loop through all set up accounts and re-fetch/re-save the client configuration. I'll save another issue. That will also solve this.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-android/issues/1327#issuecomment-889042775_

**Comment by DenBond7** [comment]
@tomholub Please let me clarify one moment. When you said

> on every startup of the app,

Did you mean?

1. Run it once when we run the app process. It will not be too often(it depends on a device, Android version, manufacturers and etc.)
2. Run every time when we open the app from the main screen. For example, open the app(`fetch FES`), go to settings, press back, press back again and exit from the app to the home screen, open the app again(`fetch FES`)

**Comment by tomholub** [comment]
How about run it "first time the user views inbox since app came into foreground" ?

So:

1) open the app - view inbox - refetch
2) go to open message, back to inbox - no refetch
3) go to open message, switch to other app - no refetch
4) switch to flowcrypt again, message opens - no refetch
5) go back to inbox - refetch
6) go back to message and back to inbox - no refetch
7) switch to other app and back to flowcrypt - inbox renders - refetch
8) kill the app. Reopen. Inbox loads. refetch
