### ISSUE TITLE
[connectivity issue] Unreliable show only encrypted message 

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-android#1389]
Description:
One of the FlowCrypt for Android user experience some network connectivity issues. I have further explored it based on the user's description. I can confirm that it is indeed not a connection issue but maybe a faulty function in showing the only encrypted messages. When the "show only encrypted message" was toggled to ON, the application will return a connection error at least for Gmail based on the user and my testing case.

Steps to reproduce:
1. Log in to your Gmail account via Flowcrypt for Android
2. Toggle the show an "only encrypted message" option
3. You will no longer be able to fetch any encrypted message and thus, it will throw a network connectivity issue. 

Additionally, this typically happens when a new encrypted message has arrived in the user's inbox which I tested and confirmed.

Reference:
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGkZkLrTWhrGllxBGdhwxHKxKMM
https://mail.google.com/mail/u/2/#inbox/FMfcgzGlkrzCNZqcrtGLwvFkqmksvWQW

**Comment by martgil** [comment]
Several more report(s):
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGpGKgJPVJdCZwDlJSCZqRdpCpn

**Comment by DenBond7** [comment]
I'm closing it. We removed "show only encrypted message". This issue is deprecated.
