### ISSUE TITLE
Create a template for sending non editable service messages

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#139]
Need to create a template for this situation.
![image](https://user-images.githubusercontent.com/2863246/32504526-b50d500c-c3e8-11e7-81e4-4fd414984df1.png)

**Comment by tomholub** [comment]
Actually these messages may be editable (the text itself), because people may want to send it in their own language. However the public key cannot be removed, and message cannot be switched to another type, recipient cannot be changed, etc.

**Comment by DenBond7** [comment]
@tomholub How do you generate a public.key name?

**Comment by DenBond7** [comment]
@tomholub Please will test what I added. I added the ability to send one or more public keys per one message.

Examples:
![- -1](https://user-images.githubusercontent.com/2863246/33231018-817d89ca-d1f6-11e7-8cf4-311006efb15f.png)
![- -2](https://user-images.githubusercontent.com/2863246/33231020-8493d5e2-d1f6-11e7-90be-28532f08c13e.png)

**Comment by tomholub** [comment]
You should ideally auto-select only the key whose email address corresponds to the email you received the message at.

Eg if you are replying to message that was received on gmail, you should respond with that key.

Also it should be a radio button if we let people choose. But ideally, the software should have a mechanism to figure out which one is the right key and don't ask the user (later).

**Comment by DenBond7** [comment]
> You should ideally auto-select only the key whose email address corresponds to the email you received the message at.

I did it.
