### ISSUE TITLE
use Gmail /upload api

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#140]
> But I found one nuance. I do not recommend sending large files (more than 5Mb) with Gmail aliases because the Gmail API uses standard POST request. Before sending a message, Gmail API create JSON structure with the message details (include raw data of attachment as a base64url encoded string). All of this information will be in the RAM and it can be a reason of memory leaks.

> Got it. On desktop I use the /upload API for this, which required a direct HTTP multipart request. This could probably be done as a stream from Java (later).

https://developers.google.com/gmail/api/guides/uploads#multipart

**Comment by tomholub** [comment]
@DenBond7 I suspect this has been done when implementing Gmail API?

**Comment by DenBond7** [comment]
Reopening. I have to check it to be sure.

**Comment by DenBond7** [comment]
@tomholub I've checked that. We still can't close this issue. Currently, all things are the same.

https://github.com/FlowCrypt/flowcrypt-android/blob/7777b5648d1f92f4920f5e1c69a8edfea4a78f86/FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/workmanager/MessagesSenderWorker.kt#L399

> On desktop I use the /upload API for this, which required a direct HTTP multipart request. 

Android uses https://developers.google.com/gmail/api/reference/rest/v1/users.messages/send to send a message. But maybe I've missed something and that can be improved.

Would you like to complete this issue as a part of `1.1.7`?

**Comment by tomholub** [comment]
If this affects our ability to send large files, please have a look. I'd like to allow sending larger files. Thanks!
