### ISSUE TITLE
I ran out of issues

### ISSUE THREAD

**Issue by IvanPizhenko** [FlowCrypt/flowcrypt-android#1401]
Following @tomholub advise :) https://github.com/FlowCrypt/flowcrypt-android/issues/1118#issuecomment-806453676

**Comment by tomholub** [comment]
Let's do the following
1) I'll assign some issues on on-prem repository, and you can do work there for some time. I suppose @DenBond7 will be doing many changes on this repo when removing NodeJS, so we'll let him work on Android alone for a month or two until the code settles.
2) For about two months later, I've prepared "for Ivan" milestone of things you can look into: https://github.com/FlowCrypt/flowcrypt-android/milestone/91

**Comment by tomholub** [comment]
@IvanPizhenko update - let's do #1402 first please. So the sequence is:

1) #1402
2) on-prem issues I'm about to assign
3) "for Ivan" milestone after that https://github.com/FlowCrypt/flowcrypt-android/milestone/91

**Comment by IvanPizhenko** [comment]
ok
