### ISSUE TITLE
Add tests for BetterInternetAddress

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#1402]
It would be nice to have tests for BetterInternetAddress(https://en.wikipedia.org/wiki/Email_address#Internationalization_examples)

### Valid email addresses

- [x] simple@example.com
- [x] very.common@example.com
- [x] disposable.style.email.with+symbol@example.com
- [x] other.email-with-hyphen@example.com
- [x] fully-qualified-domain@example.com
- [x] user.name+tag+sorting@example.com (may go to user.name@example.com inbox depending on mail server)
- [x] x@example.com (one-letter local-part)
- [x] example-indeed@strange-example.com
- [x] test/test@test.com (slashes are a printable character, and allowed)
- [ ] admin@mailserver1 (local domain name with no TLD, although ICANN highly discourages dotless email addresses[10])
- [x] example@s.example (see the List of Internet top-level domains)
- [ ] " "@example.org (space between the quotes)
- [x] "john..doe"@example.org (quoted double dot)
- [x] mailhost!username@example.org (bangified host route used for uucp mailers)
- [x] user%example.com@example.org (% escaped mail route to user@example.com via example.org)
- [x] user-@example.org (local part ending with non-alphanumeric character from the list of allowed printable characters)

### Invalid email addresses

- [x] Abc.example.com (no @ character)
- [x] A@b@c@example.com (only one @ is allowed outside quotation marks)
- [x] a"b(c)d,e:f;g<h>i[j\k]l@example.com (none of the special characters in this local-part are allowed outside quotation marks)
- [x] just"not"right@example.com (quoted strings must be dot separated or the only element making up the local-part)
- [x] this is"not\allowed@example.com (spaces, quotes, and backslashes may only exist when within quoted strings and preceded by a backslash)
- [x] this\ still\"not\\allowed@example.com (even if escaped (preceded by a backslash), spaces, quotes, and backslashes must still be contained by quotes)
- [x] 1234567890123456789012345678901234567890123456789012345678901234+x@example.com (local-part is longer than 64 characters)
- [x] i_like_underscore@but_its_not_allowed_in_this_part.example.com (Underscore is not allowed in domain part)
- [x] QA[icon]CHOCOLATE[icon]@test.com (icon characters)

Also, we should support localhost for local testing
- [x] simple@localhost
- [x] "Personal Name <simple@localhost>"

**Comment by tomholub** [comment]
@DenBond7 I'm thinking this should be the job of the library, rather then writing the tests ourselves. And most likely, the handling will end up being different on our browser extension and iOS app almost regardless of what we do. I suggest to close this issue.

**Comment by tomholub** [comment]
Ah. I see. Ok, we should probably do this.

**Comment by DenBond7** [comment]
I think this issue is quite important. And it would be nice to have a similar checking for all platforms. 

@tomholub Could you share more details on how you check if an email address is valid and how you parse emails?

@IvanPizhenko has added `BetterInternetAddress` as an alternative for [InternetAddress](https://docs.oracle.com/javaee/6/api/javax/mail/internet/InternetAddress.html). For now, we use it but don't have any tests. it should be improved.

Anyway, I think we can approve some `regex` patterns for these purposes. In that case, we will have the same behavior on all platforms.

**Comment by tomholub** [comment]
Here is browser extension. It could be worse than `BetterInternetAddress`, hard to say. But it has worked for a long time without complaints.

```ts
  public static isEmailValid = (email: string) => {
    if (email.indexOf(' ') !== -1) {
      return false;
    }
    // for MOCK tests, we need emails like me@domain.com:8001 to pass
    // this then makes the extension call fes.domain.com:8001 which is where the appropriate mock runs
    email = email.replace(/\:8001$/, '');
    return /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/i.test(email);
  }
```

**Comment by tomholub** [comment]
It doesn't support email like `" "@example.org` but to be honest that's a horrible email address, I have no issue with not supporting it even if it's valid :grin:  ..

**Comment by DenBond7** [comment]
Thank you for the example. It will be helpful for Ivan.

**Comment by DenBond7** [comment]
Btw, @Kharchevskyi what about your side? Could you share details for iOs?

**Comment by IvanPizhenko** [comment]
I've copied BetterInternetAddress from our another repo.
