### ISSUE TITLE
Add user to docker with messages but without backups

### ISSUE THREAD

**Issue by Kharchevskyi** [FlowCrypt/flowcrypt-android#1421]
Please add user to test imap/smtp server which has emails but without any backups

**Comment by DenBond7** [comment]
To add a new user to the test email server please follow these steps:

1. Go to `docker-mailserver/docker-compose.yml`. Uncomment  `#- ./maildata_volume:/var/mail`
![image](https://user-images.githubusercontent.com/2863246/130313037-60cda5a2-ce80-431b-8edb-06f7d4d261da.png)
2. Run the local email server via `docker-mailserver/run_email_server.sh`
3. Run `docker-mailserver/scripts/add_user.sh` to add a new user. For example `./add_user.sh has_msgs_no_backups@flowcrypt.test`
4. Check `docker-mailserver/config/postfix-accounts.cf`. There should be a new account.
![image](https://user-images.githubusercontent.com/2863246/130313116-5b6f58d6-1ac2-4ae2-afcd-965ae1c24e45.png)
5. After that it would be nice to log in with created credentials to prepare the user's folders on the email server. I use `Thunderbird` for that.
![image](https://user-images.githubusercontent.com/2863246/130313199-05e6d104-3904-4dff-aaa3-ff0792746648.png)
6. Then run `docker-mailserver/stop_email_server.sh` to stop the email server.
7. Go to `docker-mailserver/docker-compose.yml`. Comment  `- ./maildata_volume:/var/mail` to disable storing data locally.
8. Copy `docker-mailserver/maildata_volume/flowcrypt.test` to `docker-mailserver/maildata_source/flowcrypt.test`. `maildata_source` will be used to add changes to a docker image.
9. After that need to update the docker image to apply changes.

It would be great to add it to Wiki

**Comment by DenBond7** [comment]
@Kharchevskyi I've added such a user.
@tomholub Please deploy changes to the remote server.

**Comment by tomholub** [comment]
re-deployed
