### ISSUE TITLE
migration to PGPainless. HTML title in the message text

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#1439]
@tomholub Is it necessary to show the HTLM title in the message text? @IvanPizhenko has added a realization without that. Node.js realization includes the HTLM title in the message text.

HTML

`<title>Get started on your new device</title>`

`Node.js`
![Selection_788](https://user-images.githubusercontent.com/2863246/131341207-20f90c1b-f315-4101-a9bb-cf8c241b42e5.png)

`PGPainless`
![Selection_787](https://user-images.githubusercontent.com/2863246/131340903-c34f9aa0-d4f8-40c3-a37e-2a450752ad21.png)

**Comment by tomholub** [comment]
What does gmail app show?

**Comment by DenBond7** [comment]
Gmail shows the following

![Screenshot_2021-08-30-17-58-50-72_e307a3f9df9f380ebaf106e1dc980bb6](https://user-images.githubusercontent.com/2863246/131359859-f02de931-8ee1-48e7-bf47-219d80f00cb7.jpg)

**Comment by tomholub** [comment]
No title. In that case, the PGPainless implementation is better, I think.

**Comment by DenBond7** [comment]
Got it. So I'm closing it.
