### ISSUE TITLE
Migration to PGPainless. Message details. TRIPLE_DES

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#1445]
web

![image](https://user-images.githubusercontent.com/2863246/132049739-c8d9c5ea-40c1-426a-b96a-28cb277f6845.png)

Android Node.js

![image](https://user-images.githubusercontent.com/2863246/132049884-f7827956-2033-4254-b70b-876f46587b5d.png)

Android PGPainless

![image](https://user-images.githubusercontent.com/2863246/132049977-ce42ea64-0595-449d-8f80-ad9314183510.png)

**Comment by tomholub** [comment]
Looks good enough for this milestone. In the future, we could make the error a bit more user friendly like:

`Message was not decrypted because it uses a weak encryption algorithm (XXX)` where XXX is `TRIPLE_DES` or whatever other algorithm it was.

**Comment by tomholub** [comment]
We'll probably disallow it in browser extension too.

**Comment by DenBond7** [comment]
![image](https://github.com/FlowCrypt/flowcrypt-android/assets/2863246/5ba391de-8d2f-4c6a-a6c3-c2dad7443a36)

**Comment by DenBond7** [comment]
![image](https://github.com/FlowCrypt/flowcrypt-android/assets/2863246/e8fbee76-8fbe-46d1-987c-d7aecd14364b)
