### ISSUE TITLE
PGPainless usage. Fix changing passphrase

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#1448]
ref https://github.com/FlowCrypt/flowcrypt-browser/issues/3945
ref https://github.com/pgpainless/pgpainless/issues/176

```kotlin
  private fun changeKeyPassphrase(
    key: PGPSecretKeyRing,
    oldPassphrase: Passphrase,
    newPassphrase: Passphrase
  ): PGPSecretKeyRing {
    return PGPainless.modifyKeyRing(key)
      .changePassphraseFromOldPassphrase(oldPassphrase)
      .withSecureDefaultSettings()
      .toNewPassphrase(newPassphrase)
      .done()
  }
```

**Comment by DenBond7** [comment]
@tomholub I can fix it quite fast. I propose to make a new release with the fix. What do you think?

**Comment by tomholub** [comment]
> @tomholub I can fix it quite fast. I propose to make a new release with the fix. What do you think?

Sure, we can make a release.

**Comment by IvanPizhenko** [comment]
I've looked into issue and fix and approved PR.
