### ISSUE TITLE
reply does not get attached to gmail conversation

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#145]
I have been noticing today that my replies do not attach to the message I'm replying to. Eg when I go back to mail.google.com on laptop, the reply shows as a new conversation.

This is probably related to using the Gmail API for sending - I think it will need thread id to attach to when using the API.

I've noticed it on some non-encrypted messages.

**Comment by tomholub** [comment]
I've added this to a bugfix milestone so that we can get it out before working on 0.4.0

**Comment by tomholub** [comment]
(this is about the sent message in sent folder)

**Comment by DenBond7** [comment]
From here https://developers.google.com/gmail/api/guides/threads

In order to be part of a thread, a message or draft must meet the following criteria:

1. The requested threadId must be specified on the Message or Draft.Message you supply with your request.
2. The References and In-Reply-To headers must be set in compliance with the RFC 2822 standard.
3. The Subject headers must match.

**Comment by DenBond7** [comment]
It's strange but I don't understand what problem is. I use 2 phones with FlowCrypt and send a message/ reply to the message ---> I see a conversation on the web client.

Could you provide few steps to reproduce this issue?

**Comment by tomholub** [comment]
Just
1) receive a message from someone else on alias address
2) reply to it from Android (use the alias address to reply)
3) go to mail.google.com sent messages, the sent message will not be attached to the thread

**Comment by DenBond7** [comment]
Do you receive such message for Gmail account? Do I must add the second
Gmail account for checking incoming emails?

**Comment by tomholub** [comment]
The second gmail account is just some other person. I'll do some
screenshots.

--
Tom James Holub <http://holub.me/>

**Comment by tomholub** [comment]
Start with a message received from someone else on your alias email:

![image](https://user-images.githubusercontent.com/6306961/32667338-4b6f36ac-c5ef-11e7-92de-46ad0df01503.png)

It will look like this in the phone:

![screenshot_20171110-091308](https://user-images.githubusercontent.com/6306961/32667408-8145723c-c5ef-11e7-8fc6-85a01031a631.png)

Reply to it from phone:

![screenshot_20171110-091328](https://user-images.githubusercontent.com/6306961/32667477-a27295c0-c5ef-11e7-8603-b72416eb2b15.png)

Finally, view the original message. It will still look like this:

![image](https://user-images.githubusercontent.com/6306961/32667338-4b6f36ac-c5ef-11e7-92de-46ad0df01503.png)

Go to sent folder, and you will find this:

![image](https://user-images.githubusercontent.com/6306961/32667539-cb3ce500-c5ef-11e7-8754-73840450dada.png)

**Comment by tomholub** [comment]
It does thread correctly on original sender's side. 

But not on the replying person's side.


![image](https://user-images.githubusercontent.com/6306961/32668200-c59162fa-c5f1-11e7-8a45-736f0c192abf.png)

**Comment by DenBond7** [comment]
> I think it will need thread id to attach to when using the API.

@tomholub Yes, you were right. I found a solution.

I need a help with next situation: Before creating the reply I need to retrieve the original message thread Id using [Gmail API](https://developers.google.com/gmail/api/v1/reference/users/messages/list) . While I do that operation I can receive some errors (network and etc.). How to be with that?

1. Send reply without thread id
2. Show the error to the user and don't send the reply.

**Comment by DenBond7** [comment]
[Gmail API In-Reply-To not working(Google not handling on one side)](https://stackoverflow.com/questions/33171769/gmail-api-in-reply-to-not-workinggoogle-not-handling-on-one-side)

**Comment by tomholub** [comment]
Is it possible to get the threadId asynchronously (in the background) after reply screen is loaded so that it doesn't block displaying the reply screen?

If it didn't load by the time I pressed send button, then when I do press send button, load it synchronously + send the message. If error happens here, show retry button.

**Comment by tomholub** [comment]
That means the first attempt may fail silently (in the background), but that's ok because you can try again after clicking send button.

**Comment by DenBond7** [comment]
> load it synchronously + send the message. If error happens here, show retry button.

You already can test it. All works as you described above.

**Comment by tomholub** [comment]
Looks good
