### ISSUE TITLE
Kotlin decryption. Add support of attached signature

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#1456]
web
![Selection_809](https://user-images.githubusercontent.com/2863246/133773289-d70d54dd-3213-4473-93b8-ba00447208e7.png)

Android Node.js

![Selection_810](https://user-images.githubusercontent.com/2863246/133773484-6908171d-cbff-4fb2-aa76-bec73126735b.png)

Android PGPainless

![Selection_811](https://user-images.githubusercontent.com/2863246/133773539-1af4c0b9-82a4-4b91-8740-7ef1d3996fb3.png)

**Comment by tomholub** [comment]
same here - missing text is a problem
