### ISSUE TITLE
Migration to PGPainless. Message details. "Jira ticket should get recognized as mime"

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#1460]
web
![Selection_816](https://user-images.githubusercontent.com/2863246/133968261-88a43ea2-0b25-42b5-914d-974dea7bafed.png)

Android Node.js
![Selection_817](https://user-images.githubusercontent.com/2863246/133968329-d95e5616-0e5b-4972-b263-e02df6e05d23.png)

Android PGPainless (Kotlin)

![Selection_818](https://user-images.githubusercontent.com/2863246/133968403-2e016301-99f5-47c4-aefd-7c09a8422fac.png)

**Comment by tomholub** [comment]
Already better than before - moving to later to discuss separately.
