### ISSUE TITLE
Migration to PGPainless. Message details. "looks like a public key pasted as text but is invalid"

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#1463]
web
![Selection_827](https://user-images.githubusercontent.com/2863246/133974763-6230bdc9-a94a-433f-b621-00896ce99cdb.png)

Android Node.js

![Selection_826](https://user-images.githubusercontent.com/2863246/133974774-c357e36b-aa80-46bc-8e45-527bf3960b16.png)

Android PGPainless(kotlin)
![Selection_828](https://user-images.githubusercontent.com/2863246/133974822-f900fca5-1249-4014-9a0c-14cee9c7ed6f.png)

**Comment by tomholub** [comment]
that's ok enough for now

**Comment by DenBond7** [comment]
duplicate of #1444
