### ISSUE TITLE
what tooling do we use for test automation?

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#1466]
I received a question from a work candidate:

> What do you use for Android automation?

@DenBond7 is there anything specific that we use? is it just standard Android test tooling, or something more specific (libraries, frameworks) ?

**Comment by DenBond7** [comment]
As described in the [README](https://github.com/FlowCrypt/flowcrypt-android#readme) we have JUnit and Instrumentation tests. 

- For JUnit tests we use ["junit:junit"](https://mvnrepository.com/artifact/junit/junit) and a little [robolectric](http://robolectric.org/)
- For Instrumentation tests we use [Espresso](https://developer.android.com/training/testing/espresso)

It's a standard way for testing(nothing special)

By the way, [README](https://github.com/FlowCrypt/flowcrypt-android#readme) is a good place to start to investigate what we have for now.

**Comment by tomholub** [comment]
Thanks! Nothing else particular is used for UI tests specifically? Could you share a link to some simple UI sample test where the methods used are easy to see?

**Comment by DenBond7** [comment]
>Could you share a link to some simple UI sample test where the methods used are easy to see?

https://github.com/FlowCrypt/flowcrypt-android/blob/e635cabc673d7cbe2b3e221645072e1c1da17bff/FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/activity/ShareIntentsTest.kt#L59

**Comment by tomholub** [comment]
Thanks!
