### ISSUE TITLE
noname files related to OpenPGP should be recognized

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#1475]
To reproduce:

1) send a message from Browser Extension - Firefox and switch to `Rich Text (PGP/MIME)`. Add some bold text (ctrl+b)
2) receive the message on Android

Actual result:

![image](https://user-images.githubusercontent.com/6306961/134170552-2f32ae71-2b13-4029-b706-dbab61e8e3c4.png)

Expected result: file with an empty name `application/pgp-encrypted` and content like `Version: 1` should be recognized as pgp-related and hidden.

**Comment by DenBond7** [comment]
@tomholub I'm analyzing the MIME format of such a message and see that it doesn't equal [RFC3156](https://datatracker.ietf.org/doc/html/rfc3156) (MIME Security with OpenPGP)

I see 

```
      Content-Type: multipart/mixed; boundary=foo;

      --foo
      Content-Type: text/plain

      -----BEGIN PGP MESSAGE-----
      Version: 2.6.2

      hIwDY32hYGCE8MkBA/wOu7d45aUxF4Q0RKJprD3v5Z9K1YcRJ2fve87lMlDlx4Oj
      eW4GDdBfLbJE7VUpp13N19GL8e/AqbyyjHH4aS0YoTk10QQ9nnRvjY8nZL3MPXSZ
      g9VGQxFeGqzykzmykU6A26MSMexR4ApeeON6xzZWfo+0yOqAq6lb46wsvldZ96YA
      AABH78hyX7YX4uT1tNCWEIIBoqqvCeIMpp7UQ2IzBrXg6GtukS8NxbukLeamqVW3
      1yt21DYOjuLzcMNe/JNsD9vDVCvOOG3OCi8=
      =zzaA
      -----END PGP MESSAGE-----

      --foo
      Content-Type: application/pgp-encrypted; name=""
      Content-Disposition: attachment
      Content-Transfer-Encoding: base64
     
      --foo--
```
But `RFC3156` requires the following

```
      Content-Type: multipart/encrypted; boundary=foo;
      protocol="application/pgp-encrypted"

      --foo
      Content-Type: application/pgp-encrypted

      Version: 1

      --foo
      Content-Type: application/octet-stream

      -----BEGIN PGP MESSAGE-----
      Version: 2.6.2

      hIwDY32hYGCE8MkBA/wOu7d45aUxF4Q0RKJprD3v5Z9K1YcRJ2fve87lMlDlx4Oj
      eW4GDdBfLbJE7VUpp13N19GL8e/AqbyyjHH4aS0YoTk10QQ9nnRvjY8nZL3MPXSZ
      g9VGQxFeGqzykzmykU6A26MSMexR4ApeeON6xzZWfo+0yOqAq6lb46wsvldZ96YA
      AABH78hyX7YX4uT1tNCWEIIBoqqvCeIMpp7UQ2IzBrXg6GtukS8NxbukLeamqVW3
      1yt21DYOjuLzcMNe/JNsD9vDVCvOOG3OCi8=
      =zzaA
      -----END PGP MESSAGE-----

      --foo--
```
Could you share more details about the format that you use?

**Comment by tomholub** [comment]
I'm unable to send `      Content-Type: multipart/encrypted; boundary=foo;` due to https://github.com/FlowCrypt/flowcrypt-browser/issues/3157 so I'm sending whatever you are seeing above, unfortunately.
