### ISSUE TITLE
attachment lost when replying

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#1476]
to reproduce:

1) receive an encrypted message
2) reply all
3) attach a file (tested with 6mb image)
4) add body and send

expected result: sent reply contains the attachment

actual result: attachment missing

works on new messages

**Comment by tomholub** [comment]
observed on https://github.com/FlowCrypt/flowcrypt-android/pull/1420

**Comment by DenBond7** [comment]
I can reproduce that. But I'm not sure that it was caused by #1420.
