### ISSUE TITLE
support saving drafts during compose or reply

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#1479]
When I type my email or response, drafts should get continuously uploaded to Gmail API (can skip IMAP for now).

 - [x] once every 5 seconds, check if the content of the message, subject or recipients have changed compared to previous second
 - [x] if it changed, and initiate an upload/update of draft in the background
 - [x] (If it's the first upload of this draft, receive back the draft ID, and then use that draft id in subsequent updates of the draft)
 - [x] if it didn't change, skip updating draft and wait until next run
 - [x] cancel this timer when user leaves the screen through any means (back button or menu -> other place), 
 - [x] but make sure to run this method one last time in the background while the screen is being switched, to ensure the last changes are saved
 - [x] do not include attachments in these drafts (Gmail API is not good, would need to re-upload them each time)
 - [x] when user navigates to a draft and taps it, allow the user to send or modify+send the draft, similar to what Gmail app does
 - [x] when pass phrase is missing to save draft, request it on the compose screen unobtrusively, similarly what browser extension does in this situation, or what iOS does for password-messages
 - [x] draft should not be saved if I only just rendered compose or reply. I have to actually input something first (any of the fields)
 - [ ] if there is already a draft existing in a thread, clicking reply should take me to that draft to continue editing, instead of a new message
 - [ ] mark drafts in a conversation with red `Draft` label
 - [x] in list of drafts (draft label folder) render recipients of the draft instead of sender (which would always be me) similar to sent folder

Should probably be split into more than one PR, some core functionality first, then the rest in a follow-up.

**Comment by martgil** [comment]
A new user's suggestion to save a draft email:

https://mail.google.com/mail/u/2/#inbox/FMfcgzGpGnMjPTjqBNCGBnTwDSLrpsvZ

**Comment by tomholub** [comment]
One of our enterprise customers expressed interest in this. @DenBond7 let's add it to the current milestone?

The implementation doesn't have to be word-for-word as I've described it. Maybe you have some other idea. If so, please mention it here.

**Comment by DenBond7** [comment]
> Or if you want to do a release one, then this would be the first issue in the milestone after that.

We can include it in the current milestone.

> The implementation doesn't have to be word-for-word as I've described it. Maybe you have some other idea. If so, please clarify here.

Got it. It's a quite difficult task. Maybe I will change something during implementation.

> or what iOS does for password-messages

How can I test the last iOS version?

**Comment by tomholub** [comment]
you can get it from testflight on flowcrypt.com/download

**Comment by DenBond7** [comment]
For me https://developers.google.com/gmail/api/guides/drafts

**Comment by DenBond7** [comment]
- [ ] Store draft encrypted by Android KeyStore(the same as we do it for saving loaded messages)
- [ ] After leaving the compose screen update the local copy of a downloaded draft
- [ ] Need to think about a situation when a user modified some draft, and left the compose screen, but the updated draft was not uploaded to a remote server(maybe an internet issue).

**Comment by sosnovsky** [comment]
@tomholub @DenBond7 hi guys, I think we shouldn't implement `if there is already a draft existing in a thread, clicking reply should take me to that draft to continue editing, instead of a new message` - I checked other mail apps and they all allow to create multiple drafts for 1 thread.
And it looks useful, as there are possible cases when users will need several drafts before sending message.

What do you think?

**Comment by tomholub** [comment]
Sure, I think it makes sense to follow what other email apps, especially Gmail, does.

In either case it should still be possible for me to pick a particular draft from the conversation & continue editing it & send it.

**Comment by DenBond7** [comment]
For history

Gmail has a stable `draftId` for some draft, but different `msgId` for every new change.
For example:

1. We create a new draft - at this point, Gmail API creates a new `draftId`. For example `r777`. This draft - it's a message with `id`= `1212`
2. After that we modify a draft with `draftId` == `r777`. After that Gmail API deletes the message with `id`= `1212` and creates a new one with `id`= `4343`. I've checked. After modification Gmail API returns an error when I try to get a message with `id`= `1212`

I describe this because here can be the following situation: 

1. we move to DRAFT folder -> 
2. get the base info about messages -> 
3. show messages list with one message where `id`= `1212` -> 
4. via another email client (for example Gmail WEB) change the draft. At this point Gmail API deletes message with `id`= `1212` and creates a new one with `id`= `4343` -> 
5. came back to Android, DON'T refresh the messages list -> 
6. click on the draft  with `id`= `1212` -> 
7. show the message details screen and try to load the whole message by `id`= `1212`->
8. we will receive an error == `"Requested entity was not found."`

@sosnovsky Do you handle the such a situation?

P.S. By the way, I think creating a new message and deleting the old one for every draft iteration was developed to support IMAP behavior. Because IMAP works that way :)

**Comment by tomholub** [comment]
btw we don't need to support drafts for IMAP

**Comment by sosnovsky** [comment]
@DenBond7 currently iOS doesn't handle this situation, but I think for fixing it we can just refresh drafts list each time when app is opened from background. Then we'll have the latest draft ids

**Comment by DenBond7** [comment]
> when pass phrase is missing to save draft, request it on the compose screen unobtrusively, similarly what browser extension does in this situation, or what iOS does for password-messages

I would like to discuss it. Do we have to sign a draft? Or maybe even another question - what logic we would use for sending drafts?

I see two different approaches:

1. We are going to use [Method: users.drafts.send](https://developers.google.com/gmail/api/reference/rest/v1/users.drafts/send) to send drafts. First of all, need to say that Gmail UI doesn't allow sending a draft directly. A user has to open a draft and click on `Send` button. I don't sure what exactly API Gmail UI uses ([users.drafts.send](https://developers.google.com/gmail/api/reference/rest/v1/users.drafts/send) or [users.messages.send](https://developers.google.com/gmail/api/reference/rest/v1/users.messages/send)). For [Method: users.drafts.send](https://developers.google.com/gmail/api/reference/rest/v1/users.drafts/send) we have to prepare a final version of a message. It means we should know a passphrase and `pubkeys` for all recipients. To be honest, I don't like this idea. It requires too many things and it's not flexible when we are talking about encrypted messages.
2. We are going to use a regular sending method. It means we will use a draft just as a temp container for a message. As IMAP does it. I see the following scenario: a user opens a draft and sees the draft details, then clicks on `Edit` button, then moves to the compose a message screen where he can edit the draft or send it. It will look like this one

![draft](https://user-images.githubusercontent.com/2863246/192801326-cdb039b9-5e2d-4c1e-92a3-26b5c0117644.gif)

In this case, MAYBE it will be enough(or NOT?) to have just public keys to make an encrypted version of a message. Opening such messages already works.

@tomholub What do you think?

**Comment by tomholub** [comment]
I guess you could go with second option, and don't sign the draft when composing. Then always sign when actually sending the draft, and ask for pass phrase at that point.

ping @sosnovsky may have input

**Comment by DenBond7** [comment]
> ping @sosnovsky may have input

@sosnovsky Roma, what do you think? Can the second option be used by your realization?

**Comment by sosnovsky** [comment]
@DenBond7 I like the idea of signing message only when sending it, so users won't need to enter passphrase for storing drafts. It should be possible to update my current implementation for such approach.

For sending drafts I'm currently using [users.messages.send](https://developers.google.com/gmail/api/reference/rest/v1/users.messages/send) api method. I think it works the same as [users.drafts.send](https://developers.google.com/gmail/api/reference/rest/v1/users.drafts/send), but `drafts` endpoint also requires `draftId` param.

> I see the following scenario: a user opens a draft and sees the draft details, then clicks on Edit button, then moves to the compose a message screen where he can edit the draft or send it. It will look like this one

I implemented this one like it works in Gmail app:
- `Drafts` folder lists all drafts + threads with drafts
- if user taps on a single draft - app shows `compose message` screen, where user can edit and send draft message
- if user taps thread with draft then app opens thread details screen with all thread messages. when user taps on draft message in thread view, then app opens `compose message` screen

![Simulator Screen Recording - iPhone 13 - 2022-09-28 at 21 33 58](https://user-images.githubusercontent.com/1062093/192862021-52cd53e6-bbde-44c1-88b5-ca3a598aa0d4.gif)

**Comment by DenBond7** [comment]
Perfect. So we can just encrypt a message with pubkeys. 

@tomholub One more question. What we should use: just sender's pub keys or sender+recipients pub keys? As for me, I would prefer to use just the sender's pub keys. It will be safer.

> you can get it from testflight on flowcrypt.com/download

The last version doesn't have draft support. Please ping me when it will be available. I'd like to test compatibility.

**Comment by tomholub** [comment]
I would use sender + receipient because I think there is some chance somebody will navigate to the encrypted draft, on mobile device, and tap send from there.

**Comment by sosnovsky** [comment]
Browser extension also adds `[flowcrypt:link:draft_compose:DRAFT_ID]` before draft's encrypted message.
It seems we need to use it in mobile apps too, so users will be able to edit drafts from apps in the browser.

**Comment by DenBond7** [comment]
@sosnovsky Please look at here https://github.com/FlowCrypt/flowcrypt-browser/issues/4691

**Comment by sosnovsky** [comment]
> @sosnovsky Please look at here [FlowCrypt/flowcrypt-browser#4691](https://github.com/FlowCrypt/flowcrypt-browser/issues/4691)

Thanks!

**Comment by DenBond7** [comment]
Finally, I did it. I've added base 'drafts' functionality for Gmail API. I'd like to add some comments.

1. I've checked checkboxes that were completed as described.
2. these requirements can't be added for now. We don't use `threads` yet on Android

> if there is already a draft existing in a thread, clicking reply should take me to that draft to continue editing, instead of a new message

> mark drafts in a conversation with red Draft label
3. 
> Should probably be split into more than one PR,

unfortunately, it will be a single PR due to too many architecture changes that can't be split. 
4. Next week I will work on testing the current base functionality and fixing tests. After that, we will be ready for a new release.
5. About IMAP :). Basically, I've added changes that cover around 75% of the 'drafts' functionality for IMAP. So, the next step will be much faster.

**Comment by tomholub** [comment]
I don't think we need IMAP drafts for a very long time. Can re-consider end of 2023.

**Comment by DenBond7** [comment]
> I don't think we need IMAP drafts for a very long time. Can re-consider end of 2023.

Got it. IMAP and Gmail API - that's just a protocol for how to communicate with a server. In most cases, in the app, we have the same logic for both of them (UI and so on). That's why around 75% are already covered.
