### ISSUE TITLE
draft ui issue

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-android#1505]
Description:
Draft label contains "/" character produces  a new separate label when displayed on the android version. This first created draft label tab doesn't contain any emails, only the second draft label only. Just a minor UI issue I just noticed.

<img width="666" alt="draft tabs issue" src="https://user-images.githubusercontent.com/46025304/137073544-f063d586-f265-4081-b7ca-9a2e4d2c8992.png">

**Comment by DenBond7** [comment]
![image](https://github.com/FlowCrypt/flowcrypt-android/assets/2863246/0df5d7b0-9eb0-44cb-bc4f-c2cad1d3474b)

It looks like it is already fixed. I'm closing it.
