### ISSUE TITLE
Correct message readable from the browser extension but not on android

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-android#1531]
Description:

A number of users are having some problem reading an encrypted message from the android app. To be specific, these messages seem to be correctly formatted and can be decrypted through the browser extension but has some problem when the android app decrypt them.

The error looks exactly like this. But the main difference is that I have intentionally manipulated the message to replicate it. But I don't think I have many ideas for it as the message was ok and readable from them through the browser extension.
![image](https://user-images.githubusercontent.com/46025304/139641714-b2b93128-69c3-4aa7-8e67-12332ad0e0ad.png)

I think it doesn't make sense to diff these two raw messages (browser extension and android) since the origin of the message is only one (Gmail).

The respondents also stated that they only have experienced these in the recent version of the app.

Reference:
https://mail.google.com/mail/u/2/#inbox/FMfcgzGlkZDqTgCPCgQFJqZQdlqKqcXz
https://mail.google.com/mail/u/2/#archive/FMfcgzGlkjVqdSVlTslCmmDlxntWDkss
https://mail.google.com/mail/u/2/#inbox/FMfcgzGlkjjMzLKnFCMDkBGXrkJkMnNx
https://mail.google.com/mail/u/2/#inbox/FMfcgzGlkrzBJSkhMqfRVHgCfkMBgNWP
https://mail.google.com/mail/u/2/#inbox/FMfcgzGlksCSxzcKPmhGBrvdGvFtCdfh
https://mail.google.com/mail/u/2/#inbox/FMfcgzGlksLXsrRDdWxQjzZLZjvZRQzk
https://mail.google.com/mail/u/2/#inbox/FMfcgzGllCcNtnHFlQdSCFCrTPhgQZlb
https://mail.google.com/mail/u/2/#inbox/FMfcgzGllClRQcdFMmMCnCHvdwBcWQKh

**Comment by martgil** [comment]
I should also add that the language wherein one of the encrypted messages was written was in french. Maybe the message contained a special character that can't be decoded from the app?

**Comment by DenBond7** [comment]
Interesting... To investigate that it would be nice to have a workable version for the browser extension and not workable for the Android app.(without manipulation on our side, just as-is from a user.)

**Comment by martgil** [comment]
I truly agree with you. One of the respondents has shared the following software and version from which they experience the issue. 

> My Android FlowCrypt is 1.2.4 and the Brave extension is 8.1.4 (chromium-based). 

Let me know if you need anything else. I will help you to investigate this as possible as I can.

**Comment by DenBond7** [comment]
> Let me know if you need anything else. 

I need to have a message that can not be recognized by the Android app. Could you ask the user to share such a message(if it doesn't contain sensitive info) or generate a new one for den@flowcrypt.com? Then I will analyze the raw MIME message, check how it works in the browser version and so on.

**Comment by martgil** [comment]
Okay, sir! I have asked the user if he can share the mime message with us. I will forward them to you right away whenever I get have them. Thank you!

**Comment by martgil** [comment]
Reference: https://mail.google.com/mail/u/2/#inbox/FMfcgzGlkjccFRNjWwKKkjMpXgdCzDNx

**Comment by DenBond7** [comment]
@martgil Could you ask the user maybe he knows how such a message was created? What software was used?

**Comment by martgil** [comment]
The user having such an error usually came from kraken.com device approval (not on every email).
![image](https://user-images.githubusercontent.com/46025304/140716223-b17b5797-b437-4302-a73a-f8ea7468c5a9.png)

Email subject from kraken.com looks exactly the following: 
"Kraken Security - New Device Approval Required (11-05-21 00:10:47 -0700)"

But I think it is one of the following.

- Another issue occurs when the user views the send email from their account.

**Comment by martgil** [comment]
Hello @DenBond7, 

Yes, It seems like. I have built and run the latest version from the master branch into my android emulator and I am now able to read the encrypted message from kraken.io completely. Thanks so much!

**Comment by DenBond7** [comment]
In that case, I'm closing it.
