### ISSUE TITLE
checking of pass phrase strength when importing from EKM

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#1533]
I got feedback from customer:

> Passphrase on Mobile has no checks on weakness

when importing on EKM, do we check pass phrase strenght? If we currently don't, then we should (same requirement as when creating a passphrase for a new key)

**Comment by DenBond7** [comment]
Hmm... it's a little strange. We check pass phrase strength

![image](https://user-images.githubusercontent.com/2863246/140062208-9e092307-6ac4-4424-a071-1ab06741f028.png)

> I got feedback from customer:
> 
> Passphrase on Mobile has no checks on weakness

Could you ask a user to provide more details? screenshots?

**Comment by tomholub** [comment]
If you click set pass phrase, and it's weak, will it let you? Or stop you?

I asked them to provide more details. Just wanted to check internally as well.

**Comment by DenBond7** [comment]
let me show you how it works

![ezgif com-gif-maker](https://user-images.githubusercontent.com/2863246/140063237-8a219822-b2d7-41ed-83e6-f7bd2d08ac4f.gif)

**Comment by tomholub** [comment]
This is as expected. Let's wait for their clarification. Thanks!
