### ISSUE TITLE
include attachments in forwarded message - detached

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#1538]
customer request

**Comment by DenBond7** [comment]
@tomholub  I've added support for forwarding detached attachments. Detached should be read as a part of the MIME message(MIME part with `Content-Disposition: attachment;`). But we still do not support forwarding inline encrypted attachments. It will be for a separate issue and it will not be so easy as the current issue :(

**Comment by tomholub** [comment]
The terminology is a bit confusing, as pgp/inline normally comes with detached signatures (which is what you support) whereas pgp/mime has attachment encoded in it. It could be inline images but generally they are not. Let me rename the issues.
