### ISSUE TITLE
HTML emails - scrollable / cropped

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#154]
See "android" folder on flowcrypt.compatibility, email `FlowCrypt, your new Motorola Moto G(4) Plus doesn't have the latest Google apps`

It will appear cropped when I open the email
![screenshot_20171116-224522](https://user-images.githubusercontent.com/6306961/32930049-0e51b50c-cb11-11e7-8335-c69e7056b346.png)

I can manually zoom inside the box to make it all visible
![screenshot_20171116-224532](https://user-images.githubusercontent.com/6306961/32930050-0ecb277a-cb11-11e7-85ca-0ca3e65757fa.png)

Is it possible to scale it automatically? In Gmail app, it opens like this (looks good)

![screenshot_20171116-230137](https://user-images.githubusercontent.com/6306961/32930124-8719a558-cb11-11e7-9aeb-db40fc97d161.png)

**Comment by DenBond7** [comment]
Can you send me that message?

**Comment by tomholub** [comment]
You'll find it in "android" folder on flowcrypt.compatibility@gmail.com

The subject to look for is **FlowCrypt, your new Motorola Moto G(4) Plus doesn't have the latest Google apps**

**Comment by DenBond7** [comment]
For me: https://habrahabr.ru/sandbox/89063/
https://www.w3schools.com/html/html_responsive.asp

**Comment by tomholub** [comment]
Worked perfectly! :)
