### ISSUE TITLE
multiple pubkeys per email - Importing pub keys manually

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#1542]
> Importing pub keys
> Here we can have two cases:
> 1) key with a single user id: for example key for A@flowcrypt.test It's a simple case.
> 
> Here we have the same behavior as before.

Not the same as before. Before, you were always the public key. Now, need to compare it to existing public keys of that one recipient by primary fingerprint.
 - if the key is not present in the list of keys of that one recipient, add it to the list
 - if already present, then compare by lastModified. If the offered key is newer, then replace the existing key by the newer key. If older, then do nothing. 

> 2) key with a few user ids: for example key for A@flowcrypt.test, B@flowcrypt.test
> 
> Here we have 2 theoretical recipients: `A@flowcrypt.test`, `B@flowcrypt.test`. Should I add 2 entries to the local database
> 
> ```
> 1| FINGERPRINT| A@flowcrypt.test | KEY
> 2| FINGERPRINT| B@flowcrypt.test | KEY
>```

I suppose here we're talking about manual import of potentially many public keys? Where user is just importing keys without further interaction, and not indicating for which user they are importing the keys. Let's do the safer thing - only import for primary user id. So that would be one entry (subject to the same procedure with list handling as above). We could reconsider it in the future.

_Originally posted by @DenBond7 in https://github.com/FlowCrypt/flowcrypt-android/issues/1188#issuecomment-963205439_

**Comment by tomholub** [comment]
duplicate of #1542

**Comment by DenBond7** [comment]
I'm reopening it. It will relate to manual import

**Comment by tomholub** [comment]
In the situation above, I've described manual import in the settings. 

I suppose manual import when we receive pubkey over a message could work the same - go by primary email. On browser extension we currently show an email address input where the primary user id is prefilled. Does Android do the same? Or it doesn't give the user any choice who to import for?

**Comment by DenBond7** [comment]
> On browser extension we currently show an email address input where the primary user id is prefilled. Does Android do the same? Or it doesn't give the user any choice who to import for?

Could you attach a screenshot? To be sure we are talking about the same things

**Comment by tomholub** [comment]
here the text input that contains email address:

<img width="914" alt="image" src="https://user-images.githubusercontent.com/6306961/140791530-01895789-6634-4aa1-9c9a-0a8481f35c61.png">

**Comment by tomholub** [comment]
Android doesn't show that input field, just saw it. That's fine. Can go by primary email, as long as that one is visible.
