### ISSUE TITLE
add warning when manually importing public keys

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#1544]
A simpler version of this issue: leave everything as is and always add `Manually importing Public Keys received over email can be dangerous. Contact the sender to verify that the fingerprint matches.` (orange color text, plus change the button to orange)

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-android/issues/1543#issuecomment-963443790_

Add this warning to both importing received public keys and importing public keys in settings.

**Comment by tomholub** [comment]
This PR includes more details to cover all situations https://github.com/FlowCrypt/flowcrypt-browser/pull/4110

**Comment by tomholub** [comment]
@DenBond7 will you be able to look at this today?

**Comment by DenBond7** [comment]
No prob, I'm switching to this one.

**Comment by tomholub** [comment]
Do you have any other work currently half-finished? If so, which one?

**Comment by tomholub** [comment]
Ah, I see the project part :-) got it. Yes - better switch to this.

**Comment by DenBond7** [comment]
![image](https://user-images.githubusercontent.com/2863246/144843805-bb9eaeed-635f-431e-ab1e-23eef314c74d.png)

**Comment by tomholub** [comment]
(maybe) Ivan could later help with the Base64, since it's not Android-specific.

**Comment by DenBond7** [comment]
> (maybe) Ivan could later help with the Base64, since it's not Android-specific.

Not sure. It relates to JavaMail and Android logic. I've found how to prevent that but we need to decide if it fits our needs. Anyway, we can move it for later.

**Comment by tomholub** [comment]
ok

**Comment by DenBond7** [comment]
![image](https://user-images.githubusercontent.com/2863246/144847634-fa5234c4-200b-4b73-b4e6-c85b2517fa66.png)

**Comment by tomholub** [comment]
very good, same for the bulk imports 👍

**Comment by DenBond7** [comment]
All cases. Just to be sure that I show a warning when it is needed. @tomholub is it correct?
1. pub key can't be imported/updated
![image](https://user-images.githubusercontent.com/2863246/144848585-75e7c2a2-2ed0-49ad-92f6-5c7b12591ef4.png)
2. pub key can be imported/updated
![image](https://user-images.githubusercontent.com/2863246/144848641-9bbcdac3-c2a8-49eb-a5a9-e6cdb7b57f8c.png)
3. pub key is already imported
![image](https://user-images.githubusercontent.com/2863246/144848767-6013109e-ba24-4dcd-8acb-fc0c4da6308f.png)

**Comment by tomholub** [comment]
that looks good

**Comment by DenBond7** [comment]
> same for the bulk imports

@tomholub Do you mean here? 

![image](https://user-images.githubusercontent.com/2863246/144859945-edf3c339-f67b-48b4-a8f9-a3576fb42189.png)

**Comment by tomholub** [comment]
yup

**Comment by tomholub** [comment]
and orange buttons

**Comment by DenBond7** [comment]
![image](https://user-images.githubusercontent.com/2863246/144861503-15cfa0ec-1a2a-4e09-8726-e134b6135618.png)

**Comment by tomholub** [comment]
yes
