### ISSUE TITLE
Send password-protected messages through web portal when no public keys available

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#1545]
Similar to what browser extension does. iOS issue https://github.com/FlowCrypt/flowcrypt-ios/issues/955

 - [x] #1614
 - [x] #1615
 - [x] #1620
 - [x] #1622
 - [x] #1618
 - [x] #1621
 - [x] #1667

**Comment by DenBond7** [comment]
@tomholub While I'm working on other issues please add more details here when you will have some free time.

**Comment by DenBond7** [comment]
@tomholub Any news here :) ?

**Comment by tomholub** [comment]
- [ ] refresh id token periodically, same as access token
 - [ ] UI for password encrypted message functionality 
 - [ ] add password policy org rule for message passwords
 - [ ] disable password-protected messages if FES is not used
 - [ ] send password-protected message through FES and update email format

**Comment by DenBond7** [comment]
it would be nice to see the whole picture. @tomholub Could you show how it looks in the browser? or how I can test in in the browser

**Comment by tomholub** [comment]
To test in browser, try to send a message from flowcrypt.com account to anyone who there is no pubkey for (doesn't use FlowCrypt). Then open the link from the recipient account.
