### ISSUE TITLE
BASE64Decoder: error in encoded stream: early EOF

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#1553]
Not all Base64 streams strictly observe padding, we should probably be more tolerant of this.

> P.S : for information, I’ve also found 2 other error messages "error in encoded stream" (see screenshots) which remain displayed like this. Those are specific to email notification of a meeting invitation (so not encrypted), so it is clearly not a priority.

![image](https://user-images.githubusercontent.com/6306961/141113515-24aa3a1d-d93d-4f54-a78c-aebb0970ae5a.png)

![image](https://user-images.githubusercontent.com/6306961/141113601-4bb832f6-11b6-4c2c-aeb6-20cfbe318f78.png)

**Comment by DenBond7** [comment]
https://community.oracle.com/tech/developers/discussion/4080143/javamail-decodingexception-base64decoder

**Comment by DenBond7** [comment]
before fix 

![image](https://user-images.githubusercontent.com/2863246/147408715-445521b2-453a-4561-9da1-64c27eb747fe.png)

after fix

![image](https://user-images.githubusercontent.com/2863246/147408745-fe5f014c-b61a-42c2-b114-2e1701569139.png)
