### ISSUE TITLE
[Support] unknown PGP public key algorithm encountered

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-android#1558]
Description:
One of the users experiences this when opening an encrypted message. 
The undecryptable message contains an error that says: `unknown PGP public key algorithm encountered`

![image](https://user-images.githubusercontent.com/46025304/141887042-416d5266-f181-4954-8081-504158265c81.png)

Please let me know if there is anything I could add up to with this report. I will provide it as soon as possible. 
Thank you!

Reference: https://mail.google.com/mail/u/2/#inbox/FMfcgzGlksFmVxmldRJGJjLFBRWGJhJH

**Comment by DenBond7** [comment]
@martgil Hi, Mart. Sorry for the delayed reply. Could you ask the user to update the app to the latest version and try to open that message? If he will receive the same result I will need more details. it looks like a compatibility issue.

**Comment by martgil** [comment]
Hello sir Den, sure sir! I will ask them now and get back to you ASAP. Thank you!

**Comment by martgil** [comment]
The user has not responded to the last few emails. I have sent another email to confirm if the problem still persists today. If there is no response, we can consider closing this one and reopening the Github issue when the problem resurfaces.
