### ISSUE TITLE
add an ability to see public key details(all existing keys for a recipient)

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#1566]
Also need to add an ability to see the public key details. Before we used to show the contact details that have only one key. But now we need to change that screen

Before
`Contacts list ->  public key info`

now
`Recipients list -> Recipients details with pub key list -> public key info`

_Originally posted by @DenBond7 in https://github.com/FlowCrypt/flowcrypt-android/issues/1188#issuecomment-972874602_

**Comment by DenBond7** [comment]
@tomholub What do you think?
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/2863246/142641715-67e085b6-401b-41c6-b17b-6b0628c823bf.gif)

**Comment by tomholub** [comment]
perfect
