### ISSUE TITLE
app crash by importing a private key without an email address

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-android#1570]
Description:
I have found an issue with the latest version of FlowCrypt app 1.2.4 that crashes the `Keys` view after importing a private key that doesn't contain an email.

Tested from an emulator and a real device.

Steps to reproduce:
[crashed.asc.txt](https://github.com/FlowCrypt/flowcrypt-android/files/7579517/crashed.asc.txt)
1. Download the crashed.asc.txt file (optional to rename if the app happens to unrecognized the file`
2. Import the private key with the passphrase: `passphrase`
3. The app will crash after the key is imported successfully.
4. Open the FlowCrypt app once again and go to Keys and the app will crash once again.

Impact:
A user will no longer be able to access the Keys without even uninstalling the app.

**Comment by DenBond7** [comment]
#1523 will resolve this issue
