### ISSUE TITLE
Private Key not found for user's emails

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-android#1573]
Description:
A user cannot send an email as the following error occurs for the outgoing message. 

Public key: https://www.hammyhavoc.com/wp-content/uploads/2021/10/Hammy-Havoc_0xF2300FF6_public.asc

![image](https://user-images.githubusercontent.com/46025304/143200743-fde93ac3-387c-4592-8460-60d00724221a.png)

Reference: https://mail.google.com/mail/u/2/#inbox/FMfcgzGlksLXbBmSMlrMBPGNPVKcxPlX

Regards,
Mart Gil

**Comment by DenBond7** [comment]
@martgil Do we receive any reports about this one? Maybe we can close it.

**Comment by martgil** [comment]
We haven't received any further reports about it so far. Yes, maybe we can close it now. Thank you, sir!
