### ISSUE TITLE
progress bar when loading inbox

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#160]
Fairly frequently, I'm still experiencing the inbox loading for a very long time, or not loading at all (will kill app and then it will load). But it's hard to debug because it usually happens when I'm not around a computer.

I suggest to add a status bar on the bottom part of the screen. That will help us debug it and see where it's getting stuck. This was happening to users as well, so I can ask them to take a screen shot when it gets stuck.

It will be just a 4px high rectangle - use primary green color - all the way at the bottom of the screen and all the way to the left. When at 100%, it will be 100% wide, when at 50%, it will be 50% wide, etc. It will disappear when the inbox screen is ready to show.

Above the rectangle on the left, it should say how many % are done and which step it's doing now. This text will be aligned to the left, with the padding on the left having the same size as padding between text and progress bar. Use one of the light gray colors in the palette that is still readable. Eg

> 5% Connecting to mail server
> 10% Logging in
> 15% Getting list of emails
> .. etc

The percentages are just rough estimates, eg if you have 7 steps to go through, you can step around 15% each step, or as you see fit.

**Comment by tomholub** [comment]
This is for the inbox loading screen

**Comment by sebastianbauer** [comment]
Having this problem after deleting a mail. It seems inbox doesn't load at all in this case.

**Comment by DenBond7** [comment]
@sebastianbauer Thanks for your response. Could I know some details?

1. What email provider do you use?
1. What type of the connection do you use? (WiFi or GSM)

> Having this problem after deleting a mail.
3. Is it happen always or only sometimes?

**Comment by sebastianbauer** [comment]
@DenBond7 Of course.

1. GMail
1. It was with WiFi
1. It tested some and all had the same problem. Even after having the app in the background for some hours, and switching back, it was still "loading"

**Comment by tomholub** [comment]
When the inbox gets stuck on me, I will kill the app and it will usually work. Typically, this happens when I haven't used the app for a while and it stayed on in the background. 

It never happened to me when deleting mail.

The progress bar should help us identify where exactly it's getting stuck.

**Comment by tomholub** [comment]
My inbox loading screen just got stuck (minutes) at 10%. That means it has something to do with queue processing. Can you add more granular progress to that step? Or some other way to debug?

**Comment by tomholub** [comment]
After app killed, it loaded as usual in about 5s - still the same symptoms

**Comment by tomholub** [comment]
I will be playing with the app over the weekend to see if this issue re-surfaces
