### ISSUE TITLE
public key email response should only allow one public key attached + improvements

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#161]
- [x] 1) The selection should be a radio button - only one public key should be in the response.

- [x] 2) If there is only one key, the screen should be skipped (not sure if this is done, not tested).

- [x] 3) The process should be more automated. Most of the time, the app should figure out on its own which key to send (we have to talk about this and figure out the rules how to choose the right key) and the screen would be skipped as well.

- [ ] 4) When we ask user to select key to send, we have to give him more info. Currently it's showing just longids and I don't know which key is which. (I will think about this more)

**Comment by tomholub** [comment]
5) this type of message should not allow me to add more attachments

**Comment by tomholub** [comment]
![screenshot_20171204-123837 1](https://user-images.githubusercontent.com/6306961/33569958-4e121c00-d966-11e7-9900-668ea29bfb86.png)

**Comment by tomholub** [comment]
Here I was able to add extra attachment. You can just remove the add attachment icon.

![screenshot_20171204-124059](https://user-images.githubusercontent.com/6306961/33570017-7c3fff0c-d966-11e7-9fda-ab2497f59096.png)

**Comment by DenBond7** [comment]
> If there is only one key, the screen should be skipped (not sure if this is done, not tested).

When such case happened, I am showing the next dialog

![screenshot_2017-12-06-11-43-11-280_com flowcrypt email debug](https://user-images.githubusercontent.com/2863246/33655093-d5c3210c-da7a-11e7-92b5-bbb49110bde3.png)

I can't skip this step. I need some time to generate a public key using Js tools (few seconds). If I will skip this step the app will have some freeze.

**Comment by DenBond7** [comment]
> The process should be more automated. Most of the time, the app should figure out on its own which key to send (we have to talk about this and figure out the rules how to choose the right key) and the screen would be skipped as well.

Currently, the app selects the right key using matches by the email.

**Comment by tomholub** [comment]
> I need some time to generate a public key using Js tools (few seconds). If I will skip this step the app will have some freeze.

In the chrome extension, I will store public and private key in the same row (the public key in a separate column). You shouldn't need to re-caculate it every time, just the first time you import the private key. We should do the same on Android.

**Comment by DenBond7** [comment]
> 4) When we ask user to select key to send, we have to give him more info. Currently it's showing just longids and I don't know which key is which. (I will think about this more)

Do you have some ideas? Maybe can I show an email name instead of a longid?

![image](https://user-images.githubusercontent.com/2863246/34098795-3b584af0-e3e6-11e7-87e4-fd5a1ead45c5.png)


It remains only to make this subtask

**Comment by tomholub** [comment]
I was thinking
- email 
- keywords
- day created
I think that would be good enough for now
