### ISSUE TITLE
refresh id token periodically, same as access token

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#1614]
part of #1545 

description here: https://github.com/FlowCrypt/flowcrypt-ios/issues/1091

iOS implementation: https://github.com/FlowCrypt/flowcrypt-ios/pull/1225/files

browser extension implementation (simplified): 

![image](https://user-images.githubusercontent.com/6306961/146436763-d78b70d3-9cdc-47ea-9fba-17bfeae67581.png)

more context (browser extension) https://github.com/FlowCrypt/flowcrypt-browser/issues/4194#issuecomment-994845906

**Comment by DenBond7** [comment]
https://stackoverflow.com/questions/38737021/how-to-refresh-id-token-after-it-expires-when-integrating-google-sign-in-on-andr

**Comment by DenBond7** [comment]
To do that we can use Google's library that uses `GoogleSignInClient#silentSignIn()` to fetch the latest version of SignIn data(that contains `idToken`) without a user action(silently). If `silentSignIn()` will fail we can ask a user to re-authenticate.

That what I said means we don't need to find out how to refresh `idToken` manually. The library does it for us. I think we can close it.

**Comment by tomholub** [comment]
Should also save the id token in memory each time we renew it. Else you'll have to get a fresh new token each time, I'm not sure if that's good.

Unless google library caches it for you.

**Comment by DenBond7** [comment]
> Unless google library caches it for you.

Yes, it caches that data

**Comment by tomholub** [comment]
ok to close in that case

**Comment by DenBond7** [comment]
After adding the last changes I started to test the whole process. It seems that fetching the last `idToken` on Android has interesting behavior. The Android library can return expired `idToken` but after a few attempts the library returns an updated `idToken`. I have to reinvestigate this issue.
