### ISSUE TITLE
limit accepted message passwords based on password policy

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#1618]
part of #1545

**Comment by tomholub** [comment]
We'll need a method that will validate user message passwords to make sure it complies with password policy. I'll share the policy separately (not public).

**Comment by DenBond7** [comment]
@tomholub Any news here?

**Comment by tomholub** [comment]
Sorry, it's stuck on me.

**Comment by DenBond7** [comment]
Don't worry. I'm going to work on #1620

**Comment by tomholub** [comment]
when using FES to send the password protected message, use the following password rules:
-    minimum one uppercase
-    minimum one lowercase
-    minimum one number
-    minimum one non-alphanumeric character
-    minimum length 8 characters

**Comment by tomholub** [comment]
See https://github.com/FlowCrypt/flowcrypt-browser/pull/4252 for screenshots and implementation. Password checking as follows, for consistency:

```ts
  public isMessagePasswordStrong = (pwd: string, isFesUsed: boolean): boolean => {
    const isLengthValid = pwd.length >= 8;
    if (isFesUsed) { // enterprise FES - use common corporate password rules
      const isContentValid = /[0-9]/.test(pwd) && /[A-Z]/.test(pwd) && /[a-z]/.test(pwd) && /[^A-Za-z0-9]/.test(pwd);
      if (!isContentValid || !isLengthValid) {
        return false;
      }
    } else { // consumers - just 8 chars requirement
      if (!isLengthValid) {
        return false;
      }
    }
    return true;
  };
```

The `consumer` case is not supported on Android yet. But eventually it will be. It will be using a shared-tenant FES instance like `webportal.flowcrypt.com` or similar.

**Comment by DenBond7** [comment]
@tomholub Can I start to work on it?

**Comment by tomholub** [comment]
yup :+1:

**Comment by tomholub** [comment]
Please also add these two checks. You only need to check that the password doesn't match any "currently known" pass phrase - the stored ones, or whichever are currently in memory.

```ts
      if (await this.view.storageModule.isPwdMatchingPassphrase(pwd)) {
        throw new ComposerUserError('Please do not use your private key pass phrase as a password for this message.\n\n' +
          'You should come up with some other unique password that you can share with recipient.');
      }
      if (subject.toLowerCase().includes(pwd.toLowerCase())) {
        throw new ComposerUserError(`Please do not include the password in the email subject. ` +
          `Sharing password over email undermines password based encryption.\n\n` +
          `You can ask the recipient to also install FlowCrypt, messages between FlowCrypt users don't need a password.`);
      }
```

**Comment by DenBond7** [comment]
@tomholub  Please look at the example. What do you think?

https://user-images.githubusercontent.com/2863246/150544533-6d61fdd5-37c0-43ee-ac3f-53c0d5892159.mp4

**Comment by tomholub** [comment]
It wasn't necessary to make it so detailed one by one. But it's good.

The only thing I worry is that the checkboxes look like user could interact with them. Someone may maybe try to tap them. if you could remove the frame from the checkboxes, so either there is nothing or a standalone checkmark, that would be a bit better.

Otherwise good.

**Comment by DenBond7** [comment]
> The only thing I worry is that the checkboxes look like user could interact with them. Someone may maybe try to tap them. if you could remove the frame from the checkboxes, so either there is nothing or a standalone checkmark, that would be a bit better.

Of course. will do.

**Comment by DenBond7** [comment]
>  so either there is nothing or a standalone checkmark, that would be a bit better.

@tomholub Looks better?
![image](https://user-images.githubusercontent.com/2863246/150638734-7e1aac7a-9e37-4228-bff6-435d39566676.png)

![image](https://user-images.githubusercontent.com/2863246/150638744-2fb2bf58-66f4-4d22-bdb0-530d20f98e01.png)

![image](https://user-images.githubusercontent.com/2863246/150638756-a5f63bb2-e766-4261-90f9-1ab595ac6dae.png)

**Comment by tomholub** [comment]
Sure. Less pretty but also less confusing :-)

Two things I noticed:
 - The bottom red text can be gray like the rest of the text.
 - Also in FES situations it should say `They will have access to this message for 180 days.`

**Comment by DenBond7** [comment]
![image](https://user-images.githubusercontent.com/2863246/150639392-153c5670-c005-4a28-ac9d-09cbd7490f44.png)

**Comment by tomholub** [comment]
yup

**Comment by IvanPizhenko** [comment]
put "min 8 characters" on top of the list

**Comment by DenBond7** [comment]
tests

- [ ] hide "Tap to protect..." button when `message type == standard`
- [ ] test password strength (show checkboxes and etc.)
- [ ] test button color and 'enable" state
- [ ] test password visibiliity(not sure)
