### ISSUE TITLE
debug / fix sending web portal message so that it can be replied online

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#1636]
> * send a message from Android app through FES
> * open the received link on the other account, enter password. Make sure the message opens on fes.flowcrypt.com/...
> * click reply on fes.flowcrypt.com/...

1. send a message from Android app through FES - **works**
2. open the received link on the other account, enter password. Make sure the message opens on fes.flowcrypt.com/...- **works**
3. click reply on fes.flowcrypt.com/...- **I don't see reply button for a message that was send from Android. But I see this button for the web realization**

It seems I have bug on my side. Can we debug this case? 

@tomholub Please let me know what info I should provide.

_Originally posted by @DenBond7 in https://github.com/FlowCrypt/flowcrypt-android/issues/1629#issuecomment-1004883526_

@denbond I'm filing it as a separate issue. Likely a problem with encoding of reply info div.

**Comment by tomholub** [comment]
You you could send one message from browser extension and one from android, then download back the armored message from FES for each one of them and decrypt them. Then compare the difference in the contents.

**Comment by tomholub** [comment]
Here is the infodiv content on browser:

```ts
      const infoDiv = Ui.e('div', {
        'style': 'display: none;',
        'class': 'cryptup_reply',
        'cryptup-data': Str.htmlAttrEncode({
          sender: newMsgData.from,
          recipient: Value.arr.withoutVal(Value.arr.withoutVal(recipients, newMsgData.from), this.acctEmail),
          subject: newMsgData.subject,
          token: response.replyToken,
        })
      });
```

Contains `sender`, `recipient` (array), `subject`, `token`. Is that what you are encoding as well? I think I've seen something else.

**Comment by DenBond7** [comment]
It's strange. I can't decrypt a message from the web version via `gpg` nor `PGPainless`

https://flowcrypt.com/RtXpbqBxr0
qwerty1234

![image](https://user-images.githubusercontent.com/2863246/148180859-111c6e07-c8b1-4c48-af6f-4975a9cb00ca.png)

![image](https://user-images.githubusercontent.com/2863246/148181046-c9ea922c-d6ff-47fd-a5f8-0b98f2ceb0ac.png)

But can decrypt a message from Android

https://fes.flowcrypt.com/message/6c13d405-c984-4175-b395-2cdbfda42c64
qwerty1234

![image](https://user-images.githubusercontent.com/2863246/148181420-77bbac94-887c-4d75-a327-f95be2f12b77.png)

![image](https://user-images.githubusercontent.com/2863246/148181503-6ee23b06-a0be-4c3c-a113-8d0b751bb5e7.png)

**Comment by DenBond7** [comment]
Btw, web version and `PGPainless` produce a different password-protected message

`PGPainless` 
![image](https://user-images.githubusercontent.com/2863246/148182077-634663e7-ea84-414d-b49f-03498a9b96b0.png)

web
![image](https://user-images.githubusercontent.com/2863246/148182255-d6b32218-d393-4eb6-a670-c8c9839052a7.png)

To have more details I need to have not expired key for den@flowcrypt.com. Then I can provide examples for the same key

**Comment by tomholub** [comment]
Yes, because you are comparing legacy flowcrypt.com api (browser extension) to FES API (Android). 

I'll update your keys so you can do the same on your flowcrypt account on browser extension. Then you can compare.

**Comment by tomholub** [comment]
Updated your key on EAP - you should be now able to test from flowcrypt.com account on browser extension (after resetting it).

The password-encryption algorithm has changed between original flowcrypt.com/api (used on non-FES accounts on browser extension) and FES API (used for customers that run FES, plus flowcrypt.com accounts). Thus the difference.

**Comment by DenBond7** [comment]
Thank you! I will try it soon

**Comment by DenBond7** [comment]
Fixed
![image](https://user-images.githubusercontent.com/2863246/148398758-de4486a1-8c1b-4704-872a-0946aac9723f.png)
