### ISSUE TITLE
[User Concern] Plans to host the app aside from Google Play Store

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-android#1654]
Description:

We have received a concern asking whether we have hosted the apk file on our website or from F-Droid (an open-source website for hosting free and OSS app for android).

As of now, we don't have any of these options. There are some android phones that do not support Google services eg. Huawei devices so they won't have access to our app. They will have to download the app from a third-party website which may be dangerous as they have downloaded a reverse-engineered app that could be harmful.

Having a direct download link is a great option so it will be accessible from flowcrypt.com's download page.

If we consider hosting it to f-droid, there are pros and cons from f-droid that are mentioned in this blog post:
https://www.gadgetsnow.com/featured/what-is-f-droid-and-why-you-should-know-about-it/articleshow/82566076.cms

https://github.com/f-droid
https://gitlab.com/fdroid

Reference: https://mail.google.com/mail/u/1/#inbox/FMfcgzGmtXBKXsgHmHrZRFbjVtprTBSK

sir, @tomholub, let me know if you would like to consider it?

Thanks,

**Comment by DenBond7** [comment]
Hi, Mart. Please look at #881 and #1021

**Comment by martgil** [comment]
Thank you, sir @DenBond7. Looks like the F-Droid option will not be suitable for us. Thanks!
