### ISSUE TITLE
[User Concern] can't verify signature after importing the public key

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-android#1656]
Description:
A user reported that he is getting a notice that says "can't verify signature". As far as I know, this happens when the recipient's public key is not found in the contact list.

<img src=https://user-images.githubusercontent.com/46025304/149865235-31dcf233-72b6-462b-917c-9d04f8d92919.png width=350 height=100%>

I have replicated the issue with my account and I have a successful attempt in resolving it by either (1) importing a public key from a file or (2) searching the email and importing it.

The 2nd option does not help because the email is not uploaded to the attester key server. So I instructed him to delete the existing public key, ask his/her recipient to send the public key, and import the public key.

The user responded that he already tried it and the app says it was already imported - nothing has changed.

May I have any advice on this one? Thank you!

Ref: https://mail.google.com/mail/u/1/#inbox/FMfcgzGmtNkVBRgKlkmMnBLpTCdmBVrR

**Comment by DenBond7** [comment]
Hi @martgil, sorry for the delayed reply
>  As far as I know, this happens when the recipient's public key is not found in the contact list.

Yes, you are right

> May I have any advice on this one? Thank you!

You can ask him to ask his friend to send a test encrypted message to him and to den@flowcrypt.com with an attached public key (`subject = Issue #1656`). It may be a compatibility issue. With an encrypted message and a pub key, I will be able to find a place of the issue.

**Comment by martgil** [comment]
Thank you, sir @DenBond7. I would inform the concerned user right away. Thanks again!

**Comment by martgil** [comment]
Hello sir, @DenBond7 

The user notify us about your key being expired: https://flowcrypt.com/pub/den@flowcrypt.com

<img width="786" alt="Screen Shot 2022-01-26 at 12 34 55 PM" src="https://user-images.githubusercontent.com/46025304/151104624-4c6e51f6-88e9-4be5-b1bc-e265892a9b60.png">

If by any chance that sir, Tom ever updated your key, you can update the public key hosted in our attester as well - https://flowcrypt.com/attester/update-public-keys.

Thank you sir,

**Comment by DenBond7** [comment]
Hi @martgil, 
Sorry for that trouble.

I've updated my pub key on attester https://flowcrypt.com/pub/den@flowcrypt.com?show=pubkey. Please re-check to be sure.

@tomholub Btw, should we update our pub keys for @flowcrypt.com manually or it can be done automatically?

**Comment by tomholub** [comment]
There wasn't any need for the user to go to https://flowcrypt.com/pub/den@flowcrypt.com to fetch Den's pubkey. User can enter `den@flowcrypt.com` as a recipient, and it will automatically fetch Den's latest public key from WKD.

We'll eventually make it sync automatically, but for this usecase it wasn't required.

**Comment by DenBond7** [comment]
It seems like the user knows about `https://flowcrypt.com/pub/` (maybe he used it before) and used it to check some pub keys. It seems he tried to get a copy of my pub key to share with a friend.

Anyway, using the app(web or mobile) is the best option to have the right key.

**Comment by DenBond7** [comment]
I'm closing it as deprecated
