### ISSUE TITLE
Provide examples(raw MIME) for new/reply/forwarded and compare with web version.

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#1667]

**Comment by DenBond7** [comment]
[forwarded(Android).txt](https://github.com/FlowCrypt/flowcrypt-android/files/7949062/forwarded.Android.txt)
[forwarded(web).txt](https://github.com/FlowCrypt/flowcrypt-android/files/7949063/forwarded.web.txt)
[new (Android).txt](https://github.com/FlowCrypt/flowcrypt-android/files/7949064/new.Android.txt)
[new (web).txt](https://github.com/FlowCrypt/flowcrypt-android/files/7949065/new.web.txt)

password Qwerty1234@

**Comment by DenBond7** [comment]
@tomholub Please look at the provided examples. If Android versions look good we can close #1545 as completed.

**Comment by tomholub** [comment]
The web version manages to make the quoted message more distinct, probably by using blockquote or similar, in html (unsure - you'd nee to check).

![image](https://user-images.githubusercontent.com/6306961/153724165-4c5309b4-37c5-4d21-b4f7-3c7f3b6377a4.png)

Android is somewhat less readable. It includes more info (which is good!) but doesn't have the visual distinction.

![image](https://user-images.githubusercontent.com/6306961/153724194-1ec9d11b-8b5b-476d-b489-2cdd0cff2f39.png)

Again, this is good as is - and quoting can be improved in the future once we look into HTML on Android.
