### ISSUE TITLE
[User Concern] User cannot send an email to a certain email address using FlowCrypt android app

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-android#1681]
Description:
A user cannot send an email to an email address when using the FlowCrypt android app while sending the message using Gmail web app works.

Additionally, the email address the user trying to reach to was under of an email forwarding service called 'AnonAddy'  (https://anonaddy.com/), a free and open-source anonymous email forwarding service.

Technical details:
The email composes of special characters used for email filtering such as `+`, `=` and sometimes `.`

Scenario:
`Email Address #1`: `mail+demo=domain.com@email1.anonaddy.me`
`Email Address #2`: `mail+account=domain.com@email2.anonaddy.com`

Using the Gmail web app, I tried to send an email to both of these addresses.

I have a successful attempt at sending an email with recipient `Email Address #2` and a failed email on `Email Address #1` and returns the following error message:

<img width="727" alt="Screen Shot 2022-02-08 at 12 14 11 PM" src="https://user-images.githubusercontent.com/46025304/152919599-255548ef-28da-4e7a-9b5d-d2e7e859a2f0.png">

I tried to do the same thing on the FlowCrypt android app v.1.2.7 and I get the following error for both of the email addresses:

<img width="336" alt="Screen Shot 2022-02-08 at 12 43 45 PM" src="https://user-images.githubusercontent.com/46025304/152919866-0148de7f-284d-47ee-a4e6-382f63e5c058.png">

This prevents the user from sending an email to addresses with "complex" but a valid email addresses.

I would love to hear your thoughts about it. Thanks!

References:
https://mail.google.com/mail/u/1/#inbox/FMfcgzGmthprpZPNVdpkdkPfCmmfCQjv

**Comment by DenBond7** [comment]
We use the following pattern (a common approach in Android) to match valid addresses

```
public static final Pattern EMAIL_ADDRESS
        = Pattern.compile(
            "[a-zA-Z0-9\\+\\.\\_\\%\\-\\+]{1,256}" +
            "\\@" +
            "[a-zA-Z0-9][a-zA-Z0-9\\-]{0,64}" +
            "(" +
                "\\." +
                "[a-zA-Z0-9][a-zA-Z0-9\\-]{0,25}" +
            ")+"
        );
```

@martgil Do you think we need to switch to using something smarter? We can use for example 

https://github.com/FlowCrypt/flowcrypt-android/blob/3d76f428b09196501e1012668ed42103ce981e6e/FlowCrypt/src/main/java/com/flowcrypt/email/util/BetterEmailAddress.kt#L47

**Comment by IvanPizhenko** [comment]
There is class `BetterInternetAddress` in the flowcrypt-enterprise-on-prem, which is more comprehensive. I suggest copy it into Android app.

**Comment by martgil** [comment]
Sorry for the late reply sir @DenBond7.

I'm not really good at regex so I had to put those two regexes (proposed, current) patterns to a test so that I have a better understanding of it. 

<img width="1440" alt="Screen Shot 2022-02-09 at 4 28 12 PM" src="https://user-images.githubusercontent.com/46025304/153155834-7a581048-eaa8-4d22-9766-b5dd642e44f3.png">

I can confirm that the current one doesn't match the complex email address. The proposed one is very good.

**Comment by DenBond7** [comment]
https://github.com/FlowCrypt/flowcrypt-android/blob/3d76f428b09196501e1012668ed42103ce981e6e/FlowCrypt/src/main/java/com/flowcrypt/email/extensions/kotlin/StringExt.kt#L162

This method accepts `mail+account=domain.com@email2.anonaddy.com`

**Comment by DenBond7** [comment]
I'm closing it. #1898 fixed this issue.
