### ISSUE TITLE
Preview attachment contents

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#1682]
related issue to settle here before closing:
 - #1688

**Comment by tomholub** [comment]
@DenBond7 please look into this one soon:

When the following app is installed: https://play.google.com/store/apps/details?id=com.airwatch.contentlocker&hl=en&gl=US please send attachments to that app for preview.

Initially, don't worry about UI, instead let's look into integrating with that app, to see how it's done. See if they have any docs available, or if you need any info on the integration.

Once we know that we can use that app for viewing content, we'll look into UI.

It's a request from an important customer.

**Comment by DenBond7** [comment]
@tomholub Currently I'm working on #1602. Should I switch to this one immediately or it can wait for a few days?

**Comment by tomholub** [comment]
a few days ok. thanks

**Comment by DenBond7** [comment]
I've started to work with it. And I'm a little confused. I need more details.

> When the following app is installed: https://play.google.com/store/apps/details?id=com.airwatch.contentlocker&hl=en&gl=US please send attachments to that app for preview.

A user can use this app via a standard Android mechanism, like

![image](https://user-images.githubusercontent.com/2863246/153454676-29506762-d375-4f96-818a-d1d50bd0b318.png)

Also, that app is not a separate app. it's a part of a big architecture.

**Comment by DenBond7** [comment]
https://github.com/vmware-samples/workspace-ONE-SDK-integration-samples/blob/main/IntegrationGuideForAndroid/Documentation/snippets.md

https://vdc-download.vmware.com/vmwb-repository/dcr-public/7958fcb3-1c6d-4aa6-9d70-83498ec7ef9c/78d61c80-c488-4603-b5fc-0762e096918d/WorkspaceONE_Android_PublicMavenNote.pdf

**Comment by tomholub** [comment]
Are we able to restrict to which apps can user share when opening the attachments?

That would be the easiest way to fulfill the requirement, as follows (with client configuration, as an example)

When `FORCE_CONTENT_APP_ON_ANDROID` is Client Configuration is enabled, offer two options:
1) open with Content
2) save to device

Else, behave as usual.

**Comment by tomholub** [comment]
A little more user friendly, when `FORCE_CONTENT_APP_ON_ANDROID` is set:

Show `preview attachment` which would take user straight to Content and `download attachment` which would only offer saving it.

**Comment by tomholub** [comment]
> https://github.com/vmware-samples/workspace-ONE-SDK-integration-samples/blob/main/IntegrationGuideForAndroid/Documentation/snippets.md
> 
> https://vdc-download.vmware.com/vmwb-repository/dcr-public/7958fcb3-1c6d-4aa6-9d70-83498ec7ef9c/78d61c80-c488-4603-b5fc-0762e096918d/WorkspaceONE_Android_PublicMavenNote.pdf

We may not need this, with a bit of luck. In fact, the links don't mention the `Content` app at all, only `Workspace` at large, which may be other functionality out of scope here.

**Comment by DenBond7** [comment]
> When FORCE_CONTENT_APP_ON_ANDROID is Client Configuration is enabled, offer two options:

>open with Content
>save to device

Yup, we can do it in that way

**Comment by DenBond7** [comment]
When we share some info we should specify an intent with extra data. Via intent we can specify what an app(to be clear - what a component of some app) can handle such an intent.

**Comment by tomholub** [comment]
So it wouldn't have to have the client configuration yet - a draft PR for demo purpose.

**Comment by DenBond7** [comment]
Sure

Are we talking about this screen?

![Screenshot_2022-02-12-19-30-07-03_8a5443484bc9afa2d32cf276c137039c](https://user-images.githubusercontent.com/2863246/153721658-34739379-762d-45fb-9049-a863d47f044d.jpg)

**Comment by DenBond7** [comment]
I've investigated some moments after our discussion. What I see now:

1. We can provide the same behavior as before except for one difference - when a user clicks on the downloaded attachment we open that attachment only via `Content - Workspace ONE`. Just need to specify a package for that (`intent.setPackage("com.airwatch.contentlockerr)`). Please look at the provided example
![ezgif com-gif-maker](https://user-images.githubusercontent.com/2863246/153850015-e644ce4f-1f6a-4ddd-9e4c-bc926a85d16d.gif)

2. I thought about `open with Content` and `download` options. Not sure that we think about the same things. To do any actions with an attachment we have to download it. When a user clicks on some attachment in most cases we don't have that attachment on a device locally. I can't share an attachment to other apps if I didn't download it. Currently, by default, we download an attachment to the `Downloads` folder.

3. If downloading to the `Downloads` folder doesn't fit our needs (because in that case, a user can do any actions over an attachment via an app that can work with the file system), we can save an attachment in the app folder. After that, we can show options like `open with Content` or `Save locally`. Where `Save locally` will mean saving to the file system where a file will be available for other apps.

**Comment by tomholub** [comment]
Thank you for the demo. Here is clarification on the requirements:
 - each received file should have two buttons: `view` and `download`. Currently it only has one (download)
 - `view` should take the user to the `Content` app to preview attachment
 - `download` should work as before, but it should not give the user an option to share with `Google Drive` immediately after the download. Of course, we cannot prevent user from doing whatever they want with the file once it's on the device general storage. However, at the moment when the file is downloaded and user may want to "do something" with it, in situation when we still control the interaction, `google drive` app should be forbidden as a sharing option.

As for the preview, I hope the flow could be simplified. With current design, it is:
 - user taps view
 - a notification shows up that is downloading the attachment
 - attachment finished downloading
 - user needs to go to attachment in notification and tap it
 - content app appears

The simplified UX should be, when using Content app:
 - user taps view
 - there is a progress bar right on the attachment itself, no notification
 - when progress bar is finished, the user is sent to Content app
 - tapping back or leaving the view while preview is downloading / in progress will cancel the action

Everything discussed here will only take place when a particular client configuration flag is present. I still don't know what to call it. Let's say `RESTRICT_ANDROID_ATTACHMENT_HANDLING` ...

**Comment by IvanPizhenko** [comment]
Why forbid only Google Drive? There are more cloud storage apps that may be installed (at least: Dropbox, OneDrive, Mega, Box).

**Comment by DenBond7** [comment]
@tomholub One more question. If it is an enterprise user does it mean he uses Gmail API only? or new changes should affect Gmail API and IMAP too?

**Comment by tomholub** [comment]
Always only gmail api. no imap

**Comment by DenBond7** [comment]
@tomholub While I'm working on "save" option please look at the current result.

https://user-images.githubusercontent.com/2863246/155384749-2058a5c1-ef53-4535-90b9-bb1410f39d8b.mp4

Some important info.
1) For this case when the app downloads an attachment we store it in the RAM. 
2) When a user chooses "view" we try to open an attachment via `Content` even if it doesn't support such a type of file.
3) If a user doesn't have `Content` we will try to open an attachment via existing applications.
4) When a user uses "view" functionality I have to store a file in the internal storage (/data/data/com.flowcrypt.email/cache/current_msg/file_name.ext]. After that, I generate Uri via FileProvider.getUriForFile, create Intent, and open that intent. I can't share big files from the RAM directly.

**Comment by DenBond7** [comment]
> download should work as before, but it should not give the user an option to share with Google Drive immediately after the download. 

In that case, I propose just saving a file. Without the ability to open it from the notification. I can't filter apps as you described. I've done the research and have not found any code that can do that. The filtering requirement sounds like a developer wants to restrict the ability of other applications to process files. I think that's why we don't have such an ability.

After saving a user will be able to open a file from the file manager or send it via email and so on.

**Comment by DenBond7** [comment]
@tomholub 
> In that case, I propose just saving a file. Without the ability to open it from the notification. 

It looks like this one

https://user-images.githubusercontent.com/2863246/156402758-380df155-ade5-4096-bdee-49d7a63c290b.mp4

What do you think?

**Comment by tomholub** [comment]
> If a user doesn't have Content we will try to open an attachment via existing applications.

We can remove this functionality - if there is the appropriate Client Configuration flag, then it's always Content. If content is not available, then we could show a title `Cannot view attachment. Your organization requires the use of Content app to view attachments, but the Content app is missing. Please ask your Help Desk.`

**Comment by tomholub** [comment]
> When a user uses "view" functionality I have to store a file in the internal storage (/data/data/com.flowcrypt.email/cache/current_msg/file_name.ext]. After that, I generate Uri via FileProvider.getUriForFile, create Intent, and open that intent. I can't share big files from the RAM directly.

Does the file get cleared up after that? Additionally, all such files should be cleared up on each app startup, in case we failed to do it earlier (due to app crash, for example).

**Comment by DenBond7** [comment]
> > When a user uses "view" functionality I have to store a file in the internal storage (/data/data/com.flowcrypt.email/cache/current_msg/file_name.ext]. After that, I generate Uri via FileProvider.getUriForFile, create Intent, and open that intent. I can't share big files from the RAM directly.
> 
> Does the file get cleared up after that? Additionally, all such files should be cleared up on each app startup, in case we failed to do it earlier (due to app crash, for example).

Good question. I store a file in the cache directory. This directory can be cleaned by system if the last will need more space. But as I can see we should clear that files as soon as possible. In that case I propose to do that when a user leave the message details screen and after every startup.

**Comment by tomholub** [comment]
ok 👍

**Comment by DenBond7** [comment]
> Cannot view attachment. Your organization requires the use of Content app to view attachments, but the Content app is missing. Please ask your Help Desk.


![image](https://user-images.githubusercontent.com/2863246/156763125-c9d85c05-c39e-48d8-91a6-7617ee596756.png)
