### ISSUE TITLE
com.sun.mail.util.MailConnectException and javax.mail.MessagingException

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#170]
reports 84AE820478, 5509284309, 804FDE0047 and more

**Comment by tomholub** [comment]
But this only happens on standard auth, right? oAuth2 will work without that setting.

Maybe we should tell the user to just use oAuth instead.

When this happens, show the following notification:
"Less secure login methods are not allowed on your Gmail account. Please use a secure login method."
[ok]

When they click ok, open the oAuth screen as if they clicked the "gmail" button on initial screen.

**Comment by DenBond7** [comment]
```
javax.mail.MessagingException: Could not connect to SMTP host: smtp.gmail.com, port: 587;
com.sun.mail.util.MailConnectException: Couldn't connect to host, port: smtp.gmail.com, 25; timeout -1;
javax.mail.MessagingException: Could not connect to SMTP host: smtp.googlemail.com, port: 587;
javax.mail.MessagingException: Could not connect to SMTP host: smtp.mail.ru, port: 587;
```

All of this errors are showing an example of the next screen

![image](https://user-images.githubusercontent.com/2863246/33728204-5f8fab28-db82-11e7-8e30-ad87b07c7c6a.png)

It's mean the user use wrong settings of his an IMAP or SMTP server. Or use the IMAP or SMTP server which is unavailable (smtp.googlemail.com).

@tomholub Do you think that screen is not informative?

**Comment by DenBond7** [comment]
> But this only happens on standard auth, right? oAuth2 will work without that setting.

Yes, of course. It's only happening on standard auth.

**Comment by DenBond7** [comment]
I updated the [Email providers IMAP SMTP settings](https://github.com/FlowCrypt/flowcrypt-android/wiki/Email-providers-IMAP-SMTP-settings) Wiki page.

**Comment by tomholub** [comment]
I think this screen is ok. If the user always sees the error, that's good enough for now.
 - if it's a gmail security error, show notice as I mentioned above (no need to report to ACRA)
 - if it's a SMTP/IMAP connection error, you can leave it as is (no need to report to ACRA)
 - any other errors should be reported to ACRA

**Comment by DenBond7** [comment]
@tomholub 
> "Less secure login methods are not allowed on your Gmail account. Please use a secure login instead."

Can we use a shorter hint?

![image](https://user-images.githubusercontent.com/2863246/33771829-320aa23e-dc3b-11e7-84dd-0c14ab434c4a.png)

**Comment by tomholub** [comment]
Shortened: "Less secure login is not allowed on your Gmail account. Switching to secure login."

[ok] will open Gmail oAuth screen
