### ISSUE TITLE
Fix sending encrypted messages with attachments

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#1713]
Bug after https://github.com/FlowCrypt/flowcrypt-android/commit/316cf32c7778f8178ce2384547f14637d029cba2 (1.2.8)

ref https://mail.google.com/mail/u/3/#inbox/FMfcgzGmvLWRxnWhVmJsvlCrbHSvQMJJ

**Comment by tomholub** [comment]
Ok to do quick fix and then add a test right after.
