### ISSUE TITLE
reply not attached to gmail conversation (sender side)

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#172]
I'm seeing this issue again: #145

Let me know if you're able to reproduce.

On Gmail, but it only seems to happen with encrypted messages?

**Comment by DenBond7** [comment]
Currently, I'm testing this situation, and everything is in order.

Sender
![sender](https://user-images.githubusercontent.com/2863246/33877832-4843f114-df32-11e7-8479-b5b78c5105c2.png)

Receiver
![receiver](https://user-images.githubusercontent.com/2863246/33877845-56ce7b3c-df32-11e7-81c2-a45ad4cf5bd3.png)

I 'm sending an email from my test Gmail account to one of my Outlook accounts, which is used as an alias in my main Gmail account. I did all steps using Flowcrypt. So, in this case, the Gmail API works fine.

What is your scenario? Did you use aliases functionality?

**Comment by tomholub** [comment]
Yes, it was on an alias. I'll try again.

**Comment by tomholub** [comment]
Didn't happen this time.. I'll continue to observe.

**Comment by tomholub** [comment]
Actually, the problem is on the side of the person receiving the reply. I'll send some screenshots.

**Comment by tomholub** [comment]
Sorry, fail again.
