### ISSUE TITLE
email stucked in the outbox with error 'no available key for your email account'

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-android#1722]
Description:

A user reached out to us saying that the email won't send with an error message that says:
<img src=https://user-images.githubusercontent.com/46025304/159848833-4e78b196-663a-4ed5-b54a-355a0e67158c.png width=50%>

I look into it myself but I can't trigger the exact error message as I was already interrupted by the app at the message compose phase when using an email account that isn't present to any userid of a private key.

In the user's case, the email account and the user ids match the email account. (one is a gmail and the other is protonmail addresses).
<img src=https://user-images.githubusercontent.com/46025304/159849239-a1cda16b-3e7f-40a1-b3e5-4d528aa74a9a.png width=50%>

I'll try to give it another go and see if i can identify the issue. thanks!

**Comment by DenBond7** [comment]
Hi @martgil. This bug was fixed in 1.3.0 that should be available for all users soon. I'm closing it for now.

**Comment by martgil** [comment]
Hello sir, @DenBond7 - thanks for looking into this. updating the app works like a charm. I will try to check first if they are using the latest version next time before reporting :) thanks again sir, and take care!
