### ISSUE TITLE
encrypted message marked as not encrypted + not signed on different app version (1.3.0) but working on (1.2.8)

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-android#1727]
Description:
A user reported us a situation where the encrypted message doesn't render properly on a different versions of the app.

On version 1.3.0 the encrypted message displayed (not encrypted + not signed) while when opening on 1.2.8 shows decrypted message properly.

I'm not exactly sure how it is happening as I tried different messages + replying to an encrypted message but I never ended up to the situation stated above.

Here are the sample screenshots:

(app version 1.3.0)
<img src=https://user-images.githubusercontent.com/46025304/160797490-5900e9ee-a4f6-404d-8b2f-26df5a8db979.jpeg width=25%>
(app version 1.2.8)
<img src=https://user-images.githubusercontent.com/46025304/160797502-c089dd40-cc90-4985-99db-182f166daa9f.png width=25%>
(end pgp message footer shown on app version 1.3.0)
<img src=https://user-images.githubusercontent.com/46025304/160797512-f06cb4ca-868b-4a13-af4c-58db0d1441be.png width=25%>

Just reporting in the meantime while I'm still gathering more helpful information. Let me know if there is any specific information needed and I'll try to get an answer as quickly as possible.

reference: https://mail.google.com/mail/u/6/#search/mis01/FMfcgzGmvfbhDvmfDTDrmrRlSxBkBbrR

**Comment by DenBond7** [comment]
It can be a compatibility issue. In 1.2.9 we added a lot of changes to support detached signature. Also, I've changed the message processing logic. It seems the user's message has an unusual format. It would be nice to have a full MIME raw message. After that, I can fix this issue.

**Comment by martgil** [comment]
Thank you, sir! I'll request the full mime raw message from the user and get back to you. Thanks.

**Comment by martgil** [comment]
Hi, sir @DenBond7 - I've sent the .eml through email. The user also share that the message was indeed not readable to 1.3.0 after he accidentally updated the app on his/her older phone which he/she was able to read the encrypted message before.

**Comment by DenBond7** [comment]
Hi @martgil. I've checked your example. I can confirm that it's a compatibility issue. Could we know what software was used to create that example?

**Comment by martgil** [comment]
Hello @DenBond7 - yes, sir. I have sent the request to the user. I hope we can hear back an update from him/her soon.

**Comment by martgil** [comment]
Hello sir, @DenBond7 - The user swiftly responded to our request and shared that the software that produces a problematic encrypted email was `Mailvelope extension v4.5.2`.

I'm able to replicate the problem on my end:
<img width="343" alt="Screen Shot 2022-04-26 at 10 18 18 AM" src="https://user-images.githubusercontent.com/46025304/165206376-a2ee29d2-1071-40ec-9c09-062100a2f488.png">

Steps to reproduce:
pre-requisite: Install [mailvelope extension](https://chrome.google.com/webstore/detail/mailvelope/kajibbejlbohfaggdiogboambcijhkke/related?hl=en&authuser=2)

Here is the flow we need to follow to replicate the issue:
user 1 Flowcrypt user
user 2 Mailvelope user

1. user 1 sends an encrypted email to user 2
2. user 2 reads the email and sends an encrypted reply to user 1
3. user 1 reads the email using FlowCrypt for android v1.3.1 - the android app only an infinite shows a loading screen.

I can help you here so you won't have to start from scratch,  just send me a new encrypted email to the address I'm providing via email. After that, I'll be responding to that email using mailvelope and you should receive the encrypted reply that produces the said issue.

Many thanks!

**Comment by martgil** [comment]
It's strange that the message gets actually decrypted properly after re-opening the same encrypted email. I'll try a few more attempts, probably not what we're expecting.

**Comment by DenBond7** [comment]
Thank you @martgil for the details. I will continue my investigation soon.

**Comment by martgil** [comment]
Welcome sir, Den - btw sir, I communicate with the user and send him an encrypted message (reply) I composed using the Mailvelope browser extension. He told me that he has now been able to read the message using the android app v1.3.1. 

He added that he would like to check if the same goes for the encrypted message that came from friends who have known to use Mailvelope.
