### ISSUE TITLE
encrypted message content are completely hidden in android app

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-android#1744]
Description:
Encrypted messages sent from the contact page are completely hidden when opening it on the FlowCrypt android app. This is happening for messages with or without attachments.

Steps to reproduce:
(lets assume that you already setup encrypt contact page at https://flowcrypt.com/account/encrypted-contact-page)
1. compose and send the message through the contact page - https://flowcrypt.com/me/<\username>
2. open message using the FlowCrypt app v1.3.0 or v1.3.1
3. message was hidden from the app.

Screenshot(s):
![6 (1)](https://user-images.githubusercontent.com/46025304/163105471-e9742475-510a-45ee-bfc3-899dec1539c5.png)

related problem with message sent from contact page: https://github.com/FlowCrypt/flowcrypt-android/issues/1710

Reference:
https://mail.google.com/mail/u/6/#inbox/FMfcgzGmvpJVKZnRxWgKpDrNdZVbZTsv

**Comment by martgil** [comment]
Furthermore, another user experienced the same problem, but this time, it was a message from proton mail. 

I tried to test it myself and confirm the same problem happened: 
<img width="903" alt="Screen Shot 2022-04-14 at 10 32 18 AM" src="https://user-images.githubusercontent.com/46025304/163302547-7da3aef9-ba18-47b3-a678-a5d40b9844a7.png">
(browser extension on the left, android emulator on the right)

**Comment by DenBond7** [comment]
> compose and send message from the contact page - https://flowcrypt.com/me/

I've tried to send me a message. But I still don't see any new messages in the INBOX.

> another user experienced the same problem, but this time, it was a message from proton mail.

I've opened a separate issue for that #1752. I think it's a different case.

**Comment by martgil** [comment]
> > compose and send message from the contact page - https://flowcrypt.com/me/
> 
> I've tried to send me a message. But I still don't see any new messages in the INBOX.
> 

The email might just be delayed. I'm still able to replicate it at v.1.3.1
![image](https://user-images.githubusercontent.com/46025304/164173639-b708b9dd-e8d7-46f2-871d-9ba3faadacdb.png)

> > another user experienced the same problem, but this time, it was a message from proton mail.
> 
> I've opened a separate issue for that #1752. I think it's a different case.

You're right - it might be a different case.

**Comment by DenBond7** [comment]
> The email might just be delayed. 

All looks good. I've found that message.

>  I'm still able to replicate it at v.1.3.1

Yes, it's a compatibility issue. I'm working on it.

**Comment by martgil** [comment]
Thanks for your confirmation and no worries!
