### ISSUE TITLE
1.3.2 release

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#1756]
did you not want me to release this one? Or do we wait a bit later?

**Comment by DenBond7** [comment]
Sorry, I've forgotten about this one. 1.3.2 doesn't contain improvements for users - architecture changes and code refactoring. I don't see really needs to make a new release. For now we have only a few changes from 1.3.3 that already can be released: #1741 and #1744. Do we need to release them now or we can wait for a few new?

**Comment by tomholub** [comment]
We can release this on Monday maybe. I've moved done tasks to 1.3.2 so it will now include user fixes. What do you think?

**Comment by DenBond7** [comment]
Agree. Let's do a new release on Monday. I will recheck things and notify you soon.

**Comment by DenBond7** [comment]
@tomholub it's ready

**Comment by DenBond7** [comment]
Moved back to me. I've found an issue(#1759)

**Comment by DenBond7** [comment]
@tomholub it's finally ready

**Comment by tomholub** [comment]
- build
 - release enterprise
 - consumer 10%
