### ISSUE TITLE
Travis + Google App Engine + custom FTP

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#176]
https://docs.travis-ci.com/user/deployment/google-app-engine/

1. Travis runs a build

1. Travis sends generated apk files to Google App Engine

1. Google App Engine sends apk files to a custom FTP server.

Profit => I always have fresh apk files.

**Comment by DenBond7** [comment]
Or https://docs.travis-ci.com/user/deployment/gcs/
Or https://docs.travis-ci.com/user/deployment/s3/

**Comment by tomholub** [comment]
We could probably set up the s3 option. I'm mostly interested in the testing, but if saving it somewhere is necessary for the process, we can use our s3

**Comment by DenBond7** [comment]
That's not necessary yet. I will do that when I will have more free time.

**Comment by tomholub** [comment]
Glad to hear it's not necessary

**Comment by DenBond7** [comment]
I'm closing it as not relevant now
