### ISSUE TITLE
public key update - better handling of revoked keys

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#1767]
same as https://github.com/FlowCrypt/flowcrypt-ios/issues/1560#issue-1221328738

**Comment by DenBond7** [comment]
@tomholub It seems https://github.com/FlowCrypt/flowcrypt-ios/issues/1560#issue-1221328738 describes the following cases:

- during compose
- during signature verification (message details screen)

I've also fixed the following places(manual updating by a user)

1. message details screen with a pub key

![image](https://user-images.githubusercontent.com/2863246/174294301-14b228f0-3af9-4380-bda4-fec883e1ef9b.png)

2. Import a key from Settings -> Contacts -> Import

![image](https://user-images.githubusercontent.com/2863246/174294673-7ab5de89-9a34-4d1b-a106-a417ce6c1ae0.png)

Do you have the same for iOs?

**Comment by tomholub** [comment]
> Do you have the same for iOs?

iOS doesn't support manually importing public keys yet.

But yes - this mechanism has to apply for any time public key is imported from any source.

**Comment by tomholub** [comment]
The warning should be changed to `You already have a revoked version of this key. Further updates to this key are not allowed. Please request another key from the sender.`

**Comment by DenBond7** [comment]
Got it. I will change it.
