### ISSUE TITLE
EKM keys refresh: allow removing keys, except when revoked + improve revoked handing

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#1768]
same as https://github.com/FlowCrypt/flowcrypt-ios/issues/1559

**Comment by DenBond7** [comment]
Test the following cases:

- [ ] disallow update revoked keys
- [ ] disallow delete revoked keys
- [ ] delete not matching keys
- [ ] don't delete at least one key. To prevent unexpected issues we should be sure that at least one private key is existing in the app

**Comment by DenBond7** [comment]
That's not about a fresh install. It relates to updating existing keys via EKM

**Comment by tomholub** [comment]
Actually, if EKM wants to delete all keys, you should be deleting all keys.

What would currently happen to the app if you did that? Many things would not function (sending, opening email) but is it otherwise functional?

**Comment by DenBond7** [comment]
The problem is we don't support it. A user should have at least one private key to prevent unexpected behavior. I really don't know what will happen and where in that case. In that case need to be ready for issues over the whole app. Today we have a big app... and too many places where we can have a bug.

**Comment by DenBond7** [comment]
By the way, what is a reason to delete all user's keys? And leave a user without keys.

**Comment by tomholub** [comment]
Maybe they left the company, or maybe the admin deleted their keys with the intention to give them new ones.

You could log the account out when this happens. Then at least you follow what EKM says - delete keys.

**Comment by tomholub** [comment]
> You could log the account out when this happens. Then at least you follow what EKM says - delete keys.

Later we look into it as a separate issue to see if we could support situation of not having any keys anymore

**Comment by DenBond7** [comment]
> Later we look into it as a separate issue to see if we could support situation of not having any keys anymore

I think it will be interesting over all platforms
