### ISSUE TITLE
Using Js from the background service for decryption.

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#177]
Currently, I create a new instance of Js tool every time when I try to decrypt the message. And It's an expensive operation ( around 1000 ms).

For the faster decryption process, I can create a background service which will be containing an already configured instance of Js tool.

**Comment by tomholub** [comment]
I'm on my phone. Please create milestone "0.6.0: Speed" and add this issue to the milestone

**Comment by DenBond7** [comment]
![image](https://user-images.githubusercontent.com/2863246/36259383-baa14ee8-1266-11e8-8245-2b250c36a202.png)

**Comment by tomholub** [comment]
I am currently transitioning to a similar pattern on desktop:
1) decrypt frames do not load OpenPGP.js at all
2) decrypt frame will message a background process to decrypt a message
3) background process has a pool of workers (threads). It will schedule the decrypt job to one of the threads.
