### ISSUE TITLE
Fix UI styles for most devices

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#180]
For example this

![fdc63216855f888b250f53f287f15921287b6cb086ad8054d1 pimgpsh_fullsize_distr](https://user-images.githubusercontent.com/2863246/34603214-b58b357a-f20b-11e7-8543-08db35190f30.jpg)

I will add more details later

**Comment by tomholub** [comment]
Oh, does this happen only on some devices?

**Comment by DenBond7** [comment]
> Oh, does this happen only on some devices?

Yes, it depends on the API styles and other (maybe own phone customization - MIUI, Flyme OS etc.)

Currently, I'm testing the app in the different cases (API 19 -26, screen resolution - FULL HD (1920 × 1080) and HD (1280 × 720)). I will add more details after I'll finish the testing.

**Comment by tomholub** [comment]
ref https://mail.google.com/mail/u/0/#inbox/1611a79bbe66c6ac

**Comment by DenBond7** [comment]
Such errors are happening on devices with API below 23. Because the layer height is not supported by API below 23. So I need to use other solution for such devices.

**Comment by DenBond7** [comment]
`Based on the version rainfall, what percentage of users are affected?`

Around 3.2% (I'm using your statistics from the Google Play)

ref https://mail.google.com/mail/u/0/#inbox/160fbdd79dd352ac

**Comment by tomholub** [comment]
I would probably ignore it. Just make sure that it's clearly readable on
these versions, but I would not spend too much effort making it look the
same.
