### ISSUE TITLE
Cannot login to FlowCrypt app using Outlook account

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-android#1810]
Description:
A user cannot continue logging into the FlowCrypt app with the Outlook account. 

The app throws the following OAuth error:
<img width="341" alt="Screen Shot 2022-05-19 at 1 50 08 PM" src="https://user-images.githubusercontent.com/46025304/169261772-1b30be2f-91ce-4ddd-a8cf-c719cd3b99dd.png">

Additionally, here is the sample request which I get before the OAuth error message.
Request URL: `https://login.live.com/oauth20_authorize.srf?uaid=<redacted>&opid=<redacted>&mkt=EN-US&opidt=<redacted>&route=R3_BAY&res=success`
<details><summary> Response body </summary>
```
HTTP/1.1 302 Found
Cache-Control: no-store, no-cache
Pragma: no-cache
Content-Type: text/html; charset=utf-8
Expires: Thu, 19 May 2022 09:23:47 GMT
Location: msauth://com.flowcrypt.email/gVgrJ%2BnS3FFmy0N1RePwMwAKI70%3D?code=M.R3_BAY.<uuid-looking-strings>&state=<oauth-state-param>
P3P: CP="DSP CUR OTPi IND OTRi ONL FIN"
Referrer-Policy: strict-origin-when-cross-origin
x-ms-route-info: R3_BAY
x-ms-request-id: 0e88c1aa-1b44-4d99-9ad5-56182f436e39
PPServer: PPV: 30 H: BY1PPF0A2EAF4A9 V: 0
X-Content-Type-Options: nosniff
Strict-Transport-Security: max-age=31536000
X-XSS-Protection: 1; mode=block
Some Set-Cookie: ...
Date: Thu, 19 May 2022 09:24:47 GMT
Connection: close
Content-Length: 0
```
</details>

Both the user and I were using: Android version 12. While I noticed that there's no error occurring on Android 9 when replicating the issue on my other emulator though it redirects me onto the splash screen right after I completed the authentication flow.

I'm also sharing the original feedback from the user:
> Hi, I'm trying to do the Outlook login on Android, and I get an OAuth error, or optionally an msauth:// not supported error depending on which browser I use (Chrome, Edge, Kiwi, Samsung Internet).

Reference: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGpFzssDHCbCsgtdbWsdkkxWmZC

**Comment by DenBond7** [comment]
@martgil Please recheck this issue. I can't reproduce it. I can log in via Outlook OAuth.

**Comment by martgil** [comment]
sir, I still have a problem logging in with my account via Outlook OAuth for both emulator (android 9) and real device (android 11) though the OAuth error message box doesn't appear at all. For me, it stops as nothing happens after the authorization process. 

Video demo (restricted only for Den's corporate email as it contains personal info): https://drive.google.com/file/d/1TRg0kMXcbtB160Mb_fwnSI6Lp0nPGexl/view?usp=sharing

**Comment by DenBond7** [comment]
Thank you Mart for the video. Interesting... I have different behavior on my devices.

**Comment by martgil** [comment]
You're welcome, sir, Den. I'd like to add that in my other emulator the error is different when logging in with outlook oauth. 

<img width="340" alt="different error" src="https://user-images.githubusercontent.com/46025304/182793747-a357e50c-ec75-4b27-aae4-9bbeaeba0384.png">
