### ISSUE TITLE
Make the app name less 30 characters

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#1833]
![image](https://user-images.githubusercontent.com/2863246/172395376-45b105af-abbb-40b8-bf7c-f70313766044.png)

**Comment by DenBond7** [comment]
@tomholub Please look at this. It seems we need to use just `FlowCrypt`(or `FlowCrypt: Encrypted Email`) instead of `FlowCrypt: Encrypted Email with PGP`

**Comment by DenBond7** [comment]
More details here https://android-developers.googleblog.com/2021/04/updated-guidance-to-improve-your-app.html

**Comment by tomholub** [comment]
`FlowCrypt: PGP Encrypted Email` :shrug:

**Comment by tomholub** [comment]
or `FlowCrypt PGP Encrypted Email`

**Comment by DenBond7** [comment]
It seems you have to change it yourself (I don't have a permission)

![image](https://user-images.githubusercontent.com/2863246/172396974-133982c8-ffd8-40c7-9311-815f6797393e.png)
