### ISSUE TITLE
not offering password-protected message even though FES is available

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#1858]
Sending from account at `flowcrypt.com` to a non-pgp account, and getting this:

<img width="663" alt="image" src="https://user-images.githubusercontent.com/6306961/174585064-fcd7b273-56c7-4077-bb5f-81c95c983bd1.png">

Whereas on browser extension and iOS it correctly offers password-protected message.

**Comment by DenBond7** [comment]
@tomholub I've checked. It works on my device. Could you share more details?

https://user-images.githubusercontent.com/2863246/174745365-2a17b7f0-77ec-4b16-87e1-97f0cd95d628.mp4

**Comment by tomholub** [comment]
I can't view the video on my device. Sent email

**Comment by DenBond7** [comment]
Could you check is relevant today? I still can't reproduce it.

**Comment by DenBond7** [comment]
@tomholub ping

**Comment by tomholub** [comment]
tested on 1.4.0 no problem
