### ISSUE TITLE
[User concern] options to receive encrypted emails only

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-android#1907]
Description:
We received an inquiry from a user about an option to receive encrypted emails only. We previously offered this feature on the older version of the app.

@DenBond7 Good Morning, sir! - Do we have plans to bring it back in the future? Thank you!

Reference(s):
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGpHHKDKmctHLhzDnGbgPcFGhXt
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGxSHkFlwxPbsZzSGZWqfkKjvSH
https://mail.google.com/mail/u/human@flowcrypt.com/#archive/FMfcgzGqPpgHFbPcTsmGzjXlMKPdhvrN

**Comment by DenBond7** [comment]
Hi Mart. Unfortunately, I had to disable this feature. Filtering encrypted messages on the server side - it's a little quite difficult thing. I think we will improve it in the future and make it available. But I don't sure that will be soon ((.

**Comment by martgil** [comment]
Hello sir, Den. I understand clearly - I'll explain this to the user. Thank you very much for the immediate response!

**Comment by DenBond7** [comment]
> Also for show only encrypted messages functionality we can try to use [users.messages.list](https://developers.google.com/gmail/api/reference/rest/v1/users.messages/list?apix_params=%7B%22userId%22%3A%22me%22%2C%22q%22%3A%22BEGIN+PGP+MESSAGE%22%7D) which will search for messages containing BEGIN PGP MESSAGE and END PGP MESSAGE strings or attachments with possible encrypted msg filenames (encrypted.asc, message.asc etc). And then locally additionally filter search results to remove non-encrypted messages from results.

filename:asc AND "-----BEGIN PGP MESSAGE-----" AND "-----END PGP MESSAGE-----"

**Comment by DenBond7** [comment]
@sosnovsky Just in case, it looks like iOS app doesn't store loaded message info and just has a temporary cache in RAM. If I close the app and open it in 1 hour it will load the messages list again(`INBOX`). Or for example during switching folders. Right?

**Comment by sosnovsky** [comment]
> @sosnovsky Just in case, it looks like iOS app doesn't store loaded message info and just has a temporary cache in RAM. If I close the app and open it in 1 hour it will load the messages list again(`INBOX`). Or for example during switching folders. Right?

Correct, we don't have messages persistence mechanism in the iOS app yet, they're loaded from the remote API on each app start.

**Comment by DenBond7** [comment]
- [ ] check JavaMail realization(or disable it)
