### ISSUE TITLE
nothing happens after clicking the "import backup key" of the "Keys" settings section

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-android#1922]
I just noticed that the "import backup key" option does nothing when clicked.  It doesn't throw any error messages after clicking the "import backup key" button. 

App version: 1.3.4
Android version: 12

Screenshot:
<img width="337" alt="backup-keys-found" src="https://user-images.githubusercontent.com/46025304/182070090-ab2a33ff-6731-403d-b461-477368d5bc71.png">

**Comment by DenBond7** [comment]
Thank you, Mart. It's a bug. It will be fixed in the upcoming release.
