### ISSUE TITLE
recovery screen (?) help icons

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#193]
`(?)` icon to the right of `Enter your pass phrase` prompt recovery screen. 

When clicked, this info will show:

> Your key backup is encrypted. Good!
> 
> Please enter your pass phrase that you used when this backup was created.
> 
> **Forgotten pass phrase?**
>
> If you are setting up FlowCrypt on a second device and your first device can still read encrypted email, you can change your pass phrase on the original deice before continuing:
> 
> 1) Open "FlowCrypt Settings (on that device) -> Security -> Change pass phrase" on that original device
> 2) Set a new pass phrase 
> 3) Restart FlowCrypt Android App
> 4) Use your new pass phrase to set up the Android App

Send your questions to human@flowcrypt.com

**Comment by tomholub** [comment]
ref https://mail.google.com/mail/u/0/#inbox/1611a79bbe66c6ac

**Comment by tomholub** [comment]
Basically want a way to add an icon-link anywhere in text, eg the icon `info` or `info outline` from https://material.io/icons/ . When user clicks it, a dialog will show up looking something like this:

![image](https://user-images.githubusercontent.com/6306961/35276197-8f122a40-007d-11e8-8d2f-3860f07c768b.png)

It should have a "close" icon on the bottom. 

The text of the dialog should ideally be taken from a html file (similar to some other info pages).

**Comment by tomholub** [comment]
`(?)` icon to the right of `Found a backup of your account key`. When clicked, it will show:

> FlowCrypt found one or more backups of your account key(s) in your inbox.
>
> Key backups are encrypted for your protection. This makes them useless without your pass phrase.
> 
> Please enter pass phrase(s) that you used when the backup was made.

**Comment by DenBond7** [comment]
> FlowCrypt found one or more backups of your account key(s) in your inbox.

Is it correct? We are finding the keys in different folders.

**Comment by DenBond7** [comment]
> (?) icon to the right of Enter your pass phrase prompt recovery screen.

Could you clarify where I must set this icon? (in UI)

**Comment by DenBond7** [comment]
What to do if a user does Settings -> Keys -> Import?

There is I have the next screen

![image](https://user-images.githubusercontent.com/2863246/37526566-68220e80-2938-11e8-8cca-aa60a9468211.png)

Hide `(?) icon to the right of Found a backup of your account key.`?

**Comment by tomholub** [comment]
> Could you clarify where I must set this icon? (in UI)

To the right of `Enter your pass phrase` blue text. Is that possible?  Basically it will become
```
Enter your pass phrase (?)

_________________________________________
```

> What to do if a user does Settings -> Keys -> Import?
> Hide (?) icon to the right of Found a backup of your account key.?

Yes, in this case we would not show the (?) about found backup, but still show  `Enter your pass phrase (?)`

**Comment by DenBond7** [comment]
>  Is that possible?

Yes, it is. It will look like this

![device-2018-03-23-114623](https://user-images.githubusercontent.com/2863246/37822722-f030af3c-2e8f-11e8-8fe6-eaf869a1d328.png)

**Comment by tomholub** [comment]
- The size of the `(?)` icons should be consistent (right now each icon has a different size)
- All should be about 80% the size of the "Enter your pass phrase" icon
- Icons should have the same color as "use another account" button text
