### ISSUE TITLE
app seem to have problem fetching pubkeys from WKD

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-android#1953]
Description:
A user asks if our client app supports WKD lookup (which we support). I tried composing an encrypted email with the sample address that the user shared and the browser extension found and loads the public key immediately - response contains an octet-stream non-ASCII armored key from the respective WKD. Doing the same procedure with our app results in the public key not being found even though the requests to get the public key has been successfully sent to the WKD server.

I'll be sending the sample email and the URL in a separate email. Thank you.

To reproduce the issue, simply compose an encrypted email and enter the recipient's address under of a WKD.

Reference: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqPzBXfrMxWMrsqDhQqdfnvkDq

**Comment by DenBond7** [comment]
Hi Mart. Thank you for this feedback. I've found a reason for the issue.

It seems the user's pub key has the wrong `userId`. It doesn't fit [rfc822](https://datatracker.ietf.org/doc/html/rfc822#section-3.3)

We have `Bob D. <bob@test.test>`, but it should be `"Bob D." <bob@test.test>`

![image](https://user-images.githubusercontent.com/2863246/187160811-cce3f3cb-f14c-4442-9a97-bcbf5774dd79.png)

I need to think about what we can do here

**Comment by DenBond7** [comment]
For me
`val parsed = BetterInternetAddress(userId, verifySpecialCharacters = false)`

**Comment by martgil** [comment]
> Hi Mart. Thank you for this feedback. I've found a reason for the issue.

Thank you, sir, Den, for looking into this issue and letting us know the root cause.

> I  need to think about what we can do here

Understood, sir. Please take your time.
