### ISSUE TITLE
use response code when checking welcome message "sent" status

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-android#1961]
From https://github.com/FlowCrypt/flowcrypt-attester-ts/pull/269#discussion_r955218351_, Tom would eventually like to use for response code when checking the welcome message "sent" status in `https://flowcrypt.com/attester/test/welcome` instead of checking for "sent" JSON value from the server response. 

Code from `TestWelcomeResponse.kt` 
```kotlin
    override fun writeToParcel(dest: Parcel, flags: Int) =
    with(dest) {
      writeParcelable(apiError, 0)
      writeInt((if (isSent) 1 else 0))
    }
    ```

Please consult @tomholub regarding the priority level of this one. Also, there is https://github.com/FlowCrypt/flowcrypt-attester-ts/issues/263 where the change of the endpoint for sending the welcome message is possible. Thank you!

**Comment by tomholub** [comment]
@martgil could you quote the code where `sent` is currently being used on this repo?

**Comment by tomholub** [comment]
I see it now

![image](https://user-images.githubusercontent.com/6306961/186876759-43274235-9edf-4fdb-b539-24f17873ffa1.png)
