### ISSUE TITLE
pass phrase session length should be configurable with client configuration

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#1962]
The returned JSON may contain `"in_memory_pass_phrase_session_length": 3600` for example. The number is an integer and to be interpreted as amount of seconds a pass phrase session will last. Currently hard-coded as 4 hours.

This mechanism applies only when browser extension is storing pass phrase in-memory. In other words, it does not affect the decision as to where the pass phrase will be stored, that was decided either by user or by `FORBID_STORING_PASS_PHRASE`. If the pass phrase is stored in storage, whatever the reason for it, this new client configuration will have no effect.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-browser/issues/4613#issuecomment-1228303813_

**Comment by DenBond7** [comment]
@tomholub 
I'd like to clarify a few moments. 

1. What about `min` and `max` for `in_memory_pass_phrase_session_length`? 
2. Should I check that `in_memory_pass_phrase_session_length` is a positive number?

the `min` value is important. On Android, in 

https://github.com/FlowCrypt/flowcrypt-android/blob/f8d0c48b4053afaadb3038078d5d276058005c48/FlowCrypt/src/main/java/com/flowcrypt/email/service/PassPhrasesInRAMService.kt#L94

we check and reset (if needed) pass phrases every minute. If `in_memory_pass_phrase_session_length` can be less than 60 seconds I have to modify this code too.

**Comment by tomholub** [comment]
I guess, if someone uses 1 second value, and you check once a minute, that's fine. So a minimum would be 1, even if on Android it effectively means a higher value due to the mechanism.

I don't expect anyone will set it that low. On browser extension, we'll probably set it low during automated tests, so we don't have to wait a minute to perform the test.

**Comment by tomholub** [comment]
Yes, please do check that it's a positive integer value. For `max`, choose the largest native integer type on your platform.
