### ISSUE TITLE
Error: No direct-key signature and no user-id signature found when importing a private key

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-android#1976]
Description:
A  user was unable to import his private key on the FlowCrypt due to the following error. During our conversation, the same private key was usable on the browser extension.

Screenshot:
![Screenshot from 2022-09-14 13-06-10](https://user-images.githubusercontent.com/46025304/190086603-bed2c67a-0f10-440e-ae50-af4ec8dc0ef7.png)

Step to reproduce:
1. Download or copy the private key (will be shared via secure email).
2. Import the private key and the error will appear.

Reference: https://mail.google.com/mail/u/human@flowcrypt.com/#search/Peter/FMfcgzGqQSQBFdGwVvMmTFsKXnnWJPsx

**Comment by DenBond7** [comment]
I'm closing it. According to our old conversation(email), we are not going to support such keys as unsafe.
