### ISSUE TITLE
attester/initial/legacy_submit and welcome message changes

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#1984]
I'd like to move away from it, but I suspect we still use it on Android. If yes, please show the context where used.

**Comment by DenBond7** [comment]
1. Here we call this API after a user created a private key 
https://github.com/FlowCrypt/flowcrypt-android/blob/fc7c69c76f0458423ffe5bad04dd2b91c5891ea9/FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/PrivateKeysViewModel.kt#L431
2. ref https://github.com/FlowCrypt/flowcrypt-android/issues/773. We were going to use this API when a user adds a new private key from the settings.

**Comment by tomholub** [comment]
Are you using https://flowcrypt.com/attester/ or https://flowcrypt.attester.com ?

**Comment by DenBond7** [comment]
I use this one https://flowcrypt.com/attester/

https://github.com/FlowCrypt/flowcrypt-android/blob/9956c47ed3d3db2411c6ed5e9275683b21f66e35/FlowCrypt/build.gradle#L105

**Comment by DenBond7** [comment]
Got it. Will do.

**Comment by tomholub** [comment]
Also `attester/initial/welcome` should become `attester/welcome-message` and it should include `Bearer id_token` auth header (not enforced yet but will eventually enforce)

**Comment by tomholub** [comment]
for submitting public key on accounts that don't have id token, you can always use `submitPubkeyWithConditionalEmailVerification`

you may skip `welcome-message` calls on accounts that don't have an idToken

**Comment by DenBond7** [comment]
- [ ] attester/pub
- [ ] attester/welcome-message

**Comment by DenBond7** [comment]
@tomholub For `submitPrimaryEmailPubkey` I receive the following error 
`<-- 401 Unauthorized https://flowcrypt.com/attester/pub/...@gmail.com (154ms)`

```json
{
   "error":{
      "message":"Could not verify idToken JWT: JsonWebTokenError: jwt audience invalid. expected: 717284730244-5oejn54f10gnrektjdc4fv4rbic1bj1p.apps.googleusercontent.com or 717284730244-ostjo2fdtr3ka4q9td69tdr9acmmru2p.apps.googleusercontent.com or 679326713487-5r16ir2f57bpmuh2d6dal1bcm9m1ffqc.apps.googleusercontent.com"
   }
}
```

Is it Ok?

**Comment by tomholub** [comment]
>       "message":"Could not verify idToken JWT: JsonWebTokenError: jwt audience invalid. expected: 717284730244-5oejn54f10gnrektjdc4fv4rbic1bj1p.apps.googleusercontent.com or 717284730244-ostjo2fdtr3ka4q9td69tdr9acmmru2p.apps.googleusercontent.com or 679326713487-5r16ir2f57bpmuh2d6dal1bcm9m1ffqc.apps.googleusercontent.com"

What is the audience that it is sending?

**Comment by DenBond7** [comment]
@tomholub I've sent you `idToken` via email

**Comment by DenBond7** [comment]
just in case

```logs
OkHttpClient: --> POST https://flowcrypt.com/attester/pub/....@gmail.com
OkHttpClient: Content-Type: text/plain; charset=UTF-8
OkHttpClient: Content-Length: 767
OkHttpClient: Authorization: Bearer .......
OkHttpClient: api-version: 3
OkHttpClient: -----BEGIN PGP PUBLIC KEY BLOCK-----
........
OkHttpClient: -----END PGP PUBLIC KEY BLOCK-----
OkHttpClient: --> END POST (767-byte body)
OkHttpClient: <-- 401 Unauthorized https://flowcrypt.com/attester/pub/...@gmail.com (154ms)
OkHttpClient: Date: Wed, 12 Oct 2022 10:53:18 GMT
OkHttpClient: Content-Type: application/json
OkHttpClient: Transfer-Encoding: chunked
OkHttpClient: Connection: keep-alive
OkHttpClient: Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
OkHttpClient: {"error":{"message":"Could not verify idToken JWT: JsonWebTokenError: jwt audience invalid. expected: 717284730244-5oejn54f10gnrektjdc4fv4rbic1bj1p.apps.googleusercontent.com or 717284730244-ostjo2fdtr3ka4q9td69tdr9acmmru2p.apps.googleusercontent.com or 679326713487-5r16ir2f57bpmuh2d6dal1bcm9m1ffqc.apps.googleusercontent.com"}}
OkHttpClient: <-- END HTTP (329-byte body)
```

**Comment by tomholub** [comment]
Fyi jwt.io website can be used to parse these.

Indeed I was missing the Android audience on flowcrypt-attester-ts. I've updated it and I'm re-deploying, it should start working in 10-15 minutes.

**Comment by DenBond7** [comment]
Now it works well
`OkHttpClient: Public key successfully replaced`

**Comment by DenBond7** [comment]
> Also attester/initial/welcome should become attester/welcome-message and it should include Bearer id_token auth header (not enforced yet but will eventually enforce)

@tomholub Btw, we use `https://flowcrypt.com/attester/test/welcome`, not `attester/initial/welcome`

**Comment by tomholub** [comment]
Yes, that was my typo

**Comment by DenBond7** [comment]
Got it

**Comment by DenBond7** [comment]
@tomholub Please look at #767 and #768. It seems this functionality was broken. Is relevant nowadays? These issues relate to the current issue as they use `attester/initial/legacy_submit`

**Comment by tomholub** [comment]
it broke recently. it was the last endpoint still served by legacy server, which i shut down and removed. only later i realised android is still using it, but luckily ignoring errors. 

it does work ok using new api?

**Comment by tomholub** [comment]
have we ever implemented use of ldap-relay endpoint on android? i suppose not. that would probably mean that enterprise test will remain broken for now. i believe, this very moment, they are not using that feature on android. i'll double check

**Comment by DenBond7** [comment]
> it does work ok using new api?

It seems it was broken after some code changes or migration to new approaches. It doesn't relate to your changes. But it seems we don't receive any feedback so it's not a big problem.

Just to notify you that we don't update a pub key when a user imports a private key from anyway (setup or from the settings).

> ldap-relay endpoint on android?

not sure about that. All endpoints ->

https://github.com/FlowCrypt/flowcrypt-android/blob/a9701100e6b63fe53590be484ce5546c9e472908/FlowCrypt/src/main/java/com/flowcrypt/email/api/retrofit/ApiService.kt

**Comment by DenBond7** [comment]
Anyway, it would be simpler to cover updating a public key during the import of a private key in a separate issue. + tests

**Comment by DenBond7** [comment]
> https://github.com/FlowCrypt/flowcrypt-android/issues/767 you may fix by using the new endpoints. Can be a separate issue, as you say.

Got it. I will create a new issue for that
