### ISSUE TITLE
Unable to connect to Gmail

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-android#1985]
Description: 
I experienced a problem when connecting my Gmail account to the FlowCrypt app. I don't have any clue to share at the moment since I'm using stock settings on my regular android phone. Furthermore, some users are unable to get their email or connect to the server which may be related to this.

Also, emails are stuck in outboxes while having a strong internet connection. I noticed it only a couple of days ago.

<img width="335" alt="Screen Shot 2022-09-26 at 6 43 27 PM" src="https://user-images.githubusercontent.com/46025304/192258235-71eb369f-ed58-4a22-bbae-f06cccfbe404.png">

To reproduce the issue (based on my experience), Login to FlowCrypt app with your Gmail account -> wait for IMAP settings check -> app will then check the SMTP settings -> Will throw the following network error above.

References: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqQcvfgNBqsCVwStQHqkpKvGzr
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqQcsLgNBXMccrvKPDPkjQFdNw
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqQcrDGwSdwNwkgLTMxVGpZmpn
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqQcvdslPVBvqJHshdDHWFHjnK
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqQmNdZZCPtVKlXlXfvVjpRdnD
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqQmPlpVbSCWHrklWXQGJfCrJL
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqQvrwsQLBqWPDfdFQhKRknmxJ

**Comment by martgil** [comment]
@DenBond7 not urgent sir, but I think it is important to check since users are somehow unable to use the app properly. Thank you!

**Comment by DenBond7** [comment]
Hi @martgil. I've added some changes to the code. Please try to compile a debug version and test it.

Use this branch https://github.com/FlowCrypt/flowcrypt-android/tree/issue_1985_gmail_smtp_connection_issue

**Comment by martgil** [comment]
Hello sir, @DenBond7 - I can log in using the branch [issue_1985_gmail_smtp_connection_issue](https://github.com/FlowCrypt/flowcrypt-android/tree/issue_1985_gmail_smtp_connection_issue). The login process is very smooth this time.

![image](https://user-images.githubusercontent.com/46025304/194006510-825bb8a5-9a28-4928-9e41-e728bea96bf0.png)

**Comment by DenBond7** [comment]
@martgil by the way, please test the sending process(just in case)

**Comment by martgil** [comment]
@DenBond7 Yes, sir. I have tested the sending process and the email is no longer stuck in my outbox.

**Comment by martgil** [comment]
Android users has been informed about this patch (1.3.8) - https://mail.google.com/mail/u/human@flowcrypt.com/#sent/QgrcJHsNjpkhrFlZkrVpSTrzWxDFTHsgpbB

**Comment by martgil** [comment]
Thank you, sir, @DenBond7 for the hint.
