### ISSUE TITLE
drop `uuid`, use id_token

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#1990]
Also should drop `uuid` mechanism from iOS and Android, and use id_token there too.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-browser/issues/4686#issuecomment-1262505327_

**Comment by tomholub** [comment]
This will clean up the code too, since it's simpler.

**Comment by tomholub** [comment]
@ioanmo226 I just realized that Den is working on the same issue soon - therefore you can discuss this together as needed.

browser-extension link https://github.com/FlowCrypt/flowcrypt-browser/issues/4686

**Comment by DenBond7** [comment]
@tomholub Can we move it to the next milestone? To make a new release faster.

**Comment by tomholub** [comment]
ok

**Comment by DenBond7** [comment]
- [ ] Remove `uuid` from `accounts` table

**Comment by DenBond7** [comment]
@ioanmo226 @tomholub I have a question. We use `uuid` for the following

1. https://flowcrypt.com/api/account/get

https://github.com/FlowCrypt/flowcrypt-android/blob/de725b28c04847cd972dc2f22236fde1516ec76a/FlowCrypt/src/main/java/com/flowcrypt/email/api/retrofit/ApiService.kt#L124

2. https://flowcrypt.com/api/account/login where we use `LoginModel` too.

https://github.com/FlowCrypt/flowcrypt-android/blob/de725b28c04847cd972dc2f22236fde1516ec76a/FlowCrypt/src/main/java/com/flowcrypt/email/api/retrofit/ApiService.kt#L133

https://github.com/FlowCrypt/flowcrypt-android/blob/de725b28c04847cd972dc2f22236fde1516ec76a/FlowCrypt/src/main/java/com/flowcrypt/email/api/retrofit/request/model/LoginModel.kt#L18

I need to know how `account/get` and `account/login` look after dropping `uuid`(request and response, maybe `curl`). For example, before dropping `account/get` looked like this one

```log
I: --> POST https://flowcrypt.com/api/account/get
I: Content-Type: application/json; charset=UTF-8
I: Content-Length: 31
I: api-version: 3
I: {"account":"den@flowcrypt.com","uuid":"XXXXXX"}
I: --> END POST (31-byte body)
```

or `curl`
```ccurl
curl --location --request POST 'https://flowcrypt.com/api/account/get' \
--header 'api-version: 3' \
--header 'Content-Type: application/json' \
--data-raw '{"account":"den@flowcrypt.com","uuid":"XXXXXX"}'
```

I've tried to read sources from backend but it was not success :(

**Comment by DenBond7** [comment]
@martgil Just in case I ping you too

**Comment by DenBond7** [comment]
Just adding `Authorization: Bearer XXXXX...XXXX` does not make a server happy.

```log
I: --> POST https://flowcrypt.com/api/account/get
I: Content-Type: application/json; charset=UTF-8
I: Content-Length: 31
I: Authorization: Bearer XXXXX...XXXX
I: api-version: 3
I: {"account":"den@flowcrypt.com"}
I: --> END POST (31-byte body)
D: tagSocket(124) with statsTag=0xffffffff, statsUid=-1
I: <-- 400 Bad Request https://flowcrypt.com/api/account/get (182ms)
I: Date: Fri, 28 Oct 2022 11:01:15 GMT
I: Content-Type: application/json
I: Content-Length: 115
I: Connection: keep-alive
I: Access-Control-Allow-Origin: *
I: Access-Control-Allow-Headers: Authorization, Content-Type, api-version, user-account, user-uuid, user-token
I: Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
I: {"error": {"code": 400, "message": "Something wrong happened.", "internal": "api input: unexpected keys: account"}}
I: <-- END HTTP (115-byte body)
```

**Comment by martgil** [comment]
Hello sir, Den. Could you please try adding an empty json body and see if
that works?

**Comment by ioanmo226** [comment]
Here's curl request.
I think you shouldn't add `account` param(the line right after `api-version`).

`
{"account":"den@flowcrypt.com"}
`

```sh
curl 'https://flowcrypt.com/api/account/get' \
  -H 'Accept: application/json, text/javascript, */*; q=0.01' \
  -H 'Accept-Language: en-US,en;q=0.9,de;q=0.8,ko;q=0.7,zh-CN;q=0.6,zh;q=0.5' \
  -H 'Authorization: Bearer XXX' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json; charset=UTF-8' \
  -H 'Origin: chrome-extension://mkefadjohdmonnjbidopnmjlepdomjmi' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: none' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36' \
  -H 'api-version: 3' \
  -H 'sec-ch-ua: "Google Chrome";v="107", "Chromium";v="107", "Not=A?Brand";v="24"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  --data-raw '{}' \
  --compressed
```

**Comment by DenBond7** [comment]
@martgil @ioanmo226 Thanks! 

> empty json body

It works well

**Comment by DenBond7** [comment]
@martgil @ioanmo226 

```log
I: --> POST https://flowcrypt.com/api/account/login
I: Content-Type: application/json; charset=UTF-8
I: Content-Length: 2
I: Authorization: Bearer XXX...XXX
I: api-version: 3
I: {}
I: --> END POST (2-byte body)
I: <-- 400 Bad Request https://flowcrypt.com/api/account/login (204ms)
I: Date: Fri, 28 Oct 2022 16:19:14 GMT
I: Content-Type: application/json
I: Content-Length: 111
I: Connection: keep-alive
I: Access-Control-Allow-Origin: *
I: Access-Control-Allow-Headers: Authorization, Content-Type, api-version, user-account, user-uuid, user-token
I: Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
I: {"error": {"code": 400, "message": "Something wrong happened.", "internal": "api input: missing key: account"}}
I: <-- END HTTP (111-byte body)
```

Have I missed something?

**Comment by ioanmo226** [comment]
Still checking. 👀  But not sure yet.

**Comment by ioanmo226** [comment]
Did you try with curl?

**Comment by martgil** [comment]
Hello @DenBond7, I just realized that my reply wasn't actually sent. For the endpoint `/api/account/login` it still accepts uuid and account JSON parameters, all other authenticated pages accept JWT authentication.

**Comment by DenBond7** [comment]
> Did you try with curl?

@ioanmo226 No, I didn't. I use curl just to transform requests to [retrofit](https://square.github.io/retrofit/) implementation.

**Comment by DenBond7** [comment]
@tomholub Ping you just in case. I'm not sure who is responsible for the backend.

We don't sure that `/api/account/login` was migrated to `id_token` usage.

**Comment by tomholub** [comment]
no need to use /login anymore. 

login now happens automatically on other endpoints when id token is used
