### ISSUE TITLE
create models for common APIs

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#20]
The app will need to use two APIs: `api.cryptup.io` (called `Api`) and `attester.cryptup.io` (called `Attester`)

#### Common stuff
You should probably extend both from a common abstract class, because some of the behavior is the same in both.
Please send a header `api-version: 3` with each request to any of the two endpoints. Make the number "3" static parameter in the class, we may want to upgrade to a higher version of the apis sometime in the future.
The v3 apis return a unified error format, like this:
```json
{
  "error": {
    "code": 500,
    "message": "Error message that you can display publicly",
    "internal": "message for internal purposes or null"
  }
}
```

#### Useful Attester calls
```
* POST /test/welcome 			# Send a welcome test email
 * POST /initial/request 			# Request initial pubkey attest
 * POST /initial/confirm 			# Confirm initial pubkey validation
 * POST /lookup/email 			# Find a pubkey for email address
 * POST /replace/request 			# Request a pubkey replacement
 * POST /replace/confirm 			# Confirm a pubkey replacement
```

#### Useful Api calls
```
 * POST /link/message 			# Get URL of message data based on short
 * POST /account/subscribe 			# Subscribe to a premium account
 * POST /account/login 			# Log in or Register a new account
 * POST /message/confirm_files 			# Confirm submission of files to s3
 * POST /message/upload 			# Store a message if it cannot be sent through email provider
 * POST /message/token 			# Get a token that recipients can use to reply on the web
 * POST /message/presign_files 			# Get pre-signed approvals to POST attachments onto s3 bucket
 * POST /help/uninstall 			# User just uninstalled a client app
 * POST /help/feedback 			# Send feedback to devs
```

#### Details

Full spec on both is here:

https://github.com/tomholub/cryptup-android-prototype/wiki/attester.cryptup.io
https://github.com/tomholub/cryptup-android-prototype/wiki/api.cryptup.io

You don't really have to test them all because you may not know what exactly is it supposed to do anyway, but it probably makes sense to prepare the models and corresponding methods, and what type of values go into each call, etc.

You can also get inspired here: https://github.com/tomholub/cryptup-android-prototype/blob/master/FlowCrypt/src/main/assets/js/tool.js#L3243 to see examples of something similar in JavaScript.

**Comment by DenBond7** [comment]
![2017-07-11_16-48-56](https://user-images.githubusercontent.com/2863246/28071674-4987d48e-6659-11e7-8ae3-0ee1d0701014.png)

**Comment by DenBond7** [comment]
Attester calls

- [ ] POST /test/welcome 			# Send a welcome test email
- [ ] POST /initial/request 			# Request initial pubkey attest
- [ ] POST /initial/confirm 			# Confirm initial pubkey validation
- [ ] POST /lookup/email 			# Find a pubkey for email address
- [ ] POST /replace/request 			# Request a pubkey replacement
- [ ] POST /replace/confirm 			# Confirm a pubkey replacement

Api calls

- [ ] POST /link/message 			# Get URL of message data based on short
- [ ] POST /account/subscribe 		# Subscribe to a premium account
- [ ] POST /account/login 			# Log in or Register a new account
- [ ] POST /message/confirm_files 	# Confirm submission of files to s3
- [ ] POST /message/upload 			# Store a message if it cannot be sent through email provider
- [ ] POST /message/token 			# Get a token that recipients can use to reply on the web
- [ ] POST /message/presign_files 		# Get pre-signed approvals to POST attachments onto s3 bucket
- [ ] POST /help/uninstall 			# User just uninstalled a client app
- [ ] POST /help/feedback 			# Send feedback to devs

**Comment by tomholub** [comment]
You will be getting the results in the desired format when you add a header: `api-version: 3`

```
curl -X POST \
  https://attester.cryptup.io/lookup/email \
  -H 'api-version: 3' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'postman-token: 4085d702-a55b-7f86-9356-aff1753f0d60' \
  -d '{
    "email": null
}'
```
Will give you:
```{
    "error": {
        "message": "Something wrong happened.",
        "code": 400,
        "internal": "value(None) for key(email) does not fit definition: [<type 'str'>, <type 'list'>]"
    }
}```

I'm separating `message` from `internal` because message is language dependent, while internal is internal code for that message, or sometimes a very technical error that is already logged elsewhere (this example).

Sometimes `internal` will contain a very specific keyword, for example `auth`, which API will return that on bad authentication, and it's a result that we'll have to test for in Java and resolve it internally. I'll explain in detail later.

**Comment by DenBond7** [comment]
**"subscription" (<type 'dict'>)  # subscription status**

Can you provide JSON example? I want to know how I must reproduce this structure in the Java code.
<type 'dict'> - is this Java Map object?

**Comment by DenBond7** [comment]
@tomholub 

> You will be getting the results in the desired format when you add a header: api-version: 3

I added header: api-version: 3 and all ok. It's my mistake.

**Comment by DenBond7** [comment]
**(auth required)** what does it mean? What kind of type of auth will be used here?

**Comment by tomholub** [comment]
> <type 'dict'> - is this Java Map object?

This just means a json object. It's correct to ask what's inside the object, it's not clear from the docs.

> Can you provide JSON example? I want to know how I must reproduce this structure in the Java code. It's something like this for a `subscription` object:
```
{
  'level': account['subscription_level'], (string eg "pro" or NULL)
  'expire': account['subscription_expire'], (datetime formatted as a string, eg "2020-20-20 16:50" - expiration of subscription, or NULL)
  'method': account['subscription_method'], (payment method string: "trial" or "stripe", or NULL)
  'expired': false, (true or false - subscription expired, or NULL)
}
```

**Comment by tomholub** [comment]
Auth - I will have to produce proper spec for this. It will involve `/account/login` to retrieve login credentials, which are two things: typically email address and uuid.

I will document the whole process shortly.

**Comment by DenBond7** [comment]
> I will document the whole process shortly.

Ok. I prepared the general logic for API calls. At the moment I added simple variants, which include primitive types and not required the auth.

Now I will wait while you will document the whole process and then I will resume work on this task.

**Comment by tomholub** [comment]
closing this until needed in the future
