### ISSUE TITLE
SSL Communication issues

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#200]
Examples of SSL communication issues

**Comment by DenBond7** [comment]
#190 
#195

**Comment by Bajranghudda** [comment]
@DenBond7 any update on this?
I am getting this issue sometimes, I guess it's because of slow internet connection. Any suggestions about what we can do for this?
I am using retrofit:2.7.0

**Comment by DenBond7** [comment]
@Bajranghudda 
>  I guess it's because of slow internet connection.

Yes, you are right. 

> Any suggestions about what we can do for this?

As described [here](https://github.com/square/retrofit/issues/2388) you just need to handle IOException. For example, you can show [Snackbar](https://developer.android.com/reference/android/support/design/widget/Snackbar) with button `Try again`.
