### ISSUE TITLE
Fix SemaphoreCI test

### ISSUE THREAD

**Issue by ioanmo226** [FlowCrypt/flowcrypt-android#2013]
Tests fail randomly in semaphoreci and need to retry several times to succeed.
ex: https://flowcrypt.semaphoreci.com/workflows/6615e732-8aca-4075-806f-4aabf4c97ca1?pipeline_id=a7306829-f9b6-45c4-a47c-b572a36f25df 

Need to investigate and fix.

**Comment by DenBond7** [comment]
I've temporarily excluded flaky tests. They will be fixed in a separate issue.
