### ISSUE TITLE
[Question] How to update private key directly on Android app

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-android#2018]
Hello @DenBond7,

Sorry for the question. I can't recall if I already asked this question before.

I'm trying to find a way to update my private key directly on the app by importing an updated key but it doesn't work. Can you please enlighten me on whether it is supported on the current version or not?

Thank you,
Mart

**Comment by DenBond7** [comment]
Hi @martgil. The Android app doesn't support updating existing private keys manually. You need to delete the existing key and import a new version manually. If there is only one private key you need to make a temp private key via other PGP tools (`GnuPG` and etc.), import a created key, delete a key that you are going to update, import an updated version of a deleted key, delete the temp key.

**Comment by DenBond7** [comment]
Btw, we already have an issue https://github.com/FlowCrypt/flowcrypt-android/issues/1287

**Comment by martgil** [comment]
Thank you, sir, Den! 

> You need to delete the existing key and import a new version manually. If there is only one private key you need to make a temp private key via other PGP tools (GnuPG and etc.), import a created key, delete a key that you are going to update, import an updated version of a deleted key, delete the temp key.

That's a pretty neat trick you have there. Then after the update key is loaded, the user can go to `Backup` and save the a copy of private key inside of user's inbox.

> Btw, we already have an issue https://github.com/FlowCrypt/flowcrypt-android/issues/1287

Got it, sir. I'll close this one now. Thank you very much!
