### ISSUE TITLE
Message is not quite readable in dark mode 

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-android#2026]
Description:
The FlowCrypt ios app's font text doesn't have a better color making it hard for users to read messages. In my opinion, we may also consider adjusting the email subject's font color and the message body's background. 

<img width="342" alt="image" src="https://user-images.githubusercontent.com/46025304/196848662-2c1a0782-e99d-49ff-9e69-55f827085089.png">

Reference: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRGTBWzpLShslTZsQgjPTvgrM

**Comment by martgil** [comment]
Users to notify (for me):

https://mail.google.com/mail/u/human@flowcrypt.com/#archive/FMfcgzGqRPvFVNqVfCtwmXlkdCWvVsPC
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRPvFVLXdWNMGjFjbtMFGtNfk

**Comment by DenBond7** [comment]
ref https://issuetracker.google.com/issues/243570060

**Comment by DenBond7** [comment]
I'm still in a progress. But have some thoughts.

For now, as a quick fix, I can propose the following
### Night
![image](https://user-images.githubusercontent.com/2863246/201725265-7fc4f6df-9490-4430-8277-18452c655769.png)
### Day
![image](https://user-images.githubusercontent.com/2863246/201725374-30e4ef66-b0bf-459e-8a89-ed23e53f907a.png)

Not perfect, but is much better than we have before.

**Comment by DenBond7** [comment]
But in another hand, we will still have bad UI for the night mode. There is a problem with the repeatable background image. It would be nice to resolve this issue on the HTML side.

Currently, the app produces the following HTML
```html
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width"/>
    <style>
                body { word-wrap: break-word; word-break: break-word; hyphens: auto; margin-left: 0px; padding-left: 0px; }
                body img { display: inline !important; height: auto !important; max-width: 95% !important; }
                body pre { white-space: pre-wrap !important; }
                body > div.MsgBlock > table { zoom: 75% } /* table layouts tend to overflow - eg emails from fb */

    </style>
</head>
<body>
<div class="MsgBlock GREEN"
     style="
     padding-left: 8px;
     min-height: 50px;
     padding-top: 4px;
     padding-bottom: 4px;
     width: 100%;
     border: 1px solid #f0f0f0;
     border-left: 8px solid #31A217;
     border-right: none;
     background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFoAAABaCAMAAAAPdrEwAAAAh1BMVEXw8PD////w8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PD7MuHIAAAALXRSTlMAAAECBAcICw4QEhUZIyYqMTtGTV5kdn2Ii5mfoKOqrbG0uL6/xcnM0NTX2t1l7cN4AAAB0UlEQVR4Ae3Y3Y4SQRCG4bdHweFHRBTBH1FRFLXv//qsA8kmvbMdXhh2Q0KfknpSCQc130c67s22+e9+v/+d84fxkSPH0m/+5P9vN7vRV0vPfx7or1NB23e99KAHuoXOOc6moQsBwNN1Q9g4Wdh1uq3MA7Qn0+2ylAt7WbWpyT+Wo8roKH6v2QhZ2ghZ2ghZ2ghZ2ghZ2ghZ2ghZ2ghZ2ghZ2ghZ2ghZ2ghZ2ghZ2gjZ2AUNOLmwgQdogEJ2dnF3UJdU3WjqO/u96aYtVd/7jqvIyu76G5se6GaY7tNNcy5d7se7eWVnDz87fMkuVuS8epF6f9NPObPY5re9y4N1/vya9Gr3se2bfvl9M0mkyZdv077p+a/3z4Meby5Br4NWiV51BaiUqfLro9I3WiR61RVcffwfXI7u5zZ20EOA82Uu8x3SlrSwXQuBSvSqK0AletUVoBK96gpIwlZy0MJWctDCVnLQwlZy0MJWctDCVnLQwlZy0MJWctDCVnLQwlZy0MJWctDCVnLQwlZy0MJWckIletUVIJJxITN6wtZd2EI+0NquyIJOnUpFVvRpcwmV6FVXgEr0qitAJXrVFaASveoKUIledQWoRK+6AlSiV13BP+/VVbky7Xq1AAAAAElFTkSuQmCC);">
    <html>
    <head></head>
    <body>It's now easier than ever to make the switch from iPhone to Android. Transfer your
    contacts, messages, photos and favorite apps. Just connect, select and go.<br><br>It's now
    easier than ever to make the switch from iPhone to Android. Transfer your contacts, messages,
    photos and favorite apps. Just connect, select and go.<br><br>It's now easier than ever to make
    the switch from iPhone to Android. Transfer your contacts, messages, photos and favorite apps.
    Just connect, select and go.<br><br>It's now easier than ever to make the switch from iPhone to
    Android. Transfer your contacts, messages, photos and favorite apps. Just connect, select and
    go.<br><br>It's now easier than ever to make the switch from iPhone to Android. Transfer your
    contacts, messages, photos and favorite apps. Just connect, select and go.
    </body>
    </html>
</div><!-- next MsgBlock -->
</body>
</html>
```

We need to modify `background-image: url( ` somehow to be able to use `night` and `day` version of the background.
Maybe we can use `SVG` there. And after generation, I can replace the fill color. Something like this one [SVG as background image inlined in style attribute](https://stackoverflow.com/questions/55824731/svg-as-background-image-inlined-in-style-attribute)

I think it will be for a separate issue.

**Comment by DenBond7** [comment]
@martgil Just in a case while I remember. If you will receive any feedback from users about issues with dark UI, first of all, please ask them to update [Android System WebView](https://play.google.com/store/apps/details?id=com.google.android.webview&hl=en&gl=US).

**Comment by DenBond7** [comment]
ref https://stackoverflow.com/questions/57449900/letting-webview-on-android-work-with-prefers-color-scheme-dark

**Comment by martgil** [comment]
> @martgil Just in a case while I remember. If you will receive any feedback from users about issues with dark UI, first of all, please ask them to update [Android System WebView](https://play.google.com/store/apps/details?id=com.google.android.webview&hl=en&gl=US).

Got it, sir - Thank you!
