### ISSUE TITLE
Entering a password when creating a release apk during build time

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#204]
> is there a way to submit the passwords elsewhere? I don't want to have them in a plain file. I want to enter during build time

**Comment by DenBond7** [comment]
Here is a good example
https://gyulajuhasz.com/blog/dynamic-password-input-with-gradle/
https://www.timroes.de/2014/01/19/using-password-prompts-with-gradle-build-files/

But it's not working with a new gradle version

**Comment by DenBond7** [comment]
https://github.com/gradle/gradle/issues/1251

**Comment by DenBond7** [comment]
https://issues.gradle.org/browse/GRADLE-2357

**Comment by tomholub** [comment]
Is there a workaround for that? Eg use a command line prompt instead of ui prompt?

**Comment by DenBond7** [comment]
> Is there a workaround for that? Eg use a command line prompt instead of ui prompt?

I have added implementation where a command line and keystore.properties are working. UI is not working yet.

**Comment by DenBond7** [comment]
The working command is "gradlew clean assembleProductionRelease -PruntimeSetup --no-daemon"
