### ISSUE TITLE
Consideration in applying for Google Advanced Protection

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-android#2041]
A user suggests that we can consider submitting our app to Google Advanced Protection Program whitelist for enrolled users.

We can use the following form below to apply and submit our app:
https://docs.google.com/forms/d/1FWZf2xcRPms04XIImRD6f65U0YeQTZRILaFIGWxaOOM/viewform?edit_requested=true

Reference: 
https://support.google.com/accounts/answer/9764949
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRGgWkRrHHbxqLhdtJjGDXbKj

**Comment by martgil** [comment]
@tomholub just sharing it with you. Thanks!

**Comment by tomholub** [comment]
Same issue as https://github.com/FlowCrypt/flowcrypt-browser/issues/1325 , not this year or the next.

**Comment by tomholub** [comment]
Unless there is a larger customer who requires it. That would allow us to give it closer consideration. For now, we are busy with requests of paying customers.

It appears the cost of audits for this could run 80-100 thousand USD. Hard to justify for the few individual users who requested it so far.

**Comment by tomholub** [comment]
Unless I'm mistaken and this won't require a security audit? I may be remembering wrongly.
