### ISSUE TITLE
initial app loading (after auth) getting stuck

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#208]
![image](https://user-images.githubusercontent.com/6306961/36080667-1159b518-0fce-11e8-85be-84f0f3d71dd6.png)

> So how exactly is this supposed to work. I've installed this on couple of my android devices. Once I start it up I select  "continue with gmail" select my account, approve the permissions, then it just sits on this screen. If I put the app in the background it all starts over.

> Update I got it work for w7rtf.sgb@gmail.com (which I never use and doesn't have any emails archived) as well as sbjarna@wgu.edu which is using 0.02 GB of space. However this account is using 16.31 GB of space for archived emails and that seems to be hanging the app.

My response:

> It is just checking for backups, it's supposed to be a fast operation on standard speed functional internet. Size of the mailbox should not matter. If it takes this long, that suggests that something indeed went wrong.
> We'll look into it!

**Comment by DenBond7** [comment]
> It is just checking for backups, it's supposed to be a fast operation on standard speed functional internet. 

If an account has a lot of labels it can take some time and it's not always fast (because we need open a folder, search messages and close the folder). Try to test flowcrypt.compatibility.

I have changed code and I think it will help as.

**Comment by tomholub** [comment]
When using Gmail API, you don't have to go label by label. On Desktop it's a single api call to search a list of emails, then one call per found email to retrieve backups - very fast.

**Comment by DenBond7** [comment]
> using Gmail API

A good idea. I didn't think about that. Ok, I will try to use Gmail API for Gmail accounts.

**Comment by tomholub** [comment]
You can reuse the Gmail search string function from Js class. It's well
tested.

**Comment by tomholub** [comment]
ref https://mail.google.com/mail/u/0/#inbox/16174bd12d1933d7

**Comment by DenBond7** [comment]
I have added Gmail API for this case. Now that's really fast :)

**Comment by tomholub** [comment]
That will be better. It's a pity that we will have to use a different code path for Google a lot of times, but if it improves UX, why not.
