### ISSUE TITLE
show progress bar when checking backups on non-gmail accounts

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#209]
followup from #208

If user has many imap folders, it may still take a long time - showing a progress bar when using the IMAP to search folder by folder is appropriate.

**Comment by DenBond7** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/2863246/88289677-46372500-ccfe-11ea-9f31-83eed72b0638.gif)

**Comment by tomholub** [comment]
Excellent! Please say "Searching for backups in folder x/y"
