### ISSUE TITLE
version 1.3.9(enterprise 2022-01-15)

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#2094]
- [x] write customer
- [x] build release
- [x] release consumer 20%
- [ ] release enterprise in 2 weeks

**Comment by DenBond7** [comment]
@tomholub What do you think about making a new release? We already have some fixes and can make a new release. The last one was in November.

**Comment by DenBond7** [comment]
@ioanmo226 Please look at the opened PRs. They block making a new release.

**Comment by tomholub** [comment]
i could release around 30th dec

**Comment by DenBond7** [comment]
I'm closing it due to #2145
