### ISSUE TITLE
Documentation of OAuth client ID

### ISSUE THREAD

**Issue by chriselsen** [FlowCrypt/flowcrypt-android#2108]
When using FlowCrypt Android with Google Workspaces, it should be made simpler to improve security of the necessary IMAP access to Gmail by making the OAuth client ID better accessible. 

Google Workspace can restrict client access to IMAP via the OAuth client ID. See the [Google Workspaces documentation](https://apps.google.com/supportwidget/articlehome?hl=en&article_url=https%3A%2F%2Fsupport.google.com%2Fa%2Fanswer%2F105694%3Fhl%3Den&assistant_id=generic-unu&product_context=105694&product_name=UnuFlow&trigger_context=a) for details.

Unfortunately neither the [FlowCrypt documentation page](https://flowcrypt.com/docs/), nor the Android client itself show the necessary OAuth client ID anywhere. One has to dig through the [source code](https://github.com/FlowCrypt/flowcrypt-android/search?q=374364070962-n83b6asllhfkhij6slijr61576lqqi3v) to find it. 

Here is a sample screenshot for the desired configuration in Google Workspaces.
![image](https://user-images.githubusercontent.com/5304256/208768400-7a027207-b096-465e-b299-a05fb3d0cda3.png)
(I replaced my domain name with 'flowcrypt.com'. So you could use it for your documentation.)

**Comment by DenBond7** [comment]
ref #1457 

> Unfortunately neither the [FlowCrypt documentation page](https://flowcrypt.com/docs/), nor the Android client itself show the necessary OAuth client ID anywhere. One has to dig through the [source code](https://github.com/FlowCrypt/flowcrypt-android/search?q=374364070962-n83b6asllhfkhij6slijr61576lqqi3v) to find it.

As for me, it will be better to have such info on [FlowCrypt documentation page](https://flowcrypt.com/docs/). 99% of regular Android users will not use such info. In most cases, administrators will use it. So the web portal will be a good place. I will create an issue in a fit repo.

**Comment by DenBond7** [comment]
I'm closing it for now. Will be discussed internally at https://github.com/FlowCrypt/flowcrypt-web/issues/725.

@chriselsen Thank you for the help!
