### ISSUE TITLE
Fix handling 'multipart/alternative'

### ISSUE THREAD

**Issue by chriselsen** [FlowCrypt/flowcrypt-android#2109]
FlowCrypt Android is not able to decrypt a message from e.g. OpenKeychain that is missing the "Version" string within the PGP encrypted message. 
The FlowCrypt browser plugin can decrypt that same message just fine.

FlowCrypt Android can decrypt:

```
-----BEGIN PGP MESSAGE-----
Version: xyz

...
-----END PGP MESSAGE-----
```

FlowCrypt Android cannot decrypt:

```
-----BEGIN PGP MESSAGE-----

...
-----END PGP MESSAGE-----
```

**Comment by DenBond7** [comment]
Hello @chriselsen. Thank you for the report. it can be a compatibility issue(I'm not sure about `missing the "Version" string`). 

Could you send an example to den@flowcrypt.com([pub key](https://flowcrypt.com/attester/pub/den@flowcrypt.com))?

**Comment by DenBond7** [comment]
Hello @chriselsen. Thank you for the example. Now I understand what is wrong.

Please let me guess how you created such an example.

1. Open `OpenKeychain`
2. Encrypt some text
3. Copy encrypted text
4. Paste encrypted text to any email clients in a compose screen.
5. Also an email client adds a signature like `Den at FlowCrypt`. For example,

```
-----BEGIN PGP MESSAGE-----
Version: xyz

...
-----END PGP MESSAGE-----

--
Regards,
Den at FlowCrypt
```

6. Send such a message.

Am I right?

**Comment by chriselsen** [comment]
Yes, pretty much. :-) Except that I used "Share With" instead of the copy & paste. But the result is about the same.

**Comment by DenBond7** [comment]
@chriselsen This and #2112 were fixed. I hope a new version of the app will be available in 2 weeks or less for all users(we start rolling out with 20%).
