### ISSUE TITLE
Updating PGPainless to 1.4.0 and PGPainless.getPolicy().setEnableKeyParameterValidation(true)

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#2111]
ref #1669 

from `PGPainless 1.4.0` by default `enableKeyParameterValidation == false`. Without `PGPainless.getPolicy().setEnableKeyParameterValidation(true)` our test `PgpKeyTest.testReadCorruptedPrivateKey()` can not pass.

https://github.com/FlowCrypt/flowcrypt-android/blob/cc822a6703136428c15aa6ee54652ef405a536fa/FlowCrypt/src/test/java/com/flowcrypt/email/security/pgp/PgpKeyTest.kt#L123

@tomholub Should I enable this option by default? Or just need to fix a test?

 For example

```kotlin
@Test
  fun testReadCorruptedPrivateKey() {
    try {
      PGPainless.getPolicy().isEnableKeyParameterValidation = true
      val encryptedKeyText = loadResourceAsString("keys/issue-1669-corrupted.private.gpg-key")
      val passphrase = Passphrase.fromPassword("123")
      assertThrows(KeyIntegrityException::class.java) {
        PgpKey.checkSecretKeyIntegrity(encryptedKeyText, passphrase)
      }
    } finally {
      PGPainless.getPolicy().isEnableKeyParameterValidation = false
    }
  }
```

P.S. From the Paul's message

>I decided to disable automatic checks for attacks described in the 
KOpenPGP paper[1].
The reason for this is that those tests are very expensive (especially 
the checks for DSA and ElGamal key parameters are very costly, and for 
all keys there is an additional encryption/signing operation made), and 
the attack vector and threat model is somewhat limited.
[1]: https://www.kopenpgp.com/

**Comment by tomholub** [comment]
therefore please enable it
