### ISSUE TITLE
Hierarchy of Gmail labels not correctly displayed. 

### ISSUE THREAD

**Issue by chriselsen** [FlowCrypt/flowcrypt-android#2112]
Gmail supports hierarchies of E-Mail labels such as:

```
Travel
 | - EMEA
 |    | - Paris
 |    | - London
 | - APAC
 |    | - Auckland         
```
In the Gmail Android app this is displayed as:
```
Travel
Travel / EMEA
Travel / EMEA / Paris
Travel / EMEA / London
Travel / APAC
Travel / APAC / Auckland         
```
In Flowcrypt instead it is displayed as:
```
Travel
EMEA
Paris
London
APAC
Auckland         
```
You therefore completely loose the understanding of the hierarchy of these label. 
And especially if a label with the same name exists at different places in the hierarchy it becomes very confusing.

**Comment by DenBond7** [comment]
Hello Christian. Thank you for more details about the current issue. We already have a duplicate issue #2020. But I left this one as it has more details.

FlowCrypt for Android supports any email provider as it can work via [IMAP](https://en.wikipedia.org/wiki/Internet_Message_Access_Protocol) protocol. But only Gmail has `labels` support. We will try to add support for Gmail `labels` in the upcoming releases. But unfortunately, I can't say that it will be soon.

**Comment by chriselsen** [comment]
A few clarifications:

I think that issue #2020 was asking for managing the labels, which to me means creating new and deleting old labels. While it would be great if the FlowCrypt Android client could do that, I can also switch over to the Gmail app for that. 

The Gmail labels should translate directly into IMAP folders. And as such you would face the same issue with other IMAP based providers: A user there can create the same hierarchy with IMAP folders, but would only see the name of the final leaf, but not the branch it's hanging off from.

**Comment by DenBond7** [comment]
### Gmail
![image](https://user-images.githubusercontent.com/2863246/209679367-85919cb5-da3d-44ad-9609-2461f68ac291.png)


### FlowCrypt
![image](https://user-images.githubusercontent.com/2863246/209679322-bf744678-0b16-47e5-841b-c491a721eebe.png)
