### ISSUE TITLE
all differences between enterprise and consumer build

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#2123]
please make a list of all behavior differences currently between enterprise and consumer app

**Comment by DenBond7** [comment]
| Item | Consumer | Eneterprise|
| :--- | :--- | :--- |
| package | `com.flowcrypt.email` | `com.flowcrypt.email.enterprise` |
| GMail API Enabled`| `false` | `true` |
| Outlook OAuth redirect URI #716| `msauth://com.flowcrypt.email/gVgrJ%2BnS3FFmy0N1RePwMwAKI70%3D` | `msauth://com.flowcrypt.email.enterprise/gVgrJ%2BnS3FFmy0N1RePwMwAKI70%3D` |
| Check FES availability. SSLExceptin #1202  | `continueWithRegularFlow()` | `showDialogWithRetryButton` |
| Preview attachments #1682 | `no restrictions` | `using Content app(com.airwatch.contentlocker, RESTRICT_ANDROID_ATTACHMENT_HANDLING)` |
| Refresh Private Keys From Ekm | `not supported` | `enabled` |
| Support derepcated signature (SHA1) #1478 | `true` | `false` |

**Comment by DenBond7** [comment]
@tomholub @martgil @sosnovsky I hope it's a full list :) I have not found more differences.

**Comment by tomholub** [comment]
> Refresh Private Keys From Ekm

This should be supported on consumer too. Whenever EKM is present

**Comment by tomholub** [comment]
> GMail API Enabled

This should be enabled on both going forward, as discussed (just mentioning for clarity)

**Comment by tomholub** [comment]
> Check FES availability. SSLExceptin https://github.com/FlowCrypt/flowcrypt-android/issues/1202

This should apply to more than just SSL error.

situation | enterprise behavior | consumer behavior
---|---|---
FES returns 404 | regular flow | regular flow
FES is not reachable, internet is working | error | regular flow
FES is not reachable, internet is not working | error | error
FES SSL error | error | regular flow
FES returns wrong data | error | regular flow
FES returns 5xx | error | regular flow
FES returns 4xx other than 404 | error | regular flow

**Comment by tomholub** [comment]
> Preview attachments https://github.com/FlowCrypt/flowcrypt-android/issues/1682

I think there should probably be no difference between consumer and enterprise here.

If `RESTRICT_ANDROID_ATTACHMENT_HANDLING` is present, apply restrictions, else don't apply restrictions, regardless of build.

We can file a separate issue for this to discuss the behavior in more detail.

**Comment by DenBond7** [comment]
> This should be enabled on both going forward, as discussed (just mentioning for clarity)

Yup. Because #2122 is not completed yet I've added this info to the table.

**Comment by DenBond7** [comment]
@tomholub I've rechecked (code and ref https://github.com/FlowCrypt/flowcrypt-android/issues/1202#issuecomment-886685547). We have the following situation for Android now.
situation | enterprise behavior | consumer behavior| Situation 
---|---|---|---
FES returns 404 | regular flow | regular flow | **✓**
FES is not reachable, internet is working | error | regular flow |  `continueBasedOnFlavorSettings()`
FES is not reachable, internet is not working | error | error |  **✓**(show dialog with retry button)
FES SSL error | error | regular flow |  **✓**
FES returns wrong data | error | regular flow | as I understand it is about `"enterprise-server" == service`. `continueBasedOnFlavorSettings()`
FES returns 5xx | error | regular flow | `continueBasedOnFlavorSettings()`
FES returns 4xx other than 404 | error | regular flow | `continueBasedOnFlavorSettings()`

https://github.com/FlowCrypt/flowcrypt-android/blob/cfa872b7cc39feecc987cc0f2e09a73444d6b3ab/FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/MainSignInFragment.kt#L598

```kotlin
private fun continueBasedOnFlavorSettings() {
    if (BuildConfig.FLAVOR == Constants.FLAVOR_NAME_ENTERPRISE) {
      /*
       here we actually need to decide if we should show error or proceed with
       regular setup flow based on exact customers that will skip to regular setup flow,
       and the rest will be shown error.
      */
      continueWithRegularFlow()
    } else {
      continueWithRegularFlow()
    }
  }
```

**Comment by tomholub** [comment]
Ok, I remember this situation. Let's standardize it, as follows.

```kt
private fun continueBasedOnFlavorSettings() {
    if (BuildConfig.FLAVOR == Constants.FLAVOR_NAME_ENTERPRISE) {
      // error + retry
    } else {
      continueWithRegularFlow()
    }
  }
```

**Comment by DenBond7** [comment]
> I believe this will make it the same as my table above. If if doesn't, let me know.

Yes. It should work the same.

**Comment by DenBond7** [comment]
I'm closing it for now. We've opened separate issues for some of the questions.
