### ISSUE TITLE
Produce a warning prompt when users wishes to download a potentially dangerous file

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-android#2135]
Description:
Currently, when a user downloads a potentially dangerous file type, the app allows them to do so without any warning.

For improvement, we can add a user warning just when the user decides to download a potentially dangerous file. For the android system, some are: .apk, .appx, .appxbundle -- but could be changed. I could gather more information regarding this one.

Reference: https://github.com/FlowCrypt/flowcrypt-security/issues/224

**Comment by DenBond7** [comment]
It can be added. @martgil Please add all extensions that you would like to have a warning hint. Also please add an example of `the warning message`.

**Comment by martgil** [comment]
I think we use the message from https://github.com/FlowCrypt/flowcrypt-browser/issues/4862 for uniformity:
`This executable file was not checked for viruses, and may be dangerous to download or run. Proceed anyway?`

> Please add all extensions that you would like to have a warning hint

Yes, sir. I'd confirm it with @tomholub via https://github.com/FlowCrypt/flowcrypt-security/issues/224 then share the final list here.

**Comment by martgil** [comment]
sir, Den, the final list only contains; `.apk, .appx, .appxbundle`

**Comment by DenBond7** [comment]
Got it. Thank you, Mart!

**Comment by martgil** [comment]
Welcome, sir - thank you, too.
