### ISSUE TITLE
Preview attachments for consumer/enterprise

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#2137]
> Preview attachments https://github.com/FlowCrypt/flowcrypt-android/issues/1682

I think there should probably be no difference between consumer and enterprise here.

If `RESTRICT_ANDROID_ATTACHMENT_HANDLING` is present, apply restrictions, else don't apply restrictions, regardless of build.

We can file a separate issue for this to discuss the behavior in more detail.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-android/issues/2123#issuecomment-1372352395_

**Comment by DenBond7** [comment]
https://flowcrypt.com/docs/technical/enterprise/configuration/client-configuration.html
![image](https://user-images.githubusercontent.com/2863246/210831726-27359ff4-cf67-43ab-9c51-98a46fedad0f.png)



It should be discussed. Based on https://github.com/FlowCrypt/flowcrypt-android/issues/1682#issuecomment-1042130833, we should use `Content` app to preview an attachment. As for me, it can be used only for a specific customer or just for an enterprise.

`RESTRICT_ANDROID_ATTACHMENT_HANDLING` was created after a request from one of our customers.

**Comment by tomholub** [comment]
The description of the client configuration doesn't say anything about this only being applicable to `enterprise` build. Therefore we should honor it on consumer build equally, but only when this client configuration is present (same on enterprise).

**Comment by DenBond7** [comment]
@sosnovsky (copy @tomholub) For now `RESTRICT_ANDROID_ATTACHMENT_HANDLING` works the same for all. If we would like to allow attachment previewing for the consumer version need to clarify the logic. 

For example, if `RESTRICT_ANDROID_ATTACHMENT_HANDLING` is **not present**, we will have `download` and `preview` options for the consumer version. `download` will work as before(a user can download a file to the `Downloads` folder. Click on the attachment -> open it by available applications in a system). `preview` will download a file and open it by available applications in a system.

if `RESTRICT_ANDROID_ATTACHMENT_HANDLING` is **present** we will use the logic from https://flowcrypt.com/docs/technical/enterprise/configuration/client-configuration.html (The download button will save the file to the device, but not allow the user to directly tap to open it. Instead, the user has to navigate to the file through a file manager to open it. The view button allows the user to view the attachment without saving it, using the Content app on Android, if the user has it installed.). Please correct me if I'm wrong.

**Comment by DenBond7** [comment]
Based on #1828 non-enterprise users could have enabled preview functionality for all cases. I mean we can allow consumer users to have preview functionality for all cases. But if `RESTRICT_ANDROID_ATTACHMENT_HANDLING` is present there will be some restrictions(https://flowcrypt.com/docs/technical/enterprise/configuration/client-configuration.html)

**Comment by sosnovsky** [comment]
Ah, I see, then logic with look like this, right?

```
if RESTRICT_ANDROID_ATTACHMENT_HANDLING
    preview button - download to app folder and open in Content app
    download button - download to Downloads, on tap should open file in Content app
else
    preview button - download to Downloads folder and open in available apps
    download button - download to Downloads, on tap open in available apps
end
```

**Comment by DenBond7** [comment]
Yup, you are right. What do you think about this logic? Can we use it?

**Comment by sosnovsky** [comment]
Yes, looks good, let's use it

**Comment by tomholub** [comment]
in case the client configuration docs are less clear then this, please take this chance to update them.

**Comment by sosnovsky** [comment]
> in case the client configuration docs are less clear then this, please take this chance to update them.

yes, docs should be updated as currently they say `Without this flag, attachments on an Android app only have a download button`, but there will be 2 buttons for both cases - with and without `RESTRICT_ANDROID_ATTACHMENT_HANDLING` flag

**Comment by DenBond7** [comment]
>I think there should probably be no difference between consumer and enterprise here.

To be honest I don't understand why we have to apply any configuration to the consumer version.

Please look at this address flowcrypt.com/docs/technical/**ENTERPRISE**/configuration/client-configuration.html. The address name says that it relates to the enterprise version.

**Comment by tomholub** [comment]
"enterprise" vs "consumer" app build

"enterprise" vs "consumer" configuration

Client configurations are for enterprises, but they apply equally to enterprise app builds and consumer app builds, because enterprise app builds are difficult to deploy, and not every enterprise wants to run FES (FES being required is the biggest difference between enterprise build and consumer build).

consumer app in consumer environment - allowed
consumer app in enterprise environment - allowed
enterprise app in consumer environment - not allowed
enterprise app in enterprise environment - allowed

The URL says enterprise because client configuration is meant for enterprise customers. But it applies to enterprise and consumer apps equally, some enterprises use consumer apps.

**Comment by DenBond7** [comment]
I see. In that case, it makes sense. No questions ))

**Comment by DenBond7** [comment]
@tomholub Can we add a tiny change to the documentation? The main changes: 

1. if the flag is missing we allow to download/preview an attachment and open it in the appropriate app, depending on the type of file and which apps the user has installed. It's a default behavior in Android. 
2. if the flag is present for `download` option I can change:  `but not allow the user to directly tap to open it.` to `the user may tap on the file to view or open it in the Content app on Android, if the user has it installed`

![image](https://user-images.githubusercontent.com/2863246/236233134-47ff2b03-5c71-4a44-a9a5-f3cf96a2d413.png)

### OLD

> Without this flag, attachments on an Android app only have a download button, and after downloading, the user may tap on the file to view or open it in the appropriate app, depending on the type of file and which apps the user has installed. With this flag, there will be two buttons instead: a download and a view button. The download button will save the file to the device, but not allow the user to directly tap to open it. Instead, the user has to navigate to the file through a file manager to open it. The view button allows the user to view the attachment without saving it, using the Content app on Android, if the user has it installed.

### NEW

> An Android app has two buttons: a download and a view button
> 
> The flag is missing. The download button will save the file to the device. After downloading, the user may tap on the file to view or open it in the appropriate app, depending on the type of file and which apps the user has installed. The view button allows the user to view the attachment without saving it, using the same logic we use for downloading.
> 
> The flag is present. The download button will save the file to the device, but not allow the user to directly tap to open it. Instead, the user has to navigate to the file through a file manager to open it. The view button allows the user to view the attachment without saving it, using the Content app on Android, if the user has it installed.

**Comment by tomholub** [comment]
Sure, but the text has to be improved a bit maybe, you can check with Roma on things like this.

**Comment by sosnovsky** [comment]
What about a bit shorter documentation text:

> (affects only Android app) setting this flag will allow previewing and opening downloaded attachments only in [Content](https://play.google.com/store/apps/details?id=com.airwatch.contentlocker&hl=en_US&pli=1) app. Without this flag attachments can be opened with any supported app.

**Comment by DenBond7** [comment]
@sosnovsky looks good to me. Please open a separate issue to update docs in the right repo.

**Comment by sosnovsky** [comment]
> @sosnovsky looks good to me. Please open a separate issue to update docs in the right repo.

Done - https://github.com/FlowCrypt/flowcrypt-web/issues/1064
