### ISSUE TITLE
display signed messages - but do not verify yet

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#214]
when we receive a `block.type == 'signed_message'`

We should display that block with a gray border design (there should already be a template for it in the app).

Right now, it just shows empty message.

Example: `signed with FlowCrypt Extension (inline signature)` in flowcrypt.compatibility

**Comment by DenBond7** [comment]
@tomholub Can `block.type == 'signed_message'` have the same decrypt errors as `block.type == 'message'`? (e.g. SINGLE_SENDER, MISSING_PRIVATE_KEY and other)

**Comment by tomholub** [comment]
Actually, any block type that we don't have a handling for yet should be displayed in raw as if it was text.

**Comment by DenBond7** [comment]
Currently, we support only

- MessageBlock.TYPE_TEXT
- MessageBlock.TYPE_PGP_MESSAGE
- MessageBlock.TYPE_PGP_PUBLIC_KEY

**Comment by DenBond7** [comment]
> in raw

Can I use messageBlock.getContent() for this?

**Comment by DenBond7** [comment]
> Which border style can I use?

I have found. We use https://github.com/FlowCrypt/flowcrypt-android/blob/master/FlowCrypt/src/main/res/layout/message_part_other.xml for this.

![image](https://user-images.githubusercontent.com/2863246/37282219-53fd9d28-25fc-11e8-9b52-2b9dd1b4c94f.png)

**Comment by tomholub** [comment]
Correct, the one that produces gray border
