### ISSUE TITLE
Add support for FES 2023-01

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-android#2142]
https://fes.flowcrypt.com/api response has changed `service` value from `enterprise-server` to `external-service`.

We need to check if this change affected android app and update code to allow both values - `enterprise-server` and `external-service`

**Comment by tomholub** [comment]
After this issue, I'd like to do a release (eg tomorrow). @DenBond7 is that possible?

**Comment by DenBond7** [comment]
Yes, please look at https://github.com/FlowCrypt/flowcrypt-android/pull/2143#discussion_r1067109242

**Comment by DenBond7** [comment]
I think it will be possible today.
