### ISSUE TITLE
Add more tests fot FES during the login process

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#2147]
That's a real problem. Please file an issue for an automated test for this, and do that as the first thing in next milestone.

We have to do an analysis on this, find out exactly what the impact was, what to do to prevent similar issues in the future.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-android/pull/2143#discussion_r1067126609_

**Comment by tomholub** [comment]
Does this look feasible?

**Comment by DenBond7** [comment]
Yes. I'm working on it.

**Comment by DenBond7** [comment]
I'm relooking over

![image](https://user-images.githubusercontent.com/6306961/126993463-3c738bf8-45d8-4f79-a156-ce25473b069c.png)

and trying to test more things

**Comment by DenBond7** [comment]
> We have to do an analysis on this

@tomholub I've added a few new tests

> find out exactly what the impact was

We had this situation due to a missed test. Our tests didn't include a test where we check that we call `/api/v1/client-configuration?domain` if we should. Also, it's not easy to understand on this screen that some things are wrong. On this screen, we show a progress bar and make a few requests. If one request was missed we can not see any difference. I mean UI.

But anyway the missed test was the reason. Unfortunately, my and Ioan's code review skipped this error.

> what to do to prevent similar issues in the future. 

For such a case I will be adding tests like [MainSignInFragmentEnterpriseTestUseFesUrlFlowTest]( https://github.com/FlowCrypt/flowcrypt-android/blob/c06ea1b5f386ff4a74b23ab32ff7173401123ac2/FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/fes/login/MainSignInFragmentEnterpriseTestUseFesUrlFlowTest.kt). It tests that we really call some API at some stage.
