### ISSUE TITLE
Comlete government apps declaration in Google Play

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#2148]
![image](https://user-images.githubusercontent.com/2863246/211893994-4caf6bd9-2ebd-4388-9fed-493f3efc2792.png)

**Comment by DenBond7** [comment]
![image](https://user-images.githubusercontent.com/2863246/212314831-3323ce21-df26-41c0-bae2-81d4954ba5dc.png)
@tomholub As I understand FlowCrypt for Android is not a government app and no governments use it officially. Asking just in case(maybe I don't know something :)) ).

**Comment by tomholub** [comment]
You are correct, we don't have any government customer at the moment.

**Comment by DenBond7** [comment]
The requested info was updated. I'm closing it.
