### ISSUE TITLE
Show indicator of encryption in inbox list

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#215]

**Comment by tomholub** [comment]
Something like this:

![image](https://user-images.githubusercontent.com/6306961/37031185-c9aec7e6-2178-11e8-9595-e07ab20f380c.png)

**Comment by tomholub** [comment]
I don't know if this can be done without affecting performance. We will need a way to guess if the message is encrypted (doesn't have to be perfect).

Is it possible to get first 100 characters of each message when pulling inbox?  Can it be done in the same call? How does that affect performance?  For @DenBond7 to investigate

If we can do that without affecting affecting performance, then we can test if the first 100 characters contain `-----BEGIN PGP MESSAGE-----`, which is a good enough indicator.

**Comment by tomholub** [comment]
The width and style of the left indicator is the same as encrypted message

**Comment by DenBond7** [comment]
@tomholub You can already to test it. I've added a test version of that.

I want to know what do you think about performance. Because I've added a new transaction.

**Comment by tomholub** [comment]
Were you able to roughly measure the performance difference? How much time does it add?

Worst case we could do this asynchronously - show the markers AFTER loading messages.

**Comment by DenBond7** [comment]
< How much time does it add

It is around twice more.

**Comment by DenBond7** [comment]
>  Worst case we could do this asynchronously - show the markers AFTER loading messages.

Yes, I can do that in the passive queue.

**Comment by DenBond7** [comment]
> we can test if the first 100 characters contain 

I think it's not enough. Will be better if we will load first 2k characters

```
------sinikael-?=_1-15215458946140.6892538553227616
 Content-Type: text/plain
 Content-Transfer-Encoding: quoted-printable
 X-Microsoft-Exchange-Diagnostics: 1;VI1PR10MB0413;27:3tmneDj6CYwolH4X4gWKMYy71fM7Nq85Zt1pZKT6474mPieVkZ0uZJq+hHLR9fwpdEPaC4FW3JzLcYVQFCeseN2tb+iloBu6r15ntMH6tZEhWuAJWbE4qBJTHQk9t7sE X-Microsoft-Antispam-Mailbox-Delivery: abwl:0;wl:0;pcwl:0;kl:0;iwl:0;ijl:0;dwl:0;dkl:0;rwl:0;ex:0;auth:1;dest:I;ENG:(400001000128)(400125000095)(5062000261)(5061607266)(5061608174)(4900095)(4920089)(6515079)(4950130)(4990090)(400001001318)(400125100095)(61617190)(400001002128)(400125200095);
 X-Message-Info: 5vMbyqxGkddhh69sIkKp9pLi3PfvO4Ny18wihVylw+Ba0/j3V9f/n9oYPENvvg87/CcALndfVAaxJ9SE+o2bGXHal0Fmc9mYQIAxynO9PZXW8ZigtjN2wY7UjlDzTpRb0k970gA27Cu+MOF19Kp48KB6yhk/xTAg4RpKlfkjiK4QYCz+CAsBIbWbD1jziSrvwxdjv9z7aOQEysVDobSmSw== 
 X-Message-Delivery: Vj0xLjE7dXM9MDtsPTA7YT0xO0Q9MTtHRD0xO1NDTD0z 
 X-Microsoft-Antispam-Message-Info: M/9yokRxWUwmu4kAxKSaW879lVAgYCecfvWAunin6aVCFoywCZmeIvG09eAOKGnadm0fKKyncjQvzvSGg71i6AH6P5qszL5GKvPs1mkHxQi3iy0szc0qnU/Rz+Y7AC6GYhIxXSnJ2QO3u+Iu4eHL9XCDg+oOBxBn6KYY2gcjzZMEW3okA/14Ezd7MN2NTysGgu0Uy9um0OQSwn2LIqBO7sU28oszDax7qEiWqR00Bwh8NNM266W2+4uWrFNKMW5GfDvkEcshQVMg29nMD7Ps9Q1aFi0Fzi9bPJLdfs5tk6ZlZVH6Zrf5BN4CQKgf+Vfw58E8Ab1auh+j3qP73vNXxQCVoeSuI4h/yibdExWbhMU+QGgu2mSdWag/6GflOqItTDDxy2e0uG9V0ZDfMcofLkvCjMShBoQjEjhKfipE8yyKYUa/aUEPE9XX1vQVDjIqcJSOMyC+jkIxG6utyMCdaHxsBMRNWXUAQVP2jabLcAEvtihm9G6JoEMLPCXwGyuP
 -----BEGIN PGP MESSAGE----- Version: FlowCrypt Android 0.6.1 Gmail Encryption flowcrypt.com Comment: Seamlessly send, receive and search encrypted email 
```

We load 20 messages per one transaction. So we only add 20*2k = 40kb to the general traffic. Maybe after testing you will decide to increase such limit more.

**Comment by tomholub** [comment]
Does it not allow you to get 100 characters of the body only, without headers? Or not possible?

**Comment by DenBond7** [comment]
The example above shows only a body.

**Comment by DenBond7** [comment]
It's an example from the Outlook

**Comment by DenBond7** [comment]
> Can it be done in the same call?

I've added such realization. You already can try it. Now we have good performance(as we have before).

**Comment by tomholub** [comment]
Feel free to modify milestone for any issues that are getting ready to be shipped

**Comment by tomholub** [comment]
It feels like it's loading significantly longer. The prod app is quite fast (it's very noticeable when pulling additional messages). If this is the fastest we can do, we should:

1) have a messages table in the database, where we store message ID and an "encrypted" boolean.
2) Pulling this info and rendering it in inbox should be a background process that gets started AFTER loading and rendering list of messages.

Design detail: there should be no white space on the left side of the green stripe. It should be all the way at the screen edge.

**Comment by tomholub** [comment]
Correction - we can render the stripes with the initial render for messages that we have info about in the database. Any indicators for messages with missing info (nothing in DB) should be handled in background process.

**Comment by DenBond7** [comment]
It's ready for testing
