### ISSUE TITLE
use flowcrypt.com/shared-tenant-fes/ instead of flowcrypt.com/api for some requests

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#2162]
part of https://github.com/FlowCrypt/flowcrypt-enterprise-on-prem/issues/4097

same as https://github.com/FlowCrypt/flowcrypt-browser/issues/4890 except on Android

please also respect the naming of `potentialCustomUrlFes` vs `sharedTenantFes`, both of which are instances of the same class called `ExternalService` / `ExternalServiceXxx` (instead of previously `EnterpriseServer`)

**Comment by DenBond7** [comment]
> use flowcrypt.com/shared-tenant-fes/ instead of flowcrypt.com/api

I've added changes. As I understand, the backend is not ready yet.

`<-- 404 Not Found https://flowcrypt.com/shared-tenant-fes/help/feedback`

> please also respect the naming of potentialCustomUrlFes vs sharedTenantFes, both of which are instances of the same class called ExternalService / ExternalServiceXxx (instead of previously EnterpriseServer)

Not sure about that. I can't find such names.

**Comment by tomholub** [comment]
> <-- 404 Not Found https://flowcrypt.com/shared-tenant-fes/help/feedback

Only client configuration and password protected messages are implemented for now. That means, /help/feedback still has to use original url, and ACRA reports also.

**Comment by tomholub** [comment]
> > use flowcrypt.com/shared-tenant-fes/ instead of flowcrypt.com/api
> 
> I've added changes. As I understand, the backend is not ready yet.

It is ready except for feedback and acra endpoints.
The client configuration for our existing customers is not leaded yet, only one sample domain is loaded.
Password protected messages should work, but I haven't tested it yet - please test it.

> 
> `<-- 404 Not Found https://flowcrypt.com/shared-tenant-fes/help/feedback`
> 
> > please also respect the naming of potentialCustomUrlFes vs sharedTenantFes, both of which are instances of the same class called ExternalService / ExternalServiceXxx (instead of previously EnterpriseServer)
> 
> Not sure about that. I can't find such names.

What class contains API calls to FES? What is it called, and what are called the API request and response models when calling FES?

**Comment by DenBond7** [comment]
> What class contains API calls to FES? What is it called, and what are called the API request and response models when calling FES?

I hope it's the answer

1. https://github.com/FlowCrypt/flowcrypt-android/blob/master/FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/CheckFesServerViewModel.kt
2. https://github.com/FlowCrypt/flowcrypt-android/blob/master/FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/MainSignInFragment.kt#L524
3. https://github.com/FlowCrypt/flowcrypt-android/blob/master/FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/ClientConfigurationViewModel.kt#L39-L42
4. https://github.com/FlowCrypt/flowcrypt-android/blob/master/FlowCrypt/src/main/java/com/flowcrypt/email/api/retrofit/FlowcryptApiRepository.kt#L60-L69
5. https://github.com/FlowCrypt/flowcrypt-android/blob/master/FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/workmanager/HandlePasswordProtectedMsgWorker.kt#L186-L198
6. https://github.com/FlowCrypt/flowcrypt-android/blob/master/FlowCrypt/src/main/java/com/flowcrypt/email/util/GeneralUtil.kt#L432

**Comment by tomholub** [comment]
Thank you - we will need some updates for clarity. We have FES servers now at two possible locations, one is at fes.domain.com (possibly, if admin set it up, must be used if present) and one is always at flowcrypt.com/shared-tenant-fes. So we need to distinguish them.

Therefore, for example:
 - `generateFesUrl` should be called `generatePotentialCustomFesUrl`
 - `CheckFesServerViewModel` should be called `CheckCustomUrlFesServerViewModel`
 - `checkFesServerAvailability` should be called `checkCustomUrlFesServerAvailability`

In this code:

```kt
  override suspend fun getClientConfiguration(
    context: Context,
    fesUrl: String?,
    idToken: String
  ): Result<ClientConfigurationResponse> =
    withContext(Dispatchers.IO) {
      val apiService = ApiHelper.getInstance(context).retrofit.create(ApiService::class.java)
      getResult(context = context) {
        if (fesUrl != null) {
          apiService.getClientConfigurationFromFes(fesUrl = fesUrl)
        } else {
          apiService.getClientConfigurationFromFlowCryptComBackend(authorization = "Bearer $idToken")
        }
      }
    }
```

 - `fesUrl` should be called `customFesUrl`
 - then the two options should be `apiService.getClientConfigurationFromFes(fesUrl = fesUrl)` and apiService.getClientConfigurationFromFes(fesUrl = SHARED_TENANT_FES_URL)
 - `getClientConfigurationFromFlowCryptComBackend` should be removed

Similarly with password encrypted messages and so on. What I'm listing here is probably just the tip of the iceberg.

**Comment by DenBond7** [comment]
> then no need for if/else, instead apiService.getClientConfigurationFromFes(fesUrl = customFesUrl ?? SHARED_TENANT_FES_URL)

It means we don't need to use `idToken` here. Right?

**Comment by tomholub** [comment]
Good question, the don't actually at the moment need any authentication, since you can see they are freely available:

custom url fes example (for flowcrypt.com domain)
https://fes.flowcrypt.com/api/v1/client-configuration?domain=flowcrypt.com

shared tenant fes example (for domains that don't have their own)
https://flowcrypt.com/shared-tenant-fes/api/v1/client-configuration?domain=sample.test

However, I do plan to add authentication to this endpoint eventually. Therefore I recommend to send authentication token with bearer id token in both situations. That will make the app future-proof to that change.

**Comment by DenBond7** [comment]
Let me summarize some things. Here is all API that the app calls for now.

As I understand these will not be affected by the current issue

```
https://flowcrypt.com/attester/welcome-message
https://flowcrypt.com/attester/pub/{keyIdOrEmailOrFingerprint}
https://flowcrypt.com/attester/pub/{email}
<ekm>/v1/keys/private
https://{advancedHost}/.well-known/openpgpkey/{directDomain}/hu/{hu}
https://{advancedHost}/.well-known/openpgpkey/{directDomain}/policy
https://{directHost}/.well-known/openpgpkey/hu/{hu}
https://{directHost}/.well-known/openpgpkey/policy
```

The following maybe needs an update(code refactoring, renaming, and so on).

https://flowcrypt.com/api/help/feedback (I remember that not now)
https://flowcrypt.com/api/account/get
https://flowcrypt.com/api/help/acra (I remember that not now)

https://fes.$domain/api/v1/client-configuration?domain=$domain
https://fes.{domain}/api/
https://fes.{domain}/api/v1/message/new-reply-token
https://fes.{domain}/api/v1/message

**Comment by DenBond7** [comment]
> Good question, they don't actually at the moment need any authentication, since you can see they are freely available:

Yes. But before we used to use https://flowcrypt.com/api/account/get which requires authorization via idToken

**Comment by tomholub** [comment]
> Let me summarize some things. Here is all API that the app calls for now.
> 
> As I understand these will not be affected by the current issue
> 
> ```
> https://flowcrypt.com/attester/welcome-message
> https://flowcrypt.com/attester/pub/{keyIdOrEmailOrFingerprint}
> https://flowcrypt.com/attester/pub/{email}
> <ekm>/v1/keys/private
> https://{advancedHost}/.well-known/openpgpkey/{directDomain}/hu/{hu}
> https://{advancedHost}/.well-known/openpgpkey/{directDomain}/policy
> https://{directHost}/.well-known/openpgpkey/hu/{hu}
> https://{directHost}/.well-known/openpgpkey/policy
> ```
> 

Not affected, yes

For clarity let's add these two to "not affected" for now (but you may indeed need to refactor them or move them, in case that's needed):

> https://flowcrypt.com/api/help/feedback (I remember that not now) 
> https://flowcrypt.com/api/help/acra (I remember that not now)


> The following maybe needs an update(code refactoring, renaming, and so on).
> https://fes.$domain/api/v1/client-configuration?domain=$domain
> [https://fes.{domain}/api/](https://fes.%7Bdomain%7D/api/)
> [https://fes.{domain}/api/v1/message/new-reply-token](https://fes.%7Bdomain%7D/api/v1/message/new-reply-token)
> [https://fes.{domain}/api/v1/message](https://fes.%7Bdomain%7D/api/v1/message)

These are all perfectly fine as they are EXCEPT:
 - call them exactly as they are when `customFesUrl` is available and verified
 - call `https://flowcrypt.com/shared-tenant-fes/api/v1/...` in the opposite case, for all 4

**Comment by tomholub** [comment]
Overall, this should mean a lot of simplification for the code. Both services are exactly the same. They just have different URL. Initially, the app decides if it must use `customFesUrl` or not, based on already existing flow and logic.

After that, all logic is the same. Just the beginning of the endpoint URLs differ, based on whether `customFesUrl` or `SHARED_TENANT_FES_URL` is used.

**Comment by tomholub** [comment]
Did we ever implement password protected messages through flowcrypt.com/api? It sounds like we did, based on all of the removed endpoints? If yes, that code can be unified with the code that sends password protected messages through FES. Since the logic will now be the same, just a different service URL.

**Comment by DenBond7** [comment]
> These are all perfectly fine as they are EXCEPT:

>call them exactly as they are when customFesUrl is available and verified
call https://flowcrypt.com/shared-tenant-fes/api/v1/... in the opposite case, for all 4

Ha... that was what I needed. Now it's clearer

**Comment by DenBond7** [comment]
> Did we ever implement password protected messages through flowcrypt.com/api? 

Do you mean this one https://github.com/FlowCrypt/flowcrypt-android/issues/1545? or even https://github.com/FlowCrypt/flowcrypt-android/issues/1615?

**Comment by tomholub** [comment]
> >   Did we ever implement password protected messages through flowcrypt.com/api?
>
> Do you mean this one https://github.com/FlowCrypt/flowcrypt-android/issues/1545? or even https://github.com/FlowCrypt/flowcrypt-android/issues/1615?

The one you linked uses https://fes.domain.com URLs, for enterprises, not flowcrypt.com/api.

Did we ever implement a similar mechanism for sending password-protected messages using flowcrypt.com/api? It sounds like we haven't, on Android? That means we never actually allowed people who don't have FES to send password-protected messages?

If that is true that we haven't, we can allow that now. Of course, these users don't have `customFesUrl` so they will be using `SHARED_TENANT_FES_URL` to send out these password-protected messages.

**Comment by DenBond7** [comment]
>Did we ever implement a similar mechanism for sending password-protected messages using flowcrypt.com/api? It sounds like we haven't, on Android? That means we never actually allowed people who don't have FES to send password-protected messages?

It seems firstly it worked for all, but later we allowed it only for the enterprise.

https://github.com/FlowCrypt/flowcrypt-android/issues/1621

**Comment by tomholub** [comment]
it didn't actually work for all, there would have been an error anyway. because FES wasn't available for others. and we didn't implement this functionality for flowcrypt.com/api users. 

note that we have shared-tenant-fes, it can be allowed for all users, on both flavours.

**Comment by DenBond7** [comment]
- [ ] test database migration

**Comment by DenBond7** [comment]
@tomholub I need to clarify some moments
Let's imagine we have the following scenario:

1. A user has `user@flowcrypt.test` account on his device
2. The user clicks on `Continue with Gmail`
3. We check if `fes.flowcrypt.test` is available. It IS NOT available.
4. We call `https://flowcrypt.com/shared-tenant-fes/api/v1/client-configuration?domain=flowcrypt.test` to get client configuration. But there is no configuration for `flowcrypt.test` on `shared-tenant-fes`. We receive an error

```json
{
   "code":404,
   "message":"ClientConfiguration missing for flowcrypt.com",
   "details":""
}
```
5. Based on the app logic(the logic of `FES` scenario) we show the error details and DON'T allow the user to continue.
![image](https://user-images.githubusercontent.com/2863246/215263472-9e5e3662-d5eb-4c57-9b35-9eafb796dcb7.png)

Does it look well?

ref https://github.com/FlowCrypt/flowcrypt-android/issues/1202#issuecomment-886685547

![image](https://user-images.githubusercontent.com/6306961/126993463-3c738bf8-45d8-4f79-a156-ce25473b069c.png)

**Comment by DenBond7** [comment]
@tomholub It seems after migration to https://flowcrypt.com/shared-tenant-fes/api/v1/client-configuration? we need to review the app logic

**Comment by tomholub** [comment]
I think I'll change server behavior. so that shared-tenant-fes will always return default (empty) client configuration for domains it doesn't know. Then it should work smoothly?

**Comment by DenBond7** [comment]
Do you mean this one? 

```json
{
  "clientConfiguration": {
    "flags": []
  }
}
```

**Comment by tomholub** [comment]
yes

**Comment by DenBond7** [comment]
> Then it should work smoothly?

```json
{
  "clientConfiguration": {
    "flags": []
  }
}
```
This one works smoothly

**Comment by tomholub** [comment]
I'll do that then. We'll hold off on merging this PR until that is ready.

**Comment by tomholub** [comment]
Anyway it would be wiser to fix the reported bugs by our enterprise customer and do a release before merging this. So that we don't introduce a potentially breaking change with the bugfixes, since this change is a significant one.

**Comment by DenBond7** [comment]
> this change is a significant one

It was the reason why I didn't switch to reported issues. It was almost done. And while all things are fresh in my mind it was important to complete this one.

Anyway, I'm switching now.

**Comment by tomholub** [comment]
If there is still work to do here that you know, it's good to do it while it's fresh in your mind, before the bugs. We just wouldn't merge this PR yet until the bugfixes are merged and released.
