### ISSUE TITLE
Attachments are lost when forwarding message

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-android#2179]
Reported by customer:

> On a computer if we forward an email received from the app, we can read it but the attachment is lost, it becomes "_.pgp"

I reproduced  it:
1) send email with attachment from android app
2) open it in web extension and forward to someone
3) attachment name becomes `_.pgp` and it's not decrypted for forwarded recipient

Forwarding attachments works well for messages sent from iOS, probably there is some difference in encrypted attachments structure on iOS/Android.

**Comment by DenBond7** [comment]
@sosnovsky [android_bug](https://github.com/FlowCrypt/flowcrypt-android/labels/android_bug) is not appropriate here. As we are at the FlowCrypt Android repo it's already an Android issue :). For such an issue we have just [bug](https://github.com/FlowCrypt/flowcrypt-android/labels/bug) label.

About the issue. I've reproduced it. But I'm not sure that it's an Android bug. It seems something was changed on the web side.
@tomholub I will post an issue for that as I can't resolve it just myself. Need to investigate web app sources.

**Comment by sosnovsky** [comment]
> @sosnovsky [android_bug](https://github.com/FlowCrypt/flowcrypt-android/labels/android_bug) is not appropriate here. As we are at the FlowCrypt Android repo it's already an Android issue :). For such an issue we have just [bug](https://github.com/FlowCrypt/flowcrypt-android/labels/bug) label.

Got it 👍 I just saw that there is `android bug` label in the list of used labels, and thought that it's used for Android-specific bugs, will use `bug` in the future.

**Comment by tomholub** [comment]
I think Den used that label for bugs caused by the android OS or toolchain.

**Comment by DenBond7** [comment]
> I think Den used that label for bugs caused by the android OS

[android_bug](https://github.com/FlowCrypt/flowcrypt-android/labels/android_bug) was created for it. To be honest, we didn't have these bugs for a long time. In the morning I deleted this label to prevent misunderstood.
