### ISSUE TITLE
clicking email addr: show "FlowCrypt" in action menu

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#219]
Inside flowcrypt app (or anywhere else), when clicking on an email, I will get following prompt:

![screenshot_20180307-231222 1](https://user-images.githubusercontent.com/6306961/37100531-2b7d82ec-225e-11e8-8e5e-f65e10f978a7.png)

I t would be good to add FlowCrypt as one of the options there

**Comment by DenBond7** [comment]
Please check this message in Gmail (BlueMail). Maybe would be better to implement such behavior. I mean immediately open the Compose screen in FlowCrypt instead of showing "open with" dialog.

**Comment by tomholub** [comment]
In FlowCrypt, yes - directly open.

In other apps (eg browser) it should add FlowCrypt to the list of choices.

**Comment by DenBond7** [comment]
For me https://medium.com/@cketti/android-sending-email-using-intents-3da63662c58f

**Comment by tomholub** [comment]
I like this
