### ISSUE TITLE
test shared-tetant-fes for android app

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-android#2197]
Fixed shared-tenant-fes. Would be good to test:
 - client configuration retrieval 
      - (consumer) flowcrypt.com - doesn't use shared tenant - gets from fes.flowcrypt.com without checking shared-tenant
      - (consumer) gmail.com - gets client configuration without ever checking fes.gmail.com
      - (consumer) test.flowcrypt.com - tries fes.test.flowcrypt.com but ends up getting empty config from shared-tenant-fes. Check through browser network tab.
      - (enterprise) flowcrypt.com - doesn't use shared tenant - gets from fes.flowcrypt.com without checking shared-tenant
      - (consumer) gmail.com - I suppose this should show an error during setup?
      - (consumer) test.flowcrypt.com - tries fes.test.flowcrypt.com, no FES running there, shows error
 - send message through web portal
      - (either build) flowcrypt.com uses fes.flowcrypt.com and works. Can also reply from the web portal
      - (either build) gmail.com uses flowcrypt.com/shared-tenant-fes and works. Can also reply from the web portal

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-browser/issues/4919#issuecomment-1410252500_

**Comment by martgil** [comment]
client configuration retrieval (android):

| what to test | working as described | comments |
|--|--|--|
(consumer) flowcrypt.com - doesn't use shared tenant - gets from fes.flowcrypt.com without checking shared-tenant | yes | - |
(consumer) gmail.com - gets client configuration without ever checking fes.gmail.com | yes | - |
| (consumer) test.flowcrypt.com - tries fes.test.flowcrypt.com but ends up getting an empty config from shared-tenant-fes. Check through browser network tab. | yes | ![image](https://user-images.githubusercontent.com/46025304/217773718-1e3d3482-4223-4a01-a6a2-bf2e50439e9f.png)  |
(enterprise) flowcrypt.com - doesn't use shared tenant - gets from fes.flowcrypt.com without checking shared-tenant | true | - |
(enterprise) gmail.com - I suppose this should show an error during setup? | no | the account recovery just went through and the inbox shows up.
(enterprise) test.flowcrypt.com - tries fes.test.flowcrypt.com, no FES running there, shows error | no |  no errors shown and shared-tenant-fes endpoint is used which returns empty client configuration. 

test to be continued using https://github.com/FlowCrypt/flowcrypt-android/pull/2171 branch.

**Comment by tomholub** [comment]
Thank you, I will have to think about this and write steps for Den to possibly address this, after current milestone is released, and before that PR is merged.

**Comment by tomholub** [comment]
> (consumer) test.flowcrypt.com - tries fes.test.flowcrypt.com but ends up getting an empty config from shared-tenant-fes. Check through browser network tab.

> ![image](https://user-images.githubusercontent.com/6306961/217885816-8acd84bc-1c18-4521-9de3-db69df5ebdb2.png)

Please give me the complete details of the full URL, and what was received back, on these three API calls. I'd like to double check it.

**Comment by martgil** [comment]
> (consumer) test.flowcrypt.com - tries fes.test.flowcrypt.com but ends up getting an empty config from shared-tenant-fes. Check through browser network tab.

> Please give me the complete details of the full URL, and what was received back, on these three API calls. I'd like to double check it.

(overview) first, the android app looks on fes at `fes.test.flowcrypt.com` -> gets redirected to `flowcrypt.com` (this part depends on the server config - it can result to 404 most often) -> retrieve client configuration from https://flowcrypt.com:443/shared-tenant-fes/api/v1/client-configuration?domain=test.flowcrypt.com and returns an empty client configuration.

<details><summary>see screenshots: </summary>

1.)  ![image](https://user-images.githubusercontent.com/46025304/219006559-19ee6699-5714-4de8-ae5a-6c7683f7365f.png)

2.) ![image](https://user-images.githubusercontent.com/46025304/219006609-008fe8c0-a8e8-418b-8537-1e39a5658a0d.png)

3.) ![image](https://user-images.githubusercontent.com/46025304/219006719-3908e4fa-996e-4c10-a667-466b570568d6.png)
![image](https://user-images.githubusercontent.com/46025304/219006771-4e22d4fd-d942-494e-95c2-d6724ee95c62.png)
</details>

**Comment by tomholub** [comment]
:warning: :warning: :warning: this is a security vulnerability

![image](https://user-images.githubusercontent.com/6306961/219139575-4e3ad846-fca3-434a-bc27-619504f66379.png)

See 

```
$ curl https://fes.test.flowcrypt.com/api/
curl: (60) SSL: no alternative certificate subject name matches target host name 'fes.test.flowcrypt.com'
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

https://fes.test.flowcrypt.com/api/ has a badly configured SSL and the redirect should NOT be followed

**Nothing coming from any domain that has badly configured SSL should ever by used whatsoever, including redirects.**

**Comment by tomholub** [comment]
@martgil this should have occurred to you when testing this, no? It was right under your nose.

**Comment by tomholub** [comment]
Now I worry that this problem is present throughout the app. If it happened here, the same thing will probably happen when calling all other APIs, Gmail API, WKD and so on, and this all needs to be tested thoroughly. @martgil check similar situation on other APIs on master, see if this also happens.

**Comment by tomholub** [comment]
Unless that's a property of your testing mechanism. Are you able to test the difference?

**Comment by martgil** [comment]
> @martgil this should have occurred to you when testing this, no? It was right under your nose. The app must not follow redirects coming from an insecure connection.

@tomholub we have received a report prior to this a couple of months ago -- and back then we don't consider it to be an issue at least that time. 

subject: Vulnerability report - 3161
![image](https://user-images.githubusercontent.com/46025304/219275397-d14b9582-2bc7-4228-a4bf-45ee2a3457b7.png)

I have also given an emphasis to investigating on the said report after we decided not to accept it - (the GitHub issue wasn't closed either) https://github.com/FlowCrypt/flowcrypt-security/issues/233

> @martgil this should have occurred to you when testing this, no? It was right under your nose. The app must not follow redirects coming from an insecure connection.

That is true - however, when using burpsuite - A cert from burpsuite tool is installed from our browser to decrypt the encrypted HTTP data. 

> Unless that's a property of your testing mechanism. Are you able to test the difference?

The behavior you get from curl is the ideal one and so for web browser.

![image](https://user-images.githubusercontent.com/46025304/219276351-04cbf2b0-4ef6-438a-97bb-7f3aa70fc57d.png)

 I include all the significant info on https://github.com/FlowCrypt/flowcrypt-security/issues/233 back then.

**Comment by tomholub** [comment]
That's a completely different report.

The report is about a misconfigured SSL domain, which really doesn't matter.

My issue I'm raising here is that the app appears to follow redirects received from domains with misconfigured SSL which is a problem if true.

> The behavior you get from curl is the ideal one and so for web browser. the only difference is that I have to use a cert from the burp suite tool which would not cause the SSL error - that is.

Can you confirm that the problematic behavior is not present in the stock Android app without the burp suite?

**Comment by martgil** [comment]
> Can you confirm that the problematic behavior is not present in the stock Android app without the burp suite?

Yes. Here is the actual request for a stock android app. It is the exact one used to call by the FlowCrypt android app.

![image](https://user-images.githubusercontent.com/46025304/219552305-df89858c-1e3c-4f01-becb-e990e2ebe3eb.png)

And it is the standard behavior for example visiting fes.test.flowcrypt.com with chrome on android (stock): 

![image](https://user-images.githubusercontent.com/46025304/219553665-c1a71737-451b-4f6c-afc3-47660ff34388.png)

Then the app calls the shared-tenant-fes endpoint to retrieve the client configuration.

![image](https://user-images.githubusercontent.com/46025304/219552952-3fe13eb6-a95b-4082-9bea-45d1987deacc.png)

![image](https://user-images.githubusercontent.com/46025304/219552878-290ca05f-a2ed-4a3b-a27f-c3ab89b92c03.png)

**Comment by tomholub** [comment]
ok. is it possible to update burp suite to follow that behaviour as well? to be more realistic

**Comment by martgil** [comment]
I think there's an option in the burp suite - I'll look into it and use it all throughout the tests.

**Comment by DenBond7** [comment]
@martgil Please provide clarification on how you tested this one.(Android version, build variant and so on).

![image](https://user-images.githubusercontent.com/2863246/222067705-6cfb9bf7-8968-42bc-9e99-00ef1bdacb7a.png)

Because I have a totally different result(March 1, 2023. Maybe something was changed on flowcrypt.com).

What I did:

1. Install the app
2. Click on `Continue with Gmail`
3. Google returns account info. I tested with den@flowcrypt.com. But I manually changed the code to use den@test.flowcrypt.com

![image](https://user-images.githubusercontent.com/2863246/222068544-e19908fd-205e-450e-858a-32af2187c193.png)

4. In the logs I see the following
![image](https://user-images.githubusercontent.com/2863246/222068731-7d35a511-b5c6-436c-8edf-19d8f2007cfe.png)

5. The app shows the following error and doesn't proceed
![image](https://user-images.githubusercontent.com/2863246/222068860-0bc60dc7-0f9b-49c8-935b-4a1b4ec1479a.png)

@tomholub Does the current behavior look correct?(What I've decribed)

**Comment by martgil** [comment]
@DenBond7 you've got the correct behavior (throws an error in cert). My result is the one that shows a false result due to burp suite's behavior where they do not validate SSL cert by default - https://github.com/FlowCrypt/flowcrypt-android/issues/2197#issuecomment-1434300211. I'll test it again with other monitoring tools - I should get the same behavior as the one you've shared.

**Comment by DenBond7** [comment]
Thank you, Mart. Got it. In that case, @tomholub should I still make any changes in the code? I've fixed merge conflicts, #2171 is ready to be merged.

**Comment by tomholub** [comment]
that's possibly all, as long as you fixed the one actual login issue. i'll take a look

**Comment by DenBond7** [comment]
@martgil Please retest the app with the latest changes

**Comment by martgil** [comment]
Yes, sir - I have retested the app against the test cases above. Only two of the test cases fails (excluding testing password protected message feature for non-fes user which is not implemented yet - https://github.com/FlowCrypt/flowcrypt-android/issues/2177)

**Comment by tomholub** [comment]
which two? please list them and describe how

**Comment by martgil** [comment]
These two test cases:

1.) (enterprise) gmail.com - (enterprise) gmail.com - allow to proceed with setup by never checking fes.gmail.com, and getting an empty client configuration from shared-tenant-fes
2.) flowcrypt.com uses fes.flowcrypt.com and works. Can also reply from the web portal

For 1.) : The android app enterprise build shows a warning modal saying that is not usable for gmail.com user.
![image](https://user-images.githubusercontent.com/46025304/224275078-3b3fb23f-f48a-4aa4-8173-e8227ab98442.png)

For 2.): an error occur when sending the password protected message and the message will be stuck in the outbox:
![image](https://user-images.githubusercontent.com/46025304/224274428-bdef2a5d-e25f-4bc8-965b-f9f214805916.png)

The error doesn't occur on the browser extension (either build) when sending a password protected message

**Comment by tomholub** [comment]
Usecase 2 is a real problem - @DenBond7 can you take a look?

**Comment by DenBond7** [comment]
@martgil Just in case, please use the following build variants

![image](https://user-images.githubusercontent.com/2863246/224328177-4bc7d85e-69e2-4b5a-b0c3-d5943397ebea.png)
![image](https://user-images.githubusercontent.com/2863246/224328258-fd5ca759-a7e7-445d-9a7f-607e647a58d2.png)

#####################################################################################################

> 1.) (enterprise) gmail.com - (enterprise) gmail.com - allow to proceed with setup by never checking fes.gmail.com, and getting an empty client configuration from shared-tenant-fes

![image](https://user-images.githubusercontent.com/2863246/224327382-d60d399a-8725-4cc3-867c-22e3b7121047.png)
from here https://github.com/FlowCrypt/flowcrypt-android/pull/2171#issuecomment-1450080839
![image](https://user-images.githubusercontent.com/2863246/224327203-dfaad1e6-bfa3-4e70-a63e-af9d500d2858.png)

@tomholub which version is correct(or maybe I've skipped something, please correct me)?

#####################################################################################################
> For 2.): an error occur when sending the password protected message and the message will be stuck in the outbox:

I've tested sending password-protected messages. It works on my side(https://fes.flowcrypt.com/message/09c2838f-d9b2-435e-9e3f-7a63deb970ce
). @martgil Could you share more details? What do you see when clicking on the message in Outbox?

#####################################################################################################

![image](https://user-images.githubusercontent.com/2863246/224330711-286322b8-3da6-468e-baa0-358a0fbc6ed1.png)
@tomholub is it possible to check server logs to understand what can be wrong?

**Comment by tomholub** [comment]
> @tomholub which version is correct(or maybe I've skipped something, please correct me)?

On consumer, to fetch from shared-tenant-fes
On enterprise, to not allow setup

But it's ok as it is now. Can file it for later.

**Comment by tomholub** [comment]
>  @tomholub is it possible to check server logs to understand what can be wrong?

```
Mar 03 16:47:28 de2-leader-a fes-service.out 2023-03-03T16:47:28.269Z WARN  c.flowcrypt.shared.server.ErrorReply - Client error: [401 Unauthorized] http://127.0.0.1:32337/api/v1/message/new-reply-token | id: dd2f2c500601 | message: JWT token header does not appear to contain valid JSON
Mar 06 13:13:50 de2-leader-a fes-service.out 2023-03-06T13:13:49.944Z WARN  c.flowcrypt.shared.server.ErrorReply - Client error: [401 Unauthorized] http://127.0.0.1:32337/api/v1/message/new-reply-token | id: 3643b4d37a11 | message: JWT token header does not appear to contain valid JSON
Mar 07 15:27:25 de3-leader-a fes-service.out 2023-03-07T15:27:25.805Z WARN  c.flowcrypt.shared.server.ErrorReply - Client error: [401 Unauthorized] http://127.0.0.1:32337/api/v1/message/new-reply-token | id: 4f47cbc6eb57 | message: JWT token header does not appear to contain valid JSON
Mar 07 21:50:31 de3-leader-a fes-service.out 2023-03-07T21:50:31.551Z WARN  c.flowcrypt.shared.server.ErrorReply - Client error: [401 Unauthorized] http://127.0.0.1:32337/api/v1/message/new-reply-token | id: 380761ab1fb5 | message: JWT token header does not appear to contain valid JSON
Mar 08 10:08:49 de2-leader-b fes-service.out 2023-03-08T10:08:49.453Z WARN  c.flowcrypt.shared.server.ErrorReply - Client error: [401 Unauthorized] http://127.0.0.1:32337/api/v1/message/new-reply-token | id: 5140a121b1d7 | message: JWT token header does not appear to contain valid JSON
Mar 08 16:02:26 de2-leader-a fes-service.out 2023-03-08T16:02:26.640Z WARN  c.flowcrypt.shared.server.ErrorReply - Client error: [401 Unauthorized] http://127.0.0.1:32337/api/v1/message/new-reply-token | id: 4c4646a556d2 | message: JWT token header does not appear to contain valid JSON
Mar 08 18:26:53 de3-leader-a fes-service.out 2023-03-08T18:26:53.689Z WARN  c.flowcrypt.shared.server.ErrorReply - Client error: [401 Unauthorized] http://127.0.0.1:32337/api/v1/message/new-reply-token | id: f737c52d0361 | message: JWT token header does not appear to contain valid JSON
Mar 08 18:44:18 de2-leader-b fes-service.out 2023-03-08T18:44:18.369Z WARN  c.flowcrypt.shared.server.ErrorReply - Client error: [401 Unauthorized] http://127.0.0.1:32337/api/v1/message/new-reply-token | id: 50b8939e152b | message: JWT token header does not appear to contain valid JSON
Mar 09 18:34:25 de2-leader-b fes-service.out 2023-03-09T18:34:25.574Z WARN  c.flowcrypt.shared.server.ErrorReply - Client error: [401 Unauthorized] http://127.0.0.1:32337/api/v1/message/new-reply-token | id: e4e62c199824 | message: JWT token header does not appear to contain valid JSON
Mar 09 19:06:08 de2-leader-b fes-service.out 2023-03-09T19:06:08.307Z WARN  c.flowcrypt.shared.server.ErrorReply - Client error: [401 Unauthorized] http://127.0.0.1:32337/api/v1/message/new-reply-token | id: 5743a5d2f99b | message: JWT token header does not appear to contain valid JSON
Mar 10 07:23:55 de-ekm ekm-service.out 2023-03-10T07:23:55.243Z WARN  c.flowcrypt.shared.server.ErrorReply - Client error: [401 Unauthorized] http://127.0.0.1:32356/v1/keys/private | id: 24476e0ab1d4 | message: JWT token header does not appear to contain valid JSON
Mar 10 07:24:08 de-ekm ekm-service.out 2023-03-10T07:24:08.775Z WARN  c.flowcrypt.shared.server.ErrorReply - Client error: [401 Unauthorized] http://127.0.0.1:32356/v1/keys/private | id: 1d339b0ff022 | message: JWT token header does not appear to contain valid JSON
Mar 10 07:25:06 de-ekm ekm-service.out 2023-03-10T07:25:06.011Z WARN  c.flowcrypt.shared.server.ErrorReply - Client error: [401 Unauthorized] http://127.0.0.1:32356/v1/keys/private | id: d76d2f0dae6b | message: JWT token header does not appear to contain valid JSON
Mar 10 07:26:12 de-ekm ekm-service.out 2023-03-10T07:26:12.534Z WARN  c.flowcrypt.shared.server.ErrorReply - Client error: [401 Unauthorized] http://127.0.0.1:32356/v1/keys/private | id: 62c549ab8a3e | message: JWT token header does not appear to contain valid JSON
Mar 10 07:29:48 de-ekm ekm-service.out 2023-03-10T07:29:48.031Z WARN  c.flowcrypt.shared.server.ErrorReply - Client error: [401 Unauthorized] http://127.0.0.1:32356/v1/keys/private | id: f2afeff7290c | message: JWT token header does not appear to contain valid JSON
Mar 10 07:31:45 de-ekm ekm-service.out 2023-03-10T07:31:45.581Z WARN  c.flowcrypt.shared.server.ErrorReply - Client error: [401 Unauthorized] http://127.0.0.1:32356/v1/keys/private | id: 5f7d29b9ba0f | message: JWT token header does not appear to contain valid JSON
Mar 10 07:57:31 de-ekm ekm-service.out 2023-03-10T07:57:31.613Z WARN  c.flowcrypt.shared.server.ErrorReply - Client error: [401 Unauthorized] http://127.0.0.1:32356/v1/keys/private | id: 9e71fd31f313 | message: JWT token header does not appear to contain valid JSON
Mar 10 07:57:50 de-ekm fes-service.out 2023-03-10T07:57:50.400Z WARN  c.flowcrypt.shared.server.ErrorReply - Client error: [401 Unauthorized] http://127.0.0.1:32337/api/v1/message/new-reply-token | id: fb183eab4f86 | message: JWT token header does not appear to contain valid JSON
Mar 10 07:57:53 de-ekm ekm-service.out 2023-03-10T07:57:53.282Z WARN  c.flowcrypt.shared.server.ErrorReply - Client error: [401 Unauthorized] http://127.0.0.1:32356/v1/keys/private | id: d95cb16bc768 | message: JWT token header does not appear to contain valid JSON
Mar 10 07:58:06 de-ekm fes-service.out 2023-03-10T07:58:06.222Z WARN  c.flowcrypt.shared.server.ErrorReply - Client error: [401 Unauthorized] http://127.0.0.1:32337/api/v1/message/new-reply-token | id: 971c75bb1ec6 | message: JWT token header does not appear to contain valid JSON
Mar 10 07:58:09 de-ekm ekm-service.out 2023-03-10T07:58:09.017Z WARN  c.flowcrypt.shared.server.ErrorReply - Client error: [401 Unauthorized] http://127.0.0.1:32356/v1/keys/private | id: 83891fde7483 | message: JWT token header does not appear to contain valid JSON
Mar 10 07:58:55 de-ekm fes-service.out 2023-03-10T07:58:55.877Z WARN  c.flowcrypt.shared.server.ErrorReply - Client error: [401 Unauthorized] http://127.0.0.1:32337/api/v1/message/new-reply-token | id: fe0157d618ad | message: JWT token header does not appear to contain valid JSON
Mar 10 07:58:58 de-ekm ekm-service.out 2023-03-10T07:58:58.773Z WARN  c.flowcrypt.shared.server.ErrorReply - Client error: [401 Unauthorized] http://127.0.0.1:32356/v1/keys/private | id: b94500532649 | message: JWT token header does not appear to contain valid JSON
Mar 10 09:11:26 de-ekm ekm-service.out 2023-03-10T09:11:26.381Z WARN  c.flowcrypt.shared.server.ErrorReply - Client error: [401 Unauthorized] http://127.0.0.1:32356/v1/keys/private | id: f8ed06fdc21c | message: JWT token header does not appear to contain valid JSON
Mar 10 14:16:17 de2-leader-b fes-service.out 2023-03-10T14:16:17.476Z WARN  c.flowcrypt.shared.server.ErrorReply - Client error: [401 Unauthorized] http://127.0.0.1:32337/api/v1/message/new-reply-token | id: 131809349ae9 | message: JWT token header does not appear to contain valid JSON
```

**Comment by DenBond7** [comment]
> There isn't really much other than these

I see. Anyway, It looks like the token from Google is not correct(maybe it's already deprecated) and the Google library returns an old version. 

But changes from #2171 should not affect the app and produce such behavior. We just don't handle such a situation yet. I propose fixing it via a separate issue.

If the FES server returns `401 Unauthorized` -> ask the Google library to refresh a token. It should be fixed in the current milestone, just in a separate PR. @tomholub what do yop think?

**Comment by DenBond7** [comment]
> @martgil Could you share more details? What do you see when clicking on the message in Outbox?

@martgil After sharing details, please also try to reboot your device and try to resend a message. Maybe after a reboot, the Google library will return a correct token. Just to prove the theory.

**Comment by tomholub** [comment]
> > There isn't really much other than these
> 
> I see. Anyway, It looks like the token from Google is not correct(maybe it's already deprecated) and the Google library returns an old version.
> 
> But changes from #2171 should not affect the app and produce such behavior. We just don't handle such a situation yet. I propose fixing it via a separate issue.
> 
> If the FES server returns `401 Unauthorized` -> ask the Google library to refresh a token. It should be fixed in the current milestone, just in a separate PR. @tomholub what do yop think?

id tokens have always been jwt tokens, and parts of those could have always been decoded as JSON. We have to wait for more information from Mart, but there's a good chance that there's actually a bug in this PR that may have caused it. Maybe a migration bug? I'm unsure. But it sounds like it's maybe sending a `null` or `"null"` or some other wrong value in the authrorization header. That would have caused this response, as an example.

**Comment by DenBond7** [comment]
@martgil Please pay attention to this one. This issue is blocking me a little.

**Comment by martgil** [comment]
> Just in case, please use the following build variants

This shows up when using `enterprise (debug)` build and logging in with gmail.com. It is correct.

![image](https://user-images.githubusercontent.com/46025304/224644227-191de504-002e-4be0-9ad0-fbe97f67fee1.png)

**Comment by martgil** [comment]
> Could you share more details? What do you see when clicking on the message in Outbox?

sir @DenBond7 I tried sending a new password protected message with `enterprise (debug)` build and email is sending successfully as of now.

![image](https://user-images.githubusercontent.com/46025304/224649075-c63ad9da-57ae-4573-abe4-e70b8254c417.png)

https://fes.flowcrypt.com/message/11c7deee-a26b-4c33-b33c-2fd3f2fb7e3e

**Comment by DenBond7** [comment]
> sir @DenBond7 I tried sending a new password protected message with enterprise (debug) build and email is sending successfully as of now.

Thank you, Mart. 

> For 2.): an error occur when sending the password protected message and the message will be stuck in the outbox:

Do you still have such a message in the Outbox? Please don't delete it if yes.

**Comment by martgil** [comment]
> Do you still have such a message in the Outbox? Please don't delete it if yes.

Thank you, too, sir, Den. The previous pending emails from the outbox have all been sent out. I retry sending a password-protected message again and it wasn't get stuck anymore.
