### ISSUE TITLE
choosing our own pubkey (sender) during compose/reply

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#220]
There will need to be some logic improvements in how our own pubkey is selected when encrypting a message.

I will add details

**Comment by tomholub** [comment]
Need to solve the following:
1) I may have 2 different accounts: `me@company.com` and `me@hello.eu`
2) The `me@company.com` may have several alias emails: `me@company.com`,  `contact@company.com`,  `purchases@company.com`
3) I may have many private keys that serve various purposes for these accounts
4) Which of my own public keys to encrypt for when sending out a message?
To be continued

**Comment by tomholub** [comment]
Where do we currently get our own public key? In in the private key table, or in the contacts table?

**Comment by DenBond7** [comment]
As you can see 

https://github.com/FlowCrypt/flowcrypt-android/blob/8ea029b68dd6d0f69edccb61e4e5547e13d52768/FlowCrypt/src/main/java/com/flowcrypt/email/api/email/sync/tasks/SendMessageSyncTask.java#L462

Firstly we try to get an account public key from the database. If the key not found we generate it from the private key and save it to the database,

**Comment by tomholub** [comment]
I see it. It seems to take the first private key. That is the logic that we need to improve, I'll write something up.

**Comment by tomholub** [comment]
Note to myself: this should be a high priority

**Comment by tomholub** [comment]
Use logic from here: 
https://github.com/FlowCrypt/flowcrypt-android/issues/269#issuecomment-399626697

**Comment by DenBond7** [comment]
Is it a duplicate of #269?

**Comment by tomholub** [comment]
Not exactly - #269 was about associating the accounts, and this issue depended on it for choosing pubkeys to send with. But I think you already implemented that in #269 as well, so we can close it now.

**Comment by tomholub** [comment]
Works perfectly now
