### ISSUE TITLE
Question: How to manually end an active passphrase session

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-android#2228]
The FlowCrypt browser extension has the option to manually end the passphrase session. 

As far as I know, the FlowCrypt android app doesn't have this option. So when the FlowCrypt android app users choose to use the remember passphrase temporarily option, the user would have to wait for the passphrase session to lapse or reboot the phone to force the app to ask for the passphrase after closing the app.

By having this option, we can give the users additional confidence when using the app. 

Reference: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGrcrtWVLBsDHHQVzsmTHmKPdNt

**Comment by DenBond7** [comment]
> As far as I know, the FlowCrypt android app doesn't have this option. So when the FlowCrypt android app users choose to use the remember passphrase temporarily option, the user would have to wait for the passphrase session to lapse or reboot the phone to force the app to ask for the passphrase after closing the app.

To forget a passphrase please follow `Settings` -> `Keys` -> `click on a key` -> `click FORGET PASS PHREASE`

![image](https://user-images.githubusercontent.com/2863246/223452948-13954c98-cd0c-4919-806b-c3af5a4ef6e3.png)

But anyway it's not the best UI experience. I will think about how to improve it.

**Comment by martgil** [comment]
Thank you, sir.

**Comment by DenBond7** [comment]
For me
![image](https://user-images.githubusercontent.com/2863246/227703069-9197319f-e7e0-4f21-9e4e-c419555299ba.png)

**Comment by DenBond7** [comment]
@martgil Starting from 1.4.3 in the notification will be a button `End Pass Phrase Session`. This button will be visible only if at least one pass phrase will be available in the temp cache.

![image](https://user-images.githubusercontent.com/2863246/228581254-757392ab-737e-443e-9e63-2cafe9db74d4.png)
