### ISSUE TITLE
User suggestion: option to have a threaded message view

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-android#2229]
Description: A user shows an interest in the FlowCrypt app of having threaded emails/conversation view as it would give them ease of working with emails. 

Reference: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGrcrtXtNSPmpkjBRnxMLzMMTDt

**Comment by DenBond7** [comment]
unfortunately, it will not be soon. It will take a lot of changes. I can't give you any promises for now. We have a lot of issues with the higher priorities.

**Comment by martgil** [comment]
Thank you for looking into this. I understand completely, sir.

**Comment by DenBond7** [comment]
duplicate of #74
