### ISSUE TITLE
Situation with several private keys

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#223]
Need to think about a situation when the user has several different private keys for the same email account. 

For example, I am interested in next questions:

1. When the user does set up the app and imports his private key I need to save PgpContact with his public key. What to do if the user has different private keys?
2. When the user sends an encrypted message I use his public key. What to do if the user has different private keys? (depends on 1)

I will add more cases later.

**Comment by tomholub** [comment]
Question 2) is related to #220

**Comment by DenBond7** [comment]
deprecated
