### ISSUE TITLE
User concern: a message to fix an issue randomly appearing when opening a decryptable message

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-android#2235]
Description: When opening an encrypted message, the android app occasionally shows that the message is unable to open -- even though the encrypted message was once decrypted by the FlowCrypt android app and the user has the correct key to unlock it.

I'm sharing the video via email as it contains personal information. Thanks.

Reference: https://mail.google.com/mail/u/2/#inbox/FMfcgzGrcjVnmhTXZTkgmsvVfHwCrWQV

**Comment by DenBond7** [comment]
ref https://github.com/pgpainless/pgpainless/issues/365

**Comment by DenBond7** [comment]
Fixed by https://github.com/FlowCrypt/flowcrypt-android/pull/2294
