### ISSUE TITLE
call fes.domain.com first before falling back on flowcrypt.com/shared-tenant-fes

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#2237]
@tomholub I think I've added changes that were requested to migrate to `shared-tenant-fes`. But all of these changes are related to the setup screen. we still don't support the following:

```
going forward, client continues attempting to call fes.domain.com first before falling back on flowcrypt.com/shared-tenant-fes anytime it needs to update Client Configuration, and continues using flowcrypt.com/shared-tenant-fes for password protected messages and all other APIs, for as long as fes.domain.com is not available.
if Client Configuration is ever successfully retrieved from fes.domain.com, the app will start using fes.domain.com for all APIs going forward.
```

it means we decide at the setup screen whether will we use a custom FES server or not. After the setup screen, we don't use a custom FES server if it failed at the setup screen.

If it is possible I propose adding that functionality via a separate PR. The current PR is already not simple.

If yes, I will ask Mart to recheck #2197 and after that, we will be ready to merge it.

_Originally posted by @DenBond7 in https://github.com/FlowCrypt/flowcrypt-android/issues/2171#issuecomment-1461922519_

**Comment by DenBond7** [comment]
Based on #1375 we refetch client configuration. @tomholub Will it is enough to do checking FES availability only here?

For example,  I can have the following code

![image](https://user-images.githubusercontent.com/2863246/224715874-af992506-70db-4aab-829a-02e4ecb674e3.png)

![image](https://user-images.githubusercontent.com/2863246/224716174-8119ff98-03a3-4268-9819-6011821df5e3.png)

1. ` if (BuildConfig.FLAVOR != Constants.FLAVOR_NAME_ENTERPRISE && !tempAccount.useCustomerFesUrl) ` we check FES availability
2. If FES is available we update `useCustomerFesUrl` for a current account and after that, we will use only FES for future API calls.

Or should I check FES availability in other places too(send a password-protected message)?

**Comment by tomholub** [comment]
It looks good as you've proposed it, startup is enough.

But I don't think it needs this condition: ![image](https://user-images.githubusercontent.com/6306961/224719106-8d6c8820-eb0b-404e-96a1-3dac556a1a1e.png)

But maybe you added it because of something I said - if so, please refer me to it so I can reconsider.

**Comment by DenBond7** [comment]
Based on this one https://github.com/FlowCrypt/flowcrypt-android/pull/2171#issuecomment-1450080839

> But I don't think it needs this condition:

I've skipped some details. You are right. So just `!tempAccount.useCustomerFesUrl` will be enough.

Just in case, `result.status == Status.SUCCESS` means we receive `Http status ok(200)`. All other cases(SSL error and non-200 HTTP codes) will mean failed status.

**Comment by tomholub** [comment]
Yes, plus it should be testing for `service` value that is returned. We already have that code somewhere, should reuse it.

**Comment by DenBond7** [comment]
> plus it should be testing for service value that is returned.

Good one. I forgot about it.
