### ISSUE TITLE
Update API error format on Attester

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#2241]
ref https://github.com/FlowCrypt/flowcrypt-android/pull/2171#discussion_r1087703140

FES

```
{
  "code": 401,
  "message": "Authorization credentials required",
  "details": "io.javalin.http.UnauthorizedResponse"
}
```

Attester

```
{
    "error": {
        "message": "Body should not be empty"
    }
}
```

PubLookup
```
{
  "code": 404,
  "message": "Not Found",
  "details": ""
}
```

EKM

```
{
  "code": 401,
  "message": "Authorization credentials required",
  "details": "io.javalin.http.UnauthorizedResponse: Authorization credentials required"
}
```
Backend
```
{
    "error": {
        "code": 400,
        "message": "Wrong request received",
        "internal": "Please add a json body"
    }
}
```

@tomholub Is it possible to have the same error format for all APIs? it will help to simplify code.

It would be nice to have
(I prefer this one)
```
{
    "error": {
        "_": ""
        "_": "",
        ...
    }
}
```

or 

```
{
  "_": "",
  "_": ""
}
```

**Comment by tomholub** [comment]
`Backend` will be removed completely in 3 months

**Comment by tomholub** [comment]
That leaves `Attester` to update. can do

**Comment by tomholub** [comment]
that's correct

**Comment by tomholub** [comment]
I'm not sure - the 404 is not really an error in this case, it's a result which means "I searched the pubkey successfully, and none was found"

**Comment by DenBond7** [comment]
Got it. Can we change this behavior? On Android, handling cases with different logic is not simple if we are talking about implementation. IMHO, it will be better to have the same logic over all API if it is possible. To be honest, the best choice will be using JSON even for public key. Like, `{"public_key":"..."}`. But it seems it's not possible for the particular API.

So the question is - can we return string only for success case, and JSON for other?

**Comment by tomholub** [comment]
I guess we could, but it would be somewhat harder to do it in a backwards compatible manner. I think it would require adding `?format=json` or similar.

**Comment by DenBond7** [comment]
> I think it would require adding ?format=json or similar

Sounds good. After these changes code on my side will look much simpler and understandable for other devs.
