### ISSUE TITLE
Add "Work attributions"

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#226]
In Settings -> Legal -> License, you can add a second title on the bottom: "Work attributions", where we can have a bullet point list. I have a few to put there myself, eg OpenPGP.js and more.

**Comment by DenBond7** [comment]
I have used https://github.com/k9mail/k-9

1) https://github.com/k9mail/k-9/blob/master/k9mail/src/main/java/com/fsck/k9/helper/MailTo.java. I have renamed this class to [RFC6068Parser.java](https://github.com/FlowCrypt/flowcrypt-android/blob/0.6.2/FlowCrypt/src/main/java/com/flowcrypt/email/util/RFC6068Parser.java) and excluded some info to [ExtraActionInfo.java](https://github.com/FlowCrypt/flowcrypt-android/blob/0.6.2/FlowCrypt/src/main/java/com/flowcrypt/email/api/email/model/ExtraActionInfo.java)

2) https://github.com/k9mail/k-9/blob/master/k9mail/src/main/java/com/fsck/k9/activity/MessageCompose.java. I have used lines 484-548 with some modifications. Those lines were added in [CreateMessageFragment#parseExtraActionInfo](https://github.com/FlowCrypt/flowcrypt-android/blob/a61d0ae4cc89099b41166f6be2f743c356ff0bf7/FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/base/CreateMessageFragment.java#L645)

**Comment by DenBond7** [comment]
for me https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)

**Comment by DenBond7** [comment]
**Apache 2.0**

- [com.squareup.leakcanary](https://github.com/FlowCrypt/flowcrypt-android/blob/f41500d62110e68c180c464285554d3a50b70999/FlowCrypt/build.gradle#L212)

- [implementation 'com.google.code.gson:gson:2.8.2'](https://github.com/FlowCrypt/flowcrypt-android/blob/f41500d62110e68c180c464285554d3a50b70999/FlowCrypt/build.gradle#L237)

- [implementation "com.squareup.retrofit2:retrofit](https://github.com/FlowCrypt/flowcrypt-android/blob/f41500d62110e68c180c464285554d3a50b70999/FlowCrypt/build.gradle#L247)

- [implementation "com.squareup.retrofit2:converter-gson](https://github.com/FlowCrypt/flowcrypt-android/blob/f41500d62110e68c180c464285554d3a50b70999/FlowCrypt/build.gradle#L248)

- [implementation "com.squareup.okhttp3:logging-interceptor](https://github.com/FlowCrypt/flowcrypt-android/blob/f41500d62110e68c180c464285554d3a50b70999/FlowCrypt/build.gradle#L249)

- [implementation 'commons-io:commons-io:2.6'](https://github.com/FlowCrypt/flowcrypt-android/blob/f41500d62110e68c180c464285554d3a50b70999/FlowCrypt/build.gradle#L264)

- [implementation 'ch.acra:acra:4.9.2'](https://github.com/FlowCrypt/flowcrypt-android/blob/f41500d62110e68c180c464285554d3a50b70999/FlowCrypt/build.gradle#L265)

- [implementation 'com.hootsuite.android:nachos:1.1.1'](https://github.com/FlowCrypt/flowcrypt-android/blob/f41500d62110e68c180c464285554d3a50b70999/FlowCrypt/build.gradle#L266)

**Apache 2.0, BSD 2-clause**

- [com.github.bumptech.glide](https://github.com/FlowCrypt/flowcrypt-android/blob/f41500d62110e68c180c464285554d3a50b70999/FlowCrypt/build.gradle#L260)

**CDDL, GPL 2.0**

- [com.sun.mail](https://github.com/FlowCrypt/flowcrypt-android/blob/f41500d62110e68c180c464285554d3a50b70999/FlowCrypt/build.gradle#L251)

**EPL 1.0**

- [implementation 'com.eclipsesource.j2v8:j2v8:4.8.2@aar'](https://github.com/FlowCrypt/flowcrypt-android/blob/f41500d62110e68c180c464285554d3a50b70999/FlowCrypt/build.gradle#L263)

**Comment by tomholub** [comment]
We use LeakCanary only in developement builds, is that right? We do not really ship it with the app, correct?

**Comment by DenBond7** [comment]
> We do not really ship it with the app, correct?

Yes, we use it only for debug builds.

**Comment by tomholub** [comment]
In that case we don't have to mention it.

We can still mention it if you like - in that case feel free to append the list.
