### ISSUE TITLE
an error occur when sending a password protected message 

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-android#2268]
Description: The following error occurs when the user tries to send a password-protected message to two recipients.

The error message shown is: 
```
Message failed to send: unknown error
Illegal Packet in Stream: PK
```

Screenshot from the user:
<img src="https://user-images.githubusercontent.com/46025304/227867378-77baf57e-caa9-43bf-b9f0-278825b38890.png" width="75%">

If by any chance we need more information from the user or recipient to validate the issue, please let me know. Thanks!

Reference: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGslkhQkTbVBZWZhgXjRVTsgHXq

**Comment by martgil** [comment]
The reporting user helps us by giving a step by step on how we can reproduce the issue - I followed the instructions on my emulator: 

[Screencast from 2023-03-28 12-19-44.webm](https://user-images.githubusercontent.com/46025304/228127496-b6e5668e-bade-43bf-9e61-d5903340f0bb.webm)

**Comment by DenBond7** [comment]
@martgil Could you ask what version the user use?

**Comment by DenBond7** [comment]
I've found it. That's the latest version. It's a bug. It relates only to sending pub keys as described in the video. It will be fixed in the current milestone.
