### ISSUE TITLE
Added tests for android send(view) actions

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#228]
Need to test

- Intent#ACTION_VIEW
- Intent#ACTION_SENDTO
- Intent#ACTION_SEND (support attachments)
- Intent#ACTION_SEND_MULTIPLE  (support attachments)

1. click on email links in a browser
2. click on email links in some message
3. send one file via the app
4. send multiple files via the app
5. share some information via the app (subject + body)

**Comment by tomholub** [comment]
great!
