### ISSUE TITLE
Implement Private key passphrase anti-bruteforce protection

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-android#2356]
Description:

It is suggested that we implement an anti-bruteforce mechanism for actions involving private key passphrases, such as email signing, email decryption, saving backups, updating private keys, test passphrase, and loading private keys.

The flow of the anti-bruteforce mechanism should ideally be as follows: a 5-minute delay after 5 consecutive unsuccessful attempts.

Reference: https://github.com/FlowCrypt/flowcrypt-security/issues/219

**Comment by DenBond7** [comment]
@sosnovsky We need to discuss it. For now, we have a few places where a user can provide a pass phrase

1. Import a private key. As I understand we don't need to apply restrictions here.
2. Create an encrypted message
3. Open an encrypted message
4. Saving backups
5. updating private keys
6. test passphrase

On Android for 2-6, we show the following screen
![image](https://github.com/FlowCrypt/flowcrypt-android/assets/2863246/44747ca7-28dc-44d3-abc0-fc0c8c25c80f)

Roma, could you provide an example of a hint that I should show to a user?
For example: `you have 5 attempts, after that typing will be blocked for 10 minutes`

Also, after blocking, we can show a countdown timer on the green button.

As I understand we have to save the timestamp for the last unsuccess attempt. And this time should be separate for existing accounts.

**Comment by DenBond7** [comment]
- [ ] check database migration

**Comment by sosnovsky** [comment]
> [ ] check database migration

Maybe it's possible to implement it simpler way, without adding database fields?
For example, by using `SharedPreferences` to store timestamps

**Comment by DenBond7** [comment]
it's possible to use [DataStore](https://developer.android.com/topic/libraries/architecture/datastore) as an alternative option. I will investigate it.

**Comment by DenBond7** [comment]
> You had 5 failed passphrase attempts. For security purposes, we blocked you from entering passphrase for the next five minutes. Please wait for the specified duration before attempting to enter your passphrase again.

@sosnovsky I have one more question. Imagine the following situation

1. A user opens an encrypted message
2. The app asks for the pass phrase
3. The user provides a wrong pass phrase. 4 attempts left
4. The user provides a wrong pass phrase. 3 attempts left
5. The user lefts the message details screen.
6. The user comes back to this screen in 1 hour.
7. Question: does he have 3 attempts left or should I reset the attempts counter after some time?

**Comment by sosnovsky** [comment]
Let's reset it after 30 minutes of last unsuccessful attempt:
1) user made 3 unsuccessful attempts
2) tries again in 20 minutes - counter increases to 4th attempt, then 5th
3) if tries in more than 30 minutes - counter resets and starts from 1st attempt

**Comment by DenBond7** [comment]
Check the following cases

- [ ] Create an encrypted message
- [ ] Open an encrypted message
- [ ] Saving backups
- [ ] updating private keys
- [ ] test passphrase

**Comment by DenBond7** [comment]
@sosnovsky I've added the requested functionality. Please look at the video.

https://github.com/FlowCrypt/flowcrypt-android/assets/2863246/0a1ecdd4-2731-48f0-8521-ed5ac925d8cd

https://github.com/FlowCrypt/flowcrypt-android/assets/2863246/abde8530-5cd1-4cd8-a526-e083e5df4cb8

**Comment by sosnovsky** [comment]
Looks great 👍
