### ISSUE TITLE
consider option to only show encrypted messages in inbox

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#236]
ref https://mail.google.com/mail/u/0/#sent/1611a79404a3d3c0

> I think a good feature for the Android app would be filtering inbox to see only encrypted emails or moving encrypted ones to the top. 
> 
> I don't want or need to encrypt everything. But when I open Flowcrypt, I do.

**Comment by DenBond7** [comment]
It will be easy to do after I will complete #215

**Comment by DenBond7** [comment]
![switch](https://user-images.githubusercontent.com/2863246/41284068-f478e53c-6e40-11e8-9cc8-c0e069674e26.jpg)

**Comment by DenBond7** [comment]
> The app should remember the setting after closing though. 

I don't know is that a good idea or not. This option looks like a filter of already cached messages but it's not an ability to load only encrypted messages. I need to load a message to know that is encrypted or not. And I can do that only in "load all" mode (when we are scrolling the list). A user can have 500 messages and only the 501 message can be encrypted. If we'll apply "Show only encrypted messages" the user will see only a progress bar for a few minutes.

**Comment by tomholub** [comment]
Can we use search queries? That way we would be loading messages that are much more likely to be encrypted. For example, a gmail search query could look something like this:

`PGP OR GPG OR OpenPGP OR filename:asc OR filename:message OR filename:pgp OR filename:gpg `

**Comment by tomholub** [comment]
Of course, this would not work for non-gmail accounts.

**Comment by DenBond7** [comment]
> Can we use search queries?

I think we can. But I'll answer this question after I'll complete #137

**Comment by DenBond7** [comment]
#89 
Need to update the notification settings if a user will select the option `Only encrypted`. In that case, we will not allow selecting "All messages" (It does not make sense). Maybe will be better to show only two options: `Encrypted messages only` and `Never`

**Comment by tomholub** [comment]
When I switch, it says:
> Showing only encrypted messages. The cache will be reloaded. [cancel, continue]

I think this is too intrusive. It's a great idea to tell the user what is happening, but I think toast would be perfect for this. Please show a toast (LENGTH_LONG) as follows:
> Showing only encrypted messages

or

> Showing all messages

Just a toast, no need to have user click "ok".

**Comment by DenBond7** [comment]
I've added the dialog to prevent a fast switch between variants and an accidental clicking. Because the switching needs some time to cancel old tasks and reload the cache. Maybe we can use another text?

**Comment by tomholub** [comment]
Also, remember to put the button to correct position and enable it if there was an error (eg network?)

**Comment by tomholub** [comment]
Perfect, works well
