### ISSUE TITLE
way to add/load public keys from settings

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#239]
ref https://mail.google.com/mail/u/0/#inbox/16294ce6425923a3

**Comment by tomholub** [comment]
I first want to specify this for you, this may work a bit different than the browser extension

**Comment by DenBond7** [comment]
Ok. Currently, I can work on different task. So it's not urgent.

**Comment by DenBond7** [comment]
Please add details to this issue when you will have a free time. I'm ready to start.

**Comment by tomholub** [comment]
- there should be a `(+)` floating action button on the contacts screen (same style as inbox screen)
- clicking it should show a screen:
```
<- Add Contact               (?)                  | page title in green background
________________________________

Add public keys of your contacts
to send them encrypted messages.

[ _______________ ] [search]

[      load from file      ]

[     load from clipboard  ]

```

`load from file` will load and `load from clipboard` will do the same thing:
1) parse the contents with `MessageBlock[] js.crypto_armor_detect_blocks(String message)`. I will expose this function soon.
2) Filter blocks to only include block type: public key
3) Display blocks similar to how you display them in message view
4) If there is > 1 blocks, add "import all" button on the top
If it doesn't contain any key, show "No public key found"

The input field next to search will have placeholder/hint: `Key id or email`. Clicking `search` will:
1) use `/lookup/[query]` attester API. This will accept email, key id or fingerprint for search in the url. Examples: https://attester.flowcrypt.com/lookup/human@flowcrypt.com or https://attester.flowcrypt.com/lookup/0C9C2E6A4D273C6F and many similar formats should work.
2) extract the public key and follow same process as if `load from file` was used

**Comment by DenBond7** [comment]
> If there is > 1 blocks

@tomholub How do you think how much blocks can be here? (2-3, more 5 and etc.). Because my realization can depend for it.

**Comment by tomholub** [comment]
There could potentially be many, many blocks. Try to go to FlowCrypt Extension -> Additional Settings -> Contacts -> export.

If I did that right now, and imported it into Android, it would be 1300!

If there are more than 10, you should probably just show "import all" only, and don't actually render all the blocks.

**Comment by tomholub** [comment]
That is only if someone uses bulk export. Most commonly, there will be one. Sometimes 2-3. And sometimes very many when people export all from other software.

**Comment by DenBond7** [comment]
I've completed this issue. I've simplified some UI. But if need I can add other views.

**Comment by tomholub** [comment]
great, I'll test it
