### ISSUE TITLE
[User Feedback] Accessibility of archived email

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-android#2398]
Description: The following user concern below was about the user having some difficulty accessing an email that was accidentally archived. The FlowCrypt android app seems do not have a dedicated label for archived emails so it's a bit difficult to access older archived emails. They will need to go to "All Mail" and find the archived email(s). 

Reference: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGtwCwmrHlGnFjLksTFxFQXQTdM

**Comment by DenBond7** [comment]
@martgil Could you add more details? Maybe screenshots or video

**Comment by martgil** [comment]
Hello @DenBond7 - Greetings!

The scenario can be described as follows:

While scrolling through the "Inbox" section, a user accidentally swipes a specific email, causing it to be archived unintentionally. Since the incident happened quickly, the user does not remember the subject of the email, making it difficult to locate. The only way to find the email again is by navigating to the "All Mail" section and searching for keywords or phrases related to the email. It is important to note that there is no indication for the user if an email has already been archived in the "All Mail" section, making it challenging to identify and unarchive such emails.

Please note that I am unable to receive or view the video you mentioned.

**Comment by martgil** [comment]
In my opinion, it might be helpful to have a tag or badge, such as "archived email," for the archived emails in the "All Mail" section. Alternatively, having a specific label for archived emails could also eliminate the need for a tag or badge.

**Comment by DenBond7** [comment]
Thank you, Mart. Now I see what is wrong. It looks like we have a bug and the app doesn't show `Move to Inbox` action. It used to work some time ago but now it doesn't. I will fix it.

> The only way to find the email again is by navigating to the "All Mail" section and searching for keywords or phrases related to the email. It is important to note that there is no indication for the user if an email has already been archived in the "All Mail" section, making it challenging to identify and unarchive such emails.

Yes, it is true. It's a default behavior for Gmail based on https://support.google.com/mail/answer/6576?co=GENIE.Platform%3DDesktop&hl=en. Gmail doesn't show any labels for archived messages either. Technically  `Archived` should be read as a message without an `Inbox` label. It means that such a message will be visible only in `All Mail` folder.

Need to add that we've already added labels support. So maybe when 1.4.7 is released the user experience will be better.

**Comment by martgil** [comment]
Thank you too, I now understand the scenario better than I did before.

**Comment by DenBond7** [comment]
For history(will be updated)
- `Arhive` action should be enabled on the message details screen if a message contains `INBOX` label.
-  Because technically `Archived` should be read as a message without an `INBOX` label, the app should remove a message in the `INBOX` folder after use the `Arhive` action

**Comment by DenBond7** [comment]
Need to add tests for message archiving via Gmail API

**Comment by DenBond7** [comment]
@martgil I'm adding a short video example how it works now

https://github.com/FlowCrypt/flowcrypt-android/assets/2863246/f47f01c3-7f85-4a3e-a025-2a6fa6e5f743

**Comment by martgil** [comment]
Thank you. It is now easier to manage the archived emails that way, as they can be moved to the "Inbox" directly and conveniently.
