### ISSUE TITLE
contacts: load in the background

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#240]
I want to send first email, but when I enter recipient's first name, the app cannot suggest any email. The experience of using the app the very first time is suffering because the contacts are not loaded yet.

> We are adding the contacts when we are loading the sent folder

We could do one of two things:

1) Start loading contacts in the background from sent folder from the moment user grants permissions
2) Have a mechanism to load contacts as user types the recipient using `Gmail API search` (flowcrypt-browser does this)

We could also combine the two approaches. For simplicity, (1) will probably be sufficient, as it should load the most recently used contacts first - good enough.

**Comment by tomholub** [comment]
I put this here for consideration, let me know how long you think it would take to a basic version of this

**Comment by DenBond7** [comment]
> how long you think it would take to a basic version of this

I hope I will complete it today.

I have decided use the next command: `FETCH 1:* (FLAGS BODY[HEADER.FIELDS (TO CC BCC)]) `in the sent folder. This command return for example the next line:

```
* 240 FETCH (BODY[HEADER.FIELDS (BCC CC TO)] {96}
    Cc: denbond7test@test.com
    To: Den Den Google <denbond7@test.com>
    Bcc: denbond7@test.com
    )
```
I think it will be not very expensive (I mean the internet traffic). Later I will add an approximate value for 1000 messages(in kb). And then we will know how it expensive.

**Comment by DenBond7** [comment]
For me http://book2s.com/java/src/package/com/hs/mail/imap/message/builder/fetchrequestbuilder.html#b070bf43bcc1206ba339a1a05a97b87f

**Comment by DenBond7** [comment]
Request for 1000 messages takes around 5 sec and I receive around 140 kb of information (WIFI with 100 Mbit). I think it's not expensive and we can use my realization.

**Comment by tomholub** [comment]
The user will not have to wait for this, right? It's happening in the background?

**Comment by DenBond7** [comment]
> The user will not have to wait for this, right? It's happening in the background?

Of course. I'm using the passive queue.

**Comment by tomholub** [comment]
Perfect
