### ISSUE TITLE
don't rely on content-description header when rendering pgp/mime

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#2402]
> I tried to send FES reply message with attachment from #5129 - it works well on browser extension:
> 
> <img alt="Screenshot 2023-07-26 at 13 49 02" width="400" src="https://private-user-images.githubusercontent.com/1062093/256207691-dafcf5af-4c69-4af6-b496-25f9624b6368.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE2OTAzNzYwNjIsIm5iZiI6MTY5MDM3NTc2MiwicGF0aCI6Ii8xMDYyMDkzLzI1NjIwNzY5MS1kYWZjZjVhZi00YzY5LTRhZjYtYjQ5Ni0yNWY5NjI0YjYzNjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMDcyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzA3MjZUMTI0OTIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDJmYWNkOWI4MTc3MzQyMDVhOTJkNGMyOGI4ZDgyYmNiZGVlZGZhNzA5MDEzMjg5YmZiMTQwNDc3ZDhjYjJlMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.x5-A5vWXtuTsTuL5ThCEpaREUjvKe4nUrkVy60FxuxE">
> But on Android it renders unnecessary `Version: 1` line:
> 
> <img alt="Screenshot 2023-07-26 at 13 47 47" width="293" src="https://private-user-images.githubusercontent.com/1062093/256207773-7891ef9b-46e2-4f49-ab2d-5be3708a93ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE2OTAzNzYwNjIsIm5iZiI6MTY5MDM3NTc2MiwicGF0aCI6Ii8xMDYyMDkzLzI1NjIwNzc3My03ODkxZWY5Yi00NmUyLTRmNDktYWIyZC01YmUzNzA4YTkzYWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMDcyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzA3MjZUMTI0OTIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTY0MTU1ODliZjE4NzRkZjUwM2YxOTRhZjQ2ZDliMWY3NDhmNDMwOTBlZjdkYTQwMmJlMmViM2NhZjg5MDNiMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.NOPoq71SxFBaLa3redxNSusAXZG98mlsUBjTNpG6YDU">

Above example without the description header

Below example with it:

> > Added "Content-Description"
> 
> Now it looks good on Android too:
> 
> <img alt="Screenshot 2023-07-26 at 15 27 27" width="296" src="https://private-user-images.githubusercontent.com/1062093/256229939-89203677-a00a-4096-a7bb-f3eda81fe942.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE2OTAzNzYwNjIsIm5iZiI6MTY5MDM3NTc2MiwicGF0aCI6Ii8xMDYyMDkzLzI1NjIyOTkzOS04OTIwMzY3Ny1hMDBhLTQwOTYtYTdiYi1mM2VkYTgxZmU5NDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMDcyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzA3MjZUMTI0OTIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjgwMjE2M2JkYWVlMTc5NTBiYzdjODRkNmU5MTljMzhjYjc1NDQ5MjdmOWNmNzU0NTk1Y2ZjZWIwOTk4ZTk5YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.wOfj8aDVUa--u7pGeOkaa-uVlGbLNQ689IY0rXQhSw0">

I think Android rendering should not rely on the conent-description header. I'll file an issue on Android.

_Originally posted by @tomholub in https://github.com/FlowCrypt/enterprise-server/issues/4204#issuecomment-1651744142_

**Comment by IvanPizhenko** [comment]
Browser extension uses some logic based on the part index to hide "version" part". Here's what I found (in the file `attachment.ts`):
```ts
  public static treatAsForPgpEncryptedAttachments = (mimeType: string | undefined, pgpEncryptedIndex: number | undefined) => {
    let treatAs: 'hidden' | 'encryptedMsg' | undefined;
    if (mimeType === 'application/pgp-encrypted' && pgpEncryptedIndex === 0) {
      treatAs = 'hidden';
    }
    if (mimeType === 'application/octet-stream' && pgpEncryptedIndex === 1) {
      treatAs = 'encryptedMsg';
    }
    return treatAs;
  };
```
