### ISSUE TITLE
compose and reply screen design - input fields

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#241]
![image](https://user-images.githubusercontent.com/6306961/38633097-33e4162c-3df1-11e8-8856-9cd6112386f8.png)

I'm thinking that this could work differently: maybe clicking the down chevron could open up a menu that says `Add CC` and `Add BCC`. When I click on them, it will let me enter email address as usual, but when I'm done, the bubble/chip will show `cc:email@domain.com` or `bcc:email@domain.com` right next to the `to` fields. If there are too many of them, it would show a chip saying `+5 cc` or something similar.

**Comment by DenBond7** [comment]
Deprecated. We already have something similar.
