### ISSUE TITLE
[Feature suggestion] Ability to mark/flag email as spam, junk, or phishing  

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-android#2430]
Description: We have received a feature suggestion for the Android app: the ability to flag/move emails as spam, junk, or phishing. They find the said feature to be helpful.

Reference: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGtwqFGqfvtRLkHrmrbQNwtwVbb

**Comment by DenBond7** [comment]
- [ ] spam
- [ ] unspam

**Comment by martgil** [comment]
Thanks, Den and Ioan. I will now notify the team about the issue regarding the inclusion of this feature in the upcoming release.
