### ISSUE TITLE
Hide app content when app is in background

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-android#2442]
details - https://github.com/FlowCrypt/flowcrypt-security/issues/264

**Comment by DenBond7** [comment]
@sosnovsky I can add 

```
window.setFlags(
            WindowManager.LayoutParams.FLAG_SECURE,
            WindowManager.LayoutParams.FLAG_SECURE
)
```

![image](https://github.com/FlowCrypt/flowcrypt-android/assets/2863246/ef7f6db7-44c1-46fb-9333-c46b0424dfaf)

But this will [disable](https://developer.android.com/reference/android/view/WindowManager.LayoutParams#FLAG_SECURE) making screenshots too. Do we need the ability to make screenshots in the app?

**Comment by sosnovsky** [comment]
Yes, I think taking screenshots should still be allowed in the app. Maybe it's possible to apply this flag only when app is in background, like described here - https://stackoverflow.com/a/49442984/3091318 ?

**Comment by sosnovsky** [comment]
Also there is [setRecentsScreenshotEnabled](https://developer.android.com/reference/android/app/Activity#setRecentsScreenshotEnabled(boolean)) property added in Android 12, we can use it for Android 12+, and [View#onWindowFocusChanged(boolean)](https://stackoverflow.com/a/74823014/3091318) for older versions. What do you think, will it work?

**Comment by DenBond7** [comment]
> Yes, I think taking screenshots should still be allowed in the app. Maybe it's possible to apply this flag only when app is in background, like described here - https://stackoverflow.com/a/49442984/3091318 ?

Yes, it's possible. Also, need to add that starting from Android 12 we have a little different behavior. Please look at the example
![ezgif com-optimize](https://github.com/FlowCrypt/flowcrypt-android/assets/2863246/d7d3079f-058a-4e24-9026-bf1666107424)
Content will be hidden after switching to other apps. (At this stage the app will have a paused state)
