### ISSUE TITLE
[Feature suggestion] Implement Folder Icons in Side Menu to Match iOS App UI

### ISSUE THREAD

**Issue by ioanmo226** [FlowCrypt/flowcrypt-android#2446]
iOS app has neat folder icons in the side menu.
It would make the UI look more polished and consistent across platforms.

![image](https://github.com/FlowCrypt/flowcrypt-android/assets/77344191/f2a62224-3878-4161-a246-806820e26aec)

@DenBond7 What's your thoughts?

**Comment by DenBond7** [comment]
Looks great! I will add icons in the next release.

**Comment by DenBond7** [comment]
@ioanmo226 or @sosnovsky Could you share icons or show me where they are located?

**Comment by ioanmo226** [comment]
iOS app uses [SFSymbols](https://developer.apple.com/sf-symbols/)
![image](https://github.com/FlowCrypt/flowcrypt-android/assets/77344191/100b9034-d260-4ab1-ac9c-cee7e346aa50)

**Comment by DenBond7** [comment]
Is it possible to have SVG or PNG?

**Comment by ioanmo226** [comment]
Ok, let me export to SVG and share it here

**Comment by ioanmo226** [comment]
This envelope(For inbox folder) is exported from SF symbols.
Can you use it or you need in another format?

![envelope](https://github.com/FlowCrypt/flowcrypt-android/assets/77344191/63ac3704-bf59-4e27-8104-b34bf858035c)

**Comment by ioanmo226** [comment]
Just got those icons from https://github.com/brendanballon/sfsymbols-svg
Here's mapping for each icon for folders

```swift
var mailFolderIcon: String {
  switch self {
  case "INBOX":
      return "envelope"
  case "CHAT":
      return "message"
  case "SENT":
      return "paperplane"
  case "IMPORTANT", "":
      return "tag"
  case "TRASH":
      return "trash"
  case "DRAFT":
      return "square.and.pencil"
  case "SPAM":
      return "exclamationmark.shield"
  case "STARRED":
      return "star"
  case "UNREAD":
      return "envelope.badge"
  default:
      return "tag.fill"
  }
}
```
[Archive.zip](https://github.com/FlowCrypt/flowcrypt-android/files/12495673/Archive.zip)

**Comment by DenBond7** [comment]
> Just got those icons from https://github.com/brendanballon/sfsymbols-svg

Perfect! Thank you!

**Comment by sosnovsky** [comment]
Maybe Android has some built-in icons set? So we can use it, instead of icons exported from iOS

**Comment by DenBond7** [comment]
I'm thinking about that. And maybe due to different licenses, it will be better to use Android icons. I will try to find similar icons in the Android set.

**Comment by sosnovsky** [comment]
I think `Material Icons` are the most common for Android projects - https://developer.android.com/reference/kotlin/androidx/compose/material/icons/package-summary

**Comment by DenBond7** [comment]
yup. you are right

**Comment by DenBond7** [comment]
![image](https://github.com/FlowCrypt/flowcrypt-android/assets/2863246/667bb424-a480-41bf-9f0d-00d9f5b31c2a)

**Comment by sosnovsky** [comment]
Looks nice 👍
