### ISSUE TITLE
Labels list improvements

### ISSUE THREAD

**Issue by ioanmo226** [FlowCrypt/flowcrypt-android#2448]
Duplicate of https://github.com/FlowCrypt/flowcrypt-ios/issues/2265

- hide labels from side menu when they have labelListVisibility=false
- highlight label icon with color.backgroundColor property for user labels

iOS app screenshot
![image](https://github.com/FlowCrypt/flowcrypt-android/assets/77344191/fcafd7b5-2401-48b1-aa60-d8d20e81fbf6)

Android app screenshot
![image](https://github.com/FlowCrypt/flowcrypt-android/assets/77344191/eeb34745-cb47-4a60-be0b-2439f6cf8149)

**Comment by DenBond7** [comment]
@sosnovsky @ioanmo226 
I'm not sure that we have to use [labellistvisibility](https://developers.google.com/gmail/api/reference/rest/v1/users.labels#labellistvisibility) property in the mobile apps.

Based on the documentation we have the following

![image](https://github.com/FlowCrypt/flowcrypt-android/assets/2863246/0c73ef86-2670-4b56-a91d-6bd9a2281297)

It looks like it relates only to the web interface. And the Gmail web client doesn't hide a label at all, just moves it under `More` section. I've checked the `Gmail for Android` and it doesn't hide such a label.

Just imagine that some user can hide the `Drarts` or `Trash` folder (moves them under `More` section). In the web UI it will look like this one

![image](https://github.com/FlowCrypt/flowcrypt-android/assets/2863246/fe389278-ce01-40ce-8ccf-29fc923c4ddb)
![image](https://github.com/FlowCrypt/flowcrypt-android/assets/2863246/c2992e15-dfdf-4e96-92aa-4a75c03a6cd7)

But in the mobile UI it will look like this one

![image](https://github.com/FlowCrypt/flowcrypt-android/assets/2863246/c816a956-44de-4024-943e-539ef6b34df9)

The user will not be able to check the `Drarts` or `Trash` folder.

**Comment by DenBond7** [comment]
- [ ] check database migration

**Comment by sosnovsky** [comment]
I think `labelListVisibility` applies to the custom labels created by user - on my account `Trash` folder is hidden below `More` toggle, but it's still visible in FlowCrypt iOS app.

**Comment by DenBond7** [comment]
Android 
![image](https://github.com/FlowCrypt/flowcrypt-android/assets/2863246/4f6fd4a0-ac91-4cf6-9a93-fc5a09d70672)

web
![image](https://github.com/FlowCrypt/flowcrypt-android/assets/2863246/5e6bd116-db07-432f-9e5c-b63b0b7609ad)

**Comment by ioanmo226** [comment]
IMO Better to sort by name like gmail web does.

**Comment by DenBond7** [comment]
> IMO Better to sort by name like gmail web does.

Do you mean the user labels?

**Comment by ioanmo226** [comment]
Yep. As you can see`notify_user` label is at the bottom of Android screen but it's at top in Gmail web side.
