### ISSUE TITLE
Add Avatar Support in Thread List and Details View

### ISSUE THREAD

**Issue by ioanmo226** [FlowCrypt/flowcrypt-android#2451]
I recently implemented avatars in the thread list and details view on our iOS app.
Used Letter Avatars for the time being(Couldn't find a way to show actual avatars), but it definitely spruces up the UI.

Here's what it looks like on iOS:
![image](https://github.com/FlowCrypt/flowcrypt-android/assets/77344191/ea0bf2a4-c71d-43c5-8f60-58bbba9f5bc4)

It'd be awesome to mirror this feature on the Android side. What do you think?

Ref: https://github.com/FlowCrypt/flowcrypt-ios/pull/2320

**Comment by DenBond7** [comment]
Will do ))

**Comment by DenBond7** [comment]
@ioanmo226 Could you share avatar colors?

I need something like `0xFF000000` as a color definition.

```
@ColorInt public static final int BLACK       = 0xFF000000;
    @ColorInt public static final int DKGRAY      = 0xFF444444;
    @ColorInt public static final int GRAY        = 0xFF888888;
    @ColorInt public static final int LTGRAY      = 0xFFCCCCCC;
    @ColorInt public static final int WHITE       = 0xFFFFFFFF;
```

**Comment by ioanmo226** [comment]
I used third party library named `LetterAvatarKit`.
Here is color definition.
You may check this.

https://github.com/vpeschenkov/LetterAvatarKit/blob/21a6abe52835dbbb3e1c1fc91ae7275673733b36/LetterAvatarKit/Extensions/UIColor%2BLetterAvatarKit.swift#L103

**Comment by DenBond7** [comment]
> You may check this.
https://github.com/vpeschenkov/LetterAvatarKit/blob/21a6abe52835dbbb3e1c1fc91ae7275673733b36/LetterAvatarKit/Extensions/UIColor%2BLetterAvatarKit.swift#L103

I've used those colors. Now we have the same colors on both platforms. But for now, we have a different logic where we select colors for some strings. unfortunately, I don't understand `UIColor+LetterAvatarKit.swift` and can't convert it to `Kotlin`. As a result, for example, `ioan@flowcrtypt.com` will have `red` color on iOS, and `green` color on Android.

![image](https://github.com/FlowCrypt/flowcrypt-android/assets/2863246/01ec5f13-1064-406a-a823-ff43b28df25b)

**Comment by ioanmo226** [comment]
I think this doesn't hurt us? @sosnovsky What do you think?

> But for now, we have a different logic where we select colors for some strings. unfortunately

**Comment by ioanmo226** [comment]
I think better to add spacing between avatar and username&title view.

**Comment by ioanmo226** [comment]
Ok, For reference, if we have to set color to exactly same as iOS, here's iOS logic

https://github.com/vpeschenkov/LetterAvatarKit/blob/21a6abe52835dbbb3e1c1fc91ae7275673733b36/LetterAvatarKit/LetterAvatarBuilder.swift#L52

```swift
let usernameInfo = UsernameInfo(
    username: username,
    singleLetter: configuration.useSingleLetter
)
var colorIndex = 0
if colors.count > 1 {
    colorIndex = usernameInfo.ASCIIValue
    colorIndex *= 3557 // Prime number
    colorIndex %= colors.count - 1
}
let backgroundColor = colors[colorIndex].cgColor
```

**Comment by DenBond7** [comment]
> I think better to add some spacing between avatar and username&title view though.

Is it better? was 5, now 8. I'm trying to keep more space for text ))

![image](https://github.com/FlowCrypt/flowcrypt-android/assets/2863246/31a984c8-a989-4547-aede-05506a4c8a73)

**Comment by ioanmo226** [comment]
:-) Looks good on my side
