### ISSUE TITLE
enable thread selection/deselection by clicking the avatar as well

### ISSUE THREAD

**Issue by ioanmo226** [FlowCrypt/flowcrypt-android#2452]
In inbox screen, after user select email threads with long press, users can't deselect threads.
Currently, the only workaround is to hit the back button and reselect threads, which doesn't seem user-friendly.

PS: After adding avatars feature, we may need to enable thread selection/deselection by clicking the avatar as well? (In addition to long press thread)

**Comment by ioanmo226** [comment]
https://github.com/FlowCrypt/flowcrypt-android/assets/77344191/18322755-6107-47c2-b885-ceb98dc67c69

**Comment by ioanmo226** [comment]
As you can see from above video, you can't deselect selected threads.

**Comment by DenBond7** [comment]
Interesting...
I have the following situation

![ezgif com-optimize](https://github.com/FlowCrypt/flowcrypt-android/assets/2863246/134dcfbf-d7c4-4446-9647-62d522b3d834)

Could you share your emulator settings?

**Comment by DenBond7** [comment]
I have the following
![image](https://github.com/FlowCrypt/flowcrypt-android/assets/2863246/dbb07a27-b6af-463d-89eb-06272a0fc5ac)

**Comment by ioanmo226** [comment]
Ohh... you are right.
I only tried to long press to deselect. I can see that I can deselect threads by just tapping it.
Sorry for confusion.

We may only consider this one in this issue.
> PS: After adding avatars feature, we may need to enable thread selection/deselection by clicking the avatar as well? (In addition to long press thread)

**Comment by DenBond7** [comment]
I've renamed the issue

**Comment by DenBond7** [comment]
![ezgif com-optimize (1)](https://github.com/FlowCrypt/flowcrypt-android/assets/2863246/8735a8e7-93e0-428f-9c6b-0b75861f2ceb)

**Comment by ioanmo226** [comment]
@DenBond7 How about we make the checkbox color match the main green, like the 'Add' button and header background? For selected rows, maybe a 0.1-0.2 opacity of the main green could work for both dark and light themes, similar to iOS. 

Keeps things consistent and iOS-friendly. Thoughts?

**Comment by DenBond7** [comment]
Could share a video or screenshots? I don't have the latest iOS version.

**Comment by ioanmo226** [comment]
https://github.com/FlowCrypt/flowcrypt-ios/pull/2321
You may check video here

**Comment by DenBond7** [comment]
@ioanmo226 a newer version. What do you think?

![ezgif com-optimize (1)](https://github.com/FlowCrypt/flowcrypt-android/assets/2863246/048e729d-d273-4c0b-a9f8-eaea6d918a6b)

**Comment by ioanmo226** [comment]
Perfect!
