### ISSUE TITLE
Need to add Label management to the message list

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#2471]
Need to add Label management to the message list. For a separate issue. This one can be closed.

_Originally posted by @DenBond7 in https://github.com/FlowCrypt/flowcrypt-android/issues/2020#issuecomment-1759596392_

**Comment by martgil** [comment]
Users that needs to be informed once the said feature has been implemented:

https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRGRsHzzvktlltPPhtHtjHKdD
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGxSRMQzTkQJQDpfphWGzsPCdfk

**Comment by DenBond7** [comment]
How Gmail does bulk change for labels:

1. Imagine we have 10 messages. All of them have the `Inbox` label
2. Imagine the 2-nd message has `Test` label
3. Imagine the 5-th message has `Invoices` label
4. When a user selects all these messages to change labels in bulk the app shows a dialog where `Inbox`, `Test`,`Invoices` will be marked as checked. It means if a label is applied in any message this label will be checked by default in the above dialog.
