### ISSUE TITLE
Replace public key request is sent even when there's no public key recorded in the Attester

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-android#2514]
### Description

When a new user sets up the FlowCrypt Android app for the first time without any existing public key record on the Attester, a request to replace a public key should not be sent to the user's inbox.

![image](https://github.com/FlowCrypt/flowcrypt-android/assets/46025304/e2a76db1-b015-4e8d-af34-326e3f850820)

### Expected Behavior

A prompt could be implemented to allow users to decide whether to submit their public key to the attester or not. Additionally, inform them if there is an existing public key record on the Attester and inquire whether they wish to overwrite it or not.

### Steps to reproduce
1. Pre-check that the email address for which you are creating a key doesn't have a public key record at [Attester](https://flowcrypt.com/lookup).
2. Once confirmed, open the FlowCrypt android app and set up an account with the email address that underwent the pre-check.
3. Open the inbox and observe that the email requesting the replacement of a public key has been sent.

Reference:
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGwHpWBGcbxXBkhWJCCzrZkkjNt

**Comment by DenBond7** [comment]
It looks like a backend issue. @sosnovsky please look at this one. Can you reproduce it on iOS?

**Comment by martgil** [comment]
> Can you reproduce it on iOS?

@DenBond7 I tried to replicate the issue on the FlowCrypt iOS app and the issue were not present. There, it sends the FlowCrypt welcome message instead of the replace public key request.

**Comment by DenBond7** [comment]
Thank you, Mart. In that case, it looks like Android sends two requests instead of one. I will investigate it.

**Comment by martgil** [comment]
Thank you, too. I would like to add that in my testing case, the welcome message wasn't sent, only the replace public key request.
