### ISSUE TITLE
Missing dark mode for "error" message block

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-android#2525]
When opening in dark mode message with missing key for decryption, block with action buttons has light UI:

<img src="https://github.com/FlowCrypt/flowcrypt-android/assets/1062093/cbbd1daa-4d6c-4b8d-a4f8-3abd9bcc2472" width="300">

**Comment by DenBond7** [comment]
https://issuetracker.google.com/issues/62369594
https://stackoverflow.com/questions/36057597/how-can-we-tile-a-vector-image

**Comment by DenBond7** [comment]
| Day | Night |
|-----|-------|
| ![image](https://github.com/FlowCrypt/flowcrypt-android/assets/2863246/cd804828-e06b-473f-bba1-54398d348ad8) | ![image](https://github.com/FlowCrypt/flowcrypt-android/assets/2863246/34a21e02-e044-4306-a315-1cf359a37945)   |

**Comment by DenBond7** [comment]
ref https://github.com/FlowCrypt/flowcrypt-android/issues/2075
