### ISSUE TITLE
improving cut/paste behavior

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#253]
following from https://github.com/FlowCrypt/flowcrypt-android/issues/218

1) put two emails in the recipient field
2) select both, choose "cut"
3) click in empty field, choose "paste"

you will see single bubble `first@email.comsecond@email.com` Also, this email will end up getting saved into contacts :)

Suggestions:
 - make sure to separate emails with a separator when cutting. This could be a space ` ` or a comma `,`
 - make sure to first split pasted string by any strings of whitespaces: commas, spaces, newlines, tabs, ...
 - always do email address format validation before saving into contacts (maybe throw/catch exception if not a valid email?)

**Comment by DenBond7** [comment]
> always do email address format validation before saving into contacts (maybe throw/catch exception if not a valid email?)

@tomholub It's strange. Maybe need to fix `js.str_is_email_valid(email)`

As I've understood from [here](https://en.wikipedia.org/wiki/Email_address#Local-part), local-part does't approve `@`. So the user email must contain only one `@`

![image](https://user-images.githubusercontent.com/2863246/39471295-17c6e3f2-4d4b-11e8-8418-a630a6b224f0.png)

**Comment by tomholub** [comment]
Interesting, looks like that should be fixed

**Comment by DenBond7** [comment]
> make sure to separate emails with a separator when cutting. This could be a space ` ` or a comma `,`

Currently, I separete emails with  ` `

https://github.com/FlowCrypt/flowcrypt-android/blob/8ea029b68dd6d0f69edccb61e4e5547e13d52768/FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/base/CreateMessageFragment.java#L997

**Comment by tomholub** [comment]
Works much better now
