### ISSUE TITLE
improve handling attachments

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#2538]
based on the recent feedback the Android logic of handling MIME attachments is too aggressive

For example, the following name

`[test] reply den (copy).txt`

will be converted to

`testreplydencopy.txt`

We use the following logic

![image](https://github.com/FlowCrypt/flowcrypt-android/assets/2863246/5e5dfd94-165f-46e4-832b-1557e8333966)
https://github.com/FlowCrypt/flowcrypt-android/blob/542dea94763b55c87e1df79ec133988eb745b8ce/FlowCrypt/src/main/java/com/flowcrypt/email/util/FileAndDirectoryUtils.kt#L140

To be honest I don't remember why we decided to use this logic. This is old code.

But maybe it's redundant. Maybe we have to show an attachment name as-is.

**Comment by sosnovsky** [comment]
> @sosnovsky What do you think? what logic do we use in the web app/iOS today?

I think on iOS we render attachments names as is, without normalization, as it's just simple text label, didn't notice any issues with it.

In browser extension we [escape some characters ](https://github.com/FlowCrypt/flowcrypt-browser/blob/b32f58402e62ee03418f31f70ac14fd31125e2ab/extension/chrome/elements/pgp_block_modules/pgp-block-attachments-module.ts#L31), so they won't break HTML markup, and then [sanitize produced HTML](https://github.com/FlowCrypt/flowcrypt-browser/blob/b32f58402e62ee03418f31f70ac14fd31125e2ab/extension/chrome/elements/pgp_block_modules/pgp-block-attachments-module.ts#L34) to remove possible malicious code.

For Android I'm not sure if there can be any security issues with rendering attachment names as is, but it'll be better to render all characters
