### ISSUE TITLE
Unable to send reply and returns error message: bad base-64

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-android#2545]
### Description

When sending a reply, whether encrypted or not, the sent reply will not go through and will be stuck in the outbox. Additionally, an error with the details "bad base-64" will appear if you tap on the unsent email.

### Screenshots

<img src="https://github.com/FlowCrypt/flowcrypt-android/assets/46025304/f344e885-6fdc-41ec-8306-bc20db5ae860" width="300px"/>
<img src="https://github.com/FlowCrypt/flowcrypt-android/assets/46025304/bedc5861-0888-4a5d-b067-9cfa7843bc39" width="300px"/>

### Steps to reproduce

1. Open the FlowCrypt Android app (version 1.5.0).
2. Open an encrypted/non-encrypted email and tap on the reply icon.
3. Compose a reply message and send the email.
4. Observe that it won't be sent and will be stuck in the outbox.
5. Tap on the email from the outbox, and you'll receive the error message with details "bad base-64."

Reference: 
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGwJSCRqJMQkkxMvxgCTHGPJjvV?projector=1&messagePartId=0.1
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGwJSJDRKTsbKHnHdNbfJZqrXvc

**Comment by martgil** [comment]
It was reported to us that it also happens when the app tries to save a draft email:

```
Could not save a draft

Error details:
IllegalArgumentException:bad base-64

version: Android 1.5.0
```
Reference: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGwJcXrgffbDgmzSTQxMZpPLLbg

**Comment by DenBond7** [comment]
@martgil please notify users that we've published an update. Thank you!

**Comment by martgil** [comment]
Hello @DenBond7 thank you for fixing this one. I will notify them via email. Happy new year!
