### ISSUE TITLE
Implement semaphore's Test reports feature

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#2559]
> By the way, do you know semaphore's Test reports feature - you need to add another step to semaphore.yml to upload tests results in XML format, and Semaphore will automatically present these results in UI, like this - https://flowcrypt.semaphoreci.com/workflows/793f63f8-fd6e-4bdc-aea9-4d2abb3b5cb0/summary?report_id=4ae71336-e44b-39bf-b9d2-752e234818a5

Interesting. I will look. Thank you!

_Originally posted by @DenBond7 in https://github.com/FlowCrypt/flowcrypt-android/issues/2556#issuecomment-1903667347_

**Comment by sosnovsky** [comment]
https://docs.semaphoreci.com/essentials/test-summary/
