### ISSUE TITLE
cc/bcc display loop bug

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#256]
(on some of the incoming messages)

1) open email
2) click reply
3) there will be correct `to:` with the email of the recipient, but there will also be `cc:` that contains my own address (I don't think it's needed to Cc my own address, so I propose we automatically remove our sending email from Cc)
4) I delete the address from Cc
5) I click the chevron to hide Cc -> Bcc shows instead
6) I click the chevron to hide Bcc -> Cc shows instead

Steps 5) and 6) will keep repeating in a cycle.

This seems to be happening on messages that begin with having a Cc in them.

Todo:
 - [ ] remove my own CC addresses when I'm sending from the same address (automatically before rendering)
 - [ ] fix the cc/bcc showing bug cycle in similar situations

**Comment by DenBond7** [comment]
Could you send me such message? I can't reproduce that bug on my side.

**Comment by tomholub** [comment]
1) go to flowcrypt.compatibility email
2) open email subject "for tests new db"
3) click reply

Both bugs present: my own email in CC + the loop bug

**Comment by DenBond7** [comment]
> click reply

`reply` or `reply all?`

**Comment by tomholub** [comment]
I'm intuitively using the button on the top right - it's the reply all button.

**Comment by tomholub** [comment]
Here
[VID_20180605_213252.mp4.zip](https://github.com/FlowCrypt/flowcrypt-android/files/2073734/VID_20180605_213252.mp4.zip)

**Comment by tomholub** [comment]
Were you now able to reproduce it?

**Comment by DenBond7** [comment]
> Were you now able to reproduce it?

Yes, I've reproduced it. Thank you very much.

**Comment by DenBond7** [comment]
I've simplified a "collapse/expand" logic.

**Comment by tomholub** [comment]
Great, I'll test it

**Comment by tomholub** [comment]
Now when I expand it, I cannot collapse anymore. The chevron disappears.

**Comment by tomholub** [comment]
I think it's an improvement. But still needs some work. For example, when I click the arrow, the cc: field should get automatic focus. That way I can hide it with one click by clicking away.

**Comment by tomholub** [comment]
Eg I click the chevron, it opens and my focus is subject. It's not the best, because I may change my mind and click the subject again, but it wouldn't hide. So giving cc focus when I open it would help.

**Comment by tomholub** [comment]
I think it's perfect now. I'll let you know if I discover anything.
