### ISSUE TITLE
The setup process for SMTP/IMAP login options cannot be completed after attempting to load the private key file.

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-android#2571]
### Description

When a user logs in through the SMTP/IMAP option, the FlowCrypt Android app appears to get stuck after attempting to load a PGP private key file. There are no error messages displayed on the screen, but the android activity for loading the private key file/loading via clipboard continues to be shown even after the user attempts to select the PGP private key file several times. 

The screen recording of the issue will be shared via secure email.

Reference: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGwJvgZJssKzcFMhTVhKZsfnbCV

**Comment by DenBond7** [comment]
Hi Mart,

I can't reproduce the issue. Please try to test with different accounts.

https://github.com/FlowCrypt/flowcrypt-android/assets/2863246/ffe08789-c002-4cef-bdc7-045c8b24cc28

**Comment by martgil** [comment]
Hello @DenBond7, thanks for checking it. I can't reproduce the issue on my end either when I check it based on the description, not even switching to an Android 14. I also tried several accounts, checked if the particular activity was getting killed (on developer options, although the device is new and I doubt it could be the culprit) and there's no sign of an issue.

**Comment by DenBond7** [comment]
> Aside from checking different accounts, do you have any other suggestions that we could try out?

Mart, could you ask the user to try to setup the app on a different device or maybe try to setup a different account?

Also, it would be nice to know the app version.

**Comment by martgil** [comment]
Okay, I'll get back to you with some answers. By the way, the user is using version 1.5.2 of the FlowCrypt Android app.

**Comment by martgil** [comment]
Hello @DenBond7 I've figured out the issue. The backup they received seemed to look like a binary file of some sort the contains HTML codes and stuffs... unfortunately, I cant share it here as it also contain certain sensitive data... That being said, I believe the issue is completely not by the android app's fault but the file the user tries to load.

I will add more details here shortly including the resolution of the matter.

**Comment by DenBond7** [comment]
@martgil Hi Mart. Do you have any new details here? or we can close it?

**Comment by martgil** [comment]
Hi @DenBond7, There was no clear way for us to replicate the issue so we ended up trying to reinstall the app, and that resolves the issue. Will close this one now.
