### ISSUE TITLE
Apply Android App Bundle for the distribution

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#263]
See https://youtu.be/flU42CTF3MQ?list=PLOU2XLYxmsIInFRc3M44HUTQc3b_YJ4-Y&t=497
and https://developer.android.com/platform/technology/app-bundle/

**Comment by DenBond7** [comment]
https://www.youtube.com/watch?v=9D63S4ZRBls

**Comment by DenBond7** [comment]
I've moved it to the "later" milestone. Currently, only Android Studio (Beta) supports Android App Bundle. And only manually, no the Gradle task.

**Comment by tomholub** [comment]
ok. Any disadvantages to using the bundle? Eg security? Will all resource hashes be signed during our release so that none of them can be wrongly replaced by google?

**Comment by DenBond7** [comment]
> Any disadvantages to using the bundle?

The more complex the logic - the more errors can be. But, it's an interesting idea of improving the delivery app process. Because for example device with xxxhdpi doesn't need resources of xhdpi devices. The main idea of Android App Bundle is to make apps smaller(faster downloading).

> Will all resource hashes be signed during our release so that none of them can be wrongly replaced by google?

To use bundle we sign files locally and upload them to Google Play. Google only mixes our files and sends them to the different devices.

Here is an example for better understanding

![image](https://user-images.githubusercontent.com/2863246/40349310-eda8a276-5dae-11e8-9f23-e0d8cb17c5e8.png)

**Comment by DenBond7** [comment]
I'm closing it. As we discussed it early it'll be better to sign apps on our side. It'll not be relevant for us after dropping Node.js
