### ISSUE TITLE
add contacts improvements

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#264]
1) add pubkey to clipboard
2) go to contacts -> add contact
3) click feedback
4) click back
5) it will load pubkey from clipboard and render it atomatically - this confused me

It should instead show a screen the way it was before I clicked feedback button.

**Comment by tomholub** [comment]
Same issue with loading file:

1) add pubkey to clipboard
2) go to contacts -> add contact
3) click load from file
4) now it loaded the key from clipboard
5) I click back
6) now it asks me which file

**Comment by tomholub** [comment]
remove file size limitation

**Comment by DenBond7** [comment]
> remove file size limitation

I've increased file size limitation to 5Mb.

https://github.com/FlowCrypt/flowcrypt-android/blob/7d33a0b2f0d89d99e728c4087c182bdfb47433fb/FlowCrypt/src/main/java/com/flowcrypt/email/ui/loader/ParsePublicKeysFromStringAsyncTaskLoader.java#L43

**Comment by tomholub** [comment]
Another issue:
 - install the app
 - sign into flowcrypt.compatibility
 - go straight to Contacts, add, search "human@flowcrypt.com"
 - it will find the key and say "already imported". But I never imported it before. It's not in the contacts either (freshly installed app).

**Comment by tomholub** [comment]
A few more:
1) parsing the public keys takes a long time, with no indication. It would be great if there was a progress indication. You can re-use the inbox progress bar, except it will show percentage of keys processed
2) when I click "Import All", it takes even longer. Maybe 5 minutes on my phone? With no spinner even - so the app looks like it froze.
3) When done, my app now crashes when I open the contacts window :)

I will send you a file to test with.

**Comment by DenBond7** [comment]
The logic which I use to show "save/update" buttons https://github.com/FlowCrypt/flowcrypt-android/issues/37#issuecomment-316460805

**Comment by tomholub** [comment]
This works well now!
