### ISSUE TITLE
[User requested feature] Ability to bulk change email labels

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-android#2661]
Description: We received a feature request for the ability to bulk edit email labels. We haven't been receiving many requests regarding this feature. However, this GitHub issue will be updated if we receive more requests in the future.

From the user:

> Would be great to bulk change labels rather than having to go into the email and changing them one at a time

Reference: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGxSRMQzTkQJQDpfphWGzsPCdfk

**Comment by DenBond7** [comment]
@martgil duplicate of #2471?

**Comment by martgil** [comment]
Ah, yes, let's close this one. However, I think I need to place related emails to #2471 so that I can inform the users when the feature has been implemented.
