### ISSUE TITLE
Enterprise version. Prevent accepting user certificates when checking secure connections.

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#2668]
![image](https://github.com/FlowCrypt/flowcrypt-android/assets/2863246/c7d33402-e83b-41e5-9816-a7bab1b5a252)
https://developer.android.com/privacy-and-security/security-config#TrustingDebugCa

ref #857

**Comment by DenBond7** [comment]
@sosnovsky Please look at this one. Maybe it will be better to disallow use of user-defined system SSL certs for the enterprise version. For security reasons.

**Comment by sosnovsky** [comment]
> @sosnovsky Please look at this one. Maybe it will be better to disallow use of user-defined system SSL certs for the enterprise version. For security reasons.

Will it still allow to use custom SSL certs provided by admins? (https://developers.google.com/android/work/requirements#4.8.-certificate-management_1)
As I think it should be common for large companies to have their own certificates for accessing internal resources.

**Comment by DenBond7** [comment]
> Will it still allow to use custom SSL certs provided by admins? (https://developers.google.com/android/work/requirements#4.8.-certificate-management_1)

I'm not sure as I can't test it. If these certs will be identified as system certs - maybe. Only real testing can say.

> As I think it should be common for large companies to have their own certificates for accessing internal resources.

In that case, I propose to leave it as-is for now.

Maybe on managed devices, a user can't add a custom cert manually. But again, I'm not sure. It's not a common case.

**Comment by sosnovsky** [comment]
> In that case, I propose to leave it as-is for now.
> Maybe on managed devices, a user can't add a custom cert manually. But again, I'm not sure. It's not a common case.

Yes, let's leave it as is. I think it should be possible to prevent users from adding custom certificates in Android enterprise configuration.
