### ISSUE TITLE
Add warning for suspicious messages

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-android#2670]
Suspicious messages has `Received-SPF: softfail` header, for such messages we need to show warning before message body:

```
Potentially suspicious message

It wasn't properly verified by the sender, so its authenticity can't be confirmed.
Be careful - avoid clicking links and downloading attachments, or sharing personal info.
```

ref: https://github.com/FlowCrypt/flowcrypt-security/issues/270

**Comment by DenBond7** [comment]
@sosnovsky what do you think?
![image](https://github.com/FlowCrypt/flowcrypt-android/assets/2863246/094e67d2-9ed0-421f-ab6f-5ce4f6fdddbc)

**Comment by sosnovsky** [comment]
Looks good, let's just use bold or semi-bold font for `Potentially suspicious message` line, to make it a bit different from main text

**Comment by DenBond7** [comment]
@martgil (to see the progress)

**Comment by martgil** [comment]
Thanks @DenBond7 looks good to me overall, however, would it be good if we change the red strip on the right side of the warning message with color yellow? As warning that appears in Gmail also appears in a yellow-accent warning message.

**Comment by DenBond7** [comment]
> Thanks @DenBond7 looks good to me overall, however, would it be good if we change the red strip on the right side of the warning message with color yellow? As warning that appears in Gmail also appears in a yellow-accent warning message.

![image](https://github.com/FlowCrypt/flowcrypt-android/assets/2863246/f0b768c0-f7b8-40a5-8fc4-a00e4ac499c3)

@martgil @sosnovsky What about this one?

**Comment by DenBond7** [comment]
or 

![image](https://github.com/FlowCrypt/flowcrypt-android/assets/2863246/401dfbb0-3b48-4f68-958e-86c3a4c9297b)

**Comment by sosnovsky** [comment]
Second one looks better for me
