### ISSUE TITLE
FlowCrypt Backup are created for imported exisiting user keys 

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-android#2676]
Description:

When importing existing PGP private keys on the FlowCrypt Android app, a backup is created and stored in the user's inbox without informing them whether they want it stored there or not. Users would like to have the option to not back up their private key into the inbox.

Steps to reproduce:

1. Launch the FlowCrypt Android app and log in to a new Gmail account.
2. Import an existing PGP private key and supply its passphrase.
3. Once the setup is complete, observe the inbox where a private backup is created.

Reference:

https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGxSbrtwzQGJPwLLFWZXklsfhpp
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGxSbrtxCfgjJvLgpRpbHZjSVzg

**Comment by martgil** [comment]
Hi @DenBond7, just letting you know about this one. thanks!

**Comment by DenBond7** [comment]
Agree, need to think about a better user experience.

**Comment by DenBond7** [comment]
![image](https://github.com/FlowCrypt/flowcrypt-android/assets/2863246/da6e328a-9e02-4a95-971f-165ddcbcb0f6)

**Comment by martgil** [comment]
Hi @DenBond7 - I just noticed the message after tapping the help icon for making backup in the email says "Save unlocked PGP private keys...". We are always storing passphrase protected keys so its should say "We store a passphrase-protected PGP private key"?

**Comment by DenBond7** [comment]
> Hi @DenBond7 - I just noticed the message after tapping the help icon for making backup in the email says "Save unlocked PGP private keys...". We are always storing passphrase protected keys so its should say "We store a passphrase-protected PGP private key"?

I've checked my example. Yup, you are right. It looks a bit wrong. `Save unlocked PGP` should be read as `Keys that were unlocked with provided passphrase` (not every, only unlocked. But will be saved as passphrase-protected). I meant this one.

Thank you, I will improve the explanation text.

**Comment by martgil** [comment]
You're welcome - happy to help.
