### ISSUE TITLE
associate keys with accounts

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#269]
This issue is needed so that we can continue working on:
#220 choosing our own pubkey (sender) during compose/reply
#252  change pass phrase

We need a way to figure out which key belongs to which account.
This is important to know which key to use as our own key.

I'll add more info soon.

**Comment by arpitjindal97** [comment]
According to me, current logic is fine. Let's take your example: 

 1. I may have 2 different accounts: `me@company.com` and `me@hello.eu`
 2. The `me@company.com` may have several alias emails: `me@company.com`, `contact@company.com`, `purchases@company.com`
 3. I may have many private keys that serve various purposes for these accounts
4. Which of my own public keys to encrypt for when sending out a message?

You can add alias of different domains or same domain in a single PGP key. When you login onto `company.com` there you login differently for each of your 3 emails. (seems fair till now)

Now suppose, In App you have logged in using `me@company.com`. Assume that we have functionality to choose our sender email. You chose `contact@company.com` as your sender email. Your mail is ready to be sent with specified email but it won't send because the mail server of `company.com` doesn't authorise `me@company.com` to send mails on behalf of `contact@company.com`

**Comment by arpitjindal97** [comment]
To send mail as `contact@company.com` you need to add this account to app and compose through that

**Comment by tomholub** [comment]
In general, yes, it would be cleanest to simply follow key user ids. 

We may do that, but it will require us to create an interface to update uids. Also, currently, when we create keys, we will only use main account email for the uid, so that would need to be updated too.

**Comment by tomholub** [comment]
This would still require us to cache key user ids in db, you don't want to parse all keys on each search.

**Comment by tomholub** [comment]
More pain points:
 - not all users want all aliases to be included in uids automatically. We may need to show a screen on setup that lets them choose this
 - if no key has user id that matches the email I'm currently sending the message from, we should let the user choose which key they want to use (if more than one key available). This procedure would update the key with the new keyid.
 - However, https://attester.flowcrypt.com/ does not yet have functionality to update public keys with new versions that have uid changes. I'll need to implement that too.

**Comment by tomholub** [comment]
I should add, our philosophy is to don't ask user questions and set reasonable defaults without user interaction. This is different from other OpenPGP software which assumes the user has a fair amount of knowledge about how encryption and OpenPGP works. So in this spirit, when key is created during setup, we will do one of:
 - add keyids based on all aliases
 - add only one keyid based on main account address
 - add keyids based on email addresses that were used recently, eg email was sent from them in the last 6 months

**Comment by tomholub** [comment]
@DenBond7 action steps:

### Keeping track of private key emails

 - create a table that has `longid`, `userIdEmail`. This table will be populated with information about private keys.
 - (longid, userIdEmail) combination should have a `UNIQUE KEY` in sql, so that there can be multiple rows with same longid, multiple rows with same userIdEmail but not multiple rows where both (longid, userIdEmail) are the same.
 - fill the table with current info about private keys on app update
 - update the table when new key is imported
 - remove from the table by longid if a private key is removed

### Searching when sending a message 

If I'm sending from main account address:
1) search in the table by main account address. If found longid, use that key (public version).
2) if not found, show error `No key available for your email address main@email.com.\n\nPlease write human@flowcrypt.com for help.` 

If I'm sending from alias address:
1) search by the alias email. If a key found, use that key.
2) If no key found, search by account email address. If a key was found, use that key.
3) If no key found in step 1) and 2) then show an error: `No key available for your email addresses alias@email.com and main@email.com.\n\nPlease write human@flowcrypt.com for help.`

**Comment by DenBond7** [comment]
@tomholub I need some clarifications

> fill the table with current info about private keys on app update

1) I know how to get `longid`. But how do I get `userIdEmail`?
And as I understand [here ](https://github.com/FlowCrypt/flowcrypt-android/blob/master/FlowCrypt/src/main/java/com/flowcrypt/email/js/PgpKey.java), we don't have a method which returns information about all uids. (only `PgpContact getPrimaryUserId()`)

> search in the table by main account address. If found longid, use that key (public version).

2) Do you mean I need to use the current logic? If an active account is user@example.com I'm searching such user in the `keys` table and use a found key. Or do I need to search a row in the new table (longid, userIdEmail) and if I found longid then I search a private key in the `keys`table by longid and use the found key?

**Comment by tomholub** [comment]
1. I can give you a method to get all user ids.

2. Where is the current `keys` table defined? I'll take a look at the structure and let you know.

**Comment by DenBond7** [comment]
> Where is the current keys table defined? I'll take a look at the structure and let you know.

https://github.com/FlowCrypt/flowcrypt-android/issues/17

![sql](https://user-images.githubusercontent.com/2863246/43334343-e4deae50-91d5-11e8-8da0-ee3f309f2f63.jpg)

**Comment by DenBond7** [comment]
https://github.com/FlowCrypt/flowcrypt-android/commit/22c4fbbdf9956da125be4230af86b7c0a8db7c76
https://github.com/FlowCrypt/flowcrypt-android/commit/811d41a3f26b3690ab0cffc67b438ab1df408927

**Comment by tomholub** [comment]
Thanks, to answer your question:

> search in the table by main account address. If found longid, use that key (public version).

> If an active account is user@example.com I'm searching such user in the keys table and use a found key. 

Currently, the `keys` does not know which key is for which account - so I think this would not be possible with the current table structure. 

> Or do I need to search a row in the new table (longid, userIdEmail) and if I found longid then I search a private key in the keystable by longid and use the found key?

Yes, that's what I'd like to do. That way a key can be associated with several accounts, several email addresses, and email accounts can have several keys.

**Comment by tomholub** [comment]
I see you already added the method! I only noticed after I switched branches. I altered the method to not return null, that is not needed if returning the whole array (returning empty array is better than returning null).

**Comment by tomholub** [comment]
Yes, that's great. The function is pretty much the same as the one I've
committed to the other branch.

**Comment by DenBond7** [comment]
@tomholub 

> If I'm sending from main account address:
> 
> search in the table by main account address. If found longid, use that key (public version).

I have one test account which has two different private keys. After I imported that keys during setup the app, I see next situation in the database

![dif_keys](https://user-images.githubusercontent.com/2863246/43510130-51a4ef18-957d-11e8-87db-1e6039382aed.jpg)

When I try to send a message I get that keys for my account. Questions: What a key do I need to use? Or do I need to use both? (Both keys (pub version) will be used to encrypt a message)

**Comment by tomholub** [comment]
Good question. In this situation, pick first that matches.
