### ISSUE TITLE
Question: Public key for ProtonMail user

### ISSUE THREAD

**Issue by arpitjindal97** [FlowCrypt/flowcrypt-android#272]
I am using FlowCrypt with my Gmail account. I have account on ProtonMail also. I have imported private keys associated with my gmail account.

Now, when i send mail to proton account. It automatically fetches the public key of proton account. Proton key isn't hosted anywhere on public key server. 

I want to know from where it is getting it.

**Comment by tomholub** [comment]
We're fetching these from ProtonMail directly. Isn't it convenient?

See https://flowcrypt.com/blog/article/2017-11-08-about-flowcrypt-attester-pgp-public-key-server

The ProtonMail integration was added recently, I'll update the post.

**Comment by tomholub** [comment]
I'll close this issue, but happy to answer followup questions if any.

**Comment by arpitjindal97** [comment]
I didn't know about LDAP server. This is so cool. I was under the impression that only PKS is the place to host keys.

I will make some PRs to support the development.

**Comment by tomholub** [comment]
Your contribution will be welcome - please coordinate with us when you see an issue you'd like to tackle.
