### ISSUE TITLE
Field length for exception reports

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-android#2756]
Hi @DenBond7, I noticed on our backend many errors for `api/v1/log-collector/exception` - `ERROR: value too long for type VARCHAR(20)`. We have such validation for fields `product`, `build_type`, `version` and `environment`
I checked `flowcrypt-browser` and there all such fields seem to be under 20 characters.
Can you please check if some fields in Android reports can exceed this limit?

In the future it'll be fixed on the backend side, but for now it should be quicker to fix it on the clients.

**Comment by DenBond7** [comment]
Based on reports I see the following info

```
...
version: 157 //It will be 3 digits for a very long time
...
product: android //it's a constant
environment: release // can be `release`, `debug` or `uiTests`
buildType: consumer // can be `consumer`, `enterprise` or `dev`
...
```

It looks like all these strings fit the requirements

**Comment by sosnovsky** [comment]
Got it, thanks for checking! Then I'll try to find failing requests in the backend logs.
