### ISSUE TITLE
inbox improvements

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#28]
- when I click "[Gmail]", it will show an error message. That folder should probably be hidden.
- emails should be ordered from newest on the top top older ones on the bottom
- scrolling lower should load more messages

**Comment by DenBond7** [comment]
> scrolling lower should load more messages

https://github.com/FlowCrypt/flowcrypt-android/commit/55ebc017383b5f681be82f00d4171f1973bc238a
