### ISSUE TITLE
User is experiencing issues when logging into the app with Gmail account

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-android#2818]
Description: We received an isolated report regarding logging issue wherein user that is using `@gmail.com` account wasn't able to login with FlowCrypt android app version 1.5.7. Specifically, upon clicking the `Continue with Gmail` -> and choosing their account from OAuth screen, they are prevented by such warning saying "Google hasn't verified this app" and won't let them to proceed so like the typical OAuth Flow.

Initial investigation: I've used both Gmail and Corporate email for testing if I can replicate the issue but the OAuth Flow when just fine every time.

I've asked the bug reporter for a screen capture, which they have gladly provided. I’ll be sharing the screen capture via secure email for us to review.

Reference: 

https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzQVxlRNLMpNfgNXcbJvZSZdNfdF
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzQVxtkLRpPBQnlCVmDkspTJtJGZ
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzQVxtpxcVrFFtNvJlGPWLrRRLkC
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzQVxtpxJjcDcchdcSPXPtJpXlbX
https://mail.google.com/mail/u/human@flowcrypt.com/#archive/FMfcgzQVxtvjHXnxdlXtwqqdqPkhWdvV

**Comment by martgil** [comment]
Email subject: `FlowCrypt/flowcrypt-android/issues/2818 video screen recording`

**Comment by sosnovsky** [comment]
Seems to be similar to earlier issue in browser extension - https://github.com/FlowCrypt/flowcrypt-browser/issues/5790
I'll check what's needed for verification

**Comment by martgil** [comment]
Thanks @sosnovsky.

**Comment by DenBond7** [comment]
> Seems to be similar to earlier issue in browser extension - [FlowCrypt/flowcrypt-browser#5790](https://github.com/FlowCrypt/flowcrypt-browser/issues/5790) I'll check what's needed for verification

Maybe we have a similar situation here. I've asked Tom to check Google Play settings(verification).

**Comment by sosnovsky** [comment]
Probably we need to complete both these verifications - Google Play and [Oauth screen verification](https://support.google.com/cloud/answer/13463073?hl=en) (as for browser extension), second one is required when app uses restricted API scope. For Android app it's [mail.google.com](https://github.com/FlowCrypt/flowcrypt-android/blob/1251e627cc86228b4cd458153cf29495f12d31e8/FlowCrypt/src/main/java/com/flowcrypt/email/Constants.kt#L32C40-L32C64) scope.

**Comment by DenBond7** [comment]
> Probably we need to complete both these verifications - Google Play and [Oauth screen verification](https://support.google.com/cloud/answer/13463073?hl=en) (as for browser extension), second one is required when app uses restricted API scope. For Android app it's [mail.google.com](https://github.com/FlowCrypt/flowcrypt-android/blob/1251e627cc86228b4cd458153cf29495f12d31e8/FlowCrypt/src/main/java/com/flowcrypt/email/Constants.kt#L32C40-L32C64) scope.

Agree

**Comment by martgil** [comment]
Hi @DenBond7 and @sosnovsky cc: @tomholub , the developer's email address set to the OAuth page/app is still using Tom's developer's email under Proton domain when the error appears. Can we also check if we can replace that with `human@flowcrypt.com`?

**Comment by tomholub** [comment]
It's not Google Play, I'm only supposed to start verifying later: 

<img width="1252" alt="image" src="https://github.com/user-attachments/assets/36b99d40-6c11-416d-a0e2-024b10c2a43d">

**Comment by tomholub** [comment]
@sosnovsky do you need me to pay another fee from the verification company?

**Comment by sosnovsky** [comment]
> @sosnovsky do you need me to pay another fee from the verification company?

Probably yes, I'll share OAuth process video with Google today and then they should give a link to app verification request.
Will keep you updated

**Comment by sosnovsky** [comment]
Hello @martgil, yes - we've started verification process similar to browser extension verification, currently waiting for review team response with their feedback.

**Comment by martgil** [comment]
Understood. Thank you for the prompt update, @sosnovsky.

**Comment by sosnovsky** [comment]
Hi @martgil, Google has verified our Android app ✅
There shouldn't be any issues with logging into the app now.

**Comment by sosnovsky** [comment]
App verification process was completed, no more warnings during sign in.

**Comment by martgil** [comment]
Thanks for the heads-up, @sosnovsky. All the users mentioned in this GH issue have already been informed. Have a nice day!
