### ISSUE TITLE
Check imported keys before backup

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#284]
When a user  is trying to backup imported keys (via `Settings -> Backups -> See more backup options`) need to do next:

1. if the user has 1 key ==> just do a backup

1. if the user has more than one key we need to check are keys have the same pass phrase. 

- The keys have the same pass phrase ==> just do a backup

- The keys have different pass phrases ==> We should ask the user to change their pass phrase before backing up, which would have changed pass phrase for both to be consistent. After that, the user can back up.

**Comment by DenBond7** [comment]
#285

**Comment by DenBond7** [comment]
@tomholub Please review it and will free to change if need

**Comment by tomholub** [comment]
Looks good, thanks!
