### ISSUE TITLE
Replace developer user email with a support email address

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-android#2841]
Hi @DenBond7 and @sosnovsky cc: @tomholub , the developer's email address set to the OAuth page/app is still using Tom's developer's email under Proton domain when the error appears. Can we also check if we can replace that with `human@flowcrypt.com`?

_Originally posted by @martgil in https://github.com/FlowCrypt/flowcrypt-android/issues/2818#issuecomment-2259364105_

**Comment by martgil** [comment]
Hi @sosnovsky - Just bringing this into your attention. Needs to update the email to `human@flowcrypt.com`. Thank you!

**Comment by DenBond7** [comment]
@tomholub Please look at this one. I don't have permission to change it.

![image](https://github.com/user-attachments/assets/bd860f8d-2edd-4c0f-96f4-c2ef31937c15)

**Comment by sosnovsky** [comment]
It looks like I have permissions to change this support email, but it has only 2 options - current one and my personal email.
For now I can change it to my email and will forward received feedback to `human` email.

**Comment by sosnovsky** [comment]
Updated email, however it now requires re-verification by Google, like it was recently with sign-in warning message.
Hope it'll be fast this time, as it's just support email change, and won't show any warnings for users.

**Comment by martgil** [comment]
Thanks, @sosnovsky. Hopefully, I can recall that the last time we did this for the browser extension, it didn’t take long and went smoothly, almost unnoticed.

**Comment by sosnovsky** [comment]
Hi @martgil, Google approved my update to Android app contact email ✅

**Comment by martgil** [comment]
Thank you @sosnovsky for your help!
