### ISSUE TITLE
check strength of the password just before backing up

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#285]
Need to add an internal check (right inside an inbox backup function that sends the email, so that the check cannot be side-stepped) that will check the strength of the password just before backing up. If the password of any of the keys is too weak, or the key is not encrypted (eg can be decrypted with an empty string pass phrase: ""), it will throw an exception.

**Comment by tomholub** [comment]
re-surfacing this for me to test when #297 done
