### ISSUE TITLE
import keys - test several keys in one prv backup (clipboard or file)

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#286]
Need to test import backups which generated using the approach from #252

Settings ==> Keys ==> Import ==> `Load from file` (`Load from clipboard`)

**Comment by DenBond7** [comment]
Currently, we support import only one key per action

**Comment by DenBond7** [comment]
Also, such a situation with a variant when user setups the app and don't have any backups. Then he can import his key if he has it.

**Comment by DenBond7** [comment]
@tomholub Do I need to do that for the current milestone(0.6.4)?

**Comment by tomholub** [comment]
I think so. If we support exporting such keys, importing should also be possible on the same app
