### ISSUE TITLE
update encrypted message design in list of messages

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#289]

**Comment by tomholub** [comment]
I cannot get used to the encrypted indicator in the message list. I think it's ugly and confusing. We will have to use another indicator, I will follow up soon.

**Comment by DenBond7** [comment]
> Sorry we are re-doing this, I think it will feel much better.

No problems. It really looks better.

**Comment by tomholub** [comment]
Much better :)
