### ISSUE TITLE
Password-protected messages compliance issue

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-android#2909]
I added `test-feature` string to array of disallowed strings, but Android app still allows to send password-protected messages with `test-feature` subject. Maybe regex generator splits string and expects `test` and `feature` as separate words?

Browser extension implementation handles this case correctly - showing error alert.
Currently `test-feature` is in the list of disallowed strings for `@flowcrypt.com` email accounts, so you can test it with your real FlowCrypt email.

**Comment by sosnovsky** [comment]
Hi @DenBond7, can you please check this one, thanks!

**Comment by DenBond7** [comment]
Hi @sosnovsky 

> I added test-feature string to array of disallowed strings, but Android app still allows to send password-protected messages with test-feature subject. Maybe regex generator splits string and expects test and feature as separate words?

Based on https://github.com/FlowCrypt/flowcrypt-android/pull/2906#discussion_r1880175834 we allow password protected messages for `test-feature` term. Restriction will work for the following cases(for example):

- [test-feature]
- before [test-feature] after

But I think I understand what you are looking for. I've updated the code. 

https://github.com/FlowCrypt/flowcrypt-android/blob/9cd5443b19da7654b83de8cdeadcb372ff7bbec2/FlowCrypt/src/test/java/com/flowcrypt/email/api/retrofit/response/model/ClientConfigurationTest.kt#L18

```kotlin
val matchingSubjects = listOf(
      "[Classification: Data Control: Internal Data Control] Quarter results",
      "Conference information [Classification: Data Control: Internal Data Control]",
      "[Classification: Data Control: Internal Data Control]",
      "aaaa[Classification: Data Control: Internal Data Control]bbb",
      "[droid]",
      "check -droid- case",
      "TEST-FEATURE",
      "[test-feature}",
      "before {test-feature}",
      "[test-feature] after",
      "before [test-feature} after",
      "test-feature",
      "test-feature after",
      "before test-feature",
      "before test-feature after",
      "before TEST-feature after",
      "before {TEST-feature} after"
    )

    val nonMatchingSubjects = listOf(
      "[1Classification: Data Control: Internal Data Control] Quarter results",
      "Conference information [1Classification: Data Control: Internal Data Control]",
      "[1Classification: Data Control: Internal Data Control]",
      "aaaa[1Classification: Data Control: Internal Data Control]bbb",
      "Microdroid androids",
      "beforetest-feature",
      "test-featureafter",
      "beforetest-featureafter",
      "before {TEST-feature}after",
      "before{TEST-feature} after",
      "before{TEST-feature}after"
    )
```

What do you think?

**Comment by sosnovsky** [comment]
Updated list looks great, handles more cases, thanks!
