### ISSUE TITLE
MultiThreading in Java Mail and Shared Session

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#291]
I've found interesting things here https://community.oracle.com/thread/1589459

Maybe it'll be a great improvement :)

**Comment by DenBond7** [comment]
https://stackoverflow.com/questions/12732584/threadsafety-in-javamail

**Comment by DenBond7** [comment]
The current logic:

- We have the active and passive queue. 

- We are using the passive queue for tasks results of which are not needed right now (for example the labels updating). This queue uses a single IMAP connection and if it is empty for 30 seconds we are closing the connection. The connection will reopen if the queue receives new tasks. The passive queue works in own thread

- We are using the active queue for tasks results of which are needed right now (loading the message list, loading the message details and etc.). The active queue works in own thread. All tasks are running in order ["FIFO" stands for first-in, first-out](https://en.wikipedia.org/wiki/FIFO_and_LIFO_accounting). But this logic is not perfect and has one big minus - while the current task is working we can't start the next task. This is a real problem. For example, we have a situation: we open the app, we see INBOX. Then we want to see the detail of a message_1. We click on the message_1 and open a new window. Then we decide to see details of a message_2 (but details of the message_1 are not loaded yet. The message_1 is still loading). We click on the message_2 and open a new window. We need to wait longer because we wait for a task for message_1 and a taks for message_2.

- We are using a separate thread for [IMAP IDLE](https://tools.ietf.org/html/rfc2177) (INBOX) if an IMAP server support it. It's not perfect too. Because we can stop the IDLE command, do tasks in INBOX and resume the IDLE again.

- And the biggest problem: I can't manage states of the tasks in the active queue. I can't stop some task if I need that, because I can stop only the whole thread. I need to wait while the current task will finish and then I can decide do I need results of that task.

**Comment by DenBond7** [comment]
After some research and testing I propose next:

1. Need to change the current logic of working with IMAP. I think will be better if we'll use a separate thread for every task. Then I can manage tasks (I can use a threads executor for that). And then we don't need the active and passive queue. We will have a single queue. In this case, we'll not wait while the current task will finish.

1. I need to think more about IMAP IDLE. Maybe after 1) I'll propose the better solution.

**Comment by tomholub** [comment]
How to handle errors? For example, if a message fails to send.

**Comment by DenBond7** [comment]
If we are talking about a current logic of sending a message (currently we have a synchronous realization (I show a progress bar and user needs to wait while the message will be sent)) the current logic of sending a message will be the same even if I'll apply new multithread realization. Because I'll still be waiting a response of such opreations (All tasks have unique id, and I know which task was complete).

Resolving the current issue means creating the better management of IMAP tasks and minimize the time between two operations (which can be run at the same time)

**Comment by tomholub** [comment]
I see, so from user's point of view, it's still the same.

**Comment by DenBond7** [comment]
deprecated
