### ISSUE TITLE
"pass phrase too weak" debugging

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#297]
> The pass phrase of some of your key(s) is too weak.

This restriction should only apply to backing up in inbox, but it showed up when backing up as a file. It should not restrict file backups.

**Comment by tomholub** [comment]
Also, I need to test the following: I think it wrongly told me that my pass phrase is weak. Once I can download it as a backup, I will confirm.

**Comment by DenBond7** [comment]
@tomholub I've added changes. It's ready for testing

**Comment by tomholub** [comment]
Looks good
