### ISSUE TITLE
settings - backup - keys - add should update existing keys

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#303]
To reproduce
1) restore flowcrypt.compatibility with both keys from backups (2 different pass phrases)
2) change pass phrase. Change it to something else (eg `hello there another pp to use`)
3) backup into a new file `bup.key`
4) reset app
5) restore flowcrypt.compatibility with only the first key (do not import second from backup)
6) import backup file `bup.key` with `hello there another pp to use`

In step 6, one key was already existing, and one was newly imported. Currently, existing keys are skipped. Instead, you should overwrite existing keys when importing (the user could have modified the key in other software and wants to update the one on FlowCrypt).

That means, after step 6, both saved keys should be using pass phrase `hello there another pp to use` - the one that was used in `bup.key`, because you have imported or updated both keys.

**Comment by DenBond7** [comment]
deprecated. We've already a similar logic. #1287
