### ISSUE TITLE
rename branch 0.6.5 to 0.6.7

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#306]
I have not realized that we already have 0.6.4 released last may (a security hotfix)

Our new 0.6.4 branch was missing these updates from master.

I have merged our large new 0.6.4 branch and the security fixes into 0.6.6 and will release that.

That means our next version will be 0.6.7 - please re-name the branch. Thanks!

**Comment by DenBond7** [comment]
I've renamed
