### ISSUE TITLE
speed - imap use optimization

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#31]
We have to do some speed improvements. I'm currently also working on a Desktop app for Windows/Linux/Macos that also uses IMAP, so I have a little better understanding of this now.

Dealing with folders:
 - folders should be cached. When I open it first time, it should load the list of folders and save them somewhere local. Next time I open it, it should:
 - render the folders from the cache
 - pull messages from active folder (typically inbox)
 - when idle, re-fetch the list of folders

This will mean we don't have to wait extra time while the app is pulling list of folders every time.

Displaying messages: loading a message takes way too long. I suspect we are creating a new connection for each screen?
 - we should be keeping and re-using a single connection throughout the app, because IMAP login is an expensive operation
 - because of this, we should be able to detect a broken/failed connection and automatically reconnect it as needed before making further requests
 - in the future, we may even want to create a special connection to download attachments and do similar work. That way, the app doesn't get stuck/blocked while an attachment is being downloaded.

**Comment by DenBond7** [comment]
> Maybe some of your updates to Folder class did not get committed?

@tomholub Yes, that's right. I missed one file for the commit.

**Comment by DenBond7** [comment]
For me

> Admittedly the thread safety rules for JavaMail are not well documented, but hopefully they mostly match what you would expect.
> 
> Multiple threads can use a Session.
> 
> Since a Transport represents a connection to a mail server, and only a single thread can use the connection at a time, a Transport will synchronize access from multiple threads to maintain thread safety, but you'll really only want to use it from a single thread.
> 
> Similarly, a Store can be used by multiple threads, but access to the underlying connection will be synchronized and single threaded.
> 
> A Message should only be modified by a single thread at a time, but multiple threads should be able to read a message safely (although it's not clear why you would want to do that).

https://stackoverflow.com/questions/12732584/threadsafety-in-javamail

**Comment by tomholub** [comment]
I like the progress here! Let me know when it's ready to test, I'm looking forward to try it.

**Comment by DenBond7** [comment]
Finally, I made the stable version for testing. Now you can start testing.

After the work done, I would like to add some comments:

1. At the moment, the key object in synchronization is the EmailSyncService. Thanks to him, we use a single connection for all requests.

1.  I compared how different mail clients work. For the study, I took Gmail and BlueMail. For more logical work, I think we need to improve the way we send messages and moving them to other folders. For example, we'd better mark messages as deleted and delete them in the background, like in Gmail. (Similarly sending, replying and archiving)

1. Thanks to the first, I prepared the ground for the implementation of correct synchronization. The current implementation does not take into account many moments

- _We equally use all types of connections - WIFI, 3G and others. This can be bad for the device's autonomy._ 
- _The automatic loading of new messages has not yet been implemented. You can only download them manually._
- _Also we do not track the battery level. This is also not very good._

**Comment by tomholub** [comment]
Perfect, I like that you prepared it for auto sync. That will be great in the future. I'm closing this for now unless there are things that you want to add now.
