### ISSUE TITLE
prepare code for public release on github

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#32]
- [x] license
 - [x] license notes
 - [x] rename repo
 - [x] move repo

**Comment by tomholub** [comment]
@DenBond7 this is what my `.git/config` looks like now (example):

```
[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
[remote "origin"]
        url = git@github.com:flowcrypt/flowcrypt-android.git
        fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
        remote = origin
        merge = refs/heads/master
```

**Comment by DenBond7** [comment]
I saw that you added the license header for all source files. I can add the license header automatically when creating a new file. Can you attach the license header text to this task?

**Comment by tomholub** [comment]
Yes that looks correct, something like this:
```
Business Source License 1.0 © 2017 FlowCrypt Limited (tom@cryptup.org). Use limitations apply. See https://github.com/FlowCrypt/flowcrypt-android/blob/master/LICENSE
Contributors: DenBond7
```
It would be good to also add it to the XML files, but probably not crucial.
