### ISSUE TITLE
message details - don't know message recipients

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#321]
currently, when I open received message, there is no way to find out all of the to: and cc:. I don't know who else was the message sent to.

There should be a "more" button somewhere.

**Comment by seisvelas** [comment]
ref: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgxwLsdGLfSrtCwhpSJpFcxxXWZDx

>Can we have a way to see email in formation visible on the preview email section? This is a phising email trying to pose as someone I know. I can't tell this because there is no email address associated with this email.

**Comment by tomholub** [comment]
Agree this could be addressed soon, maybe next month

**Comment by DenBond7** [comment]
Duplicate of #1191
