### ISSUE TITLE
error: cannot load labels

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#329]
From user:

> My Google Domain is with HTTPS and without IMAP configured

![screenshot_20180913-112635](https://user-images.githubusercontent.com/6306961/45993227-66074e80-c07d-11e8-918a-970580a9839b.png)

ref https://mail.google.com/mail/u/0/#inbox/FMfcgxvzKbNpsqKVhQgZwTlcSFmzWkDx

**Comment by DenBond7** [comment]
> without IMAP configured

Does it mean IMAP protocol not allowed? We support only IMAP.

I show that error message when the app can't receive information about labels.

**Comment by tomholub** [comment]
I double checked, IMAP was disallowed. We should test this and find out the exact error returned by the API, so that we can find out if IMAP is disabled. That way we can show a better error message, such as:

```
Could not connect to mail server.

It seems IMAP access is disabled.

Please allow IMAP on your Google account.
```

**Comment by DenBond7** [comment]
Ok. Got it.  I'll try to reproduce that error.
