### ISSUE TITLE
quote previous message on reply

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#335]
The sent message will have:
```
my reply here

On 2019-08-10 at 04:22, someone@gmail.com wrote:
> bla
> ble
```
Or if the reply is encrypted, than the above will be the encrypted text.

You don't have to render this info when I'm composing a reply (yet).

You can get the quoted text by looking at returned json from parseDecryptMsg when displaying the message: field `text`.

**Comment by DenBond7** [comment]
I see you replace `>` with `&gt;` in the field `text`. Is there any special reason to do that?

``` json

 {
   "text":"3 mes from web\n\nOn 2019-08-30 at 12:20, denbond7test@gmail.com wrote:\n&gt; 2 mes from web\n&gt; \n&gt; On 2019-08-30 at 12:20, denbond7@gmail.com wrote:\n&gt; &gt; 1 mes",
   "replyType":"encrypted"
}

**Comment by DenBond7** [comment]
@tomholub 
I've added new changes to https://github.com/FlowCrypt/flowcrypt-android/compare/issue_335_quotes

**Comment by tomholub** [comment]
Yes, that's an error I also noticed earlier. For now you can use it as is, later I will fix it.

**Comment by tomholub** [comment]
I made an issue for it for another milestone

**Comment by tomholub** [comment]
Would you like me to test the changes on the new branch?

**Comment by DenBond7** [comment]
@tomholub 
> Would you like me to test the changes on the new branch?
No. I just shared a place where I added changes. But if you are going to fix that in the next milestone that doesn't matter now.

**Comment by DenBond7** [comment]
Closed via https://github.com/FlowCrypt/flowcrypt-android/commit/4e8584dc788b059a4fcf9a5e29ff8c44f74353e6

**Comment by tomholub** [comment]
There are some mistakes, I'll fix it

**Comment by tomholub** [comment]
continue with #711
