### ISSUE TITLE
newly sent messages should be automatically market as read

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#34]
When I send out a new message (I tested this with Reply) and then go to my account on mail.google.com, the sent message shows as unread.

Sent messages (new ones or replies) should be marked as read when I send them myself.

Not sure if there are some parameters to set in SMTP (that would be better) or if the message needs to be marked as read in IMAP.

Either way, something should be done so that people don't get confused.

**Comment by DenBond7** [comment]
I can not reproduce this error. Can you update your local code, generate a new build and check this error again?

**Comment by tomholub** [comment]
You're right, I got confused myself. It's all good.
