### ISSUE TITLE
A new way for attachments identification

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#343]
Need to improve a logic of identification the attachments. Currently, we don't show an attachment which doesn't have X-Attachment-Id or Content-ID. But as practice has shown a lot of attachments don't have such headers.

**Comment by DenBond7** [comment]
It's not urgent. I've moved it.

**Comment by tomholub** [comment]
Maybe we should reconsider this for the current issue

**Comment by tomholub** [comment]
Current milestone

**Comment by DenBond7** [comment]
for me
https://en.wikipedia.org/wiki/MIME#Content-Disposition
