### ISSUE TITLE
Improve download attachments notification for Android 8 and above. Notification Channels.

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#344]
Starting from android 8 we are using [Notification Channels](https://developer.android.com/training/notify-user/channels) for displaying notifications. But Notification Channels have a different behavior. They don't allow as show a single notification with sound if a notification channel was created without sound support.
Currently, we have the next situation: the notification channel `Attachments` creates with a sound support. And we can hear the sound every time when some notification is creating or updating. But the best behavior - to hear sound when the attachment will be downloaded. But we can't do that with a single notification channel. We need to have two channels: the first for progress (without sound) and the second for results (with sound). Or we don't use sound for such notifications.

![image](https://user-images.githubusercontent.com/2863246/48355503-dc4b2900-e69c-11e8-949e-6bf42b3fe58f.png)

**Comment by DenBond7** [comment]
@tomholub 
What do you think about it?

1. We need to have two channels
2. We don't use sound for such notifications

**Comment by tomholub** [comment]
Let's disable sound for now. Later when we have nothing else to do, we can split it into two channels, one with a sound.

**Comment by DenBond7** [comment]
I have great news - In #371 I've fixed that problem. Now all works fine on all versions.

**Comment by tomholub** [comment]
That's good to hear
