### ISSUE TITLE
forwarding attachments encrypted wrongly adds .pgp to original filename

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#350]

**Comment by tomholub** [comment]
https://github.com/FlowCrypt/flowcrypt-android/issues/350

**Comment by tomholub** [comment]
@DenBond7 Please review and close if good

**Comment by DenBond7** [comment]
@tomholub I've reverted back some of your changes. Basically, the current situation is the same, but I'm just removing`.pgp` during the creation of an encrypted file. I needed to that to prevent change a basic logic in the app.

**Comment by DenBond7** [comment]
https://github.com/FlowCrypt/flowcrypt-android/blob/24da3ab31285307fb4f68488829d17edea8621ca/FlowCrypt/src/main/java/com/flowcrypt/email/jobscheduler/ForwardedAttachmentsDownloaderJobService.java#L281

**Comment by tomholub** [comment]
That's ok, but in the future we may use a different mechanism. Eg maybe one day we will stop reporting the file name in IMAP, and instead use filenames like AAF0-4455-0038-CCDA-D001.pgp, and only inside the encrypted part would be the real name. So it may entail more than just adding/removing .pgp. For now it's ok.
