### ISSUE TITLE
message open stuck on loading

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#355]
You can find the email in flowcrypt.compatibility

![image](https://user-images.githubusercontent.com/6306961/47673669-359b5e80-dbad-11e8-9bf1-5ebc11c8154a.png)

**Comment by DenBond7** [comment]
I've moved it to 0.6.8. It needs to be fixed soon. I'm going to work on this issue today.

**Comment by tomholub** [comment]
Ok good
