### ISSUE TITLE
contact search - order by last used

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#356]
When composing I keep having to scroll down to find a particular contact (human@flowcrypt.com) that I use often.

1) every time I send an email to a recipient, please update the contact in db with lastUsed entry or something similar that holds a timestamp.
2) When I then compose a new message and I enter first few letters of the email address, I want the results to be sorted by when I last sent message to that contact. The most recent one should be on the top.

**Comment by tomholub** [comment]
Just a note, give contacts that I haven't sent any messages to yet some old timestamp like 2000-01-01 so that they show up at the bottom.

**Comment by DenBond7** [comment]
@tomholub 

https://github.com/FlowCrypt/flowcrypt-android/blob/af422f140e4439e80719f6363f573546854291f2/FlowCrypt/src/main/java/com/flowcrypt/email/database/dao/source/ContactsDaoSource.java#L52

> lastUsed entry or something similar that holds a timestamp.

Ok. We already have that information. So I just need to add a right sorting.

**Comment by tomholub** [comment]
Awesome

**Comment by DenBond7** [comment]
@tomholub 
I've fixed it. I really don't understand why I have not done that early. Now composing a new message is more comfortable.

**Comment by tomholub** [comment]
This is so much better :)
