### ISSUE TITLE
display info about my own public keys

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#357]
When I click at Settings -> Keys -> any key, it should show a screen as follows:

```
<-  My Public Key
_______________________________

Public Key Below is safe to 
share with others.

[SHOW PUBLIC KEY]
[COPY TO CLIPBOARD]
[SAVE TO FILE]

KeyWords: ARRIVE BLA BLA BLA 
BLA ASSUME
Fingerprint: FF03 AA22 ..... ..... 
..... ..... ..... ..... .. . . 045E
Longid: 0045 .... 045E
Date: Nov 3, 2017
Users: 
email@domain.com
email2@domain.com

[SHOW PRIVATE KEY]
```

When I click `[SHOW PRIVATE KEY]`, it will show a toast: Not implemented yet, see "Backups" to save your private key to file.

**Comment by DenBond7** [comment]
@tomholub 
![device-2018-11-20-190054](https://user-images.githubusercontent.com/2863246/48789857-a9391300-ecf6-11e8-9bd9-6d5eafbd9b77.png)

**Comment by tomholub** [comment]
That's good, just don't add the commas after emails, and the fingerprint and long id should of course show in full. Maybe show private key button should be red :)

**Comment by tomholub** [comment]
The text on the bottom seems like smaller font. Is it true? If so, please make it a standard size font.

**Comment by DenBond7** [comment]
@tomholub 
> The text on the bottom seems like smaller font. Is it true?

It's a standard text size. I think you need to test it on your phone. Maybe it's not so small.

> [SAVE TO FILE]

What a name for a file do I need to generate?

**Comment by tomholub** [comment]
same name as when saving backup to inbox

**Comment by tomholub** [comment]
Sorry, mistake. Use `longid + ".asc"`

**Comment by tomholub** [comment]
I deleted my previous two comments, they were both wrong. Below is the correct naming.

Name: `"0x" + longid + ".asc"`
Mime type: `application/pgp-keys`

The mime type is important for some pgp clients.

Create a utility function to make files like that from PgpKey, it will be useful in other places later. (replying with a public key when there is a key mismatch while decrypting. Chrome does this when you click "ASK SENDER TO UPDATE")

**Comment by DenBond7** [comment]
@tomholub 
I've finished it. Please look at it. Maybe need to improve some strings.

> The mime type is important for some pgp clients.

When I set mime type = `application/pgp-keys` Android automatically adds `.key` to the file name. So I can create only files like `0x78FDTRREYRERE.key`

**Comment by DenBond7** [comment]
To create a file I use the [Storage Access Framework (SAF)](https://developer.android.com/guide/topics/providers/document-provider). It's a standard way to create any files in Android. (From the link - The SAF makes it simple for users to browse and open documents, images, and other files across all of their preferred document storage providers. A standard, easy-to-use UI lets users browse files and access recents in a consistent way across apps and providers.)

But if I define the mime type as `application/pgp-keys` the SAF decides to set `.key` by itself. If I set the mime type as `*/*` the SAF doesn't add any extensions.

> Is there no way to control that?

I think there is no way to control that. Unfortunately, a lot of things under the cover and may difference which depends to the Android version.

> Worst case we could do .asc.key

Yes, we can do that if need.

**Comment by tomholub** [comment]
ok let's do .asc.key that shouldn't be a big deal. We just need to test later that chrome extension will recognize it as pubkeys.

**Comment by DenBond7** [comment]
@tomholub 

> Is there no way to control that?

I've found a solution. I can't manage the file extension during creation so I just rename a file after that (I've found a way). The issue is resolved.
