### ISSUE TITLE
encrypt and decrypt using Node.js

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#358]
Best would be projects that allow us to run NodeJS compatible code

One such project is https://github.com/graalvm/graaljs

**Comment by tomholub** [comment]
This one is specifically for mobile: https://github.com/janeasystems/nodejs-mobile/issues

**Comment by tomholub** [comment]
I have prototyped an alternative at https://github.com/FlowCrypt/flowcrypt-android-node

It's using https://github.com/janeasystems/nodejs-mobile and behaves much better.

I have tested files up to 50M in size and it did not crash. One day we can also add streaming support to make it more memory efficient. Overall it looks promising. 

![screenshot_20181204-211216](https://user-images.githubusercontent.com/6306961/49447641-f6c17f80-f7ce-11e8-8063-7abed98bad41.png)

**Comment by DenBond7** [comment]
@tomholub That's great! That's really great! I'm happy to hear it. We need changes. I hope we'll improve Js wrapper in the coming future.

**Comment by tomholub** [comment]
I think in 2-3 months we should be able to replace the decrypt() and encrypt() function at least to use this new method. 

We could introduce it as `Node` class. If it behaves well on user devices, we will slowly start replacing functions from `Js` and adding them to `Node`, until there are no functions left in `Js` and we can remove it completely.

The internal mechanism works quite differently.
 - In Js, we are interacting with V8 engine directly, getting back javascript objects, running methods on them, etc.
 - In Node, there is local http server running a Node.js that responds to http requests from the app. So we make a request, and then a http response back.

**Comment by tomholub** [comment]
I moved it to milestone "soon" :)

**Comment by DenBond7** [comment]
> In Node, there is local Node.js server that responds to http requests from the app.

It's an interesting realization

>So we make a request

 I think in this case we can't use synchronize calls. I'm looking forward to try it.

> So we make a request, and then we get a http response back.

I hope it's safe for our purposes.

**Comment by tomholub** [comment]
Good remark, the safety is what I'm now evaluating.

The http requests must be done in background thread to be non blocking, as you would expect.

**Comment by tomholub** [comment]
It's looking good. I'm using self-signed https certificates (generated in Java, and then cached) and http authorization to make sure that no other process can access sensitive info.

**Comment by tomholub** [comment]
First time initialization: 6-12 seconds in background (must create ssl certs)

Ssl certs are then cached in storage. Node Initialization after app restart: under 4 seconds. 

It could be improved further. For example, we could use direct process to process communication instead of http. Then there is much less overhead, but it would take time to get it right. 

Maybe we can package Node in current release. Hide it in experimental tab as a test.

**Comment by tomholub** [comment]
But the start times won't get much better than 3-4 seconds (on a cheap device like my Motorola). Starting Node that doesn't execute any code and immediately exists takes 1750ms. After that about 2000ms is spent parsing the 2MB of JavaScript source code and start a https server. Maybe that could be optimized to 1000ms, which would still mean 2800ms total startup time.

**Comment by DenBond7** [comment]
@tomholub some thoughts...

> In Node, there is local Node.js server that responds to http requests from the app.

Does it mean we can do a few requests at the same time? Or do we need to do requests using a queue?

It's a really important question for the future logic and the app architecture

**Comment by tomholub** [comment]
You can do many requests at the same time. If the requests are computation
heavy, node will queue them and process them one at a time. If the requests
don't require much computation, node can handle them simultaneously. So if
you make

1) simple request
2) computationally heavy request
3) simple request

Quickly in that order, the third request may be queued on node until second
request is finished computing, so it will look like the third request took
a long time to finish.

You do not have to worry about queueing in Java. You can call node from any
thread, or from several threads at the same time, doesn't matter.

**Comment by DenBond7** [comment]
> You can call node from any thread, or from several threads at the same time, doesn't matter.

That's really great. It'll solve a lot of problems.

**Comment by tomholub** [comment]
By the way decryption of additional megabyte takes about additional one
second. So decrypting 50 mb takes fifty seconds. It does not crash but it's
not a good user experience because during that time node will queue even
simple requests for a whole minute until it's done decrypting the big file.

This will be improved once we implement stream encryption. Node would
receive a big file, but only encrypt the first chunk. Then it will look at
other requests and can finish simple request quickly. Then it can encrypt
another chunk of the big file. This way it can process things
simultaneously without blocking on big requests.

**Comment by tomholub** [comment]
I think there was a miscommunication - For 0.7.2, I thought we are only replacing file decryption and file encryption with Node, but nothing else.

It seems in af1cf63 you are already working on replacing message encryption with node. We can keep it since you have already done it. It's a bit riskier (what if Node crashes on people?), but never mind.

**Comment by DenBond7** [comment]
@tomholub 
> For 0.7.2, I thought we are only replacing file decryption and file encryption with Node, but nothing else.

I can easily fix it. I can make this code available only for debug version :)

**Comment by tomholub** [comment]
Maybe that would be better, for now, if it's easy to do.
