### ISSUE TITLE
Migrate to use Room as a part of Architecture components

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#364]
Need to think about moving to use [Room](https://developer.android.com/topic/libraries/architecture/room?hl=RU) as the main instrument which helps to communicate with a database.

The Room persistence library provides an abstraction layer over SQLite to allow for more robust database access while harnessing the full power of SQLite.

**Comment by DenBond7** [comment]
https://medium.com/androiddevelopers/incrementally-migrate-from-sqlite-to-room-66c2f655b377
https://medium.com/@price.yvonne.86/quick-and-easy-migration-to-room-d40dbb142b51

**Comment by tomholub** [comment]
Will it solve any particular issue? Interestingly, on the backend, I'm exactly moving away from database abstractions, because they often end up complicating things and are not easy to replace.

**Comment by DenBond7** [comment]
> Will it solve any particular issue? 

Currently, we don't have any database issues. We need to migrate to use Room because it's a part of a new Android development process. Without that changes, I can't apply any new features from the Android Jetpack.

Basically, we don't use fresh libs because I was waiting while the Android team releases stable versions of the new libraries. But the time has come. 

As I've described in #362 the Loaders are already deprecated. Currently, we are using loaders as the main tools. But we need to use new tools for better user experience, better performance and etc.

Android Jetpack helps as to create better apps. So it's only one step of the big changes in the future.

**Comment by DenBond7** [comment]
- [ ] check migrations

**Comment by DenBond7** [comment]
I'm closing it for now. I've added a simple implementation of Room. Currently, the app uses RoomDatabase implementation instead of SQLiteOpenHelper. The migration process will have other steps wich separate issues. I've found we don't need to make a migration via a single step. We can do it  gradually
