### ISSUE TITLE
Migrate to use RecyclerView instead of ListView

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#365]
The [RecyclerView](https://developer.android.com/guide/topics/ui/layout/recyclerview) widget is a more advanced and flexible version of [ListView](https://developer.android.com/reference/android/widget/ListView).

**Comment by DenBond7** [comment]
#504 #552

**Comment by tomholub** [comment]
I'm closing it as done, if I'm wrong, please re-open
