### ISSUE TITLE
version 0.6.9

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#369]
@DenBond7 What do you think is a good estimate to finish 0.6.9?

**Comment by DenBond7** [comment]
@tomholub I need around 6-8 days

**Comment by tomholub** [comment]
@DenBond7 is 0.6.9 currently ready for testing? If it passes all my tests, would it also be ready for release?

**Comment by DenBond7** [comment]
It's ready for testing. All tests have passed.

**Comment by tomholub** [comment]
reopening for #378
