### ISSUE TITLE
process mime message blocks with mime_process

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#37]
Often, messages are complicated and have several different parts in them. I call each part a `MessageBlock`, here are the types:
```java
    public static String TYPE_TEXT = "text";
    public static String TYPE_PGP_MESSAGE = "message";
    public static String TYPE_PGP_PUBLIC_KEY = "public_key";
    public static String TYPE_PGP_SIGNED_MESSAGE = "signed_message";
    public static String TYPE_PGP_PASSWORD_MESSAGE = "password_message";
    public static String TYPE_ATTEST_PACKET = "attest_packet";
    public static String TYPE_VERIFICATION = "cryptup_verification";
```

For example, a single message may have the following structure:
1) a few lines of plain text (intro)
2) an encrypted message
3) a few lines of plain text (email footer, contact, etc)
4) a public key

That is why we need a more sophisticated way to parse and display messages. Each message will be parsed and displayed as a sequence of bloks, and each block type will be processed differently before rendering it.

I have exposed some functionality very similar to what I do in the browser plugin and desktop apps.

Instead of using `js.mime_decode`, we will start using `js.mime_process`. It's very similar, except instead of `getBody` and `getHtml`, you will use `getBlocks` and then treat each block based on the type. Then you render all the blocks. Something like this:

```java
ProcessedMime pm = js.mime_process(rawMessage);
System.out.println("From:" + pm.getAddressHeader("from")[0].getAddress());
MessageBlock[] blocks = pm.getBlocks();
for (MessageBlock block : blocks) {
	if (Objects.equals(block.getType(), MessageBlock.TYPE_TEXT)) {
		// should be displayed
		System.out.println(block.getContent());
	} else if (Objects.equals(block.getType(), MessageBlock.TYPE_PGP_MESSAGE)) {
		// should be decrypted, then displayed
		System.out.println(block.getContent());
	} else {
		// should display a block with Not Implemented notice in it:
		System.out.println("FlowCrypt Android cannot process " + block.getType() + " (not implemented)");
	}
}
```

Here is the key. `js.mime_process` will expect to work with first 200kb of each mime message. I have tested this on desktop apps that also use IMAP: you can request first 200kb of a message, and if the message is smaller, you'll get the whole MIME message. If larger, you'll get only the first part of it. `js.mime_process` will happily work with a cropped message, because 200kb will definitely contain all important parts in the message body, and only large attachments will be cropped. This should work in 99% of the cases, and later we can fix and improve the remaining 1%.

Here is how I do the SMTP query in JavaScript (we'll do something similar in Java):
```js
imap.listMessages(path, uid, ['RFC822.SIZE', 'BODY[]<0.204800>'], {byUid: true}).then(messages => {
      resolve(messages[0]['body[]']) // first 200kb of mime message
    }, reject)
```

This will create `IMAP UID FETCH xxxxxxxxxxxxx (RFC822.SIZE BODY[]<0.204800>)` or a similar IMAP command. The relevant spec is here: https://tools.ietf.org/html/rfc3501#section-6.4.5

This will take care of displaying the message contents.

For any actual attachments, we will later use IMAP BODYSTRUCTURE call along with fetching individual attachments as user clicks on them.

I've done some tests on IMAP desktop app I'm developing and I think it will be very robust.

**Comment by tomholub** [comment]
Here are some samples of this code in action on the desktop client

![2017-06-17-155715_1152x730_scrot](https://user-images.githubusercontent.com/6306961/27256791-da19e39e-5375-11e7-93a8-ea1a6e467232.png)

![2017-06-17-155746_1152x730_scrot](https://user-images.githubusercontent.com/6306961/27256792-da1b3460-5375-11e7-89b9-6d9f18c9981b.png)

![2017-06-17-155845_1152x730_scrot](https://user-images.githubusercontent.com/6306961/27256793-da20adb4-5375-11e7-9f77-b7d562fa0db4.png)

**Comment by tomholub** [comment]
Visual design of TYPE_PGP_MESSAGE block (successfully decrypted):
 - top and bottom borders: 1px solid #f0f0f0
 - left and right borders: 4px solid #31A217
 - background (repeat-x and repeat-y): https://github.com/CryptUp/cryptup-browser/blob/master/chrome/img/lock-seamless-bg-alpha.png

Visual design of TYPE_PGP_MESSAGE block (error decrypting - for example encrypted for wrong key):
 - top and bottom borders: 1px solid #f0f0f0
 - left and right borders: 4px solid #d14836
 - background (repeat-x and repeat-y): https://github.com/CryptUp/cryptup-browser/blob/master/chrome/img/lock-seamless-bg-alpha.png

Visual design for TYPE_TEXT block:
 - no borders, no background

Visual design for all other blocks:
 - top and bottom borders: 1px solid #f0f0f0
 - left and right borders: 4px solid #989898
 - no background

**Comment by tomholub** [comment]
@DenBond7 Please look into this and start implementing it, it's an important part of how PGP works - often times messages are structured in a variety of ways that we need to work with.

I will send you a few test emails to demonstrate that.

**Comment by tomholub** [comment]
I've sent several test emails to denbond7test@gmail.com

For now, all block types that are not a standard PGP message block (message), you can just go ahead and render them as text if you like, later we'll look into how to process them. 

Especially password encrypted messages are a bit complicated (need to be downloaded from API) - leave that for later.

**Comment by DenBond7** [comment]
How to know the public key owner?
![image](https://user-images.githubusercontent.com/2863246/28373009-e42e9814-6ca9-11e7-99a4-0184883688c6.png)

**Comment by tomholub** [comment]
You can do 
```Java
PgpKey k = js.crypto_key_read(...);
String owner = k.getPrimaryUserId().getEmail();
```

**Comment by tomholub** [comment]
Once you know the email of the owner, you can compare it to the database of public keys. And offer an action for the user: 

1) longid matches database for that email - leave as is
2) no pubkey recorded for that email - add button "Save"
3) longid is different for that email - add button "Update"

We'll worry about design details later.

**Comment by DenBond7** [comment]
Already added

- [ ] TYPE_TEXT = "text";
- [ ] TYPE_PGP_MESSAGE = "message";
- [ ] TYPE_PGP_PUBLIC_KEY = "public_key";
- [ ] TYPE_PGP_SIGNED_MESSAGE = "signed_message";
- [ ] TYPE_PGP_PASSWORD_MESSAGE = "password_message";
- [ ] TYPE_ATTEST_PACKET = "attest_packet";
- [ ] TYPE_VERIFICATION = "cryptup_verification";

**Comment by tomholub** [comment]
Looks great. I'm closing this for now, we can do future improvements as individual issues.
