### ISSUE TITLE
option to only keep pass phrase in memory

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#372]

**Comment by tomholub** [comment]
Also users often request a simple pin code option:
> I also suggest/request a pin or fingerprint protection for the app itself.

**Comment by DenBond7** [comment]
> fingerprint protection

I thought about that. It's a good idea.

**Comment by tomholub** [comment]
Another user

> Can you include support on Android devices for password/fingerprint required to view encrypted mail?

**Comment by tomholub** [comment]
part of #714

**Comment by tomholub** [comment]
> [@bilalashraf123] Note:- If the user accidentally deletes or changes the Fingerprint/FaceID (Android/iOS), then any asset protected with that biometric is no more usable. We should provide instructions to the user about this.

**Comment by DenBond7** [comment]
@tomholub Could you share more details? I mean how do you see that. Because due to the difficult lifecycle of the Android app we can have different thoughts about this issue. I need a little more info.

**Comment by bilalashraf123** [comment]
When generate key pair in Android, there is an option to associate an authentication mecahism with it. The authentication mechanism could be device fingerprint. For this, fingerprint needs to be registered.

If authentication mechanism is bound to the key, one cannot access the key without providing the fingerprint. If user deletes the fingerprint on Android device, then that particular key cannot be accessed anymore.

When use Android key store provider, the key pair is generated and stored in TEE (Trusted execution environment)/StrongBox and cannot be exported. TEE is available I believe after Andoid 6.

**Comment by tomholub** [comment]
Sorry Bilal - this issue is not about user's fingerprint or TEE or pins or other similar mechanisms. While this is a related concern (how to ensure that user has acceptable UX on a phone, instead of having to always input long pass phrases), this particular issue is purely about not storing pass phrases in long-term storage. Above, Den is asking about how exactly to achieve that, which may involve some of what you mentioned, but that's not the core of the issue.

For this particular issue, I'd like to see something like this:

-------------------

(consumers) During setup (of new OpenPGP key, or when importing key or when loading from backup - whenever I'm creating or entering pass phrase), the user should see two radio buttons:

> **o**   store pass phrase locally
> o   keep pass phrase in memory

Default is to store, just like now.

If the user switches it to memory-only, then we do not store pass phrase with the key (or at all). We only keep the pass phrase in memory for up to 4 hours from the moment it was stored - then it needs to be forgotten. During those 4 hours, the key will be used for actions (eg decrypt messages). After those 4 hours, the user will be prompted for a pass phrase with a modal / alert to re-enter it, at which point it will be again remembered for 4 hours.

If app gets killed, pass phrase gets forgotten.

For now, there will be no way for user to switch this anywhere in settings. They would have to log out and re-setup.

---------------------

(enterprise users with appropriate OrgRule as described in #1168 - don't ask user, automatically only store in memory)

--------------------

@DenBond7 with this in mind - is this achievable purely using standard Java code? Just keep some information in background process in memory for up to 4 hours, then wipe it?

**Comment by DenBond7** [comment]
@tomholub Thanks! That's what I meant.

> with this in mind - is this achievable purely using standard Java code?

It's ok in the Java world. But... It can be a little difficult on Android. Let me explain. We can any data in the RAM while the app process is alive. But you can easy reproduce a situation that kills our process due to memory optimization. And it will a regular Android system behavior. For example, please run FlowCrypt then move it to the background. After that try to open 10-20 different apps. After that try to open FlowCrypt and you will that the app starts from the fresh state. It depends on different things: manufacturer, RAM and etc. I can't control that.

So only the following can be true:
1. Keep passphrase up to 4 hours in the RAM
2. While 1 is true keep passphrase in the RAM if the app process is alive.(it can be from 0 up to 4 hours as I described in 1.)

**Comment by bilalashraf123** [comment]
Can we do something like this?

- store pass phrase locally
- keep pass phrase temprarily - In this case, store passphrase for 4 hours in local storage securely

When `keep pass phrase temprarily`, we can apply same security mesaures as we are are for option `store pass phrase locally`, only difference is the prompt of passphrase after 4 hours or not.

After 4 hours, clear the passpharse and store again securely after taking input from the user.

**Comment by DenBond7** [comment]
@bilalashraf123 of course we can do that. We can have a task for Work manager that will check and clear temporary passphrases.

@tomholub 
I'm thinking about one more way. We can use for example https://developer.android.com/guide/components/foreground-services. In that case we can have our passphrases in RAM. But we will have to show a notification in the status bar always.

**Comment by DenBond7** [comment]
For example like Mi Fit, Google Translate

![Screenshot_2021-05-05-18-24-22-33](https://user-images.githubusercontent.com/2863246/117166707-4b69ea00-adcf-11eb-8d2d-d8f4c118f762.jpg)

**Comment by bilalashraf123** [comment]
please correct me If I am wrong. The actual requirement could be not to ask for passphrase for 4 hours. It does not matter where to store the password temporarily.

**Comment by tomholub** [comment]
> please correct me If I am wrong. The actual requirement could be not to ask for passphrase for 4 hours. It does not matter where to store the password temporarily.

We didn't discuss this in detail on mobile apps, just a note that "eventually would be good to use fingerprint or pin to protect the pass phrase".

We did discuss it on the browser extension, where we could use session storage (that browser may store to file system) that we manually empty after 4 hours, and this was rejected - saving it locally is a hazard that the customer does not want.

On Android the situation is a bit different due to the abundance of options to address this further (pin/fingerprint/secure keychain and so on) but I don't want to get into it yet, because it's an implementation and design rabbit hole (plus so many types of devices, etc).

**Comment by tomholub** [comment]
> So only the following can be true:
> 
>     1. Keep passphrase up to 4 hours in the RAM
> 
>     2. While 1 is true keep passphrase in the RAM if the app process is alive.(it can be from 0 up to 4 hours as I described in 1.)

We can store in memory as you say, and consider it expected behavior that the pass phrase may last less than 4 hours if the OS kills the process for memory management.

**Comment by tomholub** [comment]
> @bilalashraf123 of course we can do that. We can have a task for Work manager that will check and clear temporary passphrases.
> 
> @tomholub
> I'm thinking about one more way. We can use for example https://developer.android.com/guide/components/foreground-services. In that case we can have our passphrases in RAM. But we will have to show a notification in the status bar always.

This is an excellent option! That way, there could also be a button "forget now" on the notification.

**Comment by DenBond7** [comment]
@tomholub By the way, what about operations like changing passphrase? As for me if a user chooses the option `keep pass phrase in memory` it should be a read-only prv key. Maybe in the future, we will improve that.

**Comment by tomholub** [comment]
> @tomholub By the way, what about operations like changing passphrase? As for me if a user chooses the option `keep pass phrase in memory` it should be a read-only prv key. Maybe in the future, we will improve that.

Initially, you can do that.

**Comment by DenBond7** [comment]
- [ ] test migration
- [ ] add to CheckKeysActivity
- [ ] add to CreatePrivateKeyActivity

**Comment by DenBond7** [comment]
@tomholub 
Let me clarify a few questions
1) Should we support importing not-protected keys(not encrypted)? Can a user import such a key to the app?
2) Can we have a situation when a key was encrypted with an empty passphrase? Should we support such a key?

**Comment by tomholub** [comment]
Encrypt with empty pass phrase, I think, equals to not encrypted (but I'm not 100% sure).

We don't have to support non-encrypted keys. On browser, when you import non-encrypted keys, you are asked to enter a pass phrase to encrypt the key with, before we store it into storage. On Android, we can ask the user to encrypt the keys and try importing again - for now (unless we already do the same thing as on browser?)

**Comment by DenBond7** [comment]
> We don't have to support non-encrypted keys. On browser, when you import non-encrypted keys, you are asked to enter a pass phrase to encrypt the key with, before we store it into storage. On Android, we can ask the user to encrypt the keys and try importing again - for now (unless we already do the same thing as on browser?)

I'll create an issue for that. On Android we don't handle such a case

**Comment by tomholub** [comment]
It doesn't cache the pass phrase itself - it caches decrypted private key packets.

**Comment by DenBond7** [comment]
@tomholub I need an advice. What info would you like to show here (notification content)?

![image](https://user-images.githubusercontent.com/2863246/119311746-1c31f480-bc7a-11eb-8bee-d73ef71648c0.png)

![image](https://user-images.githubusercontent.com/2863246/119311806-31a71e80-bc7a-11eb-9d25-cff5b8de1139.png)

https://developer.android.com/guide/topics/ui/notifiers/notifications?hl=ru#Templates

**Comment by tomholub** [comment]
content title: `Active pass phrase session`
content text: `Tap here to end session`

We may change it later

**Comment by tomholub** [comment]
`Forget pass phrase` in middle screen shot could actually be green as well

In right screenshot, can just call it `check pass phrase`. It's ok if it remembers it implicitly, after that the user can see the button changed and can say `forget pass phrase`

**Comment by tomholub** [comment]
:+1:

**Comment by DenBond7** [comment]
@tomholub I'm thinking about the current issue. It isn't a simple and for now I've just added only a base functionality. And it produced a lot of changes in the code (architecture changes). I think we have to divide the current issue to a few smaller to be able to review it comfortable.

What already works: 
- we can import a key with pass phrase in RAM
- after that the app will run a foreground service that will erase pass phrases every 4 hours
- we can go Settings - Keys - Select some key. There we can erase or add a pass phrase. It was added to be able to test a situation when we have or haven't a pass phrase in RAM.

I propose too accept the current changes for this issue and open new issues for the following:
- decrypt a message
- creat an encrypted message
- make a backup
- change passphrase of imported keys
- decrypt an attachment

All of those cases is not handled properly now. App doesn't crash but a user will see some sort of errors. 

@tomholub It would be great if you test the current changes with described cases to see what exactly happens

One more thing. We can't release the current changes while we don't cover all cases that I've described. For now I propose to make available use pass phrase in RAM only for the debug builds. The release builds should work as before.

**Comment by tomholub** [comment]
You can still render both ram and storage radio buttons during setup, but in production builds make the ram option grayed out. Then we can release even before we fix all of these.

**Comment by DenBond7** [comment]
@tomholub Please share your opinion - would you like to have a sound when we show a notification or I have to show it silently?

![image](https://user-images.githubusercontent.com/2863246/119666186-cefe8000-be3d-11eb-8289-ba62233ddc8d.png)

**Comment by tomholub** [comment]
silently please

**Comment by tomholub** [comment]
Even better if the notification didn't really "show up", and only be visible when we go to notifications

**Comment by DenBond7** [comment]
For the history. Here I've added only a base realization without error handling.
