### ISSUE TITLE
resolve situation when sender pubkey not found (disable some sending addresses)

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#378]
Can implement suggestion from https://github.com/FlowCrypt/flowcrypt-android/issues/375#issuecomment-441016028 or discuss further if cannot be implemented as described.

**Comment by DenBond7** [comment]
@tomholub Have you created a new message or a reply?

I've investigated code and found you receive an error when using the main account (not aliases).

https://github.com/FlowCrypt/flowcrypt-android/blob/782f8af3c0dd95f05f3dd3d25e223a39f3dfc56e/FlowCrypt/src/main/java/com/flowcrypt/email/security/SecurityUtils.java#L214

It means `senderEmail == accountDao.getEmail()`. But in that case `userIdEmailsKeysDaoSource.getLongIdsByEmail(context, senderEmail)` returns an empty list. It's really strange. If you have such problems on the debug build I can add logs. Maybe it'll help us.

**Comment by DenBond7** [comment]
@tomholub 
> Maybe that is the issue?

Of course, it's a reason for our issue. 

We have next code

```
    \\senderEmail = help.cryptup.org@gmail.com
    \\accountDao.getEmail() = help.cryptup.org@gmail.com
    UserIdEmailsKeysDaoSource userIdEmailsKeysDaoSource = new UserIdEmailsKeysDaoSource();
    List<String> longIds = userIdEmailsKeysDaoSource.getLongIdsByEmail(context, senderEmail);

    if (longIds.isEmpty()) {\\true, because we don't have a row with help.cryptup.org@gmail.com in the database, we have a row with human@flowcrypt.com
      if (accountDao.getEmail().equalsIgnoreCase(senderEmail)) {\\true
        throw new NoKeyAvailableException(context, accountDao.getEmail(), null);\\we receive such error
      } else {
        longIds = userIdEmailsKeysDaoSource.getLongIdsByEmail(context, accountDao.getEmail());
        if (longIds.isEmpty()) {
          throw new NoKeyAvailableException(context, accountDao.getEmail(), senderEmail);
        }
      }
    }
```

Have you received an error when you were using help.cryptup.org@gmail.com? Am I right?

**Comment by DenBond7** [comment]
@tomholub 
I've found how to reproduce such an issue.

For example, we have the account `main@google.com` and the alias `alias@example.com`. And we have a private key ONLY for `alias@example.com`.

1. We need to setup the app using another account

1. Then we go to the side menu -> **Add account** -> **CONTINUE WITH GMAIL** -> **USE EXISTING KEYS**

1. Then we go to the side menu -> **Settings** -> **Keys** -> Add a new private key for `alias@example.com`

And now we have a situation like yours:

- if we select `main@google.com` as a sender -> the app doesn't create a message

- if we select `alias@example.com` -> the app creates and sends a message

**Comment by DenBond7** [comment]
Here #269 we've described a logic what a key need to use.

I think after migration to use a service for sending messages I've skipped a logic of showing next error

> If I'm sending from main account address:search in the table by main account address. If found longid, use that key (public version). if not found, show error No key available for your email address main@email.com.\n\nPlease write human@flowcrypt.com for help.

**Comment by DenBond7** [comment]
@tomholub I've added new code. Please try it and notify me if need to add any changes.

**Comment by tomholub** [comment]
In my case, the situation was due to a manually created key in other software. This is very common for people who are migrating from other solutions. The account email, aliases and users mentioned in the key may mismatch completely, and we will over time have to improve how we deal with it.

Thank you, I will test this.

**Comment by tomholub** [comment]
Now it will properly show error when I use sender email that doesn't have a key associated. Can you also make such sending addresses gray and disabled? Ideally, if I click them, I would receive the same error as a toast.

**Comment by DenBond7** [comment]
@tomholub I've added changes. Please try it.

**Comment by DenBond7** [comment]
@tomholub 
What a logic do we have here:

1. When we open this screen we always have minimum one email address
1. If we use Gmail we can have aliases here
1. if a user uses Gmail and has aliases:
 * as the first record, we add the main account email address to the drop-down list
 * if the user has aliases we add them to the end of the drop-down list
 * if the user creates a new message we always show the main account address as "FROM"
 * if the user replies to some message we check the "TO" addresses: 
   * if the "TO" addresses contain one of the aliases we show the first matched aliases as "FROM"
   * if the "TO" addresses don't contain one of the aliases we show the main account address as "FROM"

> Please, before rendering, sort results by enabled aliases first, disabled items last. So that when I open the page, I don't have to always change it from disabled to enabled.

In this case, I propose next:

* If we use a standard creation/reply I'll use the logic above
* If we use the encrypted mode I'll check the "TO" addresses and:
  * if the "TO" addresses contain one of the aliases with a private key I'll show the first matched aliases as "FROM"
  * if the "TO" addresses don't contain one of the aliases with a private key I'll show the first matched address which has a private key
* I can change an order of addresses in the drop-down list. But I think will be better to show the main account address as the first record. I this case a user will always know that the first record it's the main account address, and other records - these are aliases.

**Comment by DenBond7** [comment]
@tomholub 
> So that when I open the page, I don't have to always change it from disabled to enabled.

I've added that.

**Comment by tomholub** [comment]
Ok this will work. In the future, we will make the order configurable just like on desktop. Also, we will have to add a way to add more user to public key.
