### ISSUE TITLE
some outbox items won't go away

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#381]
I have two items in outbox from before that are showing "Sending..." for days.

When I send a new message, it will show preparing, queued, sending etc, but the two won't move.

How can we debug this?

![screenshot_20181128-161306](https://user-images.githubusercontent.com/6306961/49141230-0c760700-f2ee-11e8-9f4b-b3e882891df1.png)

**Comment by DenBond7** [comment]
@tomholub 

>How can we debug this?

It can happen when the sending process was interrupted. For example, when J2V8 fails and kills a process. In that case, a message has a state == `Sending`. And we can't do any actions with this message.

I propose to add next:

1. When the app is starting after some kill need to check all outgoing messages and change a message state to `Queued` if the message has a state == `Sending`. It helps to resolve a situation when the app was killed unexpectedly. ( And maybe it was your case)

2. Actually, in one moment can be only one message with the state == `Sending`. Need to check other outgoing messages and change a message state to `Queued` if some other message has a state == `Sending`. It'll prevent a situation when some message freezes on the state == `Sending`.

I'll add changes and notify you. After that, we will try to debug the current issue.

**Comment by tomholub** [comment]
That sounds good, thanks

**Comment by tomholub** [comment]
Ok now both stuck messages got sent.
