### ISSUE TITLE
error opening a message - setFlag

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#39]
Started using the Android app more, I'm sometimes getting these errors:

![screenshot_20170619-000034](https://user-images.githubusercontent.com/6306961/27345650-5c0c7eea-559f-11e7-91e1-7d66f75f4ce2.png)

**Comment by DenBond7** [comment]
Is there a dependence of this error on the folder in which the message is located?

**Comment by tomholub** [comment]
It was all in inbox. It seems to happen when the app was running for a
longer time in background (hours) and then a message is opened. But not
always, sometimes it seems to happen even when the app was just started.

Maybe the IMAP connection dropped?

**Comment by DenBond7** [comment]
> Maybe the IMAP connection dropped?

Maybe.

I think this problem will be solved after I finish the issue 31.

**Comment by tomholub** [comment]
ok, I'll observe it after the update

**Comment by tomholub** [comment]
haven't seen this issue since
