### ISSUE TITLE
add a "Node backend test" button in Experimental Settings

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#395]
We would include Node backend for testing only, it would not be incorporated with the rest of the app yet

**Comment by tomholub** [comment]
@DenBond7 test out https://github.com/FlowCrypt/flowcrypt-android-node/

See if you can build it, if it works for you, and let's add the test to experimental settings

The binaries included are quite large, so we may do several builds, one per each platform, if Google Play supports that.

**Comment by tomholub** [comment]
Notice that the following .cpp paths need to be adjusted based on where you put the NativeNode class in the project structure:

https://github.com/FlowCrypt/flowcrypt-android-node/blob/ed595a77598bd9125420aa2ccfe1d6ad5372a148/FlowCrypt/src/main/cpp/native-lib.cpp#L18

https://github.com/FlowCrypt/flowcrypt-android-node/blob/master/FlowCrypt/src/main/cpp/native-lib.cpp#L35

https://github.com/FlowCrypt/flowcrypt-android-node/blob/master/FlowCrypt/src/main/cpp/native-lib.cpp#L101

https://github.com/FlowCrypt/flowcrypt-android-node/blob/master/FlowCrypt/src/main/cpp/native-lib.cpp#L108

I can help with it if needed.

**Comment by tomholub** [comment]
The Node backend can potentially handle stream encryption, but I have not implemented that yet to keep things simple. Once we start supporting files > 3MB, that would be the time to implement streaming.

**Comment by tomholub** [comment]
Also, when adding it to the project, you do not need to add the TypeScript folder. I think I will keep that in a separate project. Just the javascript source file from assets.

**Comment by DenBond7** [comment]
@tomholub Do you have an example of raw CURL request for that?

```
MultipartEntityBuilder builder = MultipartEntityBuilder.create();
      builder.setMode(HttpMultipartMode.BROWSER_COMPATIBLE);
      builder.addTextBody("endpoint", endpoint);
      builder.addTextBody("request", req != null ? req.toString() : "{}");
      builder.addBinaryBody("data", data);
      URL url = new URL("https://localhost:" + nodeSecret.port + "/");
      HttpsURLConnection conn = (HttpsURLConnection) url.openConnection();
      conn.setRequestMethod("POST");
      conn.setRequestProperty("Authorization", nodeSecret.authHeader);
      conn.setRequestProperty("Connection", "Keep-Alive");
      conn.setDoInput(true);
      conn.setDoOutput(true);
      conn.setSSLSocketFactory(nodeSecret.getSslSocketFactory());
      HttpEntity parts = builder.build();
      conn.addRequestProperty(parts.getContentType().getName(), parts.getContentType().getValue());
      OutputStream os = conn.getOutputStream();
      parts.writeTo(os);
      conn.connect();
```

Something like this

```
POST /account/login  {
	"account" (<type 'str'>)  # owner email
	"uuid" (<type 'str'>)  # uuid for authentication
	"token" (<type 'str'>, None)  # token to verify account-uuid pair
}, response(200): {
	[voluntary] "registered" (True, False)  # Account registered
	[voluntary] "verified" (True, False)  # uuid verifiedd
	[voluntary] "subscription" (<type 'dict'>, None)  # subscription status
	[voluntary] "error" (<type 'str'>)  # additional text for the user
}
```
Are these Json?

```
builder.addTextBody("endpoint", endpoint);
      builder.addTextBody("request", req != null ? req.toString() : "{}");
      builder.addBinaryBody("data", data);
```

I'm not very familar with the Apache library. I always use retrofit for the network requests

**Comment by tomholub** [comment]
```Java
builder.addTextBody("endpoint", endpoint);
builder.addTextBody("request", req != null ? req.toString() : "{}");
builder.addBinaryBody("data", data);
```
"endpoint" is a string
"request" is a JSON request, as a string (contains metadata)
"data" is a binary blob. Just bytes.

All together this is a http multipart request (`multipart/form-data`) similar to what html forms do when you submit them. It allows you to send several unrelated felds. The binary blob is at the end to allow streaming in the future (can start working on an incomplete binary file chunk by chunk).

**Comment by tomholub** [comment]
Actually, I could simplify this. I'm looking at it again. We don't really need the multipart request.

**Comment by DenBond7** [comment]
> I hope that retrofit can use HttpsURLConnection as well, or that it has a method similar to conn.setSSLSocketFactory();

Yes, it supports a custom SSLSocketFactory. I've made a success http request. But I'm receiving an error that the server can't parse json

**Comment by tomholub** [comment]
@DenBond7 for now, please completely ignore "endpoint", "req" and "data" when preparing the request. Just make create a `new ByteArrayOutputStream()` or something similar for the request body and pass that to retrofit. Let Node return parsing errors for now, and commit that back to git.

I just need some way to write byte by byte into the output stream and then close it. If you can give me that, I will get rid of the multipart mechanism. I think it's unnecessarily complicating things.

**Comment by tomholub** [comment]
Here is an example of a curl (ignoring the SSL setup)
```
curl 'https://localhost:3000/' -H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:64.0) Gecko/20100101 Firefox/64.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Referer: https://localhost:3000/' -H 'Content-Type: multipart/form-data; boundary=---------------------------16845677311209836993977559736' -H 'Authorization: Basic OmRldi1wYXNzd29yZA==' -H 'Connection: keep-alive' -H 'Upgrade-Insecure-Requests: 1' -H 'Cache-Control: max-age=0' --data '-----------------------------16845677311209836993977559736\nContent-Disposition: form-data; name="endpoint"\n\ndecryptFile\n-----------------------------16845677311209836993977559736\nContent-Disposition: form-data; name="request"\n\n{"keys": [], "passphrases": []}\n-----------------------------16845677311209836993977559736\nContent-Disposition: form-data; name="data"; filename="test.txt"\nContent-Type: text/plain\n\nthis is a test\n\n-----------------------------16845677311209836993977559736--\n'
```
Sample multipart request:
```
-----------------------------16845677311209836993977559736
Content-Disposition: form-data; name="endpoint"

decryptFile
-----------------------------16845677311209836993977559736
Content-Disposition: form-data; name="request"

{"keys": [], "passphrases": []}
-----------------------------16845677311209836993977559736
Content-Disposition: form-data; name="data"; filename="test.txt"
Content-Type: text/plain

this is a test

-----------------------------16845677311209836993977559736--
```

This was a request from browser instead of Java and Node didn't like it: `Error: Ending marker before begin marker`. That looks like a bug in my Node code.

I could fix it, but I'm starting to think that multipart requests are overkill, and hard to support, with not many well functioning builders and parsers. I think a custom format will be better suited and easier to maintain.

Going forward, we will use a simplified format where the body contains: 
1) UTF8-encoded request name before the first `LF (ASCII code 10)`
2) UTF8-encoded request JSON metadata before the second `LF (ASCII code 10)`
3) binary data afterwards until the end of stream

So a request could look like:
```
encryptFile
{"pubKeys": ["----BEGIN PGP PUBLIC KEY---\\n....\\n..."], "name": "testFile.txt"}
blablabla
binary data
this could be text, image, doesn't matter
blabla
```
If you can create a way for me to send bytes to the POST request body in Java, I will set it up and debug the connection. Once it works, you can refactor the Java code after me if needed.

**Comment by DenBond7** [comment]
> If you can create a way for me to send bytes to the POST request body in Java, I will set it up and debug the connection. Once it works, you can refactor the Java code after me if needed.

for me https://github.com/square/okhttp/wiki/Recipes

**Comment by DenBond7** [comment]
@tomholub [Here](https://github.com/FlowCrypt/flowcrypt-android-node/commit/4227dff8fb9ae1f4eef85d53c01817e056680244) I've added a simple realization which uses retrofit.

But I still need to fix 2 issues [here:](https://github.com/FlowCrypt/flowcrypt-android-node/blob/4227dff8fb9ae1f4eef85d53c01817e056680244/FlowCrypt/src/main/java/com/yourorg/sample/api/retrofit/RetrofitHelper.java#L65)

1.
```
//todo-denbond7 Need to look at sslSocketFactory deprecation 
      okHttpClientBuilder.sslSocketFactory(nodeSecret.getSslSocketFactory());
```

As documentation says 

> SSLSocketFactory does not expose its X509TrustManager, which is a field that OkHttp needs to build a clean certificate chain. This method instead must use reflection to extract the trust manager. Applications should prefer to call sslSocketFactory(SSLSocketFactory, X509TrustManager), which avoids such reflection.
 

2.
```
//todo-denbond7 Need to look at hostnameVerifier. 
      okHttpClientBuilder.hostnameVerifier(new HostnameVerifier() {
        @Override 
        public boolean verify(String hostname, SSLSession session) {
          return true; 
        } 
      });
```
Without this line, I always receive an error. 
################################################################

> If you can create a way for me to send bytes to the POST request body in Java,

Now you can send any data using `InputStream`( ByteArrayInputStream, FileInputStream, StringBufferInputStream and etc.)

**Comment by tomholub** [comment]
I actually tried using okhttp before using Apache and I was not able to get across that exact issue and successfully use `sslSocketFactory(SSLSocketFactory, X509TrustManager)` in a way that I don't get errors.

Is there any advantage of using OkHttp over URL for communication between Java and Node?

**Comment by DenBond7** [comment]
> Is there any advantage of using OkHttp over URL for communication between Java and Node?

Now it's one of the most useful tools for the network requests. It helps do network requests easy and returns a result to the main thread. I have not spent enough time to resolve that issue. I'm going to investigate more examples and the Android source code tomorrow. If I'll fail we will try something other.

**Comment by tomholub** [comment]
fixed at https://github.com/FlowCrypt/flowcrypt-android-node/commit/e7dd62f767efc81c47ecc709c90213e095d3095d
