### ISSUE TITLE
rsa routines:RSA_padding_check_PKCS1_type_2:pkcs decoding error

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#398]
Quite frequent recently

**Comment by DenBond7** [comment]
@tomholub please check your emailbox

**Comment by DenBond7** [comment]
![image](https://user-images.githubusercontent.com/2863246/50009598-06577a00-ffc0-11e8-8b2a-2c653390cd88.png)

**Comment by tomholub** [comment]
Looks good. Theoretically, you would only have to reset / delete things that are in the encrypted storage, eg maybe parts of the database can be reused if they are meaningful on their own (like cache of email metadata, etc)

**Comment by DenBond7** [comment]
> Theoretically, you would only have to reset / delete things that are in the encrypted storage, eg maybe parts of the database can be reused if they are meaningful on their own (like cache of email metadata, etc)

Will be better to reset all settings. Because a user needs to setup all accounts again (The current key pair can't decrypt saved passphrases).

**Comment by tomholub** [comment]
Got it
