### ISSUE TITLE
add JDK version to compiler options

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#403]
in build.gradle

```
android {

    // ...

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7 // todo - try 1.8
        targetCompatibility JavaVersion.VERSION_1_7
    }
}
```
To prevent Android studio from continuously switching between 1.7 and 1.8

**Comment by DenBond7** [comment]
https://jakewharton.com/androids-java-8-support/

To use Java 8 we need to use a minimum API of 26 or newer

**Comment by DenBond7** [comment]
I'm closing it. We've migrated to use Java 8 and minSdk = 26
