### ISSUE TITLE
improved email input behavior

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#405]
Feedback from user:
> The keyboard for everything am email address should be specialized for email addresses. In particular @ should be on the main keyboard screen and '.' should not be a sentence termination. Entering an email address not in your address list is impossible.

I have not tested it but having @ on the keyboard sounds reasonable

**Comment by DenBond7** [comment]
@tomholub 
>  In particular @ should be on the main keyboard screen

I've added such an ability.

> and '.' should not be a sentence termination. Entering an email address not in your address list is impossible.

It was fixed after I added inputType="textEmailAddress". But such a bug can happen only on devices where enabled the next option

![device-2019-01-08-200622](https://user-images.githubusercontent.com/2863246/50850351-512b9e00-1382-11e9-987d-bc7fc9ba21d0.png)
