### ISSUE TITLE
Fix copyright missing after added external source

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#409]
Need to fix copyright missing when #395 will be closed

**Comment by tomholub** [comment]
Just be careful with the c++ files. The copyright for those should be whatever original copyright there was, because we're reusing other people's code. It was MIT I think you should check.

**Comment by DenBond7** [comment]
It'll be fixed after #411

**Comment by DenBond7** [comment]
@tomholub [Here](https://github.com/FlowCrypt/flowcrypt-android/commit/5618d67c0a7f0189c5e20d84dbd4f4305d107e13) I've added a copyright profile. From now each file which you'll create will have a copyright header. If you need to change something you can use this instruction [IDEA Copyright (Paragraphs: Insert copyright text into files. Update copyright text)](https://www.jetbrains.com/help/idea/copyright.html). Now such work will be much easier.

**Comment by tomholub** [comment]
Looks good. They should apply to files, not classes (too much clutter)
