### ISSUE TITLE
Support 64-bit architectures

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#410]
I've temporarily disabled support 64-bit architectures. flowcrypt-android-node supports 64-bit architectures, but j2v8 doesn't. When I allow 64-bit architectures j2v8 doesn't work. So we need to enable support 64-bit architectures after we'll remove j2v8.

Important links:
https://android-developers.googleblog.com/2017/12/improving-app-security-and-performance.html
```
https://github.com/eclipsesource/J2V8/issues/379
https://github.com/eclipsesource/J2V8/issues/384
```

**Comment by DenBond7** [comment]
Need to change settings to

```
ndk {
            abiFilters "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
}
```

**Comment by tomholub** [comment]
Does this mean that Node would not work on 64bit at all? Or will it be using the 32bit binary?

**Comment by DenBond7** [comment]
@tomholub 
> Or will it be using the 32bit binary?

It'll be using the 32bit binary like j2v8 uses

**Comment by DenBond7** [comment]
Interesting links(for the future research)
https://android.jlelse.eu/controlling-apk-size-when-using-native-libraries-45c6c0e5b70a
https://developer.android.com/ndk/guides/abis

**Comment by tomholub** [comment]
I imagine in this upcoming release we will bundle binaries for all platform, so the apk will be big. Later we can maybe have a build for each platform.

**Comment by tomholub** [comment]
We are not removing J2V8 yet, right? I'm moving this to later.

**Comment by DenBond7** [comment]
@tomholub 
> We are not removing J2V8 yet, right?
Yes, you are right.

**Comment by tomholub** [comment]
:)
