### ISSUE TITLE
Node base logic

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#411]
**NodeResultParser** - should be very general with no specific logic for each call. So it would not have any JSON parsing. It would only strip the JSON line, then dump the data into a file. If there is no data after the json, it should not create a file and just pass json and a null. So the result would be - **`RawNodeResult`**:
1) `Exception error` (or null if there was no error)
2) `String jsonLine` (or null if there was error and we could not get a json line)
3) `Uri data` (or null if there was no data, or null if there was an error)

**AbstractNodeResult** - can parse a Json and do other common things with all methods protected.

Finally, we would have for example `EncryptMsgResult` and many others that extend `AbstractNodeResult`. The constructor would accept `RawNodeResult` and parse all details right in the constructor. Now we have a simple object that we can send to the main thread.

from https://github.com/FlowCrypt/flowcrypt-android-node/issues/28

**Comment by DenBond7** [comment]
@tomholub How do you think which a milestone - 0.7.1 or 0.7.2?

**Comment by DenBond7** [comment]
@tomholub I've added some changes to our logic. I've used a custom implementation of [Converter.Factor](https://square.github.io/retrofit/#restadapter-configuration) (Please look at _CUSTOM CONVERTERS_). Now [NodeConverterFactory](https://github.com/FlowCrypt/flowcrypt-android/blob/issue_411/FlowCrypt/src/main/java/com/flowcrypt/email/api/retrofit/node/NodeConverterFactory.java) it's the main point of communication to the Node.js server. Here we have:

1. [NodeRequestBodyConverter](https://github.com/FlowCrypt/flowcrypt-android/blob/issue_411/FlowCrypt/src/main/java/com/flowcrypt/email/api/retrofit/node/NodeRequestBodyConverter.java) - it's a class which makes requests.

1. [NodeResponseBodyConverter](https://github.com/FlowCrypt/flowcrypt-android/blob/issue_411/FlowCrypt/src/main/java/com/flowcrypt/email/api/retrofit/node/NodeResponseBodyConverter.java) - it's a class which handles responses.

1. [NodeJsonReader](https://github.com/FlowCrypt/flowcrypt-android/blob/issue_411/FlowCrypt/src/main/java/com/flowcrypt/email/api/retrofit/node/NodeJsonReader.java) - it's a class which parses json from an input stream.

Such a logic helps to use a common behavior of retrofit and help to use memory efficiently (Java).

**Comment by tomholub** [comment]
can you rename `yourorg/sample/` to something meaningful? Or just add it to our main package?

**Comment by tomholub** [comment]
Where is the Node experimental activity located? I don't see it in https://github.com/FlowCrypt/flowcrypt-android/tree/620483bce5f0886bdd4a4e45ba779528e2f66688/FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/settings

**Comment by DenBond7** [comment]
@tomholub 
> Where is the Node experimental activity located?

https://github.com/FlowCrypt/flowcrypt-android/blob/0.7.1/FlowCrypt/src/main/java/com/yourorg/sample/ui/activity/MainActivity.java

**Comment by DenBond7** [comment]
> can you rename yourorg/sample/ to something meaningful? Or just add it to our main package?

Ok, I'll do it soon.

**Comment by tomholub** [comment]
The changes from https://github.com/FlowCrypt/flowcrypt-android/issues/411#issuecomment-453832047 look ok

**Comment by DenBond7** [comment]
@tomholub 
We have the next example for `decryptMsg` call:

```
##the Json block##
{"success":true,"blockMetas":[{"type":"html","length":72}]}

##the binary data block##
{"type":"html","content":"this is ~<br>a test for<br><br>decrypting<br>unicode:Σ<br>that&#39;s all","complete":true}
```

Is there any reason to send decrypted data using the binary data block? Can we use the Json block for that?

**Comment by tomholub** [comment]
This is for streaming. There may be more than one block, and you want to receive one by one.

If everything was sent as a single json, if you get a 25MiB message that contains 1KiB of text and 24,999KiB of encrypted files,  you have decrypt and wait for 25MiB of data before you can even show the text of the message. In this case, it would not be even worth to bother with streaming too much, because we cannot take advantage of the streaming when decrypting messages.

Instead, when you send one json per line, it would look something like:
```
{"success":true,"blockMetas":[{"type":"html","length":1000},{"type":"file","length":2499000,"name":"some-photo.jpg"}]}
{"type":"html","content":"...","complete":true}
{"type":"file","content":"...","complete":true,"name":"some-photo.jpg"}
```
 - App gets all metadata from the first json, so it can render a general message structure right away (empty text area and encrypted file icon).
 - As soon as it receives the first JSON blob, it can render message text
 - Later it can receive the file and store into a tmp file

PGP/MIME messages can be quite complicated. You could have 1kb of text, 5mb attachment in the middle, then 1 kb of text, then another attachment, etc. All of this encrypted inside one large PGP/MIME message, where you don't know the structure until you start decrypting it. The android app doesn't support these yet, but soon will.

If you have an idea for a simpler mechanism to work well with streaming, let me know.

**Comment by DenBond7** [comment]
Got it. I asked you because I thought we have separate calls(`decryptMsg`, `decryptFile' ) for that purposes. I thought `decryptMsg` only for a not big text and `decryptFile' for files. 

> PGP/MIME messages can be quite complicated. You could have 1kb of text, 5mb attachment in the middle, then 1 kb of text, then another attachment, etc.

Yes, It's complicated. I thought encrypted files store as separate part of MIME message. I didn't know that we can have all of data as a single PGP message.

**Comment by tomholub** [comment]
Yes. PGP/MIME does this. It has better privacy properties - observers may know it's 5MB big, but they don't know if this is one big attachment or 10 small ones, or what their exact sizes are.

IF decryptMsg did not have to deal with large files, I would definitely make it return a simple json, so this is a very valid question.

**Comment by DenBond7** [comment]
> IF decryptMsg did not have to deal with large files, I would definitely make it return a simple json, so this is a very valid question.

Now we are loading only first 200kb of a message. So returning decrypted data as JSON will be enough.

If we are going to use node realization instead j2v8 I think we need to prepare very similar behavior for the first time. Then we can improve it and change, step by step.

I think for `encryptMsg` we can use JSON too (for the first time). I don't think somebody will write a huge text on Android ( for example a few Mb). For the file encryption I will use `encryptFile`. Currently we can separate those processes.

**Comment by tomholub** [comment]
You have to think about messages you are receiving, not sending.

We have to be able to receive messages created by other software. These messages may be a PGP/MIME message that is mixed text and files, for example.

**Comment by tomholub** [comment]
Is pulling the blocks one by one creating complexity in your code?

**Comment by DenBond7** [comment]
It's completed
