### ISSUE TITLE
Fix attachment header

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#425]
https://github.com/FlowCrypt/flowcrypt-browser/issues/1513

https://github.com/FlowCrypt/flowcrypt-android/blob/master/FlowCrypt/src/main/assets/js/flowcrypt-android.js#L48573

**Comment by DenBond7** [comment]
@tomholub I can just rename `X-Att-Id` to `X-Attachment-Id`. But I think it'll be better to do changes like in https://github.com/FlowCrypt/flowcrypt-browser/commit/2bcc61bbf24ffdce446292c37a981311356bae43

![screenshot from 2019-02-04 09-42-35](https://user-images.githubusercontent.com/2863246/52195711-b8455100-2861-11e9-821f-7d645a67db58.png)

**Comment by tomholub** [comment]
Ah, I didn't know this was affecting you in this way too.

**Comment by tomholub** [comment]
Basically I just need to pull the TypeScript core from flowcrypt-browser to flowcrypt-android-node, then it will get updated.

**Comment by DenBond7** [comment]
> Ah, I didn't know this was affecting you in this way too.

Maybe not :) I don't know what that code does. But I've found `X-Att-Id` and decided to post this issue.

**Comment by tomholub** [comment]
Ok that's good, I'll get it updated

**Comment by tomholub** [comment]
Actually, you can learn how to do this.
1) clone flowcrypt-android-node   # next to flowcrypt-android - same parent dir
2) clone flowcrypt-browser   # next to flowcrypt-android - same parent dir
3) cd flowcrypt-android-node/TypeScript && npm install

Now, to update to latest core, do:
1) cd flowcrypt-browser && git pull
2) cd flowcrypt-android-node && git pull
3) npm run-script updateCore  # grabs latest core from flowcrypt-browser
4) npm run-script deploy  # replaces flowcrypt-android.js in flowcrypt-android folder

If the above step did not show errors, that means typescript build is successful and most likely it will work. You can now find updated flowcrypt-android.js in your android folder, you can test it. If it passes our experimental tests, you can commit the changes to flowcrypt-android-node.

**Comment by tomholub** [comment]
I could make a shell script for you to cover the last four steps

**Comment by DenBond7** [comment]
> I could make a shell script for you to cover the last four steps

Yes, it can help me. But in most cases, I won't know what I do :) Because I'm not familiar with JavaScript :) So you'll need to check all my steps. And it can take much more time than you will do JavaScript changes by yourself as well.

**Comment by tomholub** [comment]
True, but you will become more familiar with the rest of our tech, which is
beneficial. :)

**Comment by DenBond7** [comment]
@tomholub I agree.

> I could make a shell script for you to cover the last four steps

Please do it when you will have some free time

**Comment by tomholub** [comment]
Will do. For now, I'm closing this.
