### ISSUE TITLE
list of functionality that Node is missing

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#432]
- [x] Work with keys --> get PgpKey from string, js.crypto_key_normalize, js.crypto_key_read, js.is_valid_key, 
- [x] PgpContact --> get fingerprint, longid, keywords from public key
- [x] js.str_is_email_valid
- [x] Other methods ---> time_to_utc_timestamp, uint8,js.api_gmail_query_backups

// tom - I moved remaining endpoints to a new issue for another release

**Comment by DenBond7** [comment]
@tomholub I've added details.

**Comment by DenBond7** [comment]
I see in 0.7.3 we can replace only message encryption.

**Comment by tomholub** [comment]
Ok let's just release it with message encryption

**Comment by tomholub** [comment]
Actually

**Comment by DenBond7** [comment]
> Actually

Fixed :)

**Comment by tomholub** [comment]
I have a function that works with keys, it should replicate most of
    * Work with keys --> get PgpKey from string, js.crypto_key_normalize, js.crypto_key_read, js.is_valid_key,
and also
    * PgpContact --> get fingerprint, longid, keywords from public key, js.str_is_email_valid


Also, 
    * Work with PGP blocks ---> crypto_armor_detect_blocks(). Actually, we have BlockMetas, but I think it's not the same
This will not be needed anymore. Remember, `decryptMsg` will return BlockMetas, but then it will return block by block of the actual MsgBlock[]. So no more need to detect them one by one.

**Comment by DenBond7** [comment]
> but then it will return block by block of the actual MsgBlock[]

Yes, you are right. I've found it.

https://github.com/FlowCrypt/flowcrypt-android/blob/issue_433/FlowCrypt/src/main/java/com/flowcrypt/email/api/retrofit/response/model/node/MsgBlock.java

**Comment by tomholub** [comment]
I added the following endpoints:

```js
dateStrParse = { dateStr: string } => { timestamp: string } // timestamp is string that contains a number
gmailBackupSearch = { acctEmail: string } => { query: string }
```
there should be no binary data coming in or out, only jsons

**Comment by tomholub** [comment]
Also adding `parseKeys` that takes empty json, and then the binary part contains the key(s) to parse. It can take one key or many keys, it can be private or public keys, it can be armored or binary.. doesn't matter. You should be able to use this in contacts import, key import and other places. If not, let me know what needs fixing or adding.

Possible responses:

```js
{ format: 'unknown', keyDetails: [], error: { message: `Cannot parse key: could not determine pgpType` } }
{ format: 'armored', keyDetails: KeyDetails[] }
{ format: 'binary', keyDetails: KeyDetails[] }
```

Where KeyDetails[] is an array of the following objects:

```js
{
  private: string?; // armored private key, if this was a private key, else not present
  public: string; // armored public key, this will be present for both public and private keys
  ids: {
    shortid: string; // you should probably ignore this field
    longid: string;
    fingerprint: string;
    keywords: string;
  }[]; // it's an array because that's how OpenPGP keys work. To preserve functionality to work like before, you can only pay attention to the first item in the array, that is your primary set of ids
  users: string[]; // user ids
  created: number; // unix timestamp when key was created
  algo: { // for now you can ignore this part
    algorithm: string; // eg rsa or similar
    algorithmId: number; // OpenPGP algo ID, you may ignore
    bits?: number; // 4096, 2048, 1024 etc, for RSA keys, else not present
    curve?: string; // type of curve for ECC keys, else not present
  };
}
```

**Comment by tomholub** [comment]
Adding
```js
isEmailValid = { email } => { valid: boolean }
```

**Comment by tomholub** [comment]
That should be enough for this release.

I have not tested any of the new functionality. It's using code that was already tested before, but I may have made a mistake when surfacing this code to the endpoints. So if you run into issues, let me know. Also format can be updated to be easier to work with.

**Comment by tomholub** [comment]
Here is `parse keys` sample output:
```json
{
    "format": "armored",
    "keyDetails": [
      {
        "public": "-----BEGIN PGP PUBLIC KEY BLOCK-----\r\nVersion: FlowCrypt 0.0.1-dev Gmail Encryption\r\nComment: Seamlessly send and receive encrypted email\r\n\r\nxsBNBFwBWOEBB/9uIqBYIPDQbBqHMvGXhgnm+b2i5rNLXrrGoalrp7wYQ654\r\nZln/+ffxzttRLRiwRQAOG0z78aMDXAHRfI9d3GaRKTkhTqVY+C02E8NxgB3+\r\nmbSsF0Ui+oh1//LT1ic6ZnISCA7Q2h2U/DSAPNxDZUMu9kjh9TjkKlR81fiA\r\nlxuD05ivRxCnmZnzqZtHoUvvCqsENgRjO9a5oWpMwtdItjdRFF7UFKYpfeA+\r\nct0uUNMRVdPK7MXBEr2FdWiKN1K21dQ1pWiAwj/5cTA8hu5Jue2RcF8FcPfs\r\nniRihQkNqtLDsfY5no1B3xeSnyO2SES1bAHw8ObXZn/C/6jxFztkn4NbABEB\r\nAAHNEFRlc3QgPHRAZXN0LmNvbT7CwH8EEAEIACkFAlwBWOEGCwkHCAMCCRA6\r\nMPTMCpqPEAQVCAoCAxYCAQIZAQIbAwIeAQAKCRA6MPTMCpqPENaTB/0faBFR\r\n2k3RM7P427HyZOsZtqEPxuynsLUqmsAAup6LtPhir4CAsb5DSvgYrzC8pbrf\r\njCaodoB7hMXc8RxTbSh+vQc5Su4QwY8sqy7hyMXOGGWsRxnuZ8t8BeEJBIHy\r\nPguXIR+wYvo1eveC+NMxHhTtjoSIn/E4vW0W9j5OlFeTK7HTNCuidIE0Hk2k\r\nXnEEoNO7ztxPPxsHz9g56uMhyAhf3mqKfvUFo/FLLRBOpxLO0kk64yAMcAHm\r\nc6ZI5Fz10y48+hHEv/RFOwfub9asF5NWHltanqyiZ+kHeoaieYJFc6t7Mt3j\r\ng8qxMKTUKAEeCfHt1UJCjp/aIgJRU4JRXgYXzsBNBFwBWOEBB/9nclmx98vf\r\noSpPUccBczvuZxmqk+jY6Id+vBhBFoEhtdTSpaw/JNstf0dTXN8RCFjB0lHt\r\na51llTjSobqcFwAU54/HKDOW3qMVbvadaGILpuCMCxdMgLWlpZdYY7BApv1N\r\n9zpN+iQ2tIrvnUQ312xKOXF/W83NUJ1nTObQYNpsUZLLG2N3kz11HuBS3E9F\r\ngEOYYy1tLT53hs5btqvQ5Jp4Iw5cBoBoTAmv+dPMDKYBroBPwuFeNRIokwLT\r\nrVcxrXajxlXaGXmmGS3PZ00HXq2g7vKIqWliMLLIWFl+LlVb6O8bMeXOT1l0\r\nXSO9GlLOSMDEc7pY26vkmAjbWv7iUWHNABEBAAHCwGkEGAEIABMFAlwBWOEJ\r\nEDow9MwKmo8QAhsMAAoJEDow9MwKmo8QjTcH/1pYXyXW/rpBrDg7w/dXJCfT\r\n8+RVYlhW3kqMxbid7EB8zgGVTDr3us/ki99hc2HjsKbxUqrGBxeh3Mmui7OD\r\nCI8XFeYl7lSDbgU6mZ5J4iXzdR8LNqIib4Horlx/Y24dOuvikSUNpDtFAYfa\r\nbZwxyKa/ihZT1rS1GO3V7tdAB9BJagJqVRssF5g5GBUAX3sxQ2p62HoUxPlJ\r\nOOr4AaCc1na92xScBJL8dtBBRQ5pUZWOjb2UHp9L5QdPaBX8T9ZAieOiTlSt\r\nQxoUfCk7RU0/TnsM3KqFnDFoCzkGxKAmU4LmGtP48qV+v2Jzvl+qcmqYuKtw\r\nH6FWd+EZH07MfdEIiTI=\r\n=wXbX\r\n-----END PGP PUBLIC KEY BLOCK-----\r\n",
        "users": [
          "Test <t@est.com>"
        ],
        "ids": [
          { "fingerprint": "E76853E128A0D376CAE47C143A30F4CC0A9A8F10", "longid": "3A30F4CC0A9A8F10", "shortid": "0A9A8F10", "keywords": "DEMAND MARBLE CREDIT BENEFIT POTTERY CAPITAL" },
          { "fingerprint": "9EF2F8F36A841C0D5FAB8B0F0BAB9C018B265D22", "longid": "0BAB9C018B265D22", "shortid": "8B265D22", "keywords": "ARM FRIEND ABOUT BIND GRAPE CATTLE" }
        ],
        "algo": {
          "algorithm": "rsa_encrypt_sign",
          "bits": 2048,
          "algorithmId": 1
        },
        "created": 1543592161
      }
    ]
  }
```

I just wrote automated tests & all of the new endpoints seem to be working well.

**Comment by tomholub** [comment]
Closing this as Node functionality is ready. To address Java functionality, you can create separate issues. Thanks!

**Comment by tomholub** [comment]
Also please reopen this if any functionality is buggy or should be changed.

**Comment by DenBond7** [comment]
@tomholub 
I've forgotten about js.crypto_key_decrypt(key, passphrase) for a case where we import private keys (When we are checking the passphrase). Could we include it to the current release? Then we'll have only the key creation action in the next release.

**Comment by tomholub** [comment]
Ok I can include that

**Comment by tomholub** [comment]
It will return success and `decryptedArmored`. You can ignore the decrypted field if you are only testing pass phrase. But you would also then need a `encryptKey` method for changing pass phrases, right?

**Comment by DenBond7** [comment]
> But you would also then need a `encryptKey` method for changing pass phrases, right?

Yes, you are right. But we can include it to the next release. Current code refactoring needs only the `decryptKey` function.

**Comment by tomholub** [comment]
You may also need a function like `isKeyDecrypted`, correct?

**Comment by DenBond7** [comment]
In the current code, I don't use such a function. Maybe it would be useful in the future.

**Comment by tomholub** [comment]
You will definitely need it because new version of OpenPGP.js behaves differently than the old one.
```js
// Old version:
alreadyDecryptedKey.decrypt('wrong pass phrase') -> true
alreadyDecryptedKey.decrypt('') -> true // empty pass phrase
// new version
alreadyDecryptedKey.decrypt('wrong pass phrase') // throws exception, already decrypted
alreadyDecryptedKey.decrypt('') // throws exception, already decrypted
```
So now you have to first check if it's already decrypted, and don't try to decrypt if it is.

**Comment by DenBond7** [comment]
Could we return the field 'encrypted' when I am calling `parseKeys`? Then I don't need `isKeyDecrypted`
it'll look like

```json
{
    "format": "armored",
    "keyDetails": [
      {
        "encrypted":true,
        "private": "-----BEGIN PGP PRIVATE KEY BLOCK-----\r\nVersion: FlowCrypt 0.0.1-dev Gmail Encryption\r\nComment: Seamlessly send and receive encrypted ...",
        "users": [
          "Test <t@est.com>"
        ],
        "ids": [
          { "fingerprint": "E76853E128A0D376CAE47C143A30F4CC0A9A8F10", "longid": "3A30F4CC0A9A8F10", "shortid": "0A9A8F10", "keywords": "DEMAND MARBLE CREDIT BENEFIT POTTERY CAPITAL" },
          { "fingerprint": "9EF2F8F36A841C0D5FAB8B0F0BAB9C018B265D22", "longid": "0BAB9C018B265D22", "shortid": "8B265D22", "keywords": "ARM FRIEND ABOUT BIND GRAPE CATTLE" }
        ],
        "algo": {
          "algorithm": "rsa_encrypt_sign",
          "bits": 2048,
          "algorithmId": 1
        },
        "created": 1543592161
      }
    ]
  }
```

**Comment by tomholub** [comment]
I was exactly now thinking the same thing, yes :)

**Comment by tomholub** [comment]
`keyDetails` now has `isDecrypted` property. I used this name to mimic OpenPGP.js `k.isDecrypted()` function. It returns `true | false` if this is a private key, or `null` for public keys.

Two new endpoints added:
```
decryptKey { armored: string, passphrases: string[] } => { decryptedKey: string } // you can give more pass phrases if you don't care which one matches
encryptKey { armored: string, passphrase: string } => { encrytpedKey: string }
```
You should only feed them results from our own storage or from `keyDetails.private`, because they expect that this is only one, valid, well formatted armored key.

**Comment by DenBond7** [comment]
> You should only feed them results from our own storage or from `keyDetails.private`, because they expect that this is only one, valid, well formatted armored key.

Ok, got it. Thanks!
