### ISSUE TITLE
Use Node for message decryption

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#433]

**Comment by DenBond7** [comment]
@tomholub Does Node decrypt message function support MIME message? Or I can send only a valid PGP message?

Because J2V8 realization works with MIME messages.

**Comment by tomholub** [comment]
Not yet, but I could improve that.

Maybe I can do it so that Node just accepts a whole MIME message, and gives you back decrypted or plain text blocks

**Comment by tomholub** [comment]
Then you would always just send each message to Node regardless if it's encrypted or not? Because you would not know

**Comment by DenBond7** [comment]
@tomholub 
> Then you would always just send each message to Node regardless if it's encrypted or not?

It'll be the best option.

**Comment by tomholub** [comment]
Ok. I don't think I can do that for the current release. But maybe for the next one. Are there still things that you can start using from Node on this release, or is the functionality too limited?

**Comment by tomholub** [comment]
You can also start removing functions from Js that we have completely covered in Node or that we are not using. Then the remaining functions are basically a list of what I need to do.

**Comment by DenBond7** [comment]
> Are there still things that you can start using from Node on this release, or is the functionality too limited?

I need to investigate this question. I've started to work on replacing the message decryption function and found I can't use Node.js in the current app logic. I think I will move this issue to the `later` milestone.

**Comment by tomholub** [comment]
If I remember correctly, you had to parse each mime message in Js, then get back result, and then optionally decrypt the result. Unifying that in single Node function would be quite good.

**Comment by DenBond7** [comment]
Yes, you are right.

**Comment by tomholub** [comment]
this is ready in Node for next release (0.7.4) as detailed in #437
