### ISSUE TITLE
decryptMsg and email parsing using Node

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#437]
`decryptMsg` endpoint now takes an optional `isEmail` parameter in request json (bool).

When `isEmail: true`, the binary data will be interpreted as an email mime message. This could be a plain email or encrypted.

If it was encrypted, the encrypted message parts will get decrypted. Attachments do not get decrypted.

The response format is the same: you get `MsgBlock[]` back.

We should get rid of decryption using legacy `Js` entirely.

**Comment by tomholub** [comment]
Bonus: this version now supports PGP/MIME. No change in Java needed, you get the result as `MsgBlock[]` like before.

**Comment by DenBond7** [comment]
@tomholub 
I've tried this functionality but I've received an error

I send the following request

```
{
   "isEmail":true,
   "passphrases":[
      "My password"
   ],
   "keys":[
      {
         "longid":"FFFFFFFFFFFFFFFF",
         "private":"-----BEGIN PGP PRIVATE KEY BLOCK-----....-----END PGP PRIVATE KEY BLOCK-----\r\n"
      }
   ]
}

Return-Path: <denbond7@denbond7.com>
Delivered-To: default@denbond7.com
Receivefrom mail.denbond7.com (localhost [127.0.0.1])
	by mail.denbond7.com (Postfix) with ESMTP id 35CBC202F1
	for <default@denbond7.com>; Fri, 15 Mar 2019 14:52:10 +0000 (UTC)
X-Virus-ScanneDebian amavisd-new at mail.denbond7.com
Receivefrom mail.denbond7.com ([127.0.0.1])
	by mail.denbond7.com (mail.denbond7.com [127.0.0.1]) (amavisd-new, port 10024)
	with ESMTP id EstQPjUmZ4Hn for <default@denbond7.com>;
	Fri, 15 Mar 2019 14:52:01 +0000 (UTC)
Receivefrom localhost (MiA1 [192.168.3.6])
	by mail.denbond7.com (Postfix) with ESMTP id E17EF202E9
	for <default@denbond7.com>; Fri, 15 Mar 2019 14:52:00 +0000 (UTC)
Content-Type: multipart/mixed;
 boundary="----sinikael-?=_1-15526615192100.5959024994440685"
In-Reply-To: <>
References: <>
To: default@denbond7.com
From: denbond7@denbond7.com
Subject: Simple encrypted message
Date: Fri, 15 Mar 2019 14:51:59 +0000
Message-I<1552661519275-40db11d3-834101fe-9096ab5d@denbond7.com>
MIME-Version: 1.0
------sinikael-?=_1-15526615192100.5959024994440685
Content-Type: text/plain
Content-Transfer-Encoding: quoted-printable
-----BEGIN PGP MESSAGE-----
Version: FlowCrypt 0.7.3 Gmail Encryption
Comment: Seamlessly send and receive encrypted email
wcBMA/47aTYseLEDAQf9H9LsYvzeqpscSJARVtLon9K+IhYyO0CXKo6OcJOV
gkniFsWn3x1X8jcB0yG/eGcueXvwlJGjQPM7HBwhW7yaz0K1ydtDVZuvBrPO
3hmi61rUug+GcylOEC4BmjE6EOPKScb8b9zyK/nlsk4snRHtdMvnowVenwQm
8xh1ADSzGEgYQHA4iVYZCXmqG/xKGgemTkIX1VjHHCSMmQcNEiaGSNaZCkmH
fzORHHohSK46JskSy4uBDhe+qa499pJRt6Mr2Wxyup9lJSkHd02ylVZ2uIy5
3BziomIcKa8ZG/YLnzTD1q/cvk3U/y1lPBlG+zZjppX1ZJcoq7TaAd5hkiWy
XsGMA+qN/UHblp9OAQQAmSb1km5t4QdBfRkrJRe+z+u9uO1JwNjsZ+Oi5ofo
3xIIahwYbDpE4gPpiJmKjoNmDMVdlcVIUFkQ/RVFMA2WhPVFOX3/Id+Ca5jK
GKdfo4FmwAp6lkET+rJ5Pe1p+IjAqR4umJuJPXYK3rDQHq2nUalfHHg43u1M
x24CVUHLzIrSTQGXtZNhtaig5JXmP8uQMTPxe443nY02Ti6qk2FAn4j17pXR
nFDid8sVi9p0fCIQfqjRwCGo+Bbtjex29mgbOIDjfk4oWG56tpu9lA31
=3DMP4M
-----END PGP MESSAGE-----
------sinikael-?=_1-15526615192100.5959024994440685--
```
But in logs I see

```
E: TypeError: TextEncoder is not a constructor
        at Object.encode ([eval]:3841:20)
        at Object.convert ([eval]:3895:42)
        at MimeNode._emitBody ([eval]:19672:50)
        at MimeNode.finalize ([eval]:19309:18)
        at MimeNode._processBodyLine ([eval]:19573:40)
        at MimeNode.writeLine ([eval]:19298:18)
        at MimeParser.write ([eval]:19123:23)
        at Promise ([eval]:69288:14)
        at Promise (<anonymous>)
        at Function.module.exports.Mime.decode.mimeMsg [as decode] ([eval]:69225:10)
```

```
D: <-- 200 OK https://localhost:33273/ (284ms)
D: Date: Tue, 19 Mar 2019 13:55:11 GMT
D: Connection: keep-alive
D: Content-Length: 33
D: {"success":true,"blockMetas":[]}
D: <-- END HTTP (33-byte body)

```

What do I do wrong?

**Comment by tomholub** [comment]
I'll take a look. Request looks ok

**Comment by tomholub** [comment]
@DenBond7 can you please prepare a way for me to test this? Something that I can do in the app that would cause this error, so that I can debug.

**Comment by DenBond7** [comment]
@tomholub 
> can you please prepare a way for me to test this?

I've added. You can use those [changes](https://github.com/FlowCrypt/flowcrypt-android/commit/1f54a8e0822e6ea06206ea891a5c251d4411a93d) for debugging. Just open any encrypted message.

**Comment by tomholub** [comment]
Will do

**Comment by tomholub** [comment]
> Maybe we can add a new flag ( something like "wasEncrypted")

@DenBond7 Do you only need it for styling / rendering?

I'm asking because if the only goal is styling, I could add a general `style` parameter instead, that could be `plain`, `green`, `gray` or `red`. Then in Android we render it using the suggested style, and you don't have to have separate logic to decide when to use which styling. Because you can have combinations of signed and encrypted, or we may want to have a special style for public keys, etc. This way all would be the same.

Unless you need to know if it was encrypted also for some other reason?

**Comment by DenBond7** [comment]
@tomholub 
I show information which depends of the message parts. Actually all parts may have different layouts (for example PGP_PUBLIC_KEY has a difficult layout). And those layouts are predefined. 

https://github.com/FlowCrypt/flowcrypt-android/blob/17203ea51fcc3b387970b386471c0359ba7079ec/FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/MessageDetailsFragment.java#L655

> wasEncrypted

I need it only to indentify what a part was encrypted. Because the current realization doesn't allow me identify it. I mean `type:text`. It may be a simple text or encrypted before.
When we were using J2V8 I knew what a part is encrypted before

https://github.com/FlowCrypt/flowcrypt-android/blob/17203ea51fcc3b387970b386471c0359ba7079ec/FlowCrypt/src/main/java/com/flowcrypt/email/js/MessageBlock.java#L17

**Comment by tomholub** [comment]
Right, but what do you use the information for? Is it for the styling of the blocks? Any other uses?

**Comment by DenBond7** [comment]
If I know what a block I have I'll know how to show and style it. Now we have the same blocks for a simple text and for an encrypted. it is confusing a little. To resolve it we can add or a new flag ( something like "wasEncrypted") or return a different type, for example `type: encryptedText`

> I'm asking because if the only goal is styling,

Currently, my main goal - understand what a block I have. We can add a styling block, but it's not necessary right now for me.

**Comment by tomholub** [comment]
I could actually clarify the types through the name, for example:
`text` -> `decryptedText` or `decryptedHtml`
`attachment` -> `encryptedAtt` or `plainAtt`

Would that work? I'll try to see if it's too big of a change or not.

-------------

Another thought I had is to add a `decryptFail` block. That way if the message has:
 - plain text block on top
 - then bad encrypted message
 - then something else (file or public key)
Android would still be able to render the good blocks, and only show the error instead of the decrypted message block.

But I'm afraid that it may complicate things. What do you think?

**Comment by DenBond7** [comment]
> Would that work?

I think yes. It's what I need now ( know what a block I have).

> What do you think?

I think we should parse blocks. Then if some block has some error we should add an additional info about that error to that block. Then we can show good blocks and errors of unparsed blocks. I think it's clear.

> But I'm afraid that it may complicate things

Unfortunately, it can not be simple :(. Because there are a lot of combinations of available parts.

**Comment by tomholub** [comment]
> I think we should parse blocks. Then if some block has some error we should add an additional info about that error to that block. Then we can show good blocks and errors of unparsed blocks. I think it's clear.

I would actually need to have a special block, eg `decryptErr` block, because until it's decrypted I would not know if it was `decryptedText` or `decryptedHtml` :) Is that ok?

**Comment by DenBond7** [comment]
@tomholub

> Is that ok?

Could you provide an example? It will be super helpful.

**Comment by tomholub** [comment]
Maybe success would be as follows:

Json line:
```json
{
  "success": true,
  "blockMetas": [
    { "type": "plainText", "length": 20 },
    { "type": "decryptedText", "length": 30 },
    { "type": "encryptedAtt", "length": 50 }
  ]
}
```
Data:
```
{ type: 'plainText', content: "some plain text" }
{ type: 'decryptedText', content: "some text that was successfully decrypted" }
{ type: 'encryptedAtt', length: 50, name: '...', content: '----BEGIN ENC ...' }
```

------------------
Decrypt error Json line:
```js
{
  "success": true, // meaning message was successfully parsed
  "blockMetas": [
    { "type": "plainText", "length": 20 },
    { "type": "encryptedMsg", "length: 500"}, // the code does not know it will be error yet, because of streaming
    { "type": "encryptedAtt", "length": 50 }
  ]
}
```
Data:
```
{ type: 'plainText', content: "some plain text" } // Android can render this
{ type: 'decryptErr', error: { message: ..., longids: {encryptedFor: [...] }, type: keyMismatch, ... } } // error content same as decrypt error today, but it would only affect this block
{ type: 'encryptedAtt', length: 50, name: '...', content: '----BEGIN ENC ...' }
```

**Comment by tomholub** [comment]
Now that I'm looking at it again, maybe the `blockMetas` are not very useful, because at the time Node is sending them, node has not attempted to decrypt anything yet, so it cannot know if there are errors or what will be inside encrypted blocks (there may be files or several blocks inside encrypted message). 

So actually, `blockMetas` is quite useless. The api could be simplified:

Json line:
```js
{} // empty json line except when there is fatal error
```
Success data:
```
{ type: 'plainText', content: "some plain text" }
{ type: 'decryptedText', content: "some text that was successfully decrypted" }
{ type: 'encryptedAtt', length: 50, name: '...', content: '----BEGIN ENC ...' }
```
Decrypt error data:
```
{ type: 'plainText', content: "some plain text" } // Android can render this
{ type: 'decryptErr', error: { message: ..., longids: {encryptedFor: [...] }, type: keyMismatch, ... } } // error content same as decrypt error today, but it would only affect this block
{ type: 'encryptedAtt', length: 50, name: '...', content: '----BEGIN ENC ...' }

```

**Comment by DenBond7** [comment]
> Is that ok?

Now I see I'm Ok with that.

**Comment by DenBond7** [comment]
> So actually, blockMetas is quite useless.

I parse this but don't use :)

**Comment by tomholub** [comment]
We should probably call it `parseDecryptMsg` because it does a lot more than just decrypting.

**Comment by tomholub** [comment]
@DenBond7 can you please send me a sample of a plain html message that cannot be parsed properly? The whole mime text. Please export it to file so that you don't miss newlines (the MIME sample above had missing newlines which I had to guess-add manually).

**Comment by tomholub** [comment]
The `decryptErr` block looks like this:
```json
{
    "type": "decryptErr",
    "content": "-----BEGIN PGP MESSAGE-----\nVersion: FlowCrypt [BUILD_REPLACEABLE_VERSION] Gmail Encryption\nComment: Seamlessly send and receive encrypted email\n\nwcBMAwurnAGLJl0iAQf+I2exIah3XL/zfPozDmVFSLJk4tBFIlIyFfGYcw5W\n+ebOL3Gu/+/oCIIlXrdP0FxIVEYnSEaevmB9p0FfXGpcw4Wr8PBnSubCkn2s\n+V//k6W1Uu915GmiwCgDkLTCP7vEHvwUglNvgAatDtNdJ3xrf2gjOOFiYQnn\n4JSI1msMfL5tmdFCyXm1g4mUe9MdVXfphrXIyvGu1Sufhv+T5FgteDW0c6lM\ng7G6jgX4q5xiT8r2LTxKlxHVlQSqvGlnx/yRXwqBs3PAMiS4u5JlKJX4aKVy\nFyN+gq++tWZC1XCSFzXfAf0rXcoDZ7nEkxdkKQqXgA6LCsFD79FMCtuenvzU\nU9JEAdvmmpGlextZcfCUmGgclQXgowDnjaXy5Uc6Bzmi8AlY/4MFo0Q3bOU4\nkNhLCiXTGNJlFDd0HLz8Cy7YXzLWZ94IuGk=\n=Bvit\n-----END PGP MESSAGE-----\n",
    "decryptErr": {
      "success": false,
      "error": {
        "type": "key_mismatch",
        "message": "Session key decryption failed."
      },
      "longids": {
        "message": ["0BAB9C018B265D22"],
        "matching": ["7C307E6F2092962D"],
        "chosen": ["7C307E6F2092962D"],
        "needPassphrase": []
      },
      "isEncrypted": true
    },
    "complete": true
  }
```
You can ignore the following fields: `isEncrypted`, `complete`, `success` - because they will always be the same.

**Comment by tomholub** [comment]
List of breaking changes:
 - `decryptMsg` endpoint renamed to `parseDecryptMsg`
 - `parseDecryptMsg` now always returns empty json `{}` line
 - decrypt errors are returned as `decryptErr` block among other blocks (see structure above, same as before, just inside a block)
 - renamed blocks:
    - `message` -> `encryptedMsg` (I think Android will not receive this type, it should get decrypted first)
    - `passwordMsg` -> `encryptedMsgLink`
    - `text` -> `plainText` or `decryptedText`
    - `html` -> `plainHtml` or `decryptedHtml`
    - `attachment` -> `plainAtt`, `encryptedAtt`, `decryptedAtt`, `encryptedAttLink`
