### ISSUE TITLE
Things which were affected after moving to use Node.js for the keys parsing

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#440]
```diff
- Before the current release need to test the next things:
+ Before the current release need to test the following things:
```

- [x] Settings --> Backup
- [x] Add new account --> Other accounts
- [x] Splash screen --> Gmail
- [x] Settings --> Backup--> Save private keys as a file
- [x] Message details --> case when missing keys (There are no keys for the current account)--> "I don't have any other  key"
- [x] Setting --> Keys (There are a lot of changes)
- [x] Import a pub key of the current account (SecurityUtils.getSenderPublicKey) during the message creation
- [x] Contact updating
- [x] clipboard checking
- [x] Add new account --> Gmail
- [x] Setting --> Security --> Change pass phrase
- [x] Settings --> Contacts --> Import. It would be great to test import contacts from a large file.

**Comment by tomholub** [comment]
Fixed language for you :)

**Comment by DenBond7** [comment]
@tomholub Thanks :). I've forgotten about `next` and `following`. After our discussion, I already know the differences a bit more. But I need to control myself a bit more :)

**Comment by DenBond7** [comment]
#436
