### ISSUE TITLE
Create a test for MessageDetailsActivity

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#444]
- [x] standard message (plane text)
- [x] standard message + attachment
- [x] simple encrypted message (simple encrypted text) 
- [x] simple encrypted message (simple encrypted text) + attachment
- [x] simple encrypted message (simple encrypted text) + pubkey
- [x] encrypted message with missing key error(test adding a missing private key, test sending a message with user pubkey: available one key or more)
- [x] decrypt errors
- [x] tets reply buttons (intended)

**Comment by tomholub** [comment]
Very good
