### ISSUE TITLE
Fix saving private keys for app version < 0.7.3

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#447]

**Comment by DenBond7** [comment]
https://github.com/FlowCrypt/flowcrypt-android/commit/b5ecf115d171ddd4b0ca20a863d7ac955e3fd9cb

**Comment by DenBond7** [comment]
I've found a bug. I'm reopening it.

**Comment by tomholub** [comment]
Best is to create a new issue if more code is added in another version (for the future).

**Comment by DenBond7** [comment]
Ok. Got it
