### ISSUE TITLE
dark theme option for evening work

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#448]
https://developer.android.com/guide/topics/ui/look-and-feel/darktheme

**Comment by DenBond7** [comment]
part of #714

**Comment by DenBond7** [comment]
for me https://designpub.ru/design-dark-theme-for-android-material-design-c7fb2e7a7ea3

**Comment by seisvelas** [comment]
User requested this :D

ref: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgxwKkbqGfxdjknTqgrgGzNVwslCN

**Comment by martgil** [comment]
We received another user's request:

https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGpGnFpFgTbblMmMxMxqjVXxzTh

**Comment by DenBond7** [comment]
https://github.com/FlowCrypt/flowcrypt-android/pull/1891 will close it
