### ISSUE TITLE
Google+ API deprecated

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#449]
Google is deprecating / has deprecated Google+ APIs. I was using them in browser to get user name and photo, I think. Are we using any on Android? If not then please close this.

**Comment by DenBond7** [comment]
@tomholub 
> Are we using any on Android?

We don't use Google+ APIs. We use a `following` (I remember :)) [implementation](https://developers.google.com/identity/sign-in/android/people) which uses Google Sign-in to retrieve the user's basic profile information.

**Comment by tomholub** [comment]
```diff
- We use a following
+ We use the following
```
:)
