### ISSUE TITLE
message doesn't decrypt or show any error

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#453]
see in flowcrypt.compatiblity 

![screenshot_20190227-180318](https://user-images.githubusercontent.com/6306961/53486014-877ec300-3a7f-11e9-8936-332395aa7322.png)

**Comment by tomholub** [comment]
Same thing happened in "standard encrypted message from FlowCrypt Chrome extension".

Automated tests should be definitely catching things like this.

**Comment by DenBond7** [comment]
@tomholub It's strange because I can decrypt this message.

![image](https://user-images.githubusercontent.com/2863246/53491759-d9cfdc00-3a9f-11e9-96b6-d9d9ccf6383b.png).
Could you show me Settings --> Keys? I want to know how to reproduce it.

**Comment by tomholub** [comment]
Regardless of what's causing it, messages should either decrypt or show error why they were not decrypted. Before you fix the cause of the issue, please fix the error reporting first.

I thought maybe it may have something to do with the migration / key storing fix in 0.7.3? You could try to set up on 0.7.2, then upgrade

![image](https://user-images.githubusercontent.com/6306961/53493273-e69a0300-3a92-11e9-9062-927a3c5d1a69.png)

**Comment by DenBond7** [comment]
@tomholub 
> I thought maybe it may have something to do with the migration / key storing fix in 0.7.3? You could try to set up on 0.7.2, then upgrade

Yes, you are right. I've caught this error after those steps.

> show error why they were not decrypted

I've found the reason. It's an error in my code. I'm receiving the following error:
![image](https://user-images.githubusercontent.com/2863246/53496673-32f13d00-3aab-11e9-963c-97c8da0373c3.png)

>Before you fix the cause of the issue, please fix the error reporting first. 

What should I show to a user?

**Comment by tomholub** [comment]
```
Could not decrypt this message due to error:

e.getMessage()
```
Show it in red border on the left, and report to ACRA

**Comment by tomholub** [comment]
We may need to add upgrades into automated tests, is it difficult to do upgrades as part of automated testing?

**Comment by tomholub** [comment]
For example, we could start using 0.7.2 as a "legacy". Then we would have one test that re-uses storage from 0.7.2, with 0.7.3 code, so that it's forced to use migrations as a part of the test.

Next time we have 0.8.5, it would again test it with the 0.7.2 storage, open a few messages, etc. Is that possible?

**Comment by DenBond7** [comment]
> e.getMessage()


Unfortunately, we don't have any text for that yet. (We haven't defined errorMsg for that)

https://github.com/FlowCrypt/flowcrypt-android/blob/33d14c37549237d00b59791558981fb6ff95f71c/FlowCrypt/src/main/java/com/flowcrypt/email/js/tasks/DecryptRawMimeMessageJsTask.java#L226

**Comment by tomholub** [comment]
Any string is fine as long as user can take screenshot. If the error is just a string constant, print the string constant

**Comment by DenBond7** [comment]
> Next time we have 0.8.5, it would again test it with the 0.7.2 storage, open a few messages, etc. Is that possible?

Yes. But it's a bit complicated. Because I need to prepare all the important things before running a test. For example, I need to have all files from data/data/com.flowcrypt.email for 0.7.2. Then I should replace all files in data/data/com.flowcrypt.email of the current app version. Then I can run the test.

**Comment by tomholub** [comment]
Do you have to have the 0.7.2 files at all? Is there a way to just run the 0.7.2 app manually one time, then export the storage into a file?

Then during automated tests, you would just start 0.8.5 code with 0.7.2 storage and run the test. This way you force it to do migrations.

**Comment by tomholub** [comment]
At the end of the test you throw away the updated storage, and re-use the old 0.7.2 storage on next test.

**Comment by DenBond7** [comment]
> Is there a way to just run the 0.7.2 app manually one time, then export the storage into a file?

I can backup project files. But I think you a little don't understand how the current realization of tests works. Let me explain it. I create tests which are independent as more as possible. What does it mean? It means every test can be run any time as a unique instance. Every UI test is creating for some Activity to test its functionality. For example, I need to test Settings --> Keys. 
https://github.com/FlowCrypt/flowcrypt-android/blob/33d14c37549237d00b59791558981fb6ff95f71c/FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/activity/KeysSettingsActivityTest.java#L55
I do the following steps:

1. Clear the app settings (ClearAppSettingsRule). I need to have a clear version of the app to be sure that the test before doesn't affect the current test.

1. Add an account. Because I can't test the current screen without an active account (AddAccountToDatabaseRule())

1. Add test private keys to the local database (AddPrivateKeyToDatabaseRule())

After that manipulation, I have a version of the app which looks like the installed app. Such realization helps me run any test independently.

So if I want to test the migration I need to replace files for every test. I don't say that it's impossible. It's just not easy and hard to maintain sometimes.

Actually, we don't need to replace files. We just need to prepare the right environment for a test. (as I've described for `Settings --> Keys`.)

**Comment by tomholub** [comment]
I understand that.

When you run the tests, where does the tested app keep its storage? In the ram, on the disk? Is there no way to import or export the storage into a file that can be re-used?

**Comment by tomholub** [comment]
Like, I can back up my phone storage, with 0.7.2 app on it. 

Then for each test, I could restore the backup onto the phone, upgrade to 0.8.5, then test it. This is a manual version, but surely there is a way to do something similar, automated.

Does the VM running the test not have any way to export and import the app storage?

**Comment by DenBond7** [comment]
> When you run the tests, where does the tested app keep its storage? In the ram, on the disk?

on the disk

**Comment by tomholub** [comment]
> on the disk

I'm thinking, we could just install 0.7.2, then zip the contents.

Then for each test, unzip the contents and run 0.8.5 or whatever new version with 0.7.2 storage.

**Comment by DenBond7** [comment]
> Then for each test, I could restore the backup onto the phone, upgrade to 0.8.5, then test it.

It's not a question only about upgrading the local database. The app can have other things which need to update. And this updating can be run in different places (different activities, services, broadcast receivers and etc.)

**Comment by DenBond7** [comment]
> And this updating can be run in different places (different activities, services, broadcast receivers and etc.)

it's the most difficult place. Because I run tests as independent thing

**Comment by tomholub** [comment]
What makes it difficult? Is it knowing when all of the updating is done? Or is it that you have to go through several activities to make sure the update is done?

**Comment by DenBond7** [comment]
@tomholub I've created a new issue for that. I think will be better to discuss testing that in a separate issue. 

> What makes it difficult?

I have a few different accounts on my email server which help me test different situations: no backups, one backups, a lot of the same backups, a few backups with different passwords and etc. For some tests I prepare dynamic data.

I want to say I have tests which test only a single action, not the whole process.

Need to think about testing the upgrading process. I will add details to separate issue when I will have a good idea.

**Comment by DenBond7** [comment]
Fixed

**Comment by tomholub** [comment]
Sorry for not expressing this clearly, you should still put `Could not decrypt this message due to error:` above to give the user some context, like this:

```
Could not decrypt this message due to error:

MISSING_PASS_PHRASES

Show original message [o  ]
```

This is ok for the kind of errors that we don't have any handling for yet. Of course, once we have a proper way to recognize and handle such errors, we will show a more friendly text.

**Comment by tomholub** [comment]
Also, it does not seem to get reported to ACRA? Errors that don't have good user-facing handling should be reported to ACRA.

**Comment by DenBond7** [comment]
> Also, it does not seem to get reported to ACRA?

Which build variant have you used? ACRA is enabled only for `release prod` builds by default and can be enabled for `debug prod` manually

**Comment by DenBond7** [comment]
![image](https://user-images.githubusercontent.com/2863246/53582323-ec254500-3b87-11e9-9dd9-6f65afc6cfae.png)

**Comment by tomholub** [comment]
I used `prodDebug`, so I guess I wasn't getting ACRA for that reason - understood.

**Comment by ashleysommer** [comment]
I came here due to a google search,
I installed FlowCrypt Android v0.7.3 from the Google Play Store, I imported my private keys, and added my passphrases. The keys show up correctly in the Keys screen.

When opening any encrypted email sent to me, I am seeing:
```
Cannot decrypt this message due to an error:
MISSING_PASS_PHRASES
```
Exactly like in that screenshot above.

I never used 0.7.2 and I haven't upgraded from an earlier version.

The FlowCrypt Firefox browser extension works fine, with the same private keys and passphrases.

**Comment by tomholub** [comment]
@ashleysommer where did you import the keys from? Which software originally created the keys? Thanks for reporting this.

**Comment by ashleysommer** [comment]
One key I created 3+ years ago, one key I created a couple of months ago, both using GnuPGP on Linux.
I imported them to FlowCrypt Android App by exporting from GnuPGP as ASCII-Armored text, copying them to my desktop clipboard, using a clipboard-sharing utility to copy the text to my Android phone clipboard, then using the Import from Clipboard option in the app.
The import process went smoothly, and the passphrase entered for the keys was correct.

Both keys (for two different mail accounts) show the same problem.

**Comment by tomholub** [comment]
Is this a subkey only key export?

Please put your private key into FlowCrypt settings - additional settings - experimental - check compatibility. (on the browser plugin). Please copy what it prints out here, or send it to human@flowcrypt.com with link to this issue. Thanks!

**Comment by ashleysommer** [comment]
This is a full key export, it includes multiple subkeys.
I've sent you an email to that address with the compatibility check output.

**Comment by tomholub** [comment]
@ashleysommer The key looks usual based on the export. Would you be able to create a test key for us that resembles the key you have? Then you'd share the test key and test pass phrase with us, and we'll use it to debug the app. I know it's a big ask but if you could do it, that would be of great help! Please let me know.

**Comment by ashleysommer** [comment]
Ok, I generated a new secret key using latest GnuPG v2.2.4 from Ubuntu 18.04, and sent it to that email address.
I've tried to get the key and subkeys as close as possible in configuration to my other two keys.
I imported it to the Android app and it is showing the same "MISSING_PASS_PHRASES" message when I attempt to decrypt a message.

**Comment by DenBond7** [comment]
Hello @ashleysommer. Thanks for reporting this. We've found you use the ECC keys. Unfortunately, the current realization which uses J2V8 does not support ECC keys. This issue will be fixed when we will use Node.js for the message decryption. I hope it'll be soon :)

**Comment by tomholub** [comment]
We aim to do that in upcoming update, in less than a month.

**Comment by ashleysommer** [comment]
@DenBond7 
Thank you for looking into this.
I thought it might be something along those lines.
I'm looking forward to the new release, and I will continue to use FlowCrypt just through the firefox browser extension until then.

**Comment by DenBond7** [comment]
Hello @ashleysommer. I'm happy to notify you that we've already migrated to use Node.js for all PGP actions. I hope now you can use the Flowcrypt Android app with no issues.
