### ISSUE TITLE
do not accumulate unused strings

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#455]
Is there a linter we can install that will mark unused strings as error? I'm seeing several in `strings.xml` that are not used anywhere in the project.

**Comment by DenBond7** [comment]
> Is there a linter we can install that will mark unused strings as error?

Unfortunately, we don't have such an option. Android Studio can't do that at runtime. Instead, we can use `Analyze -> Run inspection by name -> type Unused resources`.

And we can remove all unused resources before a release via `Refactor -> Remove Unused Resources`

https://stackoverflow.com/questions/4680285/is-there-any-simple-way-to-find-out-unused-strings-in-android-project/37352037

**Comment by tomholub** [comment]
Of course, not at runtime - I meant as a part of automated tests.

**Comment by tomholub** [comment]
Eventually we will be testing our source code (for good style and avoiding common mistakes), not only the built app, so this would be a first step in that direction.

**Comment by DenBond7** [comment]
@tomholub Ok. We can use ./gradlew lint for those purposes. But setup that needs some time. I've already removed unused resources. Now I propose to move the current issue to 0.7.4 or later milestone. What do you think?

**Comment by tomholub** [comment]
Ok no problem
