### ISSUE TITLE
review auto-generated code

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#456]
I know we use code generators for some of our code.

Can you please point me to which files are auto-generated?
Are they all in one folder, or are they mixed with "human" source code? 
What tools are used to generate them?
Where is the "original human-written source" based on which these are generated?

I know a common usecase for this is database classes. Anything else?

**Comment by DenBond7** [comment]
@tomholub Actually, we practically don't have such code. I just use [Android Parcelable code generator](https://plugins.jetbrains.com/plugin/7332-android-parcelable-code-generator) (https://github.com/mcharmas/android-parcelable-intellij-plugin/) for `Parcelable` objects and that's all. This plugin only adds a few methods to classes which implement `Parcelable` interface.

**Comment by tomholub** [comment]
Understood, that should not need special marking.
