### ISSUE TITLE
missing update contact / save contact button in pubkey

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#458]
Wasn't there an action button before? Like in the browser extension?

![screenshot_20190301-020558](https://user-images.githubusercontent.com/6306961/53591488-07924f00-3b8c-11e9-80d3-8baad05a759f.png)

**Comment by DenBond7** [comment]
@tomholub By default, `Save contact` and `Update contact` are not visible. I use the following logic to decide which a button should I show:
https://github.com/FlowCrypt/flowcrypt-android/blob/42088ce6d1fadbffef26c607accf5ff0ee281bab/FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/MessageDetailsFragment.java#L770

I think you didn't see any buttons, because `cryptup.tester@gmail.com` alredy presents in Contacts and has the same public key. So we don't need to show any buttons. Please correct me if I'm wrong

**Comment by tomholub** [comment]
I think we should show the button either way, because it makes it hard to update someone's public key if they have changed it.

**Comment by DenBond7** [comment]
@tomholub Could you clarify what I should to do? If we have a contact `test@test.com` with a public key `FF34..AC45` in the local database, should I show `Update contact` button if a given public key is `FF34..AC45` (which is a part of a received  message) and `test@test.com` is defined as an owner of this key?

**Comment by tomholub** [comment]
Actually, after some thought, the best would be:
1) parse public key
2) find out primary email from public key
3)
      -  if we have no public key in contacts for the primary email, show `Save Contact Pubkey`
      -  if we have public public key in contacts for the primary email, and it has the same `longid`, show `Update Contact Pubkey`
      -  if we have public public key in contacts for the primary email, and it has different `longid`, show `Replace Contact Pubkey`

Either way, once I click the button, the new public key will be in contacts for that email.

Public key can sligtly differ even if it has the same longid. For example, I may have a key that expires in 2020. In 2019 I may decide to extend expiration until 2021. The resulting key will have the same longid, but it's worthwhile to update it, because you cannot normally encrypt for expired keys.

**Comment by tomholub** [comment]
I just updated the comment above, so please don't look at email, check the text here :)

**Comment by DenBond7** [comment]
> The resulting key will have the same longid, but it's worthwhile to update it, because you cannot normally encrypt for expired keys.

Thanks a lot for this explanation. I didn't know about that.
