### ISSUE TITLE
cannot add second email account

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#459]
1) add flowcrypt.compatibility email during initial setup
2) click add account
3) click continue with gmail
4) click on one of the available emails that I was already logged into
5) screen goes darker, then after 1 second back to normal and I'm back looking at "Continue with Gmail" button

**Comment by tomholub** [comment]
Tried again and ended up with this symptom: #292

**Comment by DenBond7** [comment]
deprecated
