### ISSUE TITLE
option to attach public key when sending message

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#479]
frequently requested, definitely needed

**Comment by tomholub** [comment]
On compose screen, the three dots icon, one of the items there should be "Include Public Key". When selected, a checkmark will show next to it. When not, no checkmark.

**Comment by tomholub** [comment]
Otherwise check what browser extension does.

Very important that the sent attachment has mime type `application/pgp-keys`

**Comment by DenBond7** [comment]
@tomholub I added such an option. But with some changes. Because a user can have a few imported keys. We can discuss that

**Comment by tomholub** [comment]
Could you show a screenshot of what happens when more than one key is available?

**Comment by DenBond7** [comment]
@tomholub 
I've sent you a video for better understanding (keybase)
Here's a screenshot

![image](https://user-images.githubusercontent.com/2863246/65224950-e2841000-dacc-11e9-861e-70a0105a18d0.png)

**Comment by tomholub** [comment]
Thank you, a few updates:
 - please filter the keys in a similar (same?) way that you filter them when choosing "send-from" public key
 - if there is only one pubkey option after filtering, don't show choice confirmation
 - please turn checkboxes into radio buttons (can choose only one)
 - pre-select the first choice

**Comment by DenBond7** [comment]
Need to add tests for cases

1. A user has 1 key

1. The user has a few keys

1. The user doesn't have any keys
