### ISSUE TITLE
cannot load pubkey of a specific email

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#484]
When I enter `datan.domonkos@gmail.com` in public key search (or as recipient) it doesn't find pubkey. But we actually have one: https://flowcrypt.com/pub/datan.domonkos@gmail.com

**Comment by DenBond7** [comment]
Duplicate of #473

**Comment by DenBond7** [comment]
#473 and #484 have the same problem

**Comment by tomholub** [comment]
Got it
