### ISSUE TITLE
parseDecryptMsg: Content-Type: text/html

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#485]
If a  message has `Content-Type: multipart/alternative` we parse only `Content-Type: text/plain` and skip `Content-Type: text/html`. In that case, I can't display an HTML message as is. I can show only a simple text.

**Comment by tomholub** [comment]
Relevant code
```js
  public static process = async (mimeMsg: Uint8Array) => {
    const decoded = await Mime.decode(mimeMsg);
    const blocks: MsgBlock[] = [];
    if (decoded.text) {
      blocks.push(...Pgp.armor.detectBlocks(decoded.text).blocks);
    } else if (decoded.html) {
      blocks.push(Pgp.internal.msgBlockObj('plainHtml', decoded.html));
    }
    // ...
  }
```
Easy to change, but need to thoroughly evaluate effect on browser extension.

**Comment by tomholub** [comment]
superseded by #976
