### ISSUE TITLE
Node.js decryption performance

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#487]
I've tested the decryption process using J2V8 and Node.js realizations (the same message). What I see:

- J2V8 - around 3600 ms
- Node.js - around 5800 ms

I think need to debug the decryption process on Node.js. Maybe we can improve some steps.

**Comment by tomholub** [comment]
Same keys? I will also add time debugging in node to compare numbers.

**Comment by DenBond7** [comment]
> Same keys?

Yes. I've installed version 0.7.0 and tested. Then I've installed 0.7.4 and tested. The same keys and the same message.

> I will also add time debugging in node to compare numbers.

It'll be great and helpful

**Comment by tomholub** [comment]
Added a way to profile times

**Comment by tomholub** [comment]
Are we still on the 32bit version? I'm really hoping the 64bit one will bring improvements.

**Comment by DenBond7** [comment]
@tomholub
> Are we still on the 32bit version?

Yes, we are still on the 32bit version. Unfortunately, we can't use the 64bit version of Node.js while we are using J2V8.

**Comment by tomholub** [comment]
That's why hopefully we can remove j2v8 very soon :)

**Comment by DenBond7** [comment]
#410

**Comment by DenBond7** [comment]
@tomholub 

>I'm really hoping the 64bit one will bring improvements.

I've tested it. After I've disabled J2V8 and enabled the 64bit version of Node.js the app works better.

- the 32bit version of Node.js  - `parseDecryptMsg` takes 4644ms
- the 64bit version of Node.js  - `parseDecryptMsg` takes 3062ms

**Comment by tomholub** [comment]
That sounds better. Are these 4096 bit keys? 2048 should be much faster.

**Comment by DenBond7** [comment]
@tomholub 
> Are these 4096 bit keys?

It's my own private key, which was created in 2017 when I setup FlowCrypt

"algo":{  
            "algorithm":"rsa_encrypt_sign",
            "bits":4096,
            "algorithmId":1
         },

**Comment by tomholub** [comment]
Correct. Keys created on android are 2048 bit. Actually I will be changing default on desktop to 2048 bit too, for mobile performance.

**Comment by DenBond7** [comment]
> 2048 should be much faster.

On my emulator, the decryption takes only (283ms). It's super fast :) Usually, emulator works 3-4 times faster than a real device

**Comment by tomholub** [comment]
I would consider 3062ms for a 4096bit key to be an improvement :) We can probably close this issue (for now) unless you have some optimizations in mind.

**Comment by DenBond7** [comment]
#410
