### ISSUE TITLE
use node generateKey

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#488]
`generateKey`
`{ variant: 'rsa2048', passphrase: 'riruekfhydekdmdbsyd', userIds: [{ email: 'a@b.com', name: 'Him' }] }`
Response same as `parseKey`
```js
{
        "public": "-----BEGIN ...",
        "private": "-----BEGIN ...",
        "isDecrypted": false,
        "users": ['Him <a@b.com>']
        "ids": [
          { "fingerprint": "E76853E128A0D376CAE47C143A30F4CC0A9A8F10", "longid": "3A30F4CC0A9A8F10", "shortid": "0A9A8F10", "keywords": "DEMAND MARBLE CREDIT BENEFIT POTTERY CAPITAL" },
          { "fingerprint": "9EF2F8F36A841C0D5FAB8B0F0BAB9C018B265D22", "longid": "0BAB9C018B265D22", "shortid": "8B265D22", "keywords": "ARM FRIEND ABOUT BIND GRAPE CATTLE" }
        ],
        "algo": {
          "algorithm": "rsa_encrypt_sign",
          "bits": 2048,
          "algorithmId": 1
        },
        "created": 1543592161
}
```

**Comment by tomholub** [comment]
Key will already be encrypted with the pass phrase, so there are no other steps needed when creating a key.

**Comment by DenBond7** [comment]
@tomholub Could you wrap the response using `key` tag?

It'll be great if the response will look like

```
{
   "key":{
      "public":"-----BEGIN ...",
      "private":"-----BEGIN ...",
      "isDecrypted":false,
      "users":[
         "Him <a@b.com>"
      ],
      "ids":[
         {
            "fingerprint":"E76853E128A0D376CAE47C143A30F4CC0A9A8F10",
            "longid":"3A30F4CC0A9A8F10",
            "shortid":"0A9A8F10",
            "keywords":"DEMAND MARBLE CREDIT BENEFIT POTTERY CAPITAL"
         },
         {
            "fingerprint":"9EF2F8F36A841C0D5FAB8B0F0BAB9C018B265D22",
            "longid":"0BAB9C018B265D22",
            "shortid":"8B265D22",
            "keywords":"ARM FRIEND ABOUT BIND GRAPE CATTLE"
         }
      ],
      "algo":{
         "algorithm":"rsa_encrypt_sign",
         "bits":2048,
         "algorithmId":1
      },
      "created":1543592161
   }
}
```
Then I'll have a much simpler logic and code.

**Comment by tomholub** [comment]
Ok

**Comment by DenBond7** [comment]
@tomholub 
On my emulator:
`Key creating:      20152 ms, Node.js`
`Key creating:      5532 ms, J2V8`

I hope when we will start to use the 64bit version it'll be faster.

**Comment by tomholub** [comment]
That looks horrible.

**Comment by tomholub** [comment]
I think I should be able to optimize that one day. Normally, code in Node will use cryptographic APIs that are basically C++, but this looks like it's doing too much work in JavaScript instead of using the node crypto apis (maybe?). Which could potentially be fixed.

Worst case, we will one day create keys using BouncyCastle.

**Comment by tomholub** [comment]
> Could you wrap the response using key tag?
done

**Comment by DenBond7** [comment]
Thank a lot!

**Comment by DenBond7** [comment]
@tomholub 
My results (MI A1):

Key creating:      70530 ms, Node.js (the 64bit version)
Key creating:      146139 ms, Node.js (the 32bit version)
Key creating:      98917 ms, J2V8

**Comment by tomholub** [comment]
So that's from 98 seconds to 146 seconds on the 32bit phone? Am I reading this correctly?

**Comment by DenBond7** [comment]
@tomholub 
> So that's from 98 seconds to 146 seconds on the 32bit phone?

Correct

**Comment by tomholub** [comment]
Ok we have to do something about that later, that's ridiculous. Not on this version.

**Comment by DenBond7** [comment]
I agree. I'll create a separate issue for that
