### ISSUE TITLE
Caching message details when load new messages

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#49]
We need to add a logic of caching message details if the message not big. The Gmail on Android not loads message details everytime when we open the new screen with the message. And I think Gmail cached message details when we load new messages. 

This requires a detailed study.

For me 
https://community.oracle.com/thread/2354385

**Comment by tomholub** [comment]
Yes, eventually we'll have to do this. I would say this would be good to add after we release the app, as it's more of an optimization.

We will probably need to also load all message headers in background and store it in DB in order to be able to show messages as conversations (like Gmail does).

**Comment by DenBond7** [comment]
I was thinking about this issue. This task needs some requirements.

We need to have auto-update of the current folder. Currently, we always load new messages when we are doing a switch between the folders. I already have a code which can save and restore messages after the switching. But while the application does not automatically receive updates from the server for the current folder - there is no sense in my code, as the user will have to manually receive the letters.

I think will be better move this task to the next milestone, where I'll do a more user-friendly sync.

**Comment by tomholub** [comment]
ok

**Comment by tomholub** [comment]
Sounds good

**Comment by DenBond7** [comment]
deprecated
