### ISSUE TITLE
remove J2V8

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#490]
I've added `zxcvbnStrengthBar` endpoint, which I the last missing endpoint I know about. In this issue we will track all tasks that need to be done so that we can get rid of J2V8.

You can see the request and response structure from the relevant test:
https://github.com/FlowCrypt/flowcrypt-android-node/commit/cc1a0488193c942eb69af523dfd930c664b9827b#diff-a76389e798d223b87e7ef062b44fe1e0R258

**Comment by DenBond7** [comment]
For `zxcvbnStrengthBar` we have

```
{  
   "word":{  
      "match":"day",
      "word":"poor",
      "bar":20,
      "color":"darkred",
      "pass":false
   },
   "seconds":1111829,
   "time":"13 days"
}
```

@tomholub 
Could we rename `time`(or maybe move it)? I already have such a tag in a base response.
https://github.com/FlowCrypt/flowcrypt-android/blob/17203ea51fcc3b387970b386471c0359ba7079ec/FlowCrypt/src/main/java/com/flowcrypt/email/api/retrofit/response/node/BaseNodeResult.java#L43

**Comment by tomholub** [comment]
I would have to rename it throughout my codebase too (I don't want it named differently on Android compared to elsewhere, to keep things consistent across platforms).. so it's about the same amount of work on both ends, I think. 

You could call the base type `executionTime` or `requestSentTime` etc depending on what it means.

**Comment by DenBond7** [comment]
> You could call the base type executionTime or requestSentTime etc depending on what it means.

Sorry, I've made a mistake. `BaseNodeResult` doesn't have `time` as a JSON tag. It's my custom field. So nevermind, I can easily change it on my side.

**Comment by DenBond7** [comment]
> executionTime

Excellent. I'll choose it.

**Comment by DenBond7** [comment]
@tomholub 
About supported colors

Android supports : #RRGGBB #AARRGGBB or one of the following names: 'red', 'blue', 'green', 'black', 'white', 'gray', 'cyan', 'magenta', 'yellow', 'lightgray', 'darkgray', 'grey', 'lightgrey', 'darkgrey', 'aqua', 'fuchsia', 'lime', 'maroon', 'navy', 'olive', 'purple', 'silver', 'teal'.

`orange` - Android doesn't support it as is.

**Comment by tomholub** [comment]
You can substitute orange with `#FFA500`.

Later it could be fixed to emit rgb format instead, you could make issue for that too.

**Comment by tomholub** [comment]
finally!

**Comment by DenBond7** [comment]
:)

**Comment by DenBond7** [comment]
I'm happy too :)
