### ISSUE TITLE
Disable Node.js logs in prod builds

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#498]
I've found `03-11 22:46:26.072 I/System.out( 7466): NODEJS-NATIVE-MSG[listening on 38975 APP_ENV:prod]` in a prod app. It'll be better to disable logs for the prod builds.

**Comment by tomholub** [comment]
There are three things:
1) native direct messages
2) stdout from node
3) stderr from node

**Comment by DenBond7** [comment]
@tomholub I've disabled native direct messages for the prod builds. I think it's enough for now. We can close it.
