### ISSUE TITLE
0.7.5 ready

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#508]
We could make 0.7.5 just a bugfix release and target maybe one week release cycle (is it realistic?)

**Comment by DenBond7** [comment]
> We could make 0.7.5 just a bugfix release

I think it'll be as you wrote. Because I've already added some issues with bugs. 

> target maybe one week release cycle (is it realistic?)

I think yes. But in that case we need to select only that issues which I can fix during that time. Sometimes I have issues with a difficult problem which needs long time for fixing(include testing :( ). 

So the short answer - in most cases we can do one week release cycle.

**Comment by tomholub** [comment]
I meant for this upcoming release. The releases after that could take longer or as needed - we'll see. Ideal release cycle would be about two weeks, but it's flexible.

**Comment by DenBond7** [comment]
- [ ] check code style
- [ ] check tests

**Comment by DenBond7** [comment]
![Screenshot from 2019-04-19 18-23-04](https://user-images.githubusercontent.com/2863246/56430841-57f67500-62d0-11e9-929e-d70d3681a6e9.png)

**Comment by tomholub** [comment]
I'll test & release

**Comment by tomholub** [comment]
@DenBond7 
```

> Task :FlowCrypt:lintVitalProdRelease
/home/luke/git/flowcrypt-android/FlowCrypt/src/main/res/layout/fragment_private_keys.xml:59: Error: listViewKeys is not a sibling in the same ConstraintLayout [NotSibling]
        app:constraint_referenced_ids="listViewKeys,floatActionButtonAddKey" />
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

   Explanation for issues of type "NotSibling":
   Layout constraints in a given ConstraintLayout or RelativeLayout should
   reference other views within the same relative layout (but not itself!)

1 errors, 0 warnings

> Task :FlowCrypt:lintVitalProdRelease FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':FlowCrypt:lintVitalProdRelease'.
> Lint found fatal errors while assembling a release target.
  
  To proceed, either fix the issues identified by lint, or modify your build script as follows:
  ...
  android {
      lintOptions {
          checkReleaseBuilds false
          // Or, if you prefer, you can continue to check for errors in release builds,
          // but continue the build even when errors are found:
          abortOnError false
      }
  }
  ...

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.1.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 35s
24 actionable tasks: 22 executed, 2 up-to-date

```

**Comment by DenBond7** [comment]
@tomholub I've fixed warnings. Please pull changes and try to build. If you see `Expiring Daemon because JVM Tenured space is exhausted` in logs, you have to increase the heap size for Gradle to make a successful build. I don't why but after update to Gradle 5.1.1, the last doesn't use settings from Android studio for the heap size.

**Comment by DenBond7** [comment]
> you have to increase the heap size for Gradle to make a successful build

If you already have installed gradle on your PC, you can use the following steps

1. Go to the home directory

1. open directory `.gradle`

1. create or open file `gradle.properties`

1. add `org.gradle.jvmargs=-Xmx1536m` where 1536m - it's a size of heap which you can share for Gradle. I think `-Xmx2g` will be enaught

or you can open `gradle.properties` in the flowcrypt project and add `org.gradle.jvmargs=-Xmx1536m` there
