### ISSUE TITLE
google client id setting

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#51]
I could not find our oAuth client id anywhere in the code. How/where is this handled?

I've tried to make a release build, but the auth doesn't work, probably because it needs a new client id for production, but not sure where to put it.

**Comment by DenBond7** [comment]
> I could not find our oAuth client id anywhere in the code. How/where is this handled?

I don't use it. The client id not needed for our purpose. In Android, we just need right configuration in Google API Console. For now, you just added the combination of SHA1 and the app package for debug builds. If you want to create the release build, you must create a release key for signing the app and then will add a new combination of SHA1 and the app package (com.flowcrypt.email). After then the sign in function must be work fine.

The algorithm is the following:

1. Create the release key
2. Retrieve the SHA1 for current release key.
3. Add a new combination of SHA1 and the app package (com.flowcrypt.email) in the Google API Console.
4. In FlowCrypt/build.gradle modify the release sign options
5. Prepare a release build via command **"gradlew assembleRelease"**

# **Warning: Don't add release sign credentials to the repository**

I must be done the issue #52 before you can generate and use release builds.

**Comment by tomholub** [comment]
got it, let's do that
