### ISSUE TITLE
password-protected symmetrical encryption message

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#517]
Should create UI similar to browser:

![image](https://user-images.githubusercontent.com/6306961/55821246-8e700b00-5aec-11e9-9176-9058f3415745.png)

**Comment by seisvelas** [comment]
ref: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgxwKjdwVWtDGwpcmCnKnSQpmrjfp

User considering premium is curious if we're planning on implementing this, I said yes but we don't have a solid date for when it will happen

**Comment by tomholub** [comment]
To be honest I'm not entirely sure we'll be adding this functionality to Android - either way likely not before end of 2021.

**Comment by DenBond7** [comment]
I'm reviewing issues @tomholub is it still relevant?
