### ISSUE TITLE
enigmail html message showing empty

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#518]
![image](https://user-images.githubusercontent.com/6306961/55821379-e60e7680-5aec-11e9-972c-e992a5735c3c.png)

**Comment by tomholub** [comment]
one more

![image](https://user-images.githubusercontent.com/6306961/55821804-d4799e80-5aed-11e9-824c-a8530baf43f7.png)

**Comment by tomholub** [comment]
One more

![image](https://user-images.githubusercontent.com/6306961/55821937-1efb1b00-5aee-11e9-9794-86811441d2ae.png)

**Comment by tomholub** [comment]
Plus this one

![image](https://user-images.githubusercontent.com/6306961/55822045-4f42b980-5aee-11e9-9e92-544aea9c3799.png)

**Comment by tomholub** [comment]
Same thing emails from Facebook

**Comment by tomholub** [comment]
![image](https://user-images.githubusercontent.com/6306961/55822998-536fd680-5af0-11e9-8d67-cebc977c5394.png)

**Comment by DenBond7** [comment]
@tomholub I see all of these messages have an interesting structure. There is multipart/encrypted content. Chrome understands it as attachments.

As I understand the Android app will able to show such messages after you'll add support of `enigmail` to 
`flowcrypt-android.js`

**Comment by tomholub** [comment]
@DenBond7 The support should be there, I thought. What are you getting back from node?

**Comment by tomholub** [comment]
If you could give me one mime message input and what output are you getting, that would help.

**Comment by DenBond7** [comment]
@tomholub 
>The support should be there, I think. What are you getting back from node?

It's the whole response:
```
2019-04-17 16:27:28.071 5073-7090/com.flowcrypt.email.debug D/OkHttp: Date: Wed, 17 Apr 2019 13:27:28 GMT
2019-04-17 16:27:28.071 5073-7090/com.flowcrypt.email.debug D/OkHttp: Connection: keep-alive
2019-04-17 16:27:28.071 5073-7090/com.flowcrypt.email.debug D/OkHttp: Content-Length: 3
2019-04-17 16:27:28.072 5073-7090/com.flowcrypt.email.debug D/OkHttp: {}
2019-04-17 16:27:28.072 5073-7090/com.flowcrypt.email.debug D/OkHttp: <-- END HTTP (3-byte body)
```

The response is empty (no blocks)

**Comment by tomholub** [comment]
may be solved with #528

**Comment by tomholub** [comment]
Nope, this is an issue of its own

**Comment by tomholub** [comment]
@DenBond7 The problem is that Node only receives the first 200kb message. That works for some messages, but not for all. Especially `pgp/mime` messages that are a bit longer (eg contain an attachment) will not work.

I think we should stop using the 200kb method, and just download the whole message every time. For that, it would be good to have a % indication on the bottom, similar to loading inbox.
