### ISSUE TITLE
encrypted message treated as plain - not decrypted

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#519]
There are a few cases like this. Android doesn't know that message is encrypted, so it seems it will not even try to decrypt it. 

![image](https://user-images.githubusercontent.com/6306961/55822582-73eb6100-5aef-11e9-8e85-3bd63cffa76a.png)

**Comment by tomholub** [comment]
I would consider pulling all messages through node `parseDecryptMsg`. It should be fast if there is no decrypting. What do you think? Then we don't have to duplicate the logic of recognizing each encrypted message format.

**Comment by tomholub** [comment]
Plus this would simplify the rendering logic because everything would be just `MsgBlock`

**Comment by DenBond7** [comment]
@tomholub 
> I would consider pulling all messages through node parseDecryptMsg.

To simplify a logic I already do that.

 > It should be fast if there is no decrypting.

Yes, it's fast

**Comment by tomholub** [comment]
Good to hear. Can you check why is this message not recognized as encrypted? Is it the 200kb limit?

**Comment by DenBond7** [comment]
> Is it the 200kb limit?

No, it's not. Here all is ok. I receive parsed blocks. Need to fix an issue in my code.

**Comment by tomholub** [comment]
may be solved with #528

**Comment by tomholub** [comment]
this is now fixed, likely thanks to #528
