### ISSUE TITLE
Prepare the project to generate release builds.

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#52]
Need to prepare the project to generate release builds.

1. Configure the FlowCrypt/build.gradle
2. Configure the FlowCrypt/proguard-rules.pro

**Comment by tomholub** [comment]
Already have a production key, I'll set it up on google developer console.

Also, I'll be transferring the debug oauth credential in developer console to another account, which means it may not work for a while.

**Comment by tomholub** [comment]
@DenBond7 here https://github.com/FlowCrypt/flowcrypt-android/tree/master/release

**Comment by DenBond7** [comment]
https://stackoverflow.com/questions/34450215/use-proguard-only-to-disable-logging-and-for-shrinking-resources

**Comment by tomholub** [comment]
I commented `keepresourcexmlelements manifest/application/meta-data@value=GlideModule` as it would not work with ProGuard (only MaxGuard)

Otherwise looks like a good build, will send it to some folks who are waiting to test!
