### ISSUE TITLE
show contacts public key details

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#522]
When we click a pubkey in emails, it should show pubkey details.

This will help me debug an issue with users like this:

```
I install the pub/sec key for both accounts.
From my Gmail account, I send an encrypted email to my GMX.US account.
This is the key ID that is correct:
 0x...5047 (...)
But when it arrives, it is encrypted to an unknown key:
 0x...62B4
This key doesn't match any keys I have installed.
I cleared cache, deleted data, restarted Flowcrypt.
Imported my Gmail sec/pub keys.
Imported only the pub keys for the GMX.US account and it will
send/encrypt correctly.
If I remove the GMX.US account(resetting all data again) after
installing GMX.US sec/pub keys, Flowcrypt tells me that I must update
the contact and refuses to send.

Having found this, it may be by design on your end and isn't major.
Just not what I'm used to in other clients and is easy to work around
I think. I experiment more with it.
```

My response:

> Looks like it's encrypting for a key that you don't know. That should notbe happening. I've noted down to let you know when we have tools in the appto debug this better.

**Comment by tomholub** [comment]
Show the following details:

```
 <- Contact (Public Key)   ⎘  💾  🗑 
____________________________________

User 1: Some Name <aaa@gmail.com>
User 2: Other Name <bbbb@gmail.com>

LongID 1: AAFA444466667777
WORD WORD WORD WORD WORD WORD
LongID 2: CCFA444466667788
WORD WORD WORD WORD WORD WORD

Algorithm: RSA 4096 bit
Created: 2019-01-01
```

The KeyWords (six words) should be in smaller font and gray color.

Icons:
 - copy: means Copy to Clipboard. When you click it, user should see toast `Public Key copied to clipboard`
 - save: means save as a file (save armored text, with name `0xAAAABBBBCCCCDDDD-someemailgmailcom-publickey.asc`)
 - delete: same as the delete icons in the pubkey list

**Comment by DenBond7** [comment]
- [ ] Test saving a key when no permissions granted

**Comment by DenBond7** [comment]
@tomholub 
Is it look well? And what about Algorithm? I receive only info like `rsa_encrypt_sign`

![image](https://user-images.githubusercontent.com/2863246/65537986-07361880-df0f-11e9-967e-fd895ff31e61.png)

![image](https://user-images.githubusercontent.com/2863246/65538147-63993800-df0f-11e9-9aa1-81bb3958d78e.png)

branch `issue_522_pubkey_details`

**Comment by tomholub** [comment]
This is good as is

**Comment by tomholub** [comment]
Maybe the floppy disc icon could be a tiny bit bigger to match the size of the other icons. It looks smaller

**Comment by tomholub** [comment]
Thanks for getting this done, it will be very useful for debugging and fixing problems of users
