### ISSUE TITLE
Download button feedback

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#523]

**Comment by DenBond7** [comment]
@tomholub Maybe it isn't relevant today. Do you have any details?

**Comment by tomholub** [comment]
I think this has to do with downloading attachments - often it's not obvious that's it's actually downloading, because it's only showing in notifications, but the app UI does not show any change while files are downloading.

**Comment by tomholub** [comment]
To consider in case it can be improved

**Comment by DenBond7** [comment]
- [ ] try work manager
- [ ] cancel all downloads after switching to another account
- [ ] delete a temp file after cancel downloading
