### ISSUE TITLE
convert codebase to Kotlin

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#529]
It does not have to cover 100% yet. But maybe 50-75% of the easier parts.

**Comment by tomholub** [comment]
It does not have to be idiomatic Kotlin yet, basically Java-looking auto-converted Kotlin is ok.

After that we can start to slowly clean it up to look more like real Kotlin.

**Comment by tomholub** [comment]
About what percentage of the app has been converted so far?

**Comment by DenBond7** [comment]
@tomholub 
> About what percentage of the app has been converted so far?

Today I'll complete with `com.flowcrypt.email.database` package. And then I need to convert only `com.flowcrypt.email.ui` (around 100 files - the most difficult part). So I think today we will have around 75%

**Comment by tomholub** [comment]
Got it, thanks!

**Comment by DenBond7** [comment]
@tomholub It's completed
