### ISSUE TITLE
404 error when setting up

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#536]
Users started experiencing this error right after the latest update.

It happens after clicking connect to gmail. Several users reported this, on different devices:
 - LG V30 64g 
- Samsung Galaxy Tab A
- Samsung Galaxy S9 on Android 9 with latest updates but a German language setting
- tab s4

> Does anything show up after clicking the Gmail button, or straight 404? If something shows up first, could you describe the point at which it shows 404?

> There is a loading screen that lasts for a few seconds, then it goes to 404. This is stock android.

------------------
![image](https://user-images.githubusercontent.com/6306961/56674987-97470c00-66aa-11e9-918b-a24e85a4b2c3.png)
------------------

**Comment by tomholub** [comment]
Affected users:
https://mail.google.com/mail/u/1/#search/404/FMfcgxwCgLqGrkXNBfNrxNgBRkQjVzdG
https://mail.google.com/mail/u/1/#search/404/FMfcgxwCgLthxVmvHNxxTHjxzHBRzQCS
https://mail.google.com/mail/u/1/#search/404/FMfcgxwCgLthpDnPVrXZsRBTSzdPHjNq
https://mail.google.com/mail/u/1/#search/404/FMfcgxwCgLsZXxQlwfrFBbDVvZWcdwpk

**Comment by DenBond7** [comment]
`com.google.api.client.googleapis.json.GoogleJsonResponseException: 404 Not Found`
ref https://mail.google.com/mail/u/0/#search/%22404+Not+Found%22

Currently, I have no ideas what it can be. Need to investigate this question

**Comment by tomholub** [comment]
Do you know which API call produces it?

**Comment by tomholub** [comment]
I can reproduce it on both of my phones, actually.

1) delete storage
2) open app
3) continue with Gmail
4) choose my account
5) click approve
6) 404

Now every time I click "continue with Gmail" I get a 404 right away.

**Comment by DenBond7** [comment]
@tomholub 
> Do you know which API call produces it?

This line throws such errors

https://github.com/FlowCrypt/flowcrypt-android/blob/b406e23277d8ed6a503a9b0c84d0378165797761/FlowCrypt/src/main/java/com/flowcrypt/email/api/email/EmailUtil.java#L328

> Now every time I click "continue with Gmail" I get a 404 right away.

I already can reproduce it too. But only on a production build.

**Comment by DenBond7** [comment]
https://stackoverflow.com/questions/38768111/gmail-api-not-working-properly-when-minifyenabled-true

**Comment by tomholub** [comment]
Just a note, we don't really benefit from minification (other than apk size). So it may be interesting to see apk size difference when minification is disabled. If it's negligible, we could turn it off completely.

**Comment by DenBond7** [comment]
**R8 enabled**

- size = 40Mb
- Only one dex file - faster loading 
- dalvik code is optimized (https://android-developers.googleblog.com/2018/11/r8-new-code-shrinker-from-google-is.html)
- No logs in logcat - It's better for security

**R8 disabled**

- size = 43Mb
- mutlidex is available
- dalvik code is not optimized 
- Logs are available in logcat for release builds

**Comment by DenBond7** [comment]
@tomholub I was wrong. Here a real situation:

![Screenshot from 2019-04-26 10-54-49](https://user-images.githubusercontent.com/2863246/56792535-82858800-6812-11e9-92cf-c5dea4891553.png)

Using R8 we can save around 8 Mb (unused classes from libraries and etc.)

**Comment by tomholub** [comment]
Understood

**Comment by DenBond7** [comment]
One more interesting article https://medium.com/androiddevelopers/troubleshooting-proguard-issues-on-android-bce9de4f8a74

**Comment by DenBond7** [comment]
It's not relevant after #540. I'm closing it.
