### ISSUE TITLE
delete deprecated api classes

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#538]
/home/luke/git/flowcrypt-android/FlowCrypt/src/main/java/com/flowcrypt/email/api/retrofit/request/attester/

- [x] InitialConfirmRequest
- [x] InitialRequest
- [x] ReplaceConfirmRequest
- [x] ReplaceRequest
- [x] same in `ApiName` class

-----------
- [x] rename `api.cryptup.io` to `flowcrypt.com/api` in `ApiName`
- [x] Use `flowcrypt.com/attester` instead of `attester.flowcrypt.com` (same api)
- [x] `InitialConfirmResponse` and all the other relevant responses
- [x] Start ignoring `attested` field in `InitialLegacySubmitResponse`. I want to remove that field from the API response, but I have to wait until Android app stops using it.
- [x] Stop sending `attest` field when sending request to `initial/legacy_submit`. We were setting it to `false` by default, leave it out instead, and remove all code related to that field.
- [x] Remove `attested` from `LookUpEmailResponse`, I want to stop returning it from the API.

**Comment by tomholub** [comment]
rename `api.cryptup.io` to `flowcrypt.com/api` in `ApiName`
Use `flowcrypt.com/attester` instead of `attester.flowcrypt.com` (same api)

**Comment by tomholub** [comment]
`InitialConfirmResponse` and all the other relevant responses

**Comment by tomholub** [comment]
Start ignoring `attested` field in `InitialLegacySubmitResponse`. I want to remove that field from the API response, but I have to wait until Android app stops using it.

**Comment by tomholub** [comment]
Stop sending `attest` field when sending request to `initial_legacy_sugmit`. We were setting it to `false` by default, leave it out instead, and remove all code related to that field.

**Comment by tomholub** [comment]
- [ ] Remove `attested` from `LookUpEmailResponse`, I want to stop returning it from the API.

**Comment by DenBond7** [comment]
@tomholub 
> Remove attested from LookUpEmailResponse, I want to stop returning it from the API.

Does it mean we don't need the `attested` field in `PgpContact`? Should I remove it too? As I can see we don't use that field in code.

**Comment by tomholub** [comment]
Correct, please remove that too from `PgpContact`.
