### ISSUE TITLE
splash screen: make links clickable

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#54]
the "Privacy, Terms, Security" buttons on top should lead to the same pages as in #25 

For Security, please create a new sample file, `security.htm` just like the other ones, so that I can fill it out later.

**Comment by DenBond7** [comment]
Already done via https://github.com/FlowCrypt/flowcrypt-android/commit/68526ef4f76a7b5703584dd5ff9017930328df9e
