### ISSUE TITLE
Resolve a situation with import decrypted keys

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#548]
We have to think about a situation when a user is trying to import decrypted keys. Currently, we don't allow the import of such keys (We show a hint with _"Error. The key is decrypted!"_).

**Comment by DenBond7** [comment]
https://mail.google.com/mail/u/0/#search/%22error.+the+key+is+decrypted!%22

**Comment by tomholub** [comment]
For now we can leave it as is. We can also allow it to keep sending us reports about it. Later we will be forcing user to create a pass phrase for it during setup.

**Comment by tomholub** [comment]
But it's a good thing to think about, I had to also fix this particular scenario in the web extension before.

**Comment by DenBond7** [comment]
ref https://mail.google.com/mail/u/0/#search/%22Pass+phrase+length+seems+way+too+low!%22

**Comment by DenBond7** [comment]
Fixed by #1233
