### ISSUE TITLE
message details: attachments

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#55]
we'll need a way to work with attachments that we receive

This will involve some sort of imap message structure call (you probably already know) and then downloading messages individually based on what user clicks.

For now, don't worry about recognizing encrypted messages from plain ones. Just the ability to show a list of attachments of an email (on the very bottom of the screen), their name, size, and a standard Android download icon.

**Comment by tomholub** [comment]
If the attachment structure call is fast and doesn't slow down loading the message, you can bundle it with the body content call.

If loading info about attachments takes a long time, only load it after the body was already displayed. Eg load and show the body first, then show spinner "Loading attachments" under the message and do the structure call.

**Comment by DenBond7** [comment]
I already work on this issue. I can retrieve a message and the body structure per one transaction. It's will be fast

**Comment by DenBond7** [comment]
Can I decrypt an attachment via Js tools?

**Comment by tomholub** [comment]
We will do decrypting in another version, I need to prepare something for
you first.

On Aug 9, 2017 4:27 AM, "Den" <notifications@github.com> wrote:

Can I decrypt an attachment via Js tools?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/FlowCrypt/flowcrypt-android/issues/55#issuecomment-321216846>,
or mute the thread

**Comment by tomholub** [comment]
I think we can close this if we either hide the download button or make it just show error after clicking.

**Comment by DenBond7** [comment]
Ok, I will hide the download icon and disable a clickable effect on the attachment button.
