### ISSUE TITLE
select and manipulate more than one email

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#552]
user
> one more thing :-) if you can add long press to select emails to delete instead going inside each email ... thanx a lot 

In gmail you can tap the person's face, which we don't have.

Another way to do that is the long-press. We could consider adding support for that.. one day.

**Comment by tomholub** [comment]
which should allow for bulk archive, delete, mark read

**Comment by DenBond7** [comment]
@tomholub This functionality was added in https://github.com/FlowCrypt/flowcrypt-android/commit/09e383565c7cd3c5b8c3b9121a3f56414fe5a222. I'm closing this issue
