### ISSUE TITLE
importing key during setup (user feedback)

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#56]
I had a few people try it out and they were struggling when trying to import their keys. Here are some improvements to make it easier for them.

1) When I click "Import my key", I should see another screen (similar design). The title will be "Import Private Key" (instead of Set up FlowCrypt) and the two green buttons will be: "Load from a file" and "Load from clipboard". 

2) When I click on "Load from clipboard", it should examine the clipboard (let me know if this is possible) and do one of the following: 
  - show a notification "Your clipboard is empty. Please find your private key where you are storing it, select the text and copy it. After that, return back to FlowCrypt."
  - show a notification "The content of your clipboard does not look like a valid PGP Private Key. Please make sure to copy the whole contents of the armored private key." (if there is something in the clipboard)
  - (if valid) switch to pass phrase screen

3) When importing a key from a file, it should allow to use `.key`, `.asc`, `.ascii`, `.pgp`, `.gpg`, `.txt` or `.prv` files.

4) pass phrase screen text and buttons should be dependent on the context (method of setting up). Let's rename it as follows based on the situation:
- text: "Found a backup of your account key", buttons: "Continue" and "Use another account" (gray)
- text: "Private Key: [key_file_name.asc]", buttons: "Continue", "Choose another key" (gray)
- text: "Loaded a private from your clipboard", buttons: "Continue", "Choose another key" (gray)

5) Back button on pass phrase screen should take me to previous screen. Right now it closes the app. "Choose another key" should also do the same thing as the back button.

6) (optional bonus): We should examine the clipboard every time the user is coming back to the app (if the app was in the background), as long as email auth is already done but key is not yet set up. If the clipboard contains a valid key, show "Loaded a private from your clipboard" screen. If the clipboard does not contain a valid key, ignore the clipboard and stay on whatever screen the user was originally expecting.

**Comment by DenBond7** [comment]
> When importing a key from a file, it should allow to use .key, .asc, .ascii, .pgp, .gpg, .txt or .prv files.

I can't do this. [Android doesn't have an easy way to do this.](https://stackoverflow.com/questions/14626433/android-browse-file-intent-with-defined-extension)

I can only show all files or files for which I know the mime types. For example, CryptUp creates a private key with mime type `"application/pgp-keys". And FlowCrypt does a backup with such mime type. That way we can show this files when we can try to import the private keys. 

But we can not know all combinations of mime types of other applications. 

My variant of a solution to this problem: I can display all files and do a check of extensions after files were selected. If a selected file has a wrong extension I can show an error.

**Comment by tomholub** [comment]
Ah, got it. Show all then. Other software often saves their keys in a variety of other MIME types (text/plain and others).

No need to do an extension check. Instead, check that it's under 1MB (reject bigger files), and check the contents of it to make sure it contains a private key.

**Comment by DenBond7** [comment]
> show a notification "The content of your clipboard does not look like a valid PGP Private Key. Please make sure to copy the whole contents of the armored private key." (if there is something in the clipboard)

How can I do validation of PGP Private Key? How will I know that the private key has a valid structure?
Does Js class have this functionality?

**Comment by tomholub** [comment]
Just start with js.crypto_key_read
On the content

And make sure it returns a key that you'd expect. If it doesn't, it's not a
validly formatted key.

Second step is to make sure that you can get longid or fingerprint from
that key, and that you can get primary user from the key.

Third step is to test that the key is private (not public)

That should be enough for now.

**Comment by DenBond7** [comment]
@tomholub 
> check that it's under 1MB (reject bigger files),

Can the private key really have such size? I mean 1MB. I thought that the private key is a small file ( few kilobytes).

**Comment by tomholub** [comment]
Sometimes it can be bigger, you may see a 100kb file. Even 200kb, but
that's more rare. Sometimes people embed thumbnails in it, have many Sub
keys, etc. Maybe 250k would be a better limit, as long as it's communicated
that the key was rejected due to size.

**Comment by tomholub** [comment]
Perfect, I'll test it!
