### ISSUE TITLE
privacy policy to link to the web

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#573]
can you please remove the privacy policy from the app and make the button open browser with 
https://flowcrypt.com/privacy

Terms button should lead to https://flowcrypt.com/terms the same way

Urgently for this 0.7.9 release. Thanks!

**Comment by DenBond7** [comment]
@tomholub I've made changes. Please check it and tell me what you think about the realization.

1. On the main screen, I use [Chrome Custom Tabs](https://developer.chrome.com/multidevice/android/customtabs)

1. In the settings, I show the URLs as is. If a user clicks on some link on that tabs the system will open an external browser(to my mind it works well).

**Comment by tomholub** [comment]
perfect
