### ISSUE TITLE
A strange error when importing a private key while setup the app

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#58]
After completed issue #56, I receiving every time some strange error when trying to import a private key while setup the app.
You can reproduce my error by following steps:

1. Move to the trash folder all your backups in Gmail. It is means you do not have backups.
2. Then select "Import my key" -> "Load from a file"/"Load from clipboard"
3. After you received the private key, you will see the next screen
![2017-07-25_15-15-56](https://user-images.githubusercontent.com/2863246/28572285-fec0ee94-714e-11e7-91c5-f33907152e12.png)
4. Enter any password and you will see that the password approved. It is strange. I debugged this behavior.
![2017-07-25_15-17-26](https://user-images.githubusercontent.com/2863246/28572487-e9502e52-714f-11e7-9a99-c4bfbe794eb2.png)
5. Then open any encrypted message and you will see that the message decrypted successfully using your wrong password. 
![2017-07-25_15-19-11](https://user-images.githubusercontent.com/2863246/28572580-4d827bb4-7150-11e7-8ee5-f5431ceedfb9.png)
(I also debugged this moment. The database really contains my wrong password 
![2017-07-25_15-21-09](https://user-images.githubusercontent.com/2863246/28572688-c3ae3bac-7150-11e7-8d84-4f683c0c91e6.png)

)

But setup the app with Gmail backup works right. I do not understand why I have such situation when manually import the key.

**Comment by tomholub** [comment]
Here you go, just do `pgpKey.encrypt(...)` before doing `pgpKey.armor()`

Will only work for private keys (not public)

Please confirm that the resulting key is indeed getting encrypted.

**Comment by tomholub** [comment]
Also, the way I test that keys are encrypted is that I try `js.crypto_key_decrypt(pgpKey, "")` (with empty string as pass phrase).

If this decrypts the key, it was not protected.
