### ISSUE TITLE
discuss & clean up message pull

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#585]
@DenBond7 The problem is that Node only receives the first 200kb message. That works for some messages, but not for all. Especially `pgp/mime` messages that are a bit longer (eg contain an attachment) will not work.

I think we should stop using the 200kb method, and just download the whole message every time. For that, it would be good to have a % indication on the bottom, similar to loading inbox.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-android/issues/518#issuecomment-506840101_

**Comment by tomholub** [comment]
Doesn't make sense to always pull whole message, what if it's 20mb?

For now a compromise could be to show a message:

> This message is 18.5 MB large. Download and display anyway?

**Comment by tomholub** [comment]
Now it's 1MB

**Comment by DenBond7** [comment]
What kind of `BODYSTRUCTURE` can we have? Why am I asking?
Maybe we can analyze first 10kb-100kb of the raw MIME message and check does it contain `"-----BEGIN PGP MESSAGE-----"`. If yes we will download the whole message.

But this method will not work if a message will have an attachment in the begin. 
But for GMAIL we can use the search request which can look like
`rfc822msgid:200503292@example.com "-----BEGIN PGP MESSAGE-----"`, where `200503292@example.com` - it's a `Message-Id` header.

For other providers, we can use the following command (Standard IMAP SEARCH)
`A11 UID SEARCH HEADER Message-ID <200503292@example.com> TEXT "-----BEGIN PGP MESSAGE-----"`

@tomholub What do you think?

**Comment by tomholub** [comment]
It's more complicated than that. There are about 10 different ways to find out if a message is pgp.
 - attachments of various different names
 - sometimes also based on their content
 - various headers
 - presence of `"-----BEGIN PGP MESSAGE-----"` or `"-----BEGIN PGP SIGNED MESSAGE-----"` or even `"-----BEGIN PGP PUBLIC KEY-----"` etc.

The most reliable way is to give the whole thing to parseDecryptMsg and let it figure it out.

I would look into this in another version.

One idea is to add a button in `three dots` -> `Decrypt message`, that only shows if we detect it as a normal message. On the other hand, if we detected it as encrypted, it should say `Show without decrypting`. That way if our detection fails, user can still switch.

**Comment by DenBond7** [comment]
I want to summary what changes were added:

1. Now the app loads a whole message but excludes most attachments. To do that the app analyzes the bodystructure of the message and decides what parts will be included in a result

1. Here I've stored a logic which decides what parts will be included. For improving that logic will be better to create separate issues
 https://github.com/FlowCrypt/flowcrypt-android/blob/0c9f17501ccf54238dfeb93ba1e3435adf4beaa4/FlowCrypt/src/main/java/com/flowcrypt/email/api/email/sync/tasks/LoadMessageDetailsSyncTask.kt#L150

1. Also, I've added the ability to cancel loading the current message if a user leaves the message details screen

1. Now loading the message details via IMAP uses streams to store data to the file system. This approach doesn't use a lot of memory and gives us an opportunity to load really long messages. Now it doesn't matter what size the message has.

For now, I'm closing this issue. Please open a separate issue if we can add new changes in the next releases.

**Comment by tomholub** [comment]
Thanks
