### ISSUE TITLE
clean up and remove the other block types

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#586]
We can clean up and remove the other block types in some other release, I'll make an issue for it.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-android/issues/528#issuecomment-506848974_

**Comment by tomholub** [comment]
I'm not sure what this issue is for - do you know @DenBond7 ?

**Comment by DenBond7** [comment]
@tomholub I'm not sure too. Too old task to remember. I think we can close it.
