### ISSUE TITLE
whole toast error message doesn't show

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#594]
Toast should expand size with the error message

![Screenshot_20190629-215107](https://user-images.githubusercontent.com/6306961/60433371-367d0800-9bf4-11e9-87bc-28986840d889.png)

**Comment by DenBond7** [comment]
@tomholub I think we need a smaller text. Maybe we could change it.

Or another one variant

Currently, we have the following situation
![image](https://user-images.githubusercontent.com/2863246/65248807-77056700-dafb-11e9-8ec0-b1dc674ff388.png)

But maybe we can change it to
![image](https://user-images.githubusercontent.com/2863246/65248848-884e7380-dafb-11e9-8b23-9687f57a59a5.png)
![image](https://user-images.githubusercontent.com/2863246/65248858-8d132780-dafb-11e9-9344-0c72243bbaf2.png)

**Comment by tomholub** [comment]
Then just remove the "if you" part and after - simpler.
