### ISSUE TITLE
webpage not available err msg

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#595]
Is it possible to show a custom error message?

> No internet. Please try again later.

![Screenshot_20190629-215253](https://user-images.githubusercontent.com/6306961/60433431-57ddf400-9bf4-11e9-87e8-09bf65b35f80.png)

**Comment by DenBond7** [comment]
@tomholub I've added changes. Now it looks like this

![image](https://user-images.githubusercontent.com/2863246/75879985-1bb6ff00-5e25-11ea-9426-36b1daa05015.png)

[Here](https://github.com/FlowCrypt/flowcrypt-android/blob/3e21cd31d535324a814589c692c73e5c0d3982e6/FlowCrypt/src/main/assets/html/no_connection.htm) the HTML page which contains info to display
