### ISSUE TITLE
text hidden behind err icon?

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#596]
There seems to be some text hiding in the middle of the error icon :laughing: 

![Screenshot_20190629-215436](https://user-images.githubusercontent.com/6306961/60433509-878cfc00-9bf4-11e9-9551-89165ad655f9.png)

**Comment by DenBond7** [comment]
I'm closing it. It's not relevant today.
![image](https://user-images.githubusercontent.com/2863246/115858513-b9113000-a437-11eb-84d0-f346b0149dcf.png)
