### ISSUE TITLE
no private key available for account

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#597]
We should offer solutions to this
 -> import key (or load from backups)
 -> add email to existing key (can edit key using pgpainless to add user)
 -> create a new key for email

Keeps bothering me, and our users too

![Screenshot_20190629-215402](https://user-images.githubusercontent.com/6306961/60433572-b014f600-9bf4-11e9-8793-f2f210dbf35d.png)

**Comment by tomholub** [comment]
part of #714

**Comment by DenBond7** [comment]
@sosnovsky As I understand we should not allow to `add email to existing key` and `create a new key for email` for enterprise users where `keyManagerUrl != null`. Please correct me if needed.

**Comment by DenBond7** [comment]
How to reproduce:

1. Setup the app for example for `foo@flowcrypt.test`
2. Go to `Settings -> Keys`
3. Import a new key for example for `test@flowcrypt.test`
4. Delete the key for `foo@flowcrypt.test`
5. Go to the compose screen and try to send an encrypted message

**Comment by DenBond7** [comment]
Need to add that users who have an alias for their Gmail account can see this issue if a private key doesn't have `userId == alias` and a user is trying to use the alias to send a message.

**Comment by sosnovsky** [comment]
> @sosnovsky As I understand we should not allow to `add email to existing key` and `create a new key for email` for enterprise users where `keyManagerUrl != null`. Please correct me if needed.

I think it should be allowed in this case, but updated key needs to be synchronized to key manager.

Mentioned operations should be disabled when there is [NO_PRV_CREATE](https://flowcrypt.com/docs/technical/enterprise-admin-panel/usage/domain-configuration/client-configuration.html#client-configuration-flags) flag in client configuration (in this case app should show alert with `Please contact support at ...` message)

**Comment by DenBond7** [comment]
Fixed by #2660 #2669 #2675
