### ISSUE TITLE
forwarding message when offline - retry

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#599]
When offline -> open msg -> forward, the forwarded text will be missing.

When this happens, we could show a modal dialog with a retry / cancel button.

Cancel goes back to previous message.

![Screenshot_20190629-220342](https://user-images.githubusercontent.com/6306961/60433795-2c0f3e00-9bf5-11e9-9bbf-3a2f2ad51b26.png)

**Comment by DenBond7** [comment]
@tomholub Please clarify this issue or check if it still happens. I'm not sure how to reproduce it.

**Comment by tomholub** [comment]
The way to reproduce would be:

1) open inbox
2) go offline
3) tap on a message
4) tap forward
5) text of original message is missing in the newly composed message (text not forwarded)

The steps 2 and 3 may need to be switched - unsure. But if you cannot reproduce using these steps, then we can close. Thanks!

**Comment by DenBond7** [comment]
deprecated. I can't reproduce it.
