### ISSUE TITLE
missing other account addresses when offline

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#600]
This means that if the connection is unstable, I may sometimes miss other addresses (if connection drops exactly when pulling addresses).

Maybe can cache address list in local storage. This will make the screen load faster too, maybe?

Should still pull them with each open in case addresses changed.

![Screenshot_20190629-220415](https://user-images.githubusercontent.com/6306961/60433908-6ed11600-9bf5-11e9-8d49-c67a8e9495d3.png)

**Comment by DenBond7** [comment]
deprecated. The app already supports it.
