### ISSUE TITLE
Tell sender to update keys - fix layout

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#601]
- [ ] make the modal dialog wider
- [ ] decrease text size a bit
- [ ] prevent long email addresses from taking up more than one line
- [ ] `Select a key` should read `Choose Public Key to share`

![Screenshot_20190630-013459](https://user-images.githubusercontent.com/6306961/60434030-b657a200-9bf5-11e9-9b30-e04ef5b5d625.png)

**Comment by DenBond7** [comment]
@tomholub I've added changes. Please close this issue if all looks well

**Comment by tomholub** [comment]
I'm traveling and cannot easily build it now. Could you share a screen shot of the same screen as above?

**Comment by DenBond7** [comment]
Of course, no prob

![image](https://user-images.githubusercontent.com/2863246/65030908-074f7a80-d949-11e9-8acd-dd954136de70.png)

**Comment by tomholub** [comment]
much better!
