### ISSUE TITLE
behavior when recipient's public key not found

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#61]
When I add a recipient that doesn't have PGP set up, currently, it will still send the message using PGP, but will not encrypt it for the recipient - they will not be able to read the message.

We need a way to send plain text messages from the app, and dealing with missing public keys.

**Comment by tomholub** [comment]
See https://github.com/FlowCrypt/flowcrypt-android/commit/0c0571e413a9b9889da1b42db2950b82359d0c6b for designs

1) add a triple-dot menu icon on the right side. When clicked, a menu will show up in top-right corner (just like in standard Gmail app). This menu should contain two items for now: `Switch to standard email` and `Help`. Help will change screen to the contact form screen.

2) `Switch to standard email` in the menu on top right will switch to composing non-encrypted email with red design color: `#d14836`. Title will change from `Secure Compose` to `Compose`, and there is a notice underneath: `This message will not be encrypted`. If I click the triple dot menu again now, the options will be `Switch to secure email` and `Help`. https://github.com/FlowCrypt/flowcrypt-android/blob/master/design/app/screens/9.1-compose-standard.png

3) Messages sent out from the standard compose screen will be regular plain text emails.

4) When composing a message in secure email and the the app tries to get their public key but the request fails (network down or server down), change the "send" icon to "refresh" icon so that we can try again. Clicking on it will try to fetch public key again. I know this is not a good user experience, we will improve it later.

5) When composing a message in secure email and the recipient doesn't have PGP, show a dialog ( https://material.io/guidelines/components/dialogs.html#dialogs-simple-dialogs ) that has the following options as on this screen: https://github.com/FlowCrypt/flowcrypt-android/blob/master/design/app/screens/9.1-compose-no-pgp.png . If the user clicks back button or clicks in the dark area to cancel, show the last email in editable format and focus the cursor on it, maybe the user has just made a typo, so that they can edit it. Icons in the dialog use color `#888888`.

6) "Add public key" dialog item should lead to a form that lets the user import a public key. This will lead to a screen similar to importing private key: `Import from file`, `Import from clipboard`. I will add more details later.

Here are icon names that I used from http://ionicons.com/: ion-unlocked, ion-android-create, ion-document-text, ion-android-refresh

**Comment by tomholub** [comment]
I just realized, the option to switch to standard applies to reply as well.

Additionally, if previous message contains encrypted block or a public key, the reply message should be encrypted by default. If original message does not contain encrypted block or a public key, by default it should be standard message.

**Comment by tomholub** [comment]
Additional info for (6): The screen will use the same layout as "Import Public Key" screen in the settings.

Title: "Import Public Key"
 - load from a file (button)
 - load from clipboard (button)

Before import, check that it's indeed a public key `pgpKey.isPrivate() == false`. 
 - If it is a PRIVATE key, you can offer to import it as a private key (and transfer it to the import private key screen) - this is not necessary, we can do it later. 
 - Otherwise if it is a public key, you can import it. 

Important point: Get the user id from the public key to find out what email is it for. Then:
 - if the email is the same as the email that user was trying to compose to, save the public key for that email in db
 - if the email is different, save it for BOTH the email id and the original email address the person was emailing to (create two records in the database if both are missing).

**Comment by DenBond7** [comment]
I completed this task with some little changes.

I saw how you did this behavior in CryptUp and I tried to do such implementation in FlowCrypt, But for better user experience I need more work on using [Chips on Android](https://material.io/guidelines/components/chips.html#chips-usage). A current library is not perfect. At the moment I didn't find a better solution.
