### ISSUE TITLE
work around Binder 1MB limit for larger messages

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#610]
Most likely related to me recently changing message fetch size from 200kb to 1000kb.
```js
list.writeString("BODY[]<0.1024000>")
```
There seems to be a hard-coded limit 1MB in Binder.

I'll lower it to 450kb for now. Very soon we should see if there is a way around that - eg chunk it up and send over binder in smaller chunks, or use a file, etc.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-android/issues/609#issuecomment-507406137_

**Comment by tomholub** [comment]
To reproduce issue, switch the limit back to 
```Kotlin
list.writeString("BODY[]<0.1024000>")
```
Then open message from `michael.flowcrypt`: `HTML + Attachment + Encrypted from ...` on `flowcrypt.compatibility` account.

**Comment by tomholub** [comment]
Another message https://mail.google.com/mail/u/flowcrypt.compatibility@gmail.com/#inbox/WhctKJTrWNFtCxXXWRKkdrcSrfJrjGcmCLtvNgTqtkGgssRfhhTgqNnVpCXJpKXwVVWwgpG

**Comment by tomholub** [comment]
Sometimes it will not crash the first time I open the msg, but will crash the second time.

**Comment by tomholub** [comment]
For now I'm preventing crashes with
```Kotlin
          else -> {
            try {
              startActivityForResult(MessageDetailsActivity.getIntent(context,
                      listener!!.currentFolder, activeMsgDetails), REQUEST_CODE_SHOW_MESSAGE_DETAILS)
            } catch(e: java.lang.RuntimeException) {
              e.printStackTrace()
              // todo - https://github.com/FlowCrypt/flowcrypt-android/issues/610 - work around Binder 1MB limit for larger messages
              ExceptionUtil.handleError(ManualHandledException("App fails to open large messages"))
              Toast.makeText(context, R.string.failed_msg_too_large, Toast.LENGTH_LONG).show()
            }
          }
```

**Comment by DenBond7** [comment]
@tomholub I think maybe I know how to fix it. We use raw MIME message to create a reply. That's why we receive such errors. But as I know we only use headers of the original message. Maybe we can just use only headers instead of a whole message.

**Comment by tomholub** [comment]
You're supposed to be resting :stuck_out_tongue: 

This is when clicking in list of messages to open a message. Is it already trying to create a reply at this point?

**Comment by DenBond7** [comment]
> Is it already trying to create a reply at this point?

No, it's not. We send raw MIME message via Binder in two cases:
1. When we create a reply (click on the reply/forward button)
2. When we open an already downloaded message (open a message, close the message and open again)

Both cases we can fix (respectively):
1) use headers instead of the whole MIME message
2) fetch the raw MIME from the local database everytime when we are opening the message details

But I don't sure 100%. I don't have the code before my eyes right now.

**Comment by tomholub** [comment]
Sounds about right. I will try to only send headers in situation 1 and see if everything still works. Thanks!

**Comment by tomholub** [comment]
@DenBond7 done. I still left one todo for forwarding. It's a more rarely used feature, so I'm not too worried about it until later.
```Kotlin
// todo - msgInfo?.stripRawMsgContent() // would probably affect forwarding, leaving for DenBond
startActivity(CreateMessageActivity.generateIntent(context, msgInfo, MessageType.FORWARD, msgEncryptType))
```
