### ISSUE TITLE
more space should be utilized for subject in email list

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#612]
will add screenshot

**Comment by DenBond7** [comment]
@tomholub Please add details for the issue when you will have some free time :)

**Comment by tomholub** [comment]
Here. The subject stops where the red line is, but it could actually continue to the right, where the green line goes.

![image](https://user-images.githubusercontent.com/6306961/62039926-2d9b4880-b22b-11e9-8321-f232620d57bd.png)
