### ISSUE TITLE
regular plain text attachments don't show

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#614]
Please let me know if mobile-core is not returning them.

Examle: https://mail.google.com/mail/u/flowcrypt.copatibility@gmail.com/#inbox/WhctKJVRDxWCmPQxbDTkVdFfLZvCnJmkpNvcPbKZWTDZBsczMNTszPHlVdhpFmLxGFCShFQ

**Comment by DenBond7** [comment]
it relates to https://github.com/FlowCrypt/flowcrypt-android/issues/343

**Comment by DenBond7** [comment]
fixed via #343
