### ISSUE TITLE
date inside message view should follow date in email list

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#620]
eg click on message from 2018. It will show `18:33` inside :laughing:

**Comment by DenBond7** [comment]
@tomholub Please show an example for better understanding

**Comment by tomholub** [comment]
Every single message.

For example find a message from 5 days ago. It says `Jul 13` in inbox. Click on it. It says `10:03` in message view. It's not useful, I don't know 10:03 which day, which year, etc.

**Comment by DenBond7** [comment]
Got it. Thanks!
