### ISSUE TITLE
missing regular encrypted attachments

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#625]
https://mail.google.com/mail/u/flowcrypt.compatibility@gmail.com/#inbox/WhctKHTCDdzshCcJnBGVhKdmwbrPfZgBZLtVlPVmwtTDKxtVGmTHLxTPKxNGBFnSWmGwBXQ

**Comment by DenBond7** [comment]
it relates to https://github.com/FlowCrypt/flowcrypt-android/issues/343

**Comment by DenBond7** [comment]
fixed via #343
