### ISSUE TITLE
how to run simple tests that don't need a mailserver

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#636]
Do we have any tests that do not need a mail server? For example testing something on the initial screen?

If I already have an apk to test, how can I run only these tests?

This will be the first step in automating ci tests.

**Comment by DenBond7** [comment]
126 tests can be run without a mailserver

**Comment by tomholub** [comment]
Great! Please let me know how to run them :)

**Comment by tomholub** [comment]
Also it should be `DoesNotNeedMailserver`

**Comment by DenBond7** [comment]
@tomholub I'm working on instructions

**Comment by DenBond7** [comment]
@tomholub 

1. To run tests please be sure that you have only one available device

1. Then [set up](https://developer.android.com/training/testing/espresso/setup#set-up-environment) your device (emulator)

1. Run tests via `./script/run_test_without_mail_server.sh`

It would be great if you will use an emulator

**Comment by DenBond7** [comment]
for me

```
adb shell settings put global window_animation_scale 0.0
adb shell settings put global transition_animation_scale 0.0
adb shell settings put global animator_duration_scale 0.0
```

**Comment by tomholub** [comment]
If course this will be using emulator, the only other option is to connect an actual device, right?

**Comment by DenBond7** [comment]
@tomholub correct

**Comment by tomholub** [comment]
Unfortunately about 10% of their CI machines don't have KVM available. When the test pipeline is run by such machine, it will fail. I've asked Semaphore support about it, they should be able to fix it for us.

**Comment by tomholub** [comment]
Other than this issue, the basic tests can now run. I had to `Ignore` a few tests, which should be addressed in next release.
