### ISSUE TITLE
how to run tests that need mailserver

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#646]
Please describe what is needed to run tests with mailserver.

What kind of mailserver is used? Steps to set it up? Does it have any pre-loaded data on it? Where to get the data?

Do you currently run any such live mailserver, or do you have to turn it on each time you test?

When an email is sent using the mailserver, is it just throwing the sent emails out (instead of trying to deliver them to other mail servers?). If yes, how was this configured?

How are accounts configured, does it use any authentication? How is that set up?

_Originally posted by @DenBond7 in https://github.com/FlowCrypt/flowcrypt-android/issues/636#issuecomment-510536975_

**Comment by DenBond7** [comment]
> What kind of mailserver is used?

 I use [iredmail](https://www.iredmail.org/) 

![image](https://user-images.githubusercontent.com/2863246/61169265-cfe8da00-a563-11e9-9662-8c0bd97ed016.png)



> Steps to set it up?

It's a little hard to remember. I setup it 2 years ago :(
Actually, it's not very important how to configure it (I mean different auth types). As for me, it must be as simple as possible. I just need to be able to connect to it from the tests. If need I think I can export settings from my server. By the way, it looks like
![IMG_20190713_112336](https://user-images.githubusercontent.com/2863246/61169283-0cb4d100-a564-11e9-8495-7c84717774a8.jpg)



> Does it have any pre-loaded data on it?

Yet, it does. I have some accounts for testing. Not all of them I use in tests. As example
![image](https://user-images.githubusercontent.com/2863246/61169277-f575e380-a563-11e9-9aa7-88aca6e32db2.png)

> Do you currently run any such live mailserver, or do you have to turn it on each time you test?

It works always on my [orange pi pc](http://www.orangepi.org/orangepipc/)

**Comment by DenBond7** [comment]
In general, it works as a local mail server. I send messages only to own accounts on my server. It doesn't have access to the outer world

**Comment by DenBond7** [comment]
[Here ](https://github.com/FlowCrypt/flowcrypt-android/tree/master/FlowCrypt/src/androidTest/resources) I store the accounts settings

**Comment by tomholub** [comment]
Thanks!
