### ISSUE TITLE
bad authentication when searching

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#653]
Searching in inbox

![image](https://user-images.githubusercontent.com/6306961/61295914-9664d880-a7c8-11e9-9339-6afb0d80fe39.png)

I forgot how I resolved it. Maybe I clicked manually to open some other inbox. Maybe I killed the app. Don't know.

**Comment by DenBond7** [comment]
I'm not sure, but maybe it relates to com.google.android.gms.auth.UserRecoverableAuthException: BadAuthentication. I've added the debug code. Need to wait while I'll have more info

**Comment by tomholub** [comment]
got it

**Comment by DenBond7** [comment]
@seisvelas Please tell me do you receive similar feedback from users? If not I think it should be fixed by #993

**Comment by seisvelas** [comment]
@DenBond7 Nope! I'll reopen this if new support emails come in reporting this issue, otherwise I think we can assume it's fixed.
