### ISSUE TITLE
sign outgoing messages

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#655]
The triple dot will have an option
```
Sign this message
```
When not enabled and I tap it, it should show
```
Sign this message ✓
```
And vice versa. Then, in General settings as described in #654 there should be a toggle:
```
[x] Sign outgoing messages
```

**Comment by tomholub** [comment]
note - remember to sign by the right key based on `from:` email

**Comment by seisvelas** [comment]
Ref: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgxwJXxnSZgjbrqQFNTlhzTFMJPsq

**Comment by seisvelas** [comment]
Ref: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgxwLswFxBqKllTkVzhmgGGxkfCph
