### ISSUE TITLE
Replace attester/lookup with attester/pub

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#663]
Best would be to switch to the new api

GET https://flowcrypt.com/attester/pub/human@flowcrypt.com
GET https://flowcrypt.com/attester/pub/unknown@flowcrypt.com
GET https://flowcrypt.com/attester/pub/0C9C2E6A4D273C6F

404 means not found. Else if 200 -> you get pubkey as text.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-android/issues/662#issuecomment-513255614_

**Comment by tomholub** [comment]
Yay! I was waiting to deprecate the old api for a very long time now.
