### ISSUE TITLE
Option in settings to disable acra

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#665]
We have a user complaining about crash reports

Please change settings section `Security` to `Security and Privacy`, and add a switch or checkbox:
```
Change pass phrase
[  o] Allow anonymous crash reports
```

**Comment by tomholub** [comment]
Default on

**Comment by tomholub** [comment]
When off, just don't send any crash report.

**Comment by DenBond7** [comment]
@tomholub I've added that option. Please close it if everything looks good.

**Comment by tomholub** [comment]
Looks good
