### ISSUE TITLE
Disable animations on CI emulator

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#667]
I'm not sure that animations were disabled on the emulator on CI server.

Sometimes we receive 

```

com.flowcrypt.email.ui.activity.KeysSettingsActivityTest > testKeyDetailsShowPrivateKey[ci-test-pixel-x86-64-api28(AVD) - 9] FAILED
--
  | androidx.test.espresso.PerformException: Error performing 'single click' on view 'Animations or transitions are enabled on the target device.
  | For more info check: https://developer.android.com/training/testing/espresso/setup#set-up-environment
  | 03:29:39 V/InstrumentationResultParser: INSTRUMENTATION_STATUS_CODE: -2
```

Need to add the following command when the emulator will be started
```

adb shell settings put global window_animation_scale 0.0
adb shell settings put global transition_animation_scale 0.0
adb shell settings put global animator_duration_scale 0.0
```

**Comment by DenBond7** [comment]
> Need to add the following command when the emulator will be started

Before running the tests

**Comment by tomholub** [comment]
maybe around this line https://github.com/FlowCrypt/flowcrypt-android/blob/master/.semaphore/semaphore.yml#L42

**Comment by DenBond7** [comment]
https://issuetracker.google.com/issues/69247502
https://github.com/FlowCrypt/flowcrypt-android/commit/ac64741802d32ff28c0eea978082923759e5611d
