### ISSUE TITLE
Organize debug settings

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#675]
Add options to the debug settings to disable printing out of request/response data for:

- [x] IMAP

- [x] Retrofit

- [x] Node

All options should be disabled by default

**Comment by DenBond7** [comment]
@tomholub 
Default settings for `prod` flavor (only debug builds like `prodDebug-x86` and etc)

![image](https://user-images.githubusercontent.com/2863246/62279526-f7401200-b452-11e9-901a-f4d397303332.png)

**Comment by tomholub** [comment]
Looks good
