### ISSUE TITLE
8bit encoding utf8 fix

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#676]

**Comment by tomholub** [comment]
Message to test with:

![image](https://user-images.githubusercontent.com/6306961/62158403-d8306b80-b2fe-11e9-9096-fd81dda8b977.png)

Please also add a test when it's fixed

**Comment by DenBond7** [comment]
![image](https://user-images.githubusercontent.com/2863246/62192266-effb0480-b37d-11e9-8823-627d82c2628a.png)
