### ISSUE TITLE
option to copy pubkey from other contact

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#68]
I'll clarify this later

**Comment by tomholub** [comment]
Just needed this, maybe in v11

**Comment by tomholub** [comment]
When I want to message someone and the public key is not available, currently I can either add their public key, change the email or switch to plain text.

There should be another option "Copy from other contact" as a third option betwen "import their public key" and "remove recipient".

use https://material.io/icons/#ic_content_copy

Clicking that should bring up a list of contacts. On the top, it will say "Use Public key from" and below will be a list of contacts. Clicking on one of them will copy their public key into a new contact listed with the email that was originally missing a pubkey, so that I only have to do this one time.

This is useful because some people who use other software may have 20 email addresses, but they have key listed for just one of them.

**Comment by DenBond7** [comment]
I completed this issue.  I also added an option to find contacts easy.
