### ISSUE TITLE
Add a feedback action button to all screens

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#680]
> On Android, we have to have a very direct feedback button on every page. Maybe a small red icon of a bug (insect) somewhere in the corner. Every screen. They could click it and it will allow them to take a screenshot and include a message. If we can then respond to them fast enough, it could work.

**Comment by DenBond7** [comment]
@tomholub I've found an interesting solution [here](https://github.com/maoni-app/maoni). Maybe we can use it. What do you think?

**Comment by tomholub** [comment]
I think this could be used.

![image](https://user-images.githubusercontent.com/6306961/63763577-860a4800-c8b4-11e9-9786-99867f18f0c0.png)

The only issue is that maybe we may need to position the feedback button differently based on screen?

Unless we can always just put it all the way in the corner:

![image](https://user-images.githubusercontent.com/6306961/63764182-bc949280-c8b5-11e9-8c32-8a717b9302f8.png)

Which looks quite ugly, to be honest :laughing: 

So the better option may be to always incorporate it into the header?

![image](https://user-images.githubusercontent.com/6306961/63766277-5eb67980-c8ba-11e9-8bc4-ac2536aa7828.png)

I think that would be a better solution.

**Comment by DenBond7** [comment]
we have https://flowcrypt.com/api/help/feedback for feedbacks. Just need to modify it a little. As we discussed, we can make a field for a screenshot. Then I can send the screenshot base64 encoded

**Comment by tomholub** [comment]
withWindowTitle: `Feedback or question`
withMessage: ` ` (empty string)
withFeedbackContentHint: `How can we help?`
withScreenshotHint: ` ` (empty string)
withTouchToPreviewScreenshotText: ` ` (empty string)

[ ] Include recent application logs
[ ] Include app screenshot

----------------------

Both checkboxes unchecked by default. Also there should be no background image on top, maybe a full color instead

**Comment by DenBond7** [comment]
@tomholub I've added new changes. Please check them, maybe need to change something a  little before a release

**Comment by tomholub** [comment]
Ok I'll check, thanks!
