### ISSUE TITLE
inner decryptedAtt should be styled in green

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#681]
please make it clear that the attachment was encrypted

See desktop:
![image](https://user-images.githubusercontent.com/6306961/62796124-f26d0500-bac7-11e9-84c9-43b609c5518d.png)

See Android:

![Screenshot_20190809-190017](https://user-images.githubusercontent.com/6306961/62796139-fbf66d00-bac7-11e9-8445-a5733a3cce44.png)

I recommend to style it almost the same as the message. Green line on the left, then just subtle lines around, and should span from side to side. Maybe no shadow.

(Only for encrypted attachments)

Plain attachments should also be styled from side to side, and also no shadow, but with similar colors as now.

Please share screenshots of both when ready.

**Comment by DenBond7** [comment]
@tomholub It's a little hard to understand all requirements without UI. Please look at my examples (inner + regular atts). It would be great if you share UI which bases on my screen

### 1.Green line
![image](https://user-images.githubusercontent.com/2863246/63599762-eb1b2080-c5ca-11e9-923c-beaae3aa1043.png)

### 2.Green line + bold text
![image](https://user-images.githubusercontent.com/2863246/63599650-adb69300-c5ca-11e9-9e1b-6041e7f1b2f7.png)

### 3.Green line + bold text + black color
![image](https://user-images.githubusercontent.com/2863246/63599542-7ea02180-c5ca-11e9-903a-e5b0592cd960.png)

**Comment by tomholub** [comment]
1) green line is best, with a fix to span the whole width, and no margin. Like this:

![image](https://user-images.githubusercontent.com/6306961/63600589-5a851600-c5b3-11e9-8b48-5307594d232e.png)

**Comment by tomholub** [comment]
And also no border radius in the corners

**Comment by tomholub** [comment]
And no shadow

**Comment by DenBond7** [comment]
Now it looks like that

![image](https://user-images.githubusercontent.com/2863246/63666985-d2815500-c7da-11e9-9aa4-0f7b4d801cb7.png)

I think HTML adds space between encrypted text and atts.

![image](https://user-images.githubusercontent.com/2863246/63667145-58050500-c7db-11e9-8fbe-de87b2d29a43.png)

**Comment by DenBond7** [comment]
And need to think about this screen.

![Selection_077](https://user-images.githubusercontent.com/2863246/63667236-a31f1800-c7db-11e9-8971-dd716febe40a.png)

**Comment by tomholub** [comment]
Ok maybe add the same amount of space below each attachment. That will look good.
