### ISSUE TITLE
Bug with HTML line break

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#682]
![image](https://user-images.githubusercontent.com/2863246/62787781-1d5a5780-bace-11e9-9f1f-1dfcbc0c66dc.png)

**Comment by tomholub** [comment]
![Screenshot_20190810-140848](https://user-images.githubusercontent.com/6306961/62821651-b5f0e600-bb67-11e9-808e-75ed9a370635.png)
