### ISSUE TITLE
reply/reply-all/forward options on top

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#693]
User feedback

> The ability to reply/reply all/forward at the top, not just a reply to all.  Some of my emails can get long in replies and I don't like that I have to scroll down to the bottom just to reply to one person in the chain.  

Me

> We could add the reply-all and other options on the top, under three dots icon, similar to what Gmail does.

**Comment by tomholub** [comment]
It is true that having to scroll all the way down if the message is super long is inconvenient.

**Comment by DenBond7** [comment]
@tomholub What do you think about that?

![image](https://user-images.githubusercontent.com/2863246/65543099-20dc5d80-df19-11e9-8eed-f51d60e019c2.png)

![image](https://user-images.githubusercontent.com/2863246/65543108-289c0200-df19-11e9-97b0-09e9791d9e02.png)

**Comment by tomholub** [comment]
Yes but maybe the dots should be just gray? And a bit more space between the dots and the forward button.

**Comment by tomholub** [comment]
Actually if you could also make the reply icon change color like the bottom ones do! We forgot to do that last time

**Comment by DenBond7** [comment]
No prob, will do :)

**Comment by DenBond7** [comment]
![image](https://user-images.githubusercontent.com/2863246/65545142-7286e700-df1d-11e9-93da-200bc34f33e6.png)
![image](https://user-images.githubusercontent.com/2863246/65545372-e628f400-df1d-11e9-98b1-98e0e4a306b3.png)

**Comment by tomholub** [comment]
Perfect, maybe even more space between three dots and reply icon :)

**Comment by tomholub** [comment]
Like 50% more space
