### ISSUE TITLE
Encrypted subjects not rendered

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#695]
in the top json part
today it's { text, replyType }, so we make it {text, replyType, subject}

**Comment by tomholub** [comment]
> in the top json part
> today it's { text, replyType }, so we make it {text, replyType, subject}

I'm making a separate issue for just the TypeScript part.

**Comment by tomholub** [comment]
parseDecryptMsg now returns a `subject` as well.

**Comment by DenBond7** [comment]
@DenBond7 Need to add a test for this issue
