### ISSUE TITLE
color-coding recipients on reply screen

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#70]
I would like to mimic behavior of the chrome extension when entering recipient email in secure compose.

After loading public key of a recipient, it should either turn gray (no key found) or green (key found).

Is this possible?

**Comment by DenBond7** [comment]
> After loading public key of a recipient, it should either turn gray (no key found) or green (key found).
> 
> Is this possible?

Do you mean this? It's already working.

![2017-08-08_9-01-57](https://user-images.githubusercontent.com/2863246/29058326-7195e43c-7c18-11e7-9732-2a7b4e9fccb6.png)

**Comment by tomholub** [comment]
Yes, but also on reply screen. I must have been testing it on the reply screen. That's why I overlooked it completely :)
