### ISSUE TITLE
issue logging in on enterprise build

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#700]
Please also look into this before other things.

1) build `devEnterprise`
2) Continue with Gmail
3) click your email addr
4) you will see `Continue with Gmail` button again, nothing happened.

If there is error, please make sure that the error is properly surfaced to the user.

**Comment by DenBond7** [comment]
@tomholub I think I know what is wrong. For package `com.flowcrypt.email.enterprise` didn't setup SHA-1 and package keypair for the debug key in the Google API Console. Need to check that.

**Comment by tomholub** [comment]
I saw it on the console. I'll double check

**Comment by DenBond7** [comment]
@tomholub I've added changes. Please close this issue if all looks well
