### ISSUE TITLE
creating a new key during setup

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#71]
I will add info
 - [x] expose js / create key
 - [x] enable in UI/Java
 - [x] submitting key to keyserver (no attesting yet)

**Comment by tomholub** [comment]
```Java
PgpKey k = js.crypto_key_create(new PgpContact[]{new PgpContact("some@email.com", "Some Name")}, 2048, "pass!!");
System.out.println(k.armor());
System.out.println(k.getCreated());
System.out.println(k.getFingerprint());
System.out.println(k.getLongid());
System.out.println(k.getPrimaryUserId().getEmail());
System.out.println(k.getPrimaryUserId().getName());
System.out.println(k.isPrivate());
System.out.println(k.toPublic().armor());
```

**Comment by tomholub** [comment]
For version 0.5.0, you can use the above code snippet to create keys.

Please note that creating keys is a LONG operation (I'm guessing 1-2 minutes on my device).

The procedure is:
1) find out user's name and email address from IMAP. If it's possible to find out all of user's email address and associated names, get all.
2) prompt user to choose a pass phrase
3) measure strength of pass phrase to make sure it's satisfactory (I'll add more info about this)
4) Choose **2048** for num_bits (offers better performance compared to 4096, suitable for mobile devices)
5) Wait a long time while key is getting created
6) Save the key the way you would save imported key
7) Perform a backup of armored key in inbox
8) Register public key with attester
9) Request a test email from FlowCrypt
10) Show a screen with "You're all set!" as a header and "From now on, you can send and receive encrypted emails on this email account." underneath. Below the text, there will be a "[CONTINUE]" green button.

**Comment by tomholub** [comment]
measuring strength of pass phrase: use https://github.com/nulab/zxcvbn4j

```Java
Zxcvbn zxcvbn = new Zxcvbn();

PasswordStrength ps = js.crypto_password_estimate_strength(zxcvbn.measure("This is pass phrase", js.crypto_password_weak_words()).guesses);

System.out.println(ps.didPass()); // bool - is this strong enough for use? action button should be gray if false (and not clickable), else make action button green if yes + make it clickable
System.out.println(ps.getBar()); // length of strength bar in percentag int 0-100
System.out.println(ps.getTime()); // words describing how long it takes to crack eg "centuries"
System.out.println(ps.getWord()); // word describing how strong the pass phrase is eg "weak"
System.out.println(ps.getColor()); // name of color to use, one of ['green', 'orange', 'darkorange', 'darkred', 'red']
```

Try to mimic the behavior of browser extensions. You should evaluate strength every time the input is changed. Please re-use the same color palette that is used by the extension.

Right now, `ps.getColor()` will just return name of each color. Feel free to change this to be more convenient, eg if you want a color hex instead, we can do that.

**Comment by tomholub** [comment]
Registering key with attester:
```
POST attester.flowcrypt.com/initial/legacy_submit 
{ "email": "abc@def.com", "pubkey": "-----BEGIN ...", "attest": false }
```
Make sure to choose attest: false for now.

Note that this will only be successful if it's the first time submitting a key for this email address, or if the key being submitted has the same fingerprint as the one already recorded.

If it's an error due to key conflict, ignore the error. If it's error due to network, do not ignore it.

See https://github.com/FlowCrypt/flowcrypt-android/wiki/attester.flowcrypt.com and https://github.com/FlowCrypt/flowcrypt-android/issues/20

**Comment by tomholub** [comment]
(step 9) Requesting a test message with the new public key:

```
POST attester.flowcrypt.com/test/welcome
{ "email": "abc@def.com", "pubkey": "-----BEGIN ..." }
```

**Comment by DenBond7** [comment]
@tomholub 

> Feel free to change this to be more convenient, eg if you want a color hex instead, we can do that.

It will be great! A HEX value.

**Comment by DenBond7** [comment]
![image](https://user-images.githubusercontent.com/2863246/34770723-96b5b866-f60a-11e7-8583-2e1095f5f3f7.png)

**Comment by DenBond7** [comment]
[Changed password hint colors.](https://github.com/FlowCrypt/flowcrypt-android/commit/53b3f5e6d47072b8d22aa8eb0debb1467365b719)

**Comment by DenBond7** [comment]
@tomholub  I need some clarifications.

**Cases:**
##############################################################################
**_1._**
a) Key was generated
b) Key was saved to the local database
c) Was happen an error when we tried to send a backup

How to be in this case?
Currently, I'm deleting a key from the local database and showing the message "Cannot save a copy of the private key in INBOX"

##############################################################################
**_2._**
a) Key was generated
b) Key was saved to the local database
c) Key was backed up to INBOX
d) The public key registering with attester was not completed (Communication issue, etc.)

How to be in this case?
Currently, the private key was saved to the local database and backed up to INBOX.

##############################################################################
**_3._**
a) Key was generated
b) Key was saved to the local database
c) Key was backed up to INBOX
d) The public key registering with attester was completed successfully
e) Requesting a test message with the new public key was not completed (Communication issue, etc.)

How to be in this case?
Currently, the private key was saved to the local database and backed up to INBOX. The public key was registered.

**Comment by tomholub** [comment]
**Case 1) error saving key**
You can proceed anyway with no error. I suggest to save a list of actions needed into a queue of some sort. For example you could call this action `keyBackup` and note the `longId` and `email` next to it. When opening the app or loading inbox, you could look into the queue to do any needed operations first.

**Case 2) error submitting key**
If this was network or timeout error or a 5xx error from server, add it into a queue. You can call it `publicKeySimpleSubmit`, and save `email` and `longId` next to it so that you can submit the right key.
If this was a 4xx error from server, do not retry (probably a key conflict).

**Case 3) error requesting a test message**
Add into queue, with `email` and `longid`. Maybe `sendTestWelcome`

One day I would like to display an actions button where user could click and retry manually, for example somewhere in the inbox UI or in side menu. Maybe there could be a small rend umber in a circle on top of the side menu suggesting that certain maintenance actions are needed. That would be great, but that's for later.

**Comment by DenBond7** [comment]
I have done this task.

**Comment by tomholub** [comment]
LOVE the (?) icon during setup where you copy-pasted the pass phrase info!

Where did you put the hint text html file? I'd put it into assets/html

**Comment by DenBond7** [comment]
I copy-pasted the pass phrase info to `/res/values/strings.xml`

```
<string name="password_recommendation">
        <![CDATA[<p>Choose a VERY long passphrase. For example, combine uncommon words like this:</p>
  <font color="#088447">unconventional blueberry unlike any other<br/>
semi automated shiseido mask<br/>
icelanders prefer real sauna</font>
  <p>Combinations like that are memorable, easy to type and the most secure.</p>
  <p>In contrast, pass phrases like <font color="#AA4444">@ut0m4t3d</font>, <font color="#AA4444">Honey167!</font> or <font color="#AA4444">lA45pf8$d</font> are a poor choice when it comes to security. Because they are so short, on a fleet of 10,000 ordinary computers, these <b>can be guessed in 7 seconds</b>.</p>
  <p>To read more, see <a href="https://blogs.dropbox.com/tech/2012/04/zxcvbn-realistic-password-strength-estimation/" target="_blank">zxcvbn article</a> by Dropbox.</p>]]>
        </string>
```

> I'd put it into assets/html

Ok, I'll do that.

**Comment by tomholub** [comment]
Great, also, please remove the "Hint" headline when the hints open (all of them). Start with text only, and then ok

**Comment by DenBond7** [comment]
> I'd put it into assets/html

https://github.com/FlowCrypt/flowcrypt-android/blob/0.5.0/FlowCrypt/src/main/assets/html/pass_phrase_hint.htm

@tomholub I have changed some line of "combine uncommon words" because I need a shorter line (the shorter line looks better). Please look my changes.

**Comment by tomholub** [comment]
Also updated. Looks good
