### ISSUE TITLE
search should also search by recipient/sender

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#710]
if I search by a keyword, this should ideally also search senders and recipients for the same keyword in their name and email address, not just subjects

**Comment by DenBond7** [comment]
@tomholub Currently the app uses [X-GM-RAW](https://developers.google.com/gmail/imap/imap-extensions#extension_of_the_search_command_x-gm-raw)  IMAP extension, which does a search over all parameters(if we are talking about Gmail). For example `F18 SEARCH X-GM-RAW android ALL` returns all messages which contain text `android` in a subject, in a body, in recipients. If you have found any errors for that please add more details.

**Comment by DenBond7** [comment]
@tomholub But non-Gmail accounts use the following request `M4 SEARCH SUBJECT Android ALL`
