### ISSUE TITLE
Continue with Outlook - oauth screen

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#716]
Similar to what we do with Gmail, if possible

**Comment by tomholub** [comment]
part of #714

**Comment by DenBond7** [comment]
for me https://developer.android.com/training/id-auth/authenticate

**Comment by DenBond7** [comment]
for me
- [ ] Don't store client_id in the app

**Comment by DenBond7** [comment]
for me
- [ ] test revoke access via a site

- [ ] test adding an account twice

- [ ] test adding an account from Settings -> Accounts
