### ISSUE TITLE
hide notifications when I open the app normally

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#724]
1) close the app, send an email from another app
2) notification shows up
3) do not click on notification. Instead, open the app
4) notification stays open and never disappears (bug)

In Gmail, when you open an inbox, notifications for all messages associated with that inbox will be dismissed and go away automatically. We should do the same.

**Comment by DenBond7** [comment]
@tomholub This [commit](https://github.com/FlowCrypt/flowcrypt-android/commit/8110e35a09ee7425ae3f17bc16d52bae934aa38e) had resolved the current issue. I'm closing it.
