### ISSUE TITLE
ask user for email if not logged in

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#732]
User can share feedback before they have logged in. Then we don't know their email.

If the email is missing, please ask and require user to enter their email address, else I get email like this (and don't know who to reply).

![image](https://user-images.githubusercontent.com/6306961/65578977-647ea800-dfa9-11e9-9cc0-7b105bf9f6de.png)

**Comment by tomholub** [comment]
Another 
![image](https://user-images.githubusercontent.com/6306961/65594803-0b713d00-dfc6-11e9-9dbe-e602c65b702d.png)

**Comment by DenBond7** [comment]
@tomholub I've added new changes. Now the feedback screen looks like this if a user hasn't logged in

![image](https://user-images.githubusercontent.com/2863246/65754112-05d83c00-e119-11e9-95f4-ad625c14624d.png)

**Comment by tomholub** [comment]
Very good, thanks!

**Comment by tomholub** [comment]
It should say "Your email address"

**Comment by DenBond7** [comment]
> It should say "Your email address"

@tomholub Done
