### ISSUE TITLE
Not enough space for title - Icons should be more compacted

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#737]
![image](https://user-images.githubusercontent.com/6306961/66138574-64585b00-e5ee-11e9-91e4-06b6f31ddfab.png)

**Comment by DenBond7** [comment]
@tomholub 
Is it better? I've made the help icon 24dp (vector). Now all action items take a similar space

![image](https://user-images.githubusercontent.com/2863246/66254372-08bcd780-e77e-11e9-9efc-b03830d87e35.png)

**Comment by tomholub** [comment]
Definitely better than before.
