### ISSUE TITLE
Improve work with IMAP via JavaMail

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#739]
That's about how we can improve the app work with IMAP. Currently, we have two separate threads for active and passive tasks. 

- active - that's a task which must be run immediately (like load the message details, load next messages when a user scroll down a list)

- passive - that's a task which can be run later (like update label list, load info about contacts and etc.)

Currently, those tasks use a queue where I store tasks. Those tasks run one by one. To run the next task I have to wait while the last will be completed. But I've found that the JavaMail support access to the single connection from the multiple threads. This fact can be used to improve the app speed and user experience. So I can create a realization where I can use a single connection and run tasks via separate threads

**Comment by DenBond7** [comment]
Please notice, that it's a little complicated task and it will take some time (maybe up to one week)

**Comment by DenBond7** [comment]
@tomholub What do you think? I didn't add this issue to any milestones because I don't know what tasks are prioritized now.

**Comment by tomholub** [comment]
I'm putting it into later. It's could be a great optimization and agree it should be done. But most bad feedback I get these days is because of lack of functionality, not performance, so we will be prioritizing functionality these days.

**Comment by DenBond7** [comment]
Got it. Agree

**Comment by DenBond7** [comment]
For me https://github.com/FlowCrypt/flowcrypt-android/tree/test_multithreding
