### ISSUE TITLE
Receive message, archive it, them later open from notification

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#744]

**Comment by DenBond7** [comment]
@tomholub Could you add more details? I can't understand how to reproduce that. Thanks!

**Comment by DenBond7** [comment]
@tomholub I've found how to reproduce this issue. Need to have another one notification (for example download file result) of the Flowcrypt app. Then all your steps will be true

**Comment by DenBond7** [comment]
And that's not a Redmi bug. I've removed the wrong label.
