### ISSUE TITLE
enterprise domain rules and restrictions

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#748]
We will need to be able to disable some functionality in the app based on settings of their domain.

# API Specs

These are authenticated calls, therefore you will need to login using OpenID Connect id_token (you should already be receiving this if scopes include "openid" and "email"), else please add these scopes.

First, one time per account, you need to generate uuid which is 40 characters long, containing only lowercase hex characters 0-9a-f. Example: `8d43af.................................93`. Use secure random to generate these. You can think of `uuid` as an auto-generated password, which you create and store in the app. It is sensitive, so store it securely.

Correct `email` + `uuid` combination allows to access restricted API (similar to email+password).

## 1) FlowCrypt Account Login

To register email+uuid combination of an account, you need to prove user identity the to API backend. You can prove user identity by using the `id_token` you received from google for that account, because it is signed by google and we can verify that it's the right user.

For this initial user registration (done one time for each generated uuid), you need to call the login endpoint:

```
POST https://flowcrypt.com/api/account/login

headers:
Authorization: Bearer <id_token>

payload:
{
  "account": "some@email.com",
  "uuid": "<uuid>"
}
```

In the Authorization header you will directly paste the id_token, for example:
`Authorization: Bearer eyaskdjaskldjaslkjdaslkdjsa.aslkdakldjkasjdlsakjdlkasjdklas.ashdsakdaskjdkasjhdksajhdjksahdasjdkashkda`

Response must have both registered=true and verified=true to be success
```
response 200 { 
  "registered": true,
  "verified": true
}
```
There should be unique uuid per each account (per each device).

If any restricted API returns you http error code 401 (auth), that means your uuid is not verified, and you have to request a new id_token from the user (by asking the user to go through google oauth permission grant again), then getting the new id_token, and verify it with the call above. After that you can repeat the call that gave you 401. If you do this, remember to ask for a new id_token because they usually expire quickly (1 hour).

But once you have uuid verified, the uuid will not expire, so you can keep using it forever.

## 2) getting domain rules from backend

```
POST https://flowcrypt.com/api/account/get

payload:
{
  "account": "some@email.com",
  "uuid": "<uuid>" // this one must be already verified, else you get http error 401
}
```
response:
```
{
  "domain_org_rules": {
    "flags": [
      "NO_PRV_CREATE",
      "NO_PRV_BACKUP",
      "STRICT_GDPR",
      "ENFORCE_ATTESTER_SUBMIT"
    ]
  },
  "account": { ... } // you can ignore this
}
```

This gives you a list of flags (rules). The default is empty array. Once you make it work so you can at least receive empty array, I will help you test situations that have some other settings.

Please cache the rules forever in the app, per each account. Once cached, you don't need to pull them again (in the future, we will add periodic checks every 24 hours, but that's for another issue - not important yet)

# Working with the rules

### NO_PRV_CREATE

Disable creating of new private keys. Private keys can only be manually imported. 

When this flag is present, during setup, the only option that user will see is to import keys.

### NO_PRV_BACKUP

Disable all forms of private key backup. If creating keys is enabled, and user is creating a key, do not automatically back up the key.

### ENFORCE_ATTESTER_SUBMIT

Do not allow to skip errors during public key submission to attester during setup. Wait for the result from submission. If it is error, show the error with details, and offer a retry button. If user cannot successfully submit, the user cannot finish setup.

# How to test

I will probably have to set up some domains for you that will have special rules.

This mechanism does not work for people who log in with IMAP directly. It has to use OpenID Connect (oauth). So right now it will only work for Gmail accounts.

**Comment by tomholub** [comment]
If you are curious about id_token, look at flowcrypt browser extension -> flowcrypt settings -> additional settings -> experimental -> Login using OpenId Connect, where this login method is implemented.

You can look at the requests and responses in browser console to understand it.

**Comment by DenBond7** [comment]
@tomholub 
> you should already be receiving this if scopes include "openid" and "email"

Yes, you are right. I already have that scopes

![image](https://user-images.githubusercontent.com/2863246/67264628-55115280-f4b4-11e9-9987-986107f1da5f.png)

**Comment by DenBond7** [comment]
@tomholub 

To retrieve `id_token` I should know `Server Client ID`.  This should be a valid Web OAuth 2.0 Client ID obtained from https://console.developers.google.com/

Then I can request it by code below

```kotlin
fun generateGoogleSignInOptions(): GoogleSignInOptions {
      return GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
          .requestScopes(Scope(Constants.SCOPE_MAIL_GOOGLE_COM))
          .requestIdToken("YOUR_SERVER_CLIENT_ID")
          .requestEmail()
          .build()
    }
```

**Comment by tomholub** [comment]
Weird. Not needed in browser. Could you try to pass Android client ID?

**Comment by DenBond7** [comment]
From the chat

> You should make the app behave exactly the same on both versions. Consumer and enterprise versions should do exactly the same thing

>  But for now all stays the same between consumer and enterprise apps

**Comment by DenBond7** [comment]
@tomholub has found a bug with `NO_PRV_CREATE` rule

**Comment by tomholub** [comment]
After testing, I discovered some things to update:

1)  Security mistake. When I 1) first set up a regular account 2) click add account 3) authenticate an enterprise account, then these enterprise rules did not apply to the screen I see. I see a `CREATE A NEW KEY` option. This must be fixed
2) When `NO_PRV_CREATE` is present, please also hide `USE EXISTING KEYS` option, so that user has to either import key, or use another account (on both activities - when initially installing and also when adding another account)
3) When `NO_PRV_BACKUP` is present, please do not even try to look through backups during setup. If there is any backup, it will be ignored during setup (not sure if you already do this, haven't tested).

I saw this stack trace, maybe not relevant:
```
W/System.err: java.lang.IllegalArgumentException: Unknown color
W/System.err:     at android.graphics.Color.parseColor(Color.java:1400)
        at com.flowcrypt.email.ui.activity.base.BasePassPhraseManagerActivity.parseColor(BasePassPhraseManagerActivity.kt:312)
        at com.flowcrypt.email.ui.activity.base.BasePassPhraseManagerActivity.updateStrengthViews(BasePassPhraseManagerActivity.kt:286)
        at com.flowcrypt.email.ui.activity.base.BasePassPhraseManagerActivity.onChanged(BasePassPhraseManagerActivity.kt:224)
        at com.flowcrypt.email.ui.activity.base.BasePassPhraseManagerActivity.onChanged(BasePassPhraseManagerActivity.kt:55)
W/System.err:     at com.flowcrypt.email.jetpack.livedata.SingleLiveEvent$observe$1.onChanged(SingleLiveEvent.kt:57)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:149)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:307)
        at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
        at com.flowcrypt.email.jetpack.livedata.SingleLiveEvent.setValue(SingleLiveEvent.kt:65)
W/System.err:     at com.flowcrypt.email.api.retrofit.node.NodeRepository$Worker.onPostExecute(NodeRepository.kt:88)
        at com.flowcrypt.email.api.retrofit.node.NodeRepository$Worker.onPostExecute(NodeRepository.kt:57)
        at android.os.AsyncTask.finish(AsyncTask.java:695)
        at android.os.AsyncTask.-wrap1(Unknown Source:0)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6567)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

Otherwise it looks good. Thanks!

**Comment by tomholub** [comment]
Please also add tests for the `Add email account` screen, very important to get this right.

**Comment by tomholub** [comment]
> Please check a scenario: setup an account, then logout, then setup a new account(not already used). I want to know is it looks well for you
> Because after logout we still have already imported keys

Yes, it needs updating, in the next milestone. When I log out and log in again, and try to import my key again, it will tell me the key is already imported, and there is no way to proceed.

When importing key that is already imported during setup, should show toast "Key already imported, finishing setup.", then take me to inbox.
