### ISSUE TITLE
allow other email providers

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#75]
Under "Continue with Gmail" there should be "Other email provider". This will show a screen where they have to enter:
- email address
- password
- imap server address + port?
- smtp server address + port?

Later on, we will be guessing their server addresses and ports based on the email address. There will be a server API available for that. For now, everything has to be entered manually.

Even later, we will set up xoauth2 flow for popular mail services: eg yahoo and outlook.

**Comment by tomholub** [comment]
We will also have to update how we search for backups. 

The current solution does not work for some people. I got several reports from people that their backup is not recognized during setup and they had to copy their keys manually. 

After debugging it with them over the past week (I sent them a few test apks) it turns out that the IMAP Gmail search function does not return any emails for some people. Interestingly, using the exact same search query in Gmail UI or through Gmail API will work for them. 

This is of course hard to debug because we don't have access to the mailboxes where this happens. 

I think the problem will go away if we manually recreate the Gmail query using standard IMAP search functions, and will work regardless of email provider.

**Comment by tomholub** [comment]
We will also have to update how we search for backups. 

The current solution does not work for some people. I got several reports from people that their backup is not recognized during setup and they had to copy their keys manually. 

After debugging it with them over the past week (I sent them a few test apks) it turns out that the IMAP Gmail search function does not return any emails for some people. Interestingly, using the exact same search query in Gmail UI or through Gmail API will work for them. 

This is of course hard to debug because we don't have access to the mailboxes where this happens. 

I think the problem will go away if we manually recreate the Gmail query using standard IMAP search functions, and will work regardless of email provider.

**Comment by DenBond7** [comment]
> Later on, we will be guessing their server addresses and ports based on the email address. There will be a server API available for that. For now, everything has to be entered manually.

Do we support only the IMAP protocol?

**Comment by DenBond7** [comment]
For me. [IMAP Properties](https://javaee.github.io/javamail/docs/api//com/sun/mail/imap/package-summary.html)

**Comment by tomholub** [comment]
> Do we support only the IMAP protocol?

I think so, what else could we support? Direct Gmail API and similar? I feel that would be a lot of complexity. Let me know what you meant.

**Comment by DenBond7** [comment]
I meant that we will support only IMAP or maybe also POP3 too? I looked how
I can create an account in other applications. And there we can select
IMAP, POP3 and EXCHANGE options.

In my opinion it makes no sense to support the old POP3 protocol.

**Comment by tomholub** [comment]
You're right, we absolutely will not be supporting pop3

**Comment by DenBond7** [comment]
@tomholub  I finished this task.
Now you can test the app with different email providers using IMAP/ SMTP settings.

Also I want to tell next:

1. Some email providers doesn't have an ''Archive" folder

1. Other email providers doesn't save a cope of sent message in Sent folder automatically. I fixed it here #101 

1. Some email providers has the Spam folder with attribute \Spam (Gmail has attribute \Junk)

1. Gmail works very fast. Other providers sometimes work slow and I need to wait while a message will be sent or received.
