### ISSUE TITLE
generate uuid for enterprise users

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#750]
a part of #748 

First, one time per account, you need to generate uuid which is 40 characters long, containing only lowercase hex characters 0-9a-f. Example: 8d43af.................................93. Use secure random to generate these. You can think of uuid as an auto-generated password, which you create and store in the app. **It is sensitive, so store it securely**.

Correct email + uuid combination allows to access restricted API (similar to email+password).

**Comment by tomholub** [comment]
You can actually make a sha1 hash of any random bytes, and it will come out as this format

**Comment by tomholub** [comment]
Then you just get a hex print of the hash, and use that as uuid

**Comment by DenBond7** [comment]
> It is sensitive, so store it securely.

I use the same encryption logic as we use for saving an account password. So UUID will be encrypted via [AndroidKeyStore](https://developer.android.com/training/articles/keystore)

https://github.com/FlowCrypt/flowcrypt-android/blob/03842620f915820333c013003d8b7e9e59b1a080/FlowCrypt/src/main/java/com/flowcrypt/email/database/dao/source/AccountDaoSource.kt#L57
