### ISSUE TITLE
Add tests for domain rules

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#756]
it relates to #755 

- [x]  NO_PRV_CREATE
- [x]  NO_PRV_BACKUP
- [x]  ENFORCE_ATTESTER_SUBMIT

**Comment by DenBond7** [comment]
NO_PRV_BACKUP

1. Test **Backups** disabled

1. Test **Secutiry and Privacy --> Change pass phrase** disabled

**Comment by tomholub** [comment]
Change pass phrase is ok. But no backup should be performed.
