### ISSUE TITLE
pubkey is not submitted when setting up with imported key

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#767]
When importing a key from a file, it seems that the app does not even try to submit key to Attester. At least from the logs there is no mention of it. There should be a POST `initial/legacy_submit`.

**Comment by DenBond7** [comment]
@tomholub 
> it seems that the app does not even try to submit key to Attester

Yes, you are right. We don't have logic for that. We use `initial/legacy_submit` only when a user is creating a new key

I will add

**Comment by DenBond7** [comment]
@tomholub I need to clarify some things. If we are adding submitting an imported key (the pub version) should I use the same logic as we used for the key creation?

1. If the account rules contain `ENFORCE_ATTESTER_SUBMIT` rule, don't allow a user to continue if the operation failed

1. If the account rules do not contain `ENFORCE_ATTESTER_SUBMIT`, allow the user to continue if the operation failed

1.  `1.` and `2.` are true for `load from file` and `load from clipboard`

1.  What about `Settings -> Keys -> Import Private Key` when the user wants to add a new one key?

**Comment by tomholub** [comment]
>    If the account rules contain ENFORCE_ATTESTER_SUBMIT rule, don't allow a user to continue if the operation failed

correct

>    If the account rules do not contain ENFORCE_ATTESTER_SUBMIT, allow the user to continue if the operation failed

correct

>    1. and 2. are true for load from file and load from clipboard

correct

>    What about Settings -> Keys -> Import Private Key when the user wants to add a new one key?

Good question. Haven't thought about it. You can skip this one until I think about it more. For now I'm mainly concerned about using the right key during account setup.

**Comment by DenBond7** [comment]
> Good question. Haven't thought about it. You can skip this one until I think about it more. For now I'm mainly concerned about using the right key during account setup.

Got it. I think we will create a separate issue for that
