### ISSUE TITLE
option to submit a few pairs (pubkey/email) via initial/legacy_submit

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#772]
From the chat

> denbond7
> 4:39 PM - Yesterday
> Do we have an option to submit a few pairs (pubkey/email) to our server? Becasue I can import more than one key via 'import from file' option

> tomjh
> 4:42 PM - Yesterday
> Not for the same email address
> For now you can just submit the first key that matches the primary email address - submit it only for primary email address. If no key matches, submit the first key that was provided. Then later we will come up with a more proper mechanism how to handle this (please make an issue for me to define it).

**Comment by DenBond7** [comment]
#767

**Comment by tomholub** [comment]
I'm closing it, I think the current behavior is good enough.
