### ISSUE TITLE
display longer messages in a dialog

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#778]
It works, but the whole message does not get displayed in the toast.

I have asked this before, can't the toast have a dynamic height based on the text?

![Screenshot_20191119-093948](https://user-images.githubusercontent.com/6306961/69130635-bd9a2200-0aa8-11ea-8ccb-69b099121ea4.png)

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-android/issues/768#issuecomment-555396028_

**Comment by DenBond7** [comment]
@tomholub I've added changes. Please look at them. If all looks well, please close this issue.

**Comment by tomholub** [comment]
perfect, thanks
