### ISSUE TITLE
fix "message cannot be found" after trash -> reinbox

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#783]
1. reply to message
2. delete message
3. find deleted message
4. move it back to inbox 
5. open message in inbox
6. it will say message cannot be found and will disappear. Refreshing inbox will make it reappear, then clicking disappear again

**Comment by tomholub** [comment]
I cannot reproduce it now either. It was quite frustrating when it did happen, because I could not get the messages out of my inbox.

**Comment by DenBond7** [comment]
deprecated
