### ISSUE TITLE
reposition tags in ACRA reports

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#788]
Can we reposition a tag in ACRA reports? Usually, I watch only SUMMARY and STACK_TRACE. But currently, STACK_TRACE in the middle of a message. As for me, it would be better to have SUMMARY and STACK_TRACE one after one.

@tomholub  That's not urgent. If it is difficult, please move it to later

**Comment by tomholub** [comment]
done

**Comment by tomholub** [comment]
![image](https://user-images.githubusercontent.com/6306961/74525830-fae04580-4f19-11ea-944d-6b0663d55fa2.png)

**Comment by DenBond7** [comment]
Thanks a lot! It'll help me
