### ISSUE TITLE
Switch to use flowcrypt.com for ACRA reports

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#789]
it relates to #788

**Comment by DenBond7** [comment]
@tomholub that's not urgent too

**Comment by tomholub** [comment]
It seems to be already sending to `flowcrypt.com`? (closing)

```
@ReportsCrashes(reportSenderFactoryClasses = [CustomReportSenderFactory::class],
    formUri = "https://flowcrypt.com/api/help/acra", customReportContent = [
```

**Comment by DenBond7** [comment]
@tomholub I meant to change my email address to den@flowcrypt.com (remove my Gmail account from recipients)

**Comment by tomholub** [comment]
Ah, that's on the backend

**Comment by tomholub** [comment]
updated, will deploy today
