### ISSUE TITLE
change recipients when replying to a message

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#79]
Clicking on the recipients in reply screen should turn them into chips, and that should allow me to change them

**Comment by DenBond7** [comment]
https://github.com/FlowCrypt/flowcrypt-android/commit/a6925d94401dcce3b44a021fd1f8fdb1205271e6
https://github.com/FlowCrypt/flowcrypt-android/commit/65a65c545865a52da548949e0782ecbf438aea43
https://github.com/FlowCrypt/flowcrypt-android/commit/820db3a42a8f92a247afca4fd3d462380c078cb3
https://github.com/FlowCrypt/flowcrypt-android/commit/bdcb6aa757a45c1b06ea777354bb3ac920ce9a8b
https://github.com/FlowCrypt/flowcrypt-android/commit/bb2b40eff597631708a4e6044ac5a94b70ed457f
https://github.com/FlowCrypt/flowcrypt-android/commit/06d32864fb345b5b014b939d859706308e1c7de8
