### ISSUE TITLE
Update copyright

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#794]
Update © 2016-2019 to © 2016-2020

**Comment by tomholub** [comment]
Also make sure it says `FlowCrypt a. s.`, not `FlowCrypt Limited`

**Comment by DenBond7** [comment]
For me. Need to check this one `© 2016-2018 FlowCrypt Limited. Limitations apply. Contact human@flowcrypt.com`. Some files contain this copyright.

**Comment by tomholub** [comment]
Please change it to `© 2016 - present FlowCrypt a.s. Limitations apply. Contact human@flowcrypt.com`

That way we don't have to change it every year
