### ISSUE TITLE
test yahoo account and find out which settings

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#796]
Lately several people were writing me that they cannot connect to a yahoo account.

I think they are probably inputting the setup wrong, but I want to double check. Could you please try a yahoo account, and when you succeed, please share which imap/smtp settings were used.

**Comment by DenBond7** [comment]
@tomholub 
1) All works well with settings from here https://github.com/FlowCrypt/flowcrypt-android/wiki/Email-providers-IMAP-SMTP-settings

![device-2020-01-17-124208](https://user-images.githubusercontent.com/2863246/72606254-ed3d9d00-3926-11ea-81de-cb2ef2fadd43.png)
![device-2020-01-17-122730](https://user-images.githubusercontent.com/2863246/72606249-eb73d980-3926-11ea-932b-af8cdd1fe9de.png)

2) As a password, I use an approach from here https://help.yahoo.com/kb/create-password-sln15241.html

3) Maybe for better user experience, we have to use https://developer.yahoo.com/oauth2/guide/

**Comment by tomholub** [comment]
Thank you. I'll close this for now. But eventually we should add yahoo oauth2

But first, microsoft. I would like to do that sometime this year.

**Comment by DenBond7** [comment]
#798
