### ISSUE TITLE
bug/crash on reply

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#805]
> Hello,
> Suddenly I'm having an issue responding to a contact that never happened before. When I hit the reply button, the app reboots, back to the inbox! I never had this issue before with this contact and it only happens with this contact.
> Your help is appreciated.

**Comment by tomholub** [comment]
@DenBond7 Have you see any related ACRA reports?

**Comment by tomholub** [comment]
Maybe this is on 0.9.2, I'll make sure user has latest app first

**Comment by DenBond7** [comment]
@tomholub 
> Have you see any related ACRA reports?

I've found a few which maybe relate to this issue. But I need some time to investigate them.

By the way, one of them from 0.9.2 version.
I notify you when I'll have some results.

**Comment by DenBond7** [comment]
@tomholub I think #808 is a reason for this issue. The user was trying to make a reply to a big message. Currently, we don't support that. I've added some changes which help prevent crashing the app. Also, I've created #809 and milestone for large messages.

Currently, the reply text will include only clipped text if it bigger than 50000 symbols

You can reproduce a bug by opening a message with a subject [Long encrypted msg ](https://mail.google.com/mail/u/6/#search/Long+encrypted+msg) (compatibility account)

**Comment by tomholub** [comment]
ok. Thanks
