### ISSUE TITLE
consider LiquidCore instead of Node

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#811]
I will experiment with using LiquidCore instead of full-fledged Nodejs instance.

On iOS we use something very similar to that, and it works well + is very light weight.

https://github.com/LiquidPlayer/LiquidCore/wiki/LiquidCore-as-a-Raw-JavaScript-engine-for-Android-(v.-0.7.0-)

Another advantage will be that we would not need to create RSA certs when app starts, and we would not need to communicate over https and so on. Quite similar to what we have done before with J2V8, but hopefully it will work better.

This will almost certainly resolve #753

**Comment by tomholub** [comment]
Also it will reduce app footprint, no longer need to include node binaries for all platforms.

**Comment by DenBond7** [comment]
@tomholub Very interesting... need to investigate that. Basically, the current realization works much better than j2v8. But of course, we have many places which we can improve.

**Comment by tomholub** [comment]
They designed it to be very similar to JavaScriptCore which we use on iOS:

https://github.com/FlowCrypt/flowcrypt-ios/blob/master/FlowCrypt/Core/Core.swift#L84

**Comment by tomholub** [comment]
superseded by #976
