### ISSUE TITLE
consider sending pgp/mime encrypted data straight to node

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#818]
![image](https://user-images.githubusercontent.com/6306961/73574108-c45ff080-446c-11ea-9e9b-c3d62bdda1b7.png)

Plus also differentiate by size. You only have to do it if the pgp-encrypted part is > 1mb.

Also, once you receive the ascii-armored message as bytes, it would be great to de-armor it in Kotlin to get back raw bytes:

```java
import org.bouncycastle.bcpg.ArmoredInputStream

    public static byte[] dearmor( byte[] data ) {
            ArmoredInputStream armoredInput = new ArmoredInputStream( new ByteArrayInputStream( data ) );
            ByteArrayOutputStream binaryOutput = new ByteArrayOutputStream();
            while ((ch = armoredInput.read()) >= 0) {
                binaryOutput.write((byte) ch);
            }
            return binaryOutput.toByteArray();
    }
```
With that, we would be saving about 30 seconds on a 7-mb attachment.

I will prepare a method to send this to.

**Comment by tomholub** [comment]
Determine a file as pgp/mime part if ALL are true:
 - over 1 mb
 - filename equals one of: ['message', 'msg.asc', 'message.asc', 'encrypted.asc', 'encrypted.eml.pgp', 'Message.pgp', ''] // including the empty string
 - content-type one of: ["application/octet-stream", "application/pgp-encrypted"]
 - email body has 0 bytes, or there is no email body

That should be enough - no need to evaluate the contents.

**Comment by tomholub** [comment]
No need to prepare a new endpoint, I already have it: send it to `parseDecryptMsg` as usual, just add an `isEmail=false` json property when you give it the encrypted bytes directly like this.

**Comment by tomholub** [comment]
Are you checking for all of the conditions as above? I didn't see a check for > 1mb size.

**Comment by DenBond7** [comment]
> Are you checking for all of the conditions as above? I didn't see a check for > 1mb size.

Yes, I am.

https://github.com/FlowCrypt/flowcrypt-android/blob/5f750652ea99c442916959259f41c50db8891ea4/FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/DecryptMessageViewModel.kt#L79

**Comment by tomholub** [comment]
I overlooked it, thanks!
