### ISSUE TITLE
attachment download manager

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#82]
Need to create an attachment download manager which will be using the IMAP connection for download email attachments. This manager will be working separately sync mail service and must have the standard download manager behavior.

Requirements:

1. Can download simultaneously 3 attachments. The other attachments must be added to the queue.
2. All loading attachments must be visible in the status bar. For example <img width="388" alt="download-manager" src="https://user-images.githubusercontent.com/2863246/29276104-2b8889ba-8116-11e7-8b28-ff7760e78094.png">
3. The user can stop loading an attachment at any time.
4. Need to show a progress (in %).
5. All attachments will be download to the Download folder. Later we can add settings to enable user change the download destination folder.

Subtasks:

- [x] Runtime permission "android.permission.WRITE_EXTERNAL_STORAGE"
- [x] A progress notification
- [x] Remove a file if a loading was cancelled
- [x] Open a file if user will click on the downloaded attachment.
- [x] speed up download.

Links
- https://developer.android.com/training/basics/data-storage/files.html
- https://material.io/guidelines/patterns/notifications.html#notifications-behavior
- https://developer.android.com/training/secure-file-sharing/index.html
- https://inthecheesefactory.com/blog/how-to-share-access-to-file-with-fileprovider-on-android-nougat/en

**Comment by tomholub** [comment]
Please note that for encrypted attachments, we will have to download them,
then decrypt them on the device, then save them to the device. Just making
sure that the download manager can support some operations on the file when
download is done but before it's saved to storage.  (To be done later, just
make sure it's possible)

**Comment by DenBond7** [comment]
> Just making
> sure that the download manager can support some operations on the file when
> download is done but before it's saved to storage. 

Can you help me understand how this process will happen? I mean decryption. Maybe you have some links where I can read about it. If you can tell me briefly about the decryption process - how it happens, whether I need to work with the whole file (a character array) or I can work with the buffer. This is an important question for the correct design of the download manager.

As a rule, to work with files in Java should use streams(Input/output) that work with the buffer. At the same time, we get a lot of profits - saving memory, the ability to show the progress of the process itself, etc.

**Comment by tomholub** [comment]
At the moment, the whole file is needed. In the future, we may implement
decrypting a stream while it's being downloaded, but I don't have that
implemented in JavaScript yet.

Maximum file size should be about 25-35mb, but typically 1-3 MB.

**Comment by DenBond7** [comment]
For now, I completed this task.

- I think we can already close this task. For decryption will be better create a new one.

- We will also need to test the download speed of attachments. Because of the specifics of working with IMAP there may be some difficulties. I tried to make an optimal buffer for loading. But in principle, we can make the buffer even more. But then it's better to do no more than 2 simultaneous downloads. Since the larger the buffer, the greater the probability of getting an OutOfMemory error.

**Comment by tomholub** [comment]
That's good, let's start with a single IMAP connection to deal with
downloads, because many IMAP servers have a limit on how many IMAP
connections can exist per account. I forgot how many Gmail allows, maybe 5
or so? That means using more than 2 connections for one device may be too
many.

**Comment by DenBond7** [comment]
For now, I will be using maximum 5 connection:

- 1 connection for communication with server (fetch labels, fetch messages etc.)

- 3 connection for download attachments

- 1 connection for idle incoming messages (not working at the moment)

> That means using more than 2 connections for one device may be too
> many.

It's not good. Because I need minimum 3 connections.

**Comment by tomholub** [comment]
Just read somewhere online that it's 15 for Gmail. Let's leave it as is and
observe if users complain
