### ISSUE TITLE
Fix pull-to-refresh functionality after switching between accounts

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#822]
![image](https://user-images.githubusercontent.com/2863246/74018603-e1ca1880-499e-11ea-9e61-ab9871577eb6.png)

**Comment by tomholub** [comment]
@DenBond7 When do you think we could do an update that includes this issue? It looks quite annoying / broken when this happens.

**Comment by DenBond7** [comment]
@tomholub  To my mind I need about 2 days to complete all issues for the current milestone

**Comment by tomholub** [comment]
Understood, thanks
