### ISSUE TITLE
smtp/imap check can fail without showing error message

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#853]
User:

> Hello,
> I'm having trouble setting up my email account in FlowCrypt for Android. My setup is a little special in terms that I'm using a private mail collector on a self-hosted server (imap) and the smtp server of my email provider.
> The mail collector listens on a special port using SSL.
> Even though I'm pretty sure that all the data provided in FlowCrypt's account setup is correct (I checked with the setup of another mail application), FlowCrypt just ends up "Checking email settings" and brings me back to the setup dialog.
> The network connection is generally working.
> Not sure what I'm doing wrong here. Any suggestions?
> Thanks for your help,

Me:

> thanks for reporting. Does it not show an error message or toast as it brings you back to the setup page?

User:

> It did, when I mistyped the imap server's name at the beginning, but once I corrected that, it just briefly shows the "Checking email settings" message, but nothing else...

Me:

> The first problem is that you should always see a clear error message.
> We'll get that corrected. After you update, at least we'll know what's the real issue, and then fix that too.

Conversation https://mail.google.com/mail/u/8/#inbox/FMfcgxwHMPfZTwGcmSDlLSwfWttjWbKh

**Comment by DenBond7** [comment]
@tomholub I've added changes. Now it looks like this one

![image](https://user-images.githubusercontent.com/2863246/76681628-bff72d80-65fd-11ea-8c56-3c96231aff60.png)

> it just briefly shows the "Checking email settings" message, but nothing else...

It means that the app is still trying to connect. The app didn't have a timeout for such an action. But now it has 10 seconds timeout for checking IMAP or SMTP settings.

https://github.com/FlowCrypt/flowcrypt-android/blob/987b249fc9cb9d1ff5f532881b905219e9972818/FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/CheckEmailSettingsViewModel.kt#L47

**Comment by tomholub** [comment]
Much better, thanks. Always good to show errors to the user.

**Comment by Schwefelholz** [comment]
Is there already a beta app I could check my case with our do I need to wait for a new version on Google Play?

**Comment by DenBond7** [comment]
Hello @Schwefelholz. We are going release a new build in a few days. I'll notify you about that.

**Comment by tomholub** [comment]
We'll be releasing it today, you should get an update soon.
