### ISSUE TITLE
allow use of user-defined system SSL certs

### ISSUE THREAD

**Issue by Schwefelholz** [FlowCrypt/flowcrypt-android#857]
I'm having trouble setting up my email account in FlowCrypt for Android. My setup is a little special in terms that I'm using a private mail collector on a self-hosted server (imap) and the smtp server of my email provider.
The imap service is using an SSL certificate issued by my own PKI. Actually, the PKI's root and intermediate certificates do show up in the user-specific certificate store in Android. I'm unfortunately not sure how they're called in English, my Android is in German, but as a matter of fact, Chrome is accepting certificates issued by the PKI on this Android device which I'm using on several internal web UI's.
FlowCrypt, however, complains about the certificate used on my imap service:

Info
IMAP: java.security.cert.CertPathValidationException: Trust anchor for certification path not found.

**Comment by tomholub** [comment]
This should be something we can address - there's probably some settings in that we can switch to rely on the locally installed truststore that should include your custom certs.

**Comment by tomholub** [comment]
I'm moving it to a milestone that is follows the upcoming one, to be released in approximately one month.

**Comment by tomholub** [comment]
Meaning, there will be one version upcoming (0.9.9) that will not yet have the fix, and your fix will likely be included in version 1.0.0.

**Comment by Schwefelholz** [comment]
Meanwhile, FlowCrypt is at version 1.0.3, but it still does not accept
private certificates. Any idea if/when this will be implemented?

**Comment by tomholub** [comment]
I'm sorry, we got busy with other things that needed to get done first. At this point I cannot promise a specific date. If there is still no action by August, feel free to ping me again.

**Comment by tomholub** [comment]
We still hope to look into this but we are still busy with other fixes until about the end of this year - sorry for the delay.

**Comment by DenBond7** [comment]
for me https://stackoverflow.com/questions/6825226/trust-anchor-not-found-for-android-ssl-connection

**Comment by DenBond7** [comment]
It seems we are talking about the following
https://developer.android.com/training/articles/security-config#CustomTrust
https://developer.android.com/training/articles/security-config#TrustingAdditionalCas

**Comment by DenBond7** [comment]
@tomholub I need a bit of advice. Please look at https://android-developers.googleblog.com/2016/07/changes-to-trusted-certificate.html and propose what option we would like to support.

We can support all user-defined CA. But I'm worrying it can be a little dangerous for users.

**Comment by tomholub** [comment]
It's ok to trust all user-provided certificates that they set in Android Settings. It's the user device, if they put wrong certificates there, that's their problem. Not much we can do about that.
