### ISSUE TITLE
unknown error after starting the app (freshly installed app)

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#866]
please never just show an "unknown error" or a similar meaningless message. You can at least show the message and class name of the root cause exception.

![image](https://user-images.githubusercontent.com/6306961/77820111-c2668680-70d7-11ea-986e-e96084fa6715.png)

**Comment by DenBond7** [comment]
@tomholub 

It's already fixed via https://github.com/FlowCrypt/flowcrypt-android/commit/8deb483ce96663f05a547b22728ee3a93a5ddfbf. A user just needs to update the app. Only users with the freshly installed app were affected.

> Please never just show an "unknown error" 

I'll look through the code and fix other places where we have such a hint

**Comment by DenBond7** [comment]
I'm closing this issue. I've created a separate issue for "unknown error"
