### ISSUE TITLE
ignore "registered" json value from "account/login" endpoint

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#868]
I want to deprecate it, let's start ignoring it.

It always returns true anyway.

**Comment by tomholub** [comment]
This is a tiny issue where we want to stop expecting a property called `registered` that we currently return from backend API server endpoint at `account/login`. Just need to remove it from response models so that eventually I can stop returning it from API itself.

I'm assigning to @IvanPizhenko since it's a tiny enough issue that he may not need much context about the Android app in general.

**Comment by IvanPizhenko** [comment]
Hmm. What I see now is that it reads and writes it from "parcel". Should this remain as is or we can modify how LoginResponse is written and read to/from parcel by excluding this field?

**Comment by DenBond7** [comment]
close via https://github.com/FlowCrypt/flowcrypt-android/pull/1102

**Comment by tomholub** [comment]
> Hmm. What I see now is that it reads and writes it from "parcel". Should this remain as is or we can modify how LoginResponse is written and read to/from parcel by excluding this field? Will this break compatibility with existing server or something?

@DenBond7 is there generally any risk editing parcels? do they get stored in the app in between version updates?

**Comment by DenBond7** [comment]
@tomholub 
> is there generally any risk editing parcels?

Of course. If you do it wrongly, you will get a runtime error.

> do they get stored in the app in between version updates?

No, it is used only at runtime.

Anyway, don't worry about that. We have JUnit test [ParcelableTest](https://github.com/FlowCrypt/flowcrypt-android/blob/master/FlowCrypt/src/test/java/com/flowcrypt/email/ParcelableTest.kt) that helps us to test all `Parcelable` implementation over the app. If some class that implements Parcelable will be broken we will know about that before a new release.
