### ISSUE TITLE
Do not show css styles in message body

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#87]
Some email messages seem to display css styles on the beginning of the email. Is there a setting in the HTML-text convertor to omit that?

**Comment by tomholub** [comment]
![screenshot_20170815-211420](https://user-images.githubusercontent.com/6306961/29491711-9af61690-8518-11e7-8b66-73f7f1e7f7f7.png)

**Comment by DenBond7** [comment]
I debugged this situation. And I found that sometimes I received MessageBlock.TYPE_TEXT with CSS style.

As I know CryptUp doesn't support the HTML message. So, I prepared next logic: if the message has HTML body I display this HTML in a WebView. If the message contains PGP elements I display them as before.

**Comment by tomholub** [comment]
That's good. We just need to make 100% sure that JavaScript is always
disabled in these web views.
