### ISSUE TITLE
Publish on F-Droid

### ISSUE THREAD

**Issue by supermamie** [FlowCrypt/flowcrypt-android#881]
I found issue #348 but as it is 2 years old and closed, I open a new one.

I am leaving all Google services and my phone is "cleaned" (no gapps in it, even Google Play Store or Google Play services), only F-Droid + microg. Gmail is one the last service I use (hard to change address).

Is it possible to publish Flowcrypt on F-Droid ?

Another valuable thing with F-Droid, as they build the app, this is a proof that the builded app is exactly build from the published source code.

**Comment by tomholub** [comment]
Eventually we will definitely have an F-Droid listing. I think it fits well with the kind of work we do. We just don't have the manpower to focus on it right now, even if it may look like not much work.

But maybe we could start offering direct apk downloads. Then folks like you can still download the app and install it manually. As for F-Droid itself, probably in 2021.

**Comment by supermamie** [comment]
There are multiple ways to do this, depending on how easy is the app to build :

1. Easy to build / easy to do : Open an issue on https://gitlab.com/fdroid/rfp/-/issues?scope=all&utf8=%E2%9C%93&state=opened and let them do it
2. Easy to build / longer to do : Submit the conf to build the app on their repository : https://gitlab.com/fdroid/fdroiddata/blob/master/CONTRIBUTING.md
3. Hard to build / even longer to do : Create your own F-Droid repo (path taken by BitWarden for example), details here : https://f-droid.org/en/docs/Setup_an_F-Droid_App_Repo/

APK download is a first step, take your time. As FlowCrypt needs a GMail account, I am not sure that this issue is very important for many people.

Thanks for your answer.

**Comment by tomholub** [comment]
Thanks for the writeup.

FlowCrypt on Android can work with any email provider that supports SMTP.
--
Tom James Holub <http://holub.me/>

**Comment by supermamie** [comment]
Oh, then it can be more important, there are few mail clients supporting encryption on F-Droid : K9-Mail (the one I currently use) and FairEmail are the only 2 that I know.

**Comment by gardenappl** [comment]
The main problem is that FlowCrypt [seems to rely on Google Play Services](https://github.com/FlowCrypt/flowcrypt-android/blob/1f888e1333f89fc291efc51a37079e638ddb1eb1/FlowCrypt/build.gradle#L378).

F-Droid requires that every app and every dependency is 100% open source. If you're going to release it on F-Droid, you might need a separate build flavor which removes any features like "Continue with Gmail".

**Comment by tomholub** [comment]
Actually, it's worse than that - FlowCrypt Android App is in fact not open source. We make sources publicly available but it's still proprietary software. With that, I think I'll have to close this :disappointed: 

If the situation changes and F-Droid starts accepting source-available apps that are not open source, we'll be happy to do the work to create a separate build without Google services.
