### ISSUE TITLE
err 400 during attester submit not properly rendered?

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#899]
> Jun 13 14:16:48 de3-leader-a flowcrypt-attester-api.err: s-2xx-200 POST /attester/initial/legacy_submit | {"email": "tmp.cure53@org-rules-test.flowcrypt.com", "pubkey": ":pubkey:"} => {"saved": "False", "error": {"code": "400", "message": "Could not find LDAP pubkey on a LDAP-only domain f:::", "internal": "None"}} 

This would be good to have a test for as well, such errors can happen and are meaningful for the user to see.

**Comment by tomholub** [comment]
Don't necessarily have to get tone in 1.0.5 but if it's easy, would be good to include. Otherwise it should be the first thing in 1.0.6.

**Comment by DenBond7** [comment]
for me
![image](https://user-images.githubusercontent.com/2863246/87158440-6ca19d00-c2c8-11ea-9193-61fe890a6cdf.png)
