### ISSUE TITLE
Add a restriction to allow import public keys up to 256kb

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#902]
![image](https://user-images.githubusercontent.com/2863246/84737918-93aecc80-afb1-11ea-983e-e3a07a9b197e.png)
![image](https://user-images.githubusercontent.com/2863246/84737945-a0332500-afb1-11ea-83f6-fb9825673849.png)

**Comment by DenBond7** [comment]
@tomholub For now we can support only keys up to 256kb. To support bigger keys I need to change an approach of using pub keys over the whole app, which will not be fast. I've added a restriction to allow the import of keys up to 256kb. I'm closing this issue and will create another one for pub keys up to 1Mb for later

**Comment by tomholub** [comment]
Ok. Supporting 1mb is not urgent. It's ok to do it next year, for example.
