### ISSUE TITLE
imap/smtp action queue

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#91]
the following actions should be queued instead of immediately done:
 - sending email
 - deleting + archiving + back to inbox

This will speed up the experience considerably.

**Comment by tomholub** [comment]
- refreshing mail folders periodically

**Comment by tomholub** [comment]
We can probably move this out of this milestone, let me know if you agree

**Comment by DenBond7** [comment]
I've moved

**Comment by DenBond7** [comment]
> sending email

@tomholub I was thinking about that task. And I have one interesting question. If we'll use a background queue for sending messages (like Gmail does that) after a user clicks the send button we'll show a notification like "Sending the message" and immediately show a previous screen. At that moment I'll create a new task for a queue which includes information about the message. If we use a standard (not encrypted) option all is clear. But what to do if we use an encrypted option? Do I need to encrypt all content (include attachments) before I create such task?

**Comment by tomholub** [comment]
Yes, I would definitely encrypt the message into a MIME format before you put it into the queue.

That makes is simpler - you just pass name of action to the queue (send) and one variable (the MIME string or buffer)

**Comment by tomholub** [comment]
* encrypt the message, then encode as MIME, then put to queue

**Comment by DenBond7** [comment]
Ok, got it

**Comment by DenBond7** [comment]
for me
- [ ] need to test preparing an encrypted message after reboot (test URI permissions)
- [ ] need to test sending a message after reboot (test URI permissions)

**Comment by DenBond7** [comment]
I've created new separate issues for tasks which I think can be done later. We can close the current issue.

**Comment by tomholub** [comment]
@DenBond7 it works well and the experience is much better now.

I will be changing the toast from `The message will be sent soon` to just `Sending..`

Although `The message will be sent soon` is technically correct from code perspective, it may confuse the user:
 - Why will it be sent soon?
 - Why not now?
 - Where is my message now if it wasn't sent yet?
 - How soon will it be sent? Seconds, minutes, hours?

Since the sending should be more or less instantaneous most of the time, I think it's more appropriate to say `Sending`.

Also changed `No connection. The message will be sent later` to `Offline. The message will be sent later`. I think both are very clear, but the second is a bit shorter (got inspired by the Gmail app)

**Comment by DenBond7** [comment]
> technically correct from code perspective

You are right. I've used that string because the app needs a few seconds to create a message and add it to a queue after a user clicks on the `Send `button (You can test it in the `Outbox folder --> Add a new message(float button)`).  But after your examples of questions, I see that my variant really can confuse the users.

**Comment by tomholub** [comment]
I was posting the explanation so that when I change something, you can understand why. That way, over time, you may be able to more precisely guess what kind of language I like for the UI
