### ISSUE TITLE
Update Node to the latest version

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#915]
https://github.com/janeasystems/nodejs-mobile/releases/

**Comment by DenBond7** [comment]
Currently, the last is v0.3.1

**Comment by DenBond7** [comment]
@tomholub I've tried to use the latest version, but it seems something was changed from version 3.0.0 and I can't just replace old files with new. Currently, we have 0.2.0, and updating to 0.2.2 works well. I've checked 0.2.2, 0.3.0, and 0.3.1 on the library sample project and all those versions work well. But in Flowcrypt Node-mobile-0.3.1 doesn't start. I see the following in logs

![image](https://user-images.githubusercontent.com/2863246/87222455-6bca4300-c37c-11ea-8279-2ef01f7278d2.png)

**Comment by tomholub** [comment]
Got it. For now we'll have to stick to the latest version that works. I think we will try to switch later everything to LiquidCore later https://github.com/FlowCrypt/flowcrypt-android/issues/811 so for upgrading node, we'll only do the low-effort upgrades until we know if LiquidCore is viable.

**Comment by DenBond7** [comment]
![image](https://user-images.githubusercontent.com/2863246/87408262-e50ba500-c5cb-11ea-962e-0f57ecf915ab.png)
