### ISSUE TITLE
Simplify the setup process of adding a new account

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#918]
To add a new account manually we have a screen where a user can fill all data like IMAP and SMTP settings. But this screen is a little complicated for most users and we should improve this screen. Usually, we can guess those settings from the domain name. For example for account `example@mydomain.com` usually we have `imap@mydomain.com` and `smtp@mydomain.com`.

**Comment by tomholub** [comment]
That's right. Talk to @Kharchevskyi who has done this on iOS. We could probably over time also have a service on the backend that will help prefill those fields.
