### ISSUE TITLE
loading message gets stuck when message moved

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#92]
Scenario:
 - open app and let inbox load
 - go to Gmail app and archive a message. Wait some time to make sure the message is archived (gmail is sometimes slow to process queued actions)
 - go back to FlowCrypt and click to open that message
It will just stay stucked on the loader

**Comment by tomholub** [comment]
Similar feedback from a tester:
```
Feedback: 
Error messages are programmer oriented. For example, received "Attempt to invoke virtual method Boolean javax.mail.Me..."   RETRY?      when trying to archive an already archived entry.  These should be appropriate user facing messages with a transmittable error log or id key or similar.... (otherwise, it adds to an impression of lack of polish)
Subsequent refresh in the inbox did not update the message as archived.

Same thing occurs when trying to open an already deleted email (but with different message for void javax.mail.SetFlag(javax.mai...).
```

Let's test these scenarios and handle them gracefully (with user notification when appropriate):
 - archiving already archived email
 - opening already archived email
 - deleting already deleted email
 - opening already deleted email

**Comment by tomholub** [comment]
ref https://mail.google.com/mail/u/1/#inbox/15f0ef486d25d3de

**Comment by DenBond7** [comment]
> Let's test these scenarios and handle them gracefully (with user notification when appropriate):
> 
>  archiving already archived email
>  opening already archived email
>  deleting already deleted email
>  opening already deleted email

All these cases mean that the email was moved to another folder. And in this case, I will show the toast "This email doesn\'t available in this folder", finish the current activity and back.

**Comment by tomholub** [comment]
Ok, though the language should be "This email isn't available in this folder". Actually, even better, "Message not found, it may have been moved to another folder."

In the future, we should try to handle the error better. For example, if I want to archive an email and it was meanwhile archived by someone, it should just proceed silently because the intended action is already done. And also try to locate the email in the new folder and refresh the screen to show me new options based on where the email is now.

**Comment by DenBond7** [comment]
> In the future, we should try to handle the error better. For example, if I want to archive an email and it was meanwhile archived by someone, it should just proceed silently because the intended action is already done.

I think many algorithms will be changed after the issue #91 will be completed.
