### ISSUE TITLE
Add an ability to remove a private key permanently

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#920]
We have the following feedback from a user

> Really good stuff, but why app still remember password to the key when I am logging out and login again. Is there any chance to erase any data stored in flowcrypt?

**Comment by tomholub** [comment]
I think they are actually referring to making the phone not remember pass phrase, issue #372

**Comment by DenBond7** [comment]
@tomholub maybe... But maybe the user told us that after logout we still keep private keys in the app. Because it sounds logical to remove all imported data (sensitive) when a user does logout. For example, I've tried to use the app with my test keys, I see that I can use the app with my main keys( with my main account), how I can remove keys which I'm not going to use? Currently, I have to reinstall the app.

**Comment by tomholub** [comment]
True. There are maybe 4 things to think about:

1) option to not remember pass phrases (for later)
2) wiping all pass phrases when logging out (for later)
3) option to also remove keys when logging out (you could give the user an alert with two options, when logging out - keep keys or wipe keys)
4) a way to remove private keys manually from the list (but there should still be at least one key available for each email account, so if I want to remove one key, I should have another one already imported for that account - I think?)

**Comment by DenBond7** [comment]
@tomholub 
Agree. I think for the current issue we can leave 3 and 4. Then 1 and 2 will be for separate issues.
