### ISSUE TITLE
Improve private key management - associate private key with email account

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#923]
![image](https://user-images.githubusercontent.com/2863246/88390944-e5712080-cdc1-11ea-978b-1f52b928b85f.png)

**Comment by DenBond7** [comment]
- [ ] check setup the app when no accounts exist (adding keys to the local database)

- [ ] check adding one more account (adding keys to the local database)

- [ ] check to import a new private key

**Comment by DenBond7** [comment]
@tomholub 
I'm thinking about this one https://github.com/FlowCrypt/flowcrypt-android/issues/269. As for me can drop `user_id_emails_and_keys` table. When I will close this issue we will have much clearer logic

![image](https://user-images.githubusercontent.com/2863246/96991092-9f4a6b00-1530-11eb-9f98-ec0b9ba35c96.png)

**Comment by DenBond7** [comment]
I guess I jumped to conclusions :(. That table is still needed for not primary uids.

**Comment by tomholub** [comment]
I think so - you may still need them for secondary ids. Since you are putting secondary ids there, you might as well put the primary there too? That may simplify choosing logic (maybe - not sure).
