### ISSUE TITLE
Add an ability to add an alias to a private key

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#928]
We should add an option to update a key to add the alias. It's very important for Gmail users.

ref https://mail.google.com/mail/u/1/#inbox/FMfcgxwJXCLhzXcFGFSWrJSVFHMwNhXz

**Comment by tomholub** [comment]
I will need to write some functionality for this

**Comment by tomholub** [comment]
superseded by #976 and https://github.com/pgpainless/pgpainless/issues/14
