### ISSUE TITLE
crash after clicking Settings -> Keys

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#93]
There should be a crash report from Tobias. Let me know if you received one.

**Comment by tomholub** [comment]
for my reference  https://mail.google.com/mail/u/1/#inbox/15deeecf5cdbac1e

**Comment by DenBond7** [comment]
Do you have an error stack trace?

**Comment by tomholub** [comment]
The user said that he reported it though the debug email. See it you can
find any, if not, I can ask him to crash the app and send again.

**Comment by DenBond7** [comment]
I don't have an unknown crash report in my Gmail inbox. Please ask him to send this report again.

**Comment by tomholub** [comment]
I'll check with him. Moving it to version 10

**Comment by DenBond7** [comment]
@tomholub Is this issue still relevant?

**Comment by tomholub** [comment]
@DenBond7 haven't heard back, I'm assuming it's ok now. Closing
