### ISSUE TITLE
Add an ability to replace pubkey of the given account (locally)

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#931]
We can have the following situation.

1. A user can import a PGP contact from a different source(file, clipboard). For example, he imports a pubkey with primary email `primary@example.com`. But this key can contain one more user id, for example, `secondary@example.com`.

1. After that, the user thinks he has a pub key for `secondary@example.com`, goes to the main screen -> click on "+"-> create a new message -> type `secondary@example.com`. Then the app fetches an available pubkey for `secondary@example.com` from Attester and adds this contact with the given pubkey to the local database.

1. Now the user has `secondary@example.com` with pubkey from attester. But the Attester pubkey not equal to pubkey for `primary@example.com`. And the for now the user can't change a pubkey (locally) for the existed contact.

We should improve that.

**Comment by hpmax** [comment]
A few potential solutions:

1) If user attempts to send mail to secondary@example.com, Flowcrypt should find any available key locally that works, and only if not available (or expired), contact Attester.

2) If multiple keys exist, the user should be allowed to select the public key to be used).

3) User should be able to disable/enable particular keys.

4) User should be asked be prompted before getting a key from Attester.

5) User should be able to manually select the key.

6) User should be able to change the emails associated with a key.

Personally, I like the idea of being able enable/disable keys and then have Flowcrypt prompt to select among enabled keys if multiple enabled keys exist.  I think this gives the most flexibility.  This would not only fix the current problem, but also address the issue of what if one person has multiple public keys on the same email address (for example, potentially a shared email address among multiple people)  A "nickname" or "name" field could be added to help distinguish between multiple keys with the same or similar email addresses.  Lastly, I think it would be helpful to be able to manually select (or override) a key if no key is on file (for example, a long time contact gets a new email address which isn't present in the current key).

**Comment by tomholub** [comment]
Thank you for your input @hpmax . For this issue, the easiest for us will be to give you an option to find secondary@example.com in Settings -> Contacts and replace linked public key with the intended one.

This will also make it behave the same as what FlowCrypt does on other platforms.

Public Key management UX is a tricky thing to get right across a spectrum of users (from technical users to the average Joe) while making everyone happy. In the future, when we can dedicate more time to it, public key management ux will be an area that will receive a more holistic focus.

**Comment by DenBond7** [comment]
for @DenBond7 
- [ ] test a key with many uid (Test UI)
- [ ] resolve a case with expired keys
- [ ] resolve a case with emails mismatch

**Comment by DenBond7** [comment]
@DenBond7 
Need to create a test for this issue
