### ISSUE TITLE
View address email was sent from while reading it

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-android#941]
Currently we show the display name, but not the actual address. To view the address, you have to click the reply button.

But the address that shows up when you do that, I'm not sure if it's the From address or the Reply-To address (which can be different).

Ref: https://mail.google.com/mail/u/1/#inbox/FMfcgxwJXfprBXthRcfGQjjlpLssCGSH

The user also asks:  Do you think it is a good idea to introduce select all feature to select all the message in a folder?

**Comment by DenBond7** [comment]
@seisvelas We have quite a similar issue here #321. So yes, we should improve the message details screen.

> Do you think it is a good idea to introduce select all feature to select all the message in a folder?

I think we can't do that. It depends on the app logic. We don't store all messages of some folder locally. A user only can manage messages which were cached.

**Comment by seisvelas** [comment]
Sorry I missed that, indeed that's the same thing!
