### ISSUE TITLE
Trust anchor for certification path not found

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-android#944]
Ref: https://mail.google.com/mail/u/1/#inbox/FMfcgxwJXpTMsXzmLLlDnVLlKpqCDKlc

![android_java_cert](https://user-images.githubusercontent.com/44826516/93163364-91592d00-f6dc-11ea-887f-89e5cd22873f.png)

**Comment by DenBond7** [comment]
Deprecated
