### ISSUE TITLE
Fix saving backups to Inbox after a user changes passphrase

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#946]
Here we have a bug 

https://github.com/FlowCrypt/flowcrypt-android/blob/66ff543fbd1cb937f115424d51b48150ff57f7db/FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/PrivateKeysViewModel.kt#L137

we use a wrong passphrase(encrypted)

**Comment by tomholub** [comment]
It will be good to cover this with tests

**Comment by DenBond7** [comment]
@tomholub I've found this thanks to our tests
