### ISSUE TITLE
Useless Codacy rules to ignore

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#958]
Sometimes Codacy will come up with rules that make no sense. I have only enabled it recently. Here you can tell me which rules are not useful, and I'll disable them.

**Comment by DenBond7** [comment]
@tomholub Please disable `CommentOverPrivateProperty`. Some comments for private things make a logic much clearer

**Comment by tomholub** [comment]
Agree, that's a silly rule

**Comment by tomholub** [comment]
removed
