### ISSUE TITLE
Option to password protect app

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-android#959]
>Hi can the app be password protected? So you have to enter a code to open the app. As an extra security. Now when the phone is unlocked you can easily open flowcrypt and read every message. I would love some extra protection preventing unauthorized access to the app and all encrypted messages inside it.

>By the way, thank you for the app, love it and recommend it to many people!

Ref: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgxwJXxwXKxjTwmNqNLjfRbzkrpsr

**Comment by tomholub** [comment]
This is a bit similar to #372 but asks for phone password protection, which may be more convenient then pass phrase protection, but less secure.

**Comment by seisvelas** [comment]
I see you actually mentioned this as well in #372  

>Also users often request a simple pin code option:
>>I also suggest/request a pin or fingerprint protection for the app itself. 

Since this idea is covered there as well, I'll close this.
