### ISSUE TITLE
HTML view improvements

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#96]
- all links should open in a new tab. Ideally, this should create a temporary browser tab link Gmail app does, with a back button that gets you back to the email. Right now, it will let me click a link and the contents of the link will display inside the email - not ideal (although interesting). 

- when there is a large image, the email will be wider than the screen, and it will let me scroll within the web view

- same for horizontal scrolling - the web view should extend to need size and do not scroll itself. It should just behave like text

**Comment by DenBond7** [comment]
> all links should open in a new tab. Ideally, this should create a temporary browser tab link Gmail app does, with a back button that gets you back to the email. Right now, it will let me click a link and the contents of the link will display inside the email - not ideal (although interesting).

Do you mean this https://android-developers.googleblog.com/2015/09/chrome-custom-tabs-smooth-transition.html?

**Comment by DenBond7** [comment]
> when there is a large image, the email will be wider than the screen, and it will let me scroll within the web view

Could you provide an example? For better understand.

And for this too.

> same for horizontal scrolling - the web view should extend to need size and do not scroll itself. It should just behave like text

**Comment by tomholub** [comment]
lost the screenshots.. I'll try to reproduce it again

**Comment by tomholub** [comment]
@DenBond7 sent you a sample email. See the difference between how FlowCrypt shows it and how Gmail shows it.

FlowCrypt will let you scroll around to the sides. Gmail will fit the email to the width of the phone even if there are large images in it.

**Comment by DenBond7** [comment]
Now your message looks like this
![image](https://user-images.githubusercontent.com/2863246/30909591-5adaf824-a38a-11e7-868f-49087d612de6.png)

I managed to do this by adding my own style to the displayed HTML. I think Gmail uses this decision too.

**Comment by tomholub** [comment]
That's perfect!
