### ISSUE TITLE
when we release public Beta on Google Play

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#97]
Need to resolve next steps before we releasing the app to Google Play

- [x] Need to read https://developers.google.com/terms/api-services-user-data-policy. (You must list the privacy policy URL in your OAuth client configuration when your application is made available to the public.)

- [x] Upgrade all libs to the last version. (@DenBond7)

**Comment by tomholub** [comment]
Looks good, we did link to https://flowcrypt.com/privacy on the oAuth screen. The rest looks good
