### ISSUE TITLE
do PGP functionality in JVM instead of node

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#976]
I have some good news - some PGP functionality will become available for you to do directly from Kotlin using a Java library.

Take a look here https://github.com/FlowCrypt/flowcrypt-key-manager/blob/master/emailEncryption/src/main/kotlin/com/flowcrypt/crypto/Pgp.kt
And here https://github.com/FlowCrypt/flowcrypt-key-manager/pull/490

Eventually, maybe we can move everything to Java and drop node.

**Comment by DenBond7** [comment]
I'm exited. Great news. If we'll move to use all things via Java I'll control them on my side = Better performance, stability and debugging

**Comment by DenBond7** [comment]
@tomholub 
By the way, if we will move to use native JVM instead of node we drop NDK -> we will have a much smaller app size. We will lose 70% of the current size.

**Comment by tomholub** [comment]
I know. And we can process much larger attachments and messages.

**Comment by tomholub** [comment]
Relevant discussion do develop a library for this https://github.com/pgpainless/pgpainless/issues/13

**Comment by tomholub** [comment]
superseded by https://github.com/FlowCrypt/flowcrypt-android/issues/1051
