### ISSUE TITLE
Messages in Gmail not syncing to Android

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-android#996]
ref: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgxwKjdtDBChNLCswLJWdtxRvzSfk

>This is for the android app. Note the screenshots, Gmail is showing an email from you on the inbox... The android app is not showing that email. Strange one.

ref: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgxwKjdvMVZNBWnswFZVfXrhgZjnB

>Syncing problem with Android Samsung? 

This user's screenshot didn't make it through, so I've requested they resend it

**Comment by seisvelas** [comment]
My phone isn't having this issue, as I was unable to reproduce

**Comment by seisvelas** [comment]
The second user is actually getting the "There was a syncing problem" error, so that goes in https://github.com/FlowCrypt/flowcrypt-android/issues/657. 

The first user, I've asked whether the message still hasn't arrived (maybe it just didn't get there instantly, but did eventually arrive - we'll see)

**Comment by DenBond7** [comment]
I hope this issue will be fixed after #993. There will be a lot of changes that relate to the current issue.

**Comment by DenBond7** [comment]
I'm closing it for now. This issue should be fixed via #1006. Please reopen it if you will receive similar feedback from users which have a version = 1.1.4 or high

**Comment by seisvelas** [comment]
Haven't received any new complaints about this, I'll let the previous users who experienced this know there is a fix and they just have to update.

Thanks Den!

**Comment by tomholub** [comment]
Wait - we haven't released the update yet. I'll let you know when we did.

**Comment by seisvelas** [comment]
> Wait - we haven't released the update yet. I'll let you know when we did.

Thanks - I did indeed check the version in the Play Store before sending the emails, just in case, and saw it was still at 1.1.3.
